### ISSUE TITLE
Can't boot on PXE with public network!

### ISSUE THREAD

**Issue by 0xelion** [vagrant-libvirt/vagrant-libvirt#1002]
Hi!
I've used one of the network examples to make my VM boot in PXE while having a box:

```
     config.vm.define :pxeclient do |pxeclient|
      pxeclient.vm.network :private_network,ip: '10.0.0.5',
            libvirt__network_name: "foreman_managed",
            libvirt__dhcp_enabled: false,
            libvirt__host_ip: '10.0.0.1'

       pxeclient.vm.provider :libvirt do |domain|
          domain.memory = 1000
          boot_network = {'network' => 'foreman_managed'}
          domain.storage :file, :size => '100G', :type => 'qcow2'
          domain.boot boot_network
          domain.boot 'hd'
        end
      end
```

However, i wanted to connect to a local PXE server, so i tried with a bridged public network configuration.

With just `libvirt.boot "network"`, only the first network which is automatically created try to boot and it doesn't work.

And when i tried to give a network name to the public network and set the boot values as:
```
      boot_network = {'network' => 'foreman_managed'}
      libvirt.boot boot_network
      libvirt.boot 'hd'`
```
It only boot on the box, no network boot

### Steps to reproduce
1. sudo vagrant up (bridge on hotedev requires sudo)
2. the vm is deployed but it doesn't boot properly

### Expected behaviour
I should be able to boot on the public network with PXE.

### Actual behaviour
Either only the first auto network wants to boot or only the box.

### System configuration
**OS/Distro version:**:
Linux Fedora 5.0.11-300.fc30.x86_64 GNU/Linux
**Libvirt version:**
Libvirt 5.1.0

**Output of `vagrant version; vagrant plugin list`:**
Vagrant Installed Version: 2.2.3
vagrant-libvirt (0.0.45, system)

**A Vagrantfile to reproduce the issue:**
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define :libvirt_capture do |config|
    config.vm.box = "roboxes/fedora30"
    config.vm.network "public_network",
    :dev => "enp1s0",
    :mode => "bridge",
    :network_name => "foreman_managed"

    config.vm.provider :libvirt do |libvirt|
      libvirt.cpus = 4
      libvirt.memory = 2048
      libvirt.driver = "kvm"
      boot_network = {'network' => 'foreman_managed'}
      libvirt.boot boot_network
      libvirt.boot 'hd'
    end
  end
end

```

**Are you using upstream vagrant package or your distros package?**
Upstream / Distro
Distro package with Fedora 30

**Comment by eoli3n** [comment]
did you figure it out ?
