### ISSUE TITLE
Clarify which versions of Vagrant are supported

### ISSUE THREAD

**Issue by mlda065** [vagrant-libvirt/vagrant-libvirt#1004]
The README states:

> Vagrant-libvirt supports Vagrant 1.5, 1.6, 1.7 and 1.8.

The template for github issues state:

> Please be aware that we are not actively testing previous versions of both Vagrant and Vagrant-libvirt, so before reporting an issue, please install the latest Vagrant version from Vagrantup.com

The latest version is 2.2.4.

Vagrant 1.8 no longer works, because the servers which serve boxes have changed their URLs.

So can I use Vagrant 2 or not? I'm confused.

**Comment by daks** [comment]
You can, it definitely works on vagrant 2.2.

**Comment by electrofelix** [comment]
The unit tests that are in place are run against multiple versions which includes 2.2

https://github.com/vagrant-libvirt/vagrant-libvirt/blob/master/.travis.yml#L18-L21

#1006 should take care of updating the README
