### ISSUE TITLE
Global plugin install

### ISSUE THREAD

**Issue by GrueMaster** [vagrant-libvirt/vagrant-libvirt#1010]
### Steps to reproduce
1.  Follow installation steps as currently documented for any Linux distro
2. Login as different user
3. Attempt to use vagrant as different user (make sure user is in libvirt group)

### Expected behaviour
Tell us what should happen
All users should be able to run vagrant with libvirt

### Actual behaviour
Tell us what happens instead
Current install places plugin in ~/.vagrant.d path instead of /opt/vagrant/embedded path where all users can utilize it without having to individually rebuild it.

### System configuration
**OS/Distro version:**:
Any
**Libvirt version:**
Any
**Output of `vagrant version; vagrant plugin list`:**
user1@testsystem:~$ vagrant version
Installed Version: 2.2.4
Latest Version: 2.2.4
 
You're running an up-to-date version of Vagrant!
user1@testsystem:~$ vagrant plugin list
vagrant-libvirt (0.0.45, global)

user2@testsystem:~$ vagrant plugin list
No plugins installed.

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**
```
Not needed for this issue
```

**A Vagrantfile to reproduce the issue:**
```
Not needed for this issue
```

**Are you using upstream vagrant package or your distros package?**
Upstream (very recent install)

**Comment by electrofelix** [comment]
@GrueMaster this is not something that a plugin can do anything about, instead it needs to be requested from https://github.com/hashicorp/vagrant, note they have stated there is no plans to implement support for such a request see hashicorp/vagrant#2457
