### ISSUE TITLE
Why not forward ssh-port?

### ISSUE THREAD

**Issue by Blaimi** [vagrant-libvirt/vagrant-libvirt#1011]
the port-forwarding for the ssh-port is skipped on purpose
https://github.com/vagrant-libvirt/vagrant-libvirt/blame/0f037bab9b8dba3e8c260986c1858348c65cb161/lib/vagrant-libvirt/action/forward_ports.rb#L75

we are heavily using this port-forwarding in our configurations of IDEs to auto-upload, browse files, tunneling to databases, …

at the moment we are using this workaround:

```ruby
	config.vm.provider "virtualbox" do |vb, override|
		vb.memory = "2048"
		vb.cpus = 2
		override.vm.network "forwarded_port", guest: 22, host: 2202, id: "ssh"
	end
	config.vm.provider :libvirt do |libvirt, override|
		libvirt.cpus = 2
		libvirt.memory = "2048"
		libvirt.volume_cache = "unsafe"
		# this is necessary because libvirt-provider skips any forwarding with id:'ssh'
		override.vm.network "forwarded_port", guest: 22, host: 2202, id: "ssh_lh"
	end
```

it would be better if there is a documented option to enable or disable the forwarding. To prevent backwards-compatibility-breaks, this option can default to "not forward"

```ruby
	config.vm.network "forwarded_port", guest: 22, host: 2202, id: "ssh"
	config.vm.provider :libvirt do |libvirt|
		libvirt.forward_ssh_port = true
	end
```

At least a hint in the documentation woud be nice to prevent searching for a configuration-bug.

### Steps to reproduce
1. create a vagrant-box with libvirt-provider
2. configure tools to connect with ssh with persistent config but independend of vagrant or static ip like an IDE

### Expected behaviour
ssh-connection to localhost:2222 or any other configured port should work

### Actual behaviour
ssh-port is not forwarded to localhost

### System configuration
**OS/Distro version:**: debian “buster” testing

**Libvirt version:** 5.0.0

**Output of `vagrant version; vagrant plugin list`:** Installed Version: 2.2.3 vagrant-libvirt (0.0.45, system)

**Comment by axmetishe** [comment]
I'm just curious due to some circumstances you forced to define the 'id'?
`node.vm.network :forwarded_port, guest: remote, host: local`
this construction will work out of the box for libvirt

**Comment by Blaimi** [comment]
we are using different ssh-ports in different projects to be able to run them simultaneous (and to prevent accidential usage of a wrong box). The forwarding with the id 'ssh' is always defined for host:2222, necessary for at least virtualbox and can be overridden by manually defining a forwarding with the id 'ssh'. Even if it would be fine to forward another port to guest:22 for usage in IDEs, this will only work for libvirt-boxes or the first virtualbox-box — the second one will complain for the already used port host:2222.

**Comment by axmetishe** [comment]
I mean that 'id' used within VirtualBox to define the name of the rule within 'Forwarded ports' window only and mean almost nothing for libvirt.
I'm using 2 different forwarded ports at least for each node within 6 node env(test env for software router) and never thought about the naming.
Actually I'm using simple yaml config which loaded by Vagrant:
```
    instance:
      interfaces:
        nic0:
          dev: 'eth1'
          address: 'mgmt'
        nic1:
          dev: 'eth2'
          address: '10.99.45.110'
        nic2:
          dev: 'eth3'
          address: '10.99.45.140'
        nic3:
          dev: 'eth4'
          address: '10.99.45.200'
      ports:
        '22': '2222'
        '80': '8888'
```

It's like a topology configuration for environment which parsed and then some helper method take this values and put it into into instance network configuration:
```
      if use_nat && !parameters['ports'].nil?
        parameters['ports'].each do |remote, local|
          node.vm.network :forwarded_port, guest: remote, host: local
        end
      end
```

In fact you at this helper you may handle the presence of 'id' parameter in case of different providers.
Topology file consumed by Vagrant will definitely provide well documented env configuration.

**Comment by electrofelix** [comment]
@Blaimi I think the skip on `id` being set to `ssh` is something that should be removed. I can't see a good reason for it, I don't think we need another option for this as @axmetishe points out that not setting it to `ssh`, which would be the default, works just fine, so skipping it when set to `ssh` doesn't make any sense unless something was using this elsewhere to manage another port forward and I can't see anything that would have set it in the first place.

**Comment by Blaimi** [comment]
ok, I think I have to make some more examples :)

first of all, host:2222->guest:22 is a _built in_ forward – at least for virtualbox, but because of this special code to explicitly skip this forwarding I assume this is a global one.

So, if no forward is set in Vagrantfile, **this one is always active**:
```ruby
override.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh"
```

# Example-situations
All situations have two independent Projects with their own Vagrantfile and -box

## Situation “empty”
* Vagrantfiles do not contain any forwardings

### libvirt
* I can start both boxes
* No forwarding is set at all
  * The built-in forward has no effect, because forwardings with id 'ssh' are skipped
* I can access both machines with ssh-shell via `vagrant ssh`
* `vagrant ssh` is an alias for `ssh $ip_of_box -p 2222` where $ip_of_box is read from libvirt and is **not** guaranteed to be **static**.
* I can not acces any machine with `ssh localhost -p 2222`

### virtualbox
* I can start one machine
* I can access the machine with `vagrant ssh`
* I can access the machine with `ssh localhost -p 2222` which is also the alias for `vagrant ssh` and ist static.
* starting the second one will give an **error** because port 2222 is already in use on the host-system
  * This is because the built-in ssh-forward takes into account
  * Virtualbox needs this ssh-forward because this is the default way to connect to the box

### conclusion
Both setups are not covering the requirements of having multiple machines running in parallel while having access via ssh and some static configuration on a per project base.

## situation “ssh-config”
* both Vagrantfiles contain a line to override the built in ssh-forward like
```ruby
# Machine one:
override.vm.network "forwarded_port", guest: 22, host: 2201, id: "ssh"
# Machine two:
override.vm.network "forwarded_port", guest: 22, host: 2202, id: "ssh"
```
### libvirt
* acts exactly the same like in situation “empty” because it ignores all forwards with id "ssh"

### virtualbox
* now I can run both machines in parallel
* I can access either machine one with `ssh localhost -p 2201` or machine two with `ssh localhost -p 2202` which are the aliases for `vagrant ssh` and is used for provisioning.

### conclusion
* virtualbox meets all the requirement:
  * running multiple machines at the same time (assuming all have set a different ssh-forward) is possible
  * the IDE-configuration for the ssh-access can be shared over multiple hosts and multiple destroy&up since each project will always have a static ssh-access via `ssh localhost -p 220X`
* libvirt did not change anything, we still have a different guest-ip on different systems and different instances of the same project.

## situation “anonymous“
Both vagrantfiles have forwards without the "ssh"-id (or any other id)
```ruby
# Machine one:
override.vm.network "forwarded_port", guest: 22, host: 2201
# Machine two:
override.vm.network "forwarded_port", guest: 22, host: 2202
```
### libvirt
Yeah, thats what I want. I have static ssh-configurations like in virtualbox.

### virtualbox
* Same **error** as in situation “empty” for the second machine
  * the built in forward 22->2222 is still active.
  * the configured one is only an _addition_ to the built in
  * host:2222 is in conflict staring with the second box

### conclusion
situation has flipped. Now libvirt does what I want but not virtualbox.

## situation “half workaround”
the Vagrantfile looks like this:
```ruby
override.vm.network "forwarded_port", guest: 22, host: 2202, id: "ssh"
config.vm.provider :libvirt do |libvirt, override|
    override.vm.network "forwarded_port", guest: 22, host: 2202
end
```
this configuration “mixes” the best of the above

### conclusion
vagrant does not start. I mentions something like “hey, you must not configure the same host-port multiple times” (freely quoted from memory); i.e. vagrant does a validation of the Vagrantfile before even choosing the provider.

## situation “workaround”
like described in the very first message
### conclusion
libvirt and virtualbox works. For virtualbox the built in ssh-forward is replaced with the configured one and for libvirt is an additional forward configured which will not be skipped only because of its id.

Since the forwarded ports are not conflicting anymore on vm.network for any ot the providers, the Vagrantfile passes the validation.

### “Problems”
1. It took me hours to find out, why forwarding of any port but the ssh-port was working. I had to have a look in the source-code to get it. (OK, this one could be simply achieved by documenting that port-forwardings with the id "ssh" is skipped)
2. It's not very intuitive for new users, the workaround is not obvious and
3. becomes more and more uglier, the more providers one wants to support. E.g. adding the support for Hyper-V or VMware-Player makes it necessary to add another block with the correct forwarding-configuration.

## situation “forward the ssh-port”
* All of the advantages from the above
* None of the disadvantages except a single config-entry on libvirt – even this is only necessary if you want to retain backwards-compatibility to not switch to the same behaviour virtualbox has in situation “blank”

**Comment by electrofelix** [comment]
I see where it's coming from now, https://github.com/hashicorp/vagrant/blob/4ce8d84f7e6709e4478612a9f0810dc686076ee0/plugins/kernel_v2/config/vm.rb#L456-L463

>     * I can access the machine with `ssh localhost -p 2222` which is also the alias for `vagrant ssh` and ist static.
> 
>     * starting the second one will give an **error** because port 2222 is already in use on the host-system
>       
>       * This is because the built-in ssh-forward takes into account
>       * Virtualbox needs this ssh-forward because this is the default way to connect to the box

Being static is only the case because you are disabling the auto collision handling though, not something that is default? 

Still back to the question as to whether it's useful to skip the default forwarding? Not sure, if it causes issues with remote libvirt instances then we have a bug, though might need to be ready to be responsive if this occurred.
Is it useful for someone to enable a separate config option in isolation without touching the forwarded_ports? Your last point suggests you'd find it useful to be able to enable it without changing anything.

I guess I'd be concerned that someone else will come along and look to use forwarded ports, set the id to `ssh` and not realise they need to enable a specific option for it to work. The documentation is long enough that people miss stuff already, so another option is just an opportunity for another thing missed.

Perhaps some info output to the UI to highlight to the user that the default port forward is currently being skipped but won't be in the future so as to allow us to switch behaviour in a future releases to default to forwarding and require something to disable it instead, and maybe to indicate the option to set if they don't want it skipped?

I wonder if something was added to the auto added port forward to allow it to be distinguished from port forwards added/enabled by users would that be better? Basically make it so that there is some option setting `autoadded: true` if coming from the vagrant system settings and only skip if this option was set. Or would it still be better to be able to use the default ssh forwarded port anyway?

**Comment by Blaimi** [comment]
> I wonder if something was added to the auto added port forward to allow it to be distinguished from port forwards added/enabled by users would that be better? Basically make it so that there is some option setting `autoadded: true` if coming from the vagrant system settings and only skip if this option was set. Or would it still be better to be able to use the default ssh forwarded port anyway?

you already found it: `auto_correct: true` :)

https://github.com/hashicorp/vagrant/blob/4ce8d84f7e6709e4478612a9f0810dc686076ee0/plugins/kernel_v2/config/vm.rb#L452

I'll update https://github.com/vagrant-libvirt/vagrant-libvirt/pull/1012 when I find a free minute the next few days to skip if it is `ssh` _and_ `auto_correct`. I also think this is the best way. It makes everything obvious.

**Comment by electrofelix** [comment]
`auto_correct: true` is still a valid setting, see https://www.vagrantup.com/docs/networking/forwarded_ports.html#auto_correct, I mean it's not purely internal so might cause some surprise if someone was overriding it explicitly to change one attribute such as port or host, but other than that it should reduce the number of scenarios it skips. Guess we can always ask upstream if they would consider accepting a PR so that it's possible for providers to distinguish between automatically injected network config from vagrant core and use requested config

**Comment by Blaimi** [comment]
> Being static is only the case because you are disabling the auto collision handling though, not something that is default?

ah, the ability to read is a clear benefit ;)

Hmmmmm... I probably didn't test the sitiution "empty" really good.

I think relying on this setting is still ok. since the user cannot trust the port if it has 'auto_correct', it should be fine to not forward it at all.

Who does the correction of the port collision? is this done by vagrant or has this to be implemented by the provider?

I think the best solution would be not skipping ssh by default but use a correct handling of auto_correct …
