### ISSUE TITLE
File system not fully synced on `vagrant package`

### ISSUE THREAD

**Issue by mcandre** [vagrant-libvirt/vagrant-libvirt#1013]
### Steps to reproduce

1. Customize a ppc64el guest vagrant-libvirt box with a provisioning script.
2. `vagrant package`
3. Import the resulting box.
4. `vagrant up` the resulting box.

### Expected behaviour

All customizations specified in the provisioning script, such as systemd modifications, appear in the exported box.

### Actual behaviour

* The upstream box is not shutdown correctly during the `vagrant package` procedure.
* Many modifications provisioned on the upstream box, fail to appear on the downstream box.

For context, my shutdown command configured originally in the root base box with Packer, is `echo 'vagrant' | sudo -S halt -p`. This command appears to work normally when triggered by `vagrant halt`. It's just the `vagrant package` command interfacing with vagrant-libvirt that somehow fails to shutdown the box and thereby sync the file system to virtual disk persistence.

I can confirm that all the customizations are present in the parent box (either by `vagrant ssh` or VNC). However, neither the ensure-host-key shell script nor the ensure-host-key service are present on the child box (`vagrant ssh` broken, hence working on these scripts; use VNC instead).

### System configuration
**OS/Distro version:** Ubuntu 19.04 Disco Dingo amd64

**Libvirt version:** 5.0.0-1ubuntu2.3

**Output of `vagrant version; vagrant plugin list`:**

```console
$ vagrant version; vagrant plugin list
2.2.4
vagrant-libvirt (0.0.45, global)
vagrant-rsync-back (0.0.1, global)
```

bootstrap.sh:

```sh
#!/bin/sh
sudo apt-get update &&
    sudo apt-get install -y clang &&
    sudo apt-get autoclean -y &&
    sudo apt-get clean -y &&
    sudo rm -rf /var/lib/apt/lists/* \
        /var/cache/apt/pkgcache.bin \
        /var/cache/apt/srcpkgcache.bin


sudo cp /tmp/ensure-host-keys /usr/sbin/ensure-host-keys &&
    sudo chmod u+x /usr/sbin/ensure-host-keys &&
    sudo cp /tmp/ensure-host-keys.service /lib/systemd/system &&
    sudo systemctl enable ensure-host-keys
```

ensure-host-keys:

```sh
#!/bin/sh
test \
    -f /etc/ssh/ssh_host_rsa_key \
    -a -f /etc/ssh/ssh_host_ecdsa_key \
    -a -f /etc/ssh/ssh_host_ed25519_key ||
    dpkg-reconfigure openssh-server
```

ensure-host-keys.service:

```
[Unit]
Description=Prepare sshd host keys
Before=ssh.service

[Service]
Type=oneshot
RemainAfterExit=true
StandardOutput=journal
ExecStart=/usr/sbin/ensure-host-keys

[Install]
WantedBy=multi-user.target
```

**A Vagrantfile to reproduce the issue:**

```ruby
Vagrant.configure("2") do |config|
    config.vm.box = "mcandre/debian-ppc64el"
    config.vm.box_version = "0.0.1"

    # Prepare for vagrant package
    config.ssh.insert_key = false
    config.vm.synced_folder ".", "/vagrant", type: "rsync", disabled: true

    config.vm.provision "file", source: "ensure-host-keys", destination: "/tmp/ensure-host-keys"
    config.vm.provision "file", source: "ensure-host-keys.service", destination: "/tmp/ensure-host-keys.service"

    config.vm.provision "shell", path: "bootstrap.sh"
end
```

**Are you using upstream vagrant package or your distros package?**

Distro

### Workaround

Forcibly write `sudo sync` at the end of my provisioning scripts.

**Comment by daks** [comment]
> For context, my shutdown command configured originally in the root base box with Packer, is `echo 'vagrant' | sudo -S halt -p`. This command appears to work normally when triggered by `vagrant halt`. It's just the `vagrant package` command interfacing with vagrant-libvirt that somehow fails to shutdown the box and thereby sync the file system to virtual disk persistence.

I'm not sure but I think that the shutdown command defined in Packer is only uses during the Packer build process, not 'exported' in some way to the Vagrant box.

**Comment by mmlb** [comment]
I think I'm coming across this too in https://github.com/tinkerbell/sandbox/pull/81. Most of the work done during the build is correct, only the `docker-compose` binary is incorrect. I do in fact see `/usr/local/bin/docker-compose` but it is truncated to 0 bytes.

Forcing a data flush via `sync` or lots of writes (I copied the same binary 2 more times) works too.

**Comment by electrofelix** [comment]
Probably just need the package action to ask the user if it's alright to halt (assuming interactive session) and then package and resume the machine afterwards. A workaround is to shutdown the machine before calling package as that will ensure any writes have been completed and the disk being copied is up to date

**Comment by esend7881** [comment]
> I think I'm coming across this too in [tinkerbell/sandbox#81](https://github.com/tinkerbell/sandbox/pull/81). Most of the work done during the build is correct, only the `docker-compose` binary is incorrect. I do in fact see `/usr/local/bin/docker-compose` but it is truncated to 0 bytes.
> 
> Forcing a data flush via `sync` or lots of writes (I copied the same binary 2 more times) works too.

I think I am facing this same issue ([as described here](https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1335#issuecomment-910862059))

What do you mean by `sync`? I tried the ideas of running a `shutdown -h now` and a `vagrant halt` before packaging however the file modifications made to the base box are not transitioning after a package operation...
