### ISSUE TITLE
vagrant package fails with qemu >= 2.10

### ISSUE THREAD

**Issue by jonasjoest** [vagrant-libvirt/vagrant-libvirt#1019]
Vagrant package fails if the disk to package has a backing image and  the installed qemu version is greater than 2.10 while the virtual machine is still running.

The command fails with the following output:
```
qemu-img: Could not open '/var/lib/libvirt/images/[...].img': Failed to get shared "write" lock
Is another process using the image?
```

This openstack-nova issue lead me to the fix of the issue:
https://bugzilla.redhat.com/show_bug.cgi?id=1654804#c4

**To fix this issue you need to change the following line:**
Change
https://github.com/vagrant-libvirt/vagrant-libvirt/blob/3f30606021444ac922c398e1737e09be4fe8fcfd/lib/vagrant-libvirt/action/package_domain.rb#L30

to:
```
backing = `qemu-img info --force-share "#{root_disk.path}" | grep 'backing file:' | cut -d ':' -f2`.chomp
```

Referring to the man page of `qemu-img` the `--force-share` option does the following:
```
If specified, qemu-img will open the image in shared mode, allowing other QEMU processes to open it in write mode. For example, this can be used to get the image information (with 'info' subcommand) when the image is used by a running guest.  Note that this could produce inconsistent results because of concurrent metadata changes, etc. This option is only allowed when opening images in read-only mode.
```

### Steps to reproduce
1. Install vagrant-libvirt on qemu >= 2.10 environment
2. Run and customize any vagrant box via libvirt provider
[Do not shutdown the virtual machine!]
3. Package the customized box via `vagrant package --output [...].box`

### Expected behaviour
The box should be packaged including copying and rebasing backing image

### Actual behaviour
The package command fails with:
```
qemu-img: Could not open '/var/lib/libvirt/images/[...].img': Failed to get shared "write" lock
Is another process using the image?
```

### System configuration
**OS/Distro version:**: RHEL 8

**Libvirt version:** 4.5.0

**qemu-img version:** 2.12.0 (qemu-kvm-2.12.0-63.module+el8+2833+c7d6d092)

**Output of `vagrant version; vagrant plugin list`:** 
Installed Version: 2.2.4
vagrant-libvirt (0.0.45, global)

**Are you using upstream vagrant package or your distros package?**
Upstream

**Comment by electrofelix** [comment]
#1307 fixed this in a different way by switching to halt the domain when packaging in line with how the virtualbox provider works
