### ISSUE TITLE
Need to be able to release bugfixes

### ISSUE THREAD

**Issue by electrofelix** [vagrant-libvirt/vagrant-libvirt#1051]
Latest release has been some time ago and various fixes have been landed since. In addition there are further PRs queued up that are most likely ready for landing but we should release first the current code base and then begin landing and releasing over a period of time to make it easier for people to spot issues due to code having been landed.

Request access/steps from existing maintainers to be able to publish to rubygems

**Comment by infernix** [comment]
@pronix can give you access to do this iirc

**Comment by infernix** [comment]
@electrofelix added as owner. 

As for releasing a new version, iirc update `./lib/vagrant-libvirt/version.rb` to a new version, commit to master, then build the gem and push it to rubygems. But @pronix may have a different process, I never did push a release.

**Comment by electrofelix** [comment]
@infernix should be straight forward, I think the problem is just to get permissions to push to rubygems @pronix can you help with that?

**Comment by infernix** [comment]
@electrofelix you have permissions. I added you as owner already.

**Comment by electrofelix** [comment]
Ah, crap, didn't know as hadn't received anything from rubygems, I see it there now

Thanks, it'll probably be next week when I do the release, as I'm busy doing some conference organizing over the next week

**Comment by grantral** [comment]
@electrofelix ping

**Comment by electrofelix** [comment]
I have access and have completed a number of releases
