### ISSUE TITLE
Please release new version

### ISSUE THREAD

**Issue by pvalena** [vagrant-libvirt/vagrant-libvirt#1058]
Latest release is `0.0.45` from `Oct 23, 2018`.

**Comment by tjanez** [comment]
This should be simpler after [more people have permissions to prepare a new release](https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1051).

**Comment by electrofelix** [comment]
Closing as the release process is as automated as possible now, and a few releases have been made, just lack additional maintainers to make it more regular.
