### ISSUE TITLE
verify the unit tests pass with rspec: 25 examples, 23 failures

### ISSUE THREAD

**Issue by poige** [vagrant-libvirt/vagrant-libvirt#1064]
Is anyone following "[Development](https://github.com/vagrant-libvirt/vagrant-libvirt#development)" instructions getting anything other than lots of failed tests?

My result: **25 examples, 23 failures** — and time waste, of course.

If the tests are actually broken why Docs don't say a thing to reflect this?

Also it's not documented whether _all the_ "[Installation](https://github.com/vagrant-libvirt/vagrant-libvirt#installation)" steps should be done before (anyways I tried both cases).

**Comment by poige** [comment]
I think it's a follow-up to #1018

**Comment by electrofelix** [comment]
Sorry for taking so long. The tests are run via GitHub actions and cover multiple versions of ruby so they do work, but sometimes there is breakage with specific versions of vagrant.

I should add some notes to that development section as there are a couple of things to help isolate if you need to test with a specific version of vagrant and also if you have a plugin installed already via vagrant to prevent clashes.
