### ISSUE TITLE
generic/fedora31 box fails when running with libvirt on fedora31

### ISSUE THREAD

**Issue by chaudron** [vagrant-libvirt/vagrant-libvirt#1067]
I tried to install a simple fedora31 box on a fedora 31 machine and it's failing (even tried a brand new install). It seems to work fine on RHEL8 which is the only alternative I had available (or on OSX with the virtual box provider).

Version information:
```
$ rpm -q vagrant vagrant-libvirt libvirt qemu-kvm
vagrant-2.2.6-1.fc31.noarch
vagrant-libvirt-0.0.45-3.fc31.noarch
libvirt-5.6.0-5.fc31.x86_64
qemu-kvm-4.1.1-1.fc31.x86_64
$ vagrant version; vagrant plugin list
Installed Version: 2.2.6

Vagrant was unable to check for the latest version of Vagrant.
Please check manually at https://www.vagrantup.com
vagrant-libvirt (0.0.45, system)
vagrant-reload (0.0.1, global)
vagrant-sshfs (1.3.3, global)

```

Replication step, install latest fedora 31 with updates:

```
$ mkdir test

$ cd test

$ vagrant init generic/fedora31
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.

$ vagrant up
Bringing machine 'default' up with 'libvirt' provider...
==> default: Checking if box 'generic/fedora31' version '2.0.6' is up to date...
==> default: Creating image (snapshot of base box volume).
==> default: Creating domain with the following settings...
==> default:  -- Name:              test_default
==> default:  -- Domain type:       kvm
==> default:  -- Cpus:              2
==> default:  -- Feature:           acpi
==> default:  -- Feature:           apic
==> default:  -- Feature:           pae
==> default:  -- Memory:            2048M
==> default:  -- Management MAC:    
==> default:  -- Loader:            
==> default:  -- Nvram:             
==> default:  -- Base box:          generic/fedora31
==> default:  -- Storage pool:      default
==> default:  -- Image:             /home/echaudro/.local/share/libvirt/images/test_default.img (32G)
==> default:  -- Volume Cache:      default
==> default:  -- Kernel:            
==> default:  -- Initrd:            
==> default:  -- Graphics Type:     vnc
==> default:  -- Graphics Port:     -1
==> default:  -- Graphics IP:       127.0.0.1
==> default:  -- Graphics Password: Not defined
==> default:  -- Video Type:        cirrus
==> default:  -- Video VRAM:        256
==> default:  -- Sound Type:	
==> default:  -- Keymap:            en-us
==> default:  -- TPM Path:          
==> default:  -- INPUT:             type=mouse, bus=ps2
==> default: Creating shared folders metadata...
==> default: Starting domain.
==> default: Waiting for domain to get an IP address...
```
It's waiting for the IP forever, on the console for the VM I can see it's waiting for start job to complete (see attachment).

![console](https://user-images.githubusercontent.com/18258026/72168256-0eedd000-33cd-11ea-8498-546730ccad78.png)

**Comment by phamduchongan93** [comment]
@chaudron I have the same issue as you do, you have to define your network set up within the vagrantfile. This is what different libvirt from virtual box. If you want, you can pull my vagrant file to test out the environment. Please clone the this file [Vagrantfile](https://github.com/phamduchongan93/vagrant.git)

**Comment by chaudron** [comment]
> @chaudron I have the same issue as you do, you have to define your network set up within the vagrantfile.

Don't think it's related to my network configuration as other virtual boxes work just fine, like centos or generic/ubuntu1910.

**Comment by phamduchongan93** [comment]
@chaudron right, if other boxes working, that might not be the case. My version stuck as `get an IP address`, I assumed that certain config of you network is a cause. After the vm defining, It runs fine.

**Comment by electrofelix** [comment]
@chaudron there have been a number of issues regarding the internal networking of generic/fedora images, that looks like the VM wasn't cleaned up correctly and is expecting a specific disk to be attached. I'm not sure what exactly would be possible here besides reporting it to the image builder. You may be able to get the VM to boot by working out a suitable kernel boot param to get systemd to disable the specific service via `systemd.mask=servicename`, but in general I'd recommend using a different image until the underlying issues with the image has been fixed.

@phamduchongan93 take a look at https://github.com/vagrant-libvirt/vagrant-libvirt#troubleshooting-vms on how to debug boot issues with VMs to see why the networking isn't getting an IP address without your custom network definition. It's possible there are some unusual assumptions being made by the image builder.

This issue will probably just have to be closed as there isn't really much that can be done to solve issues with images not booting besides helping point out how to view the console via virt-viewer and getting confirmation that something is blocking the VM from getting to the point where it will start the network.

**Comment by chaudron** [comment]
I've created an issue with the box provider:

https://github.com/lavabit/robox/issues/115
