### ISSUE TITLE
Fedora box download is not available 

### ISSUE THREAD

**Issue by phamduchongan93** [vagrant-libvirt/vagrant-libvirt#1070]
### Steps to reproduce
1. create vagrant file as instructed by README file
```
Vagrant.configure("2") do |config|
  config.vm.define :test_vm do |test_vm|
    test_vm.vm.box = "fedora/24-cloud-base"
  end
end
```
2. After the `vagrant up --provider=libvirt` command, the vagrant box won't be able to download. But others boxes is fine. For example, the following Vagrantfile can be successfully downloaded.
```
Vagrant.configure("2") do |config|
  config.vm.define :test_vm do |test_vm|
    test_vm.vm.box = "centos/7"
  end
end
```

**Comment by phamduchongan93** [comment]
I'm happy to make a pull request if you guys want to.

**Comment by electrofelix** [comment]
I guess we've fallen behind, if you can just bump the version of fedora used in the README and see if that works, that should be sufficient.
