### ISSUE TITLE
Does it support remote libvirt?

### ISSUE THREAD

**Issue by gabssnake** [vagrant-libvirt/vagrant-libvirt#1075]
Hi, thanks for your work in this project :)

Was wondering about the support for remote Libvirt.

Can you have Vagrant installed on a local machine and have it create VMs in a remote machine running Libvirt? If so, are there any limitations?

Sorry if this is repeated or already documented, could not find a clear answer in the docs or issues.

Best,

**Comment by GSergeevich** [comment]
Yes,remote creations/any other operations work in vagrant-libvirt.
You may see example here:

`Vagrant.configure(2) do |config|
	config.vm.box = "ubuntu_os"
	#  libvirt host connection
	config.vm.provider :libvirt do |libvirt|
           libvirt.driver = "kvm"
           libvirt.host = 'home' 
           libvirt.uri = "qemu+ssh://192.168.1.2/system"
           libvirt.storage_pool_name = 'images'
           libvirt.connect_via_ssh = 'yes'
           libvirt.username ='remote_host_username'
           libvirt.id_ssh_key_file = '/home/user/.ssh/id_rsa'
           libvirt.disk_bus = "virtio"
           libvirt.nic_model_type = "virtio"
           libvirt.video_type = "qxl"
           libvirt.graphics_type = "spice"
    end`

**Comment by GSergeevich** [comment]
More example:
[https://github.com/GSergeevich/openstack/blob/develop/Vagrantfile](url)

**Comment by gabssnake** [comment]
Thanks for the quick feedback!
