### ISSUE TITLE
Names of machine assigned by Vagrant-Libvirt to itself and to Libvirt, differ from each other

### ISSUE THREAD

**Issue by Ricky-Tigg** [vagrant-libvirt/vagrant-libvirt#1076]
### Steps to Reproduce
```
$ vagrant status
default                shutoff (libvirt)
$ virsh -c qemu:///session list --all
 Id   Name             State
---------------------------------
 -    fedora_default   shut off
```

### Expected behaviour
A name unique of machine

### Actual behaviour
The name of machine is _default_ under Vagrant-Libvirt while it is _fedora_default_ under Libvirt.

### System configuration
- OS: Fedora;
- libvirt.x86_64 5.6.0-5.fc31;
- vagrant version: 2.2.6;
- vagrant-libvirt (0.0.45, system);
- Using distros packages;
- Vagrant box name: generic/fedora31

**Comment by electrofelix** [comment]
Sorry about the delay in replying, the solution is to use the `default_prefix` config setting

```
Vagrant.configure("2") do |config|
  config.vm.box = "generic/fedora35"
  config.vm.provider "libvirt" do |lv|
    lv.default_prefix = ''
  end
end
```
This will result in both libvirt and vagrant using the same name for the machine of `default`.
