### ISSUE TITLE
Unable to install vagrant-libvirt

### ISSUE THREAD

**Issue by ikerexxe** [vagrant-libvirt/vagrant-libvirt#1080]
### Steps to reproduce
1. Start with a fresh vagrant install.
2. Execute ```vagrant plugin install vagrant-libvirt```

### Expected behaviour
vagrant-libvirt is installed

### Actual behaviour
vagrant-libvirt shows an error and is not installed

### System configuration
**OS/Distro version:**: Fedora release 31 (Thirty One)

**Libvirt version:** NA

**Output of `vagrant version; vagrant plugin list`:**
Installed Version: 2.2.6

Vagrant was unable to check for the latest version of Vagrant.
Please check manually at https://www.vagrantup.com
vagrant-sshfs (1.3.3, global)
vagrant-vbguest (0.23.0, global)
winrm (2.3.4, global)
winrm-elevated (1.2.1, global)
winrm-fs (1.3.3, global)

**Output of ```vagrant plugin install vagrant-libvirt```**
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

conflicting dependencies rubyzip (\~> 2.0) and rubyzip (= 1.1.7)
  Activated rubyzip-1.1.7
  which does not match conflicting dependency (~> 2.0)

  Conflicting dependency chains:
    rubyzip (= 1.1.7), 1.1.7 activated

  versus:
    winrm-elevated (> 0), 1.2.1 activated, depends on
    winrm-fs (\~> 1.0), 1.3.4 activated, depends on
    rubyzip (\~> 2.0)

**Are you using upstream vagrant package or your distros package?**
Distro

**Comment by agriffis** [comment]
@ikerexxe I've wrestled with this too. Currently I'm using the distro package which does work, the caveat is that you have to install any *local* vagrant plugins before you install the distro package because of dependency madness.

Like this:

```
sudo dnf install vagrant
vagrant plugin install whatever
sudo dnf install vagrant-libvirt
```

and then I think you'll find everything works. If you need more local plugins, you can temporarily uninstall vagrant-libvirt, then reinstall it afterward.

See https://bugzilla.redhat.com/show_bug.cgi?id=1539181

**Comment by ikerexxe** [comment]
I tried that approach but it's not working because the script that I'm using (https://github.com/SSSD/sssd-test-suite/blob/master/readme.md) tries to install vagrant-libvirt using vagrant environment anyways.

**Comment by ikerexxe** [comment]
I've tried today again and it has worked. There must have been some update in the middle solving this problem. I'm closing the issue.
