### ISSUE TITLE
Plugin does not install on Fedora 31

### ISSUE THREAD

**Issue by AlexMax** [vagrant-libvirt/vagrant-libvirt#1082]
### Steps to reproduce
Just attempt to install the plugin after following the dependency directions for Fedora in the main README.md.

### Expected behaviour
Plugin is installed.

### Actual behaviour
Get a long error message that eventually points to this logfile:
```
"pkg-config --exists libvirt"
| pkg-config --libs libvirt
=> "-lvirt \n"
"gcc -o conftest -I/opt/vagrant/embedded/include/ruby-2.4.0/x86_64-linux -I/opt/vagrant/embedded/include/ruby-2.4.0/ruby/backward -I/opt/vagrant/embedded/include/ruby-2.4.0 -I. -I/opt/vagrant/embedded/include -I/opt/vagrant/embedded/include   -I/opt/vagrant/embedded/include -fPIC conftest.c  -L. -L/opt/vagrant/embedded/lib -Wl,-rpath,/opt/vagrant/embedded/lib -L/opt/vagrant/embedded/lib -Wl,-rpath,/opt/vagrant/embedded/lib -L. -L/opt/vagrant/embedded/lib -L/opt/vagrant/embedded/lib64 -Wl,-rpath=XORIGIN/../lib:XORIGIN/../lib64:/opt/vagrant/embedded/lib:/opt/vagrant/embedded/lib64 -fstack-protector -rdynamic -Wl,-export-dynamic -L/opt/vagrant/embedded/lib  -Wl,-rpath,/opt/vagrant/embedded/lib     -Wl,-rpath,'/../lib' -Wl,-rpath,'/../lib' -lruby  -lpthread -lrt -lgmp -ldl -lcrypt -lm   -lc"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

"gcc -o conftest -I/opt/vagrant/embedded/include/ruby-2.4.0/x86_64-linux -I/opt/vagrant/embedded/include/ruby-2.4.0/ruby/backward -I/opt/vagrant/embedded/include/ruby-2.4.0 -I. -I/opt/vagrant/embedded/include -I/opt/vagrant/embedded/include   -I/opt/vagrant/embedded/include -fPIC conftest.c  -L. -L/opt/vagrant/embedded/lib -Wl,-rpath,/opt/vagrant/embedded/lib -L/opt/vagrant/embedded/lib -Wl,-rpath,/opt/vagrant/embedded/lib -L. -L/opt/vagrant/embedded/lib -L/opt/vagrant/embedded/lib64 -Wl,-rpath=XORIGIN/../lib:XORIGIN/../lib64:/opt/vagrant/embedded/lib:/opt/vagrant/embedded/lib64 -fstack-protector -rdynamic -Wl,-export-dynamic -L/opt/vagrant/embedded/lib  -Wl,-rpath,/opt/vagrant/embedded/lib     -Wl,-rpath,'/../lib' -Wl,-rpath,'/../lib' -lruby -lvirt -lpthread -lrt -lgmp -ldl -lcrypt -lm   -lc"
/usr/bin/ld: warning: libcrypt.so.2, needed by /usr/lib64/libsasl2.so.3, may conflict with libcrypt.so.1
/usr/bin/ld: /usr/lib64/libssh.so.4: undefined reference to `EVP_KDF_derive@OPENSSL_1_1_1b'
/usr/bin/ld: /usr/lib64/libssh.so.4: undefined reference to `EVP_KDF_ctrl@OPENSSL_1_1_1b'
/usr/bin/ld: /usr/lib64/libssh.so.4: undefined reference to `EVP_KDF_CTX_free@OPENSSL_1_1_1b'
/usr/bin/ld: /usr/lib64/libssh.so.4: undefined reference to `EVP_KDF_CTX_new_id@OPENSSL_1_1_1b'
collect2: error: ld returned 1 exit status
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

package configuration for libvirt is not found
```

### System configuration
**OS/Distro version:**:
```
Fedora release 31 (Thirty One)
```

**Libvirt version:**
```
Name         : libvirt
Version      : 5.6.0
Release      : 5.fc31
```

**Output of `vagrant version; vagrant plugin list`:**

```
Installed Version: 2.2.7
Latest Version: 2.2.7
 
You're running an up-to-date version of Vagrant!
vagrant-linode (0.4.1, global)
```

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**
N/A (Can't even install)

**A Vagrantfile to reproduce the issue:**
N/A

**Are you using upstream vagrant package or your distros package?**
Upstream

**Comment by grantral** [comment]
Did you install all dependencies?
`sudo dnf install libvirt libvirt-devel ruby-devel libxslt-devel libxml2-devel libguestfs-tools-c`
`sudo dnf group install 'Development Tools'`

Maybe need OpenSSL?
`sudo dnf install openssl openssl-devel`

**Comment by AlexMax** [comment]
Hrm.  I saw the conflicting symbols and thought that there was no way out.  After installing your suggestions, I get a completely different error.

```
opalexmax@DESKTOP-52N20QO ~ % vagrant plugin install libvirt
Installing the 'libvirt' plugin. This can take a few minutes...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

conflicting dependencies ffi (~> 0.6.3) and ffi (= 1.12.1)
  Activated ffi-1.12.1
  which does not match conflicting dependency (~> 0.6.3)

  Conflicting dependency chains:
    ffi (= 1.12.1), 1.12.1 activated

  versus:
    libvirt (> 0), 0.1.0 activated, depends on
    ffi (~> 0.6.3)
```

**Comment by grantral** [comment]
I installed clear Fedora 31 with [rbenv](https://github.com/rbenv/rbenv).
`curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash`
`echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile`
`echo 'eval "$(rbenv init -)"' >> ~/.bash_profile`
`. ~/.bash_profile`

Check if everything is OK.
`curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | bash`

Then install ruby.
`rbenv install 2.7.0`
`rbenv global 2.7.0`

After all, I tried to install plugin.
`vagrant plugin install libvirt`

And...
```
[vagrant@localhost ~]$ vagrant plugin install libvirt
Installing the 'libvirt' plugin. This can take a few minutes...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

conflicting dependencies ffi (~> 0.6.3) and ffi (= 1.12.1)
  Activated ffi-1.12.1
  which does not match conflicting dependency (~> 0.6.3)

  Conflicting dependency chains:
    ffi (= 1.12.1), 1.12.1 activated

  versus:
    libvirt (> 0), 0.1.0 activated, depends on
    ffi (~> 0.6.3)
```

I'll try to compile master branch later and fix it if it broken.

**Comment by grantral** [comment]
Master branch build on Fedora 31. Just need push new version to rubygems.org.

@electrofelix, can you push?

**Comment by ricfeatherstone** [comment]
Any idea how to resolve? Unable to install on Fedora 31 after following all of the above.

gem_make.out

```
current directory: xxx/.vagrant.d/gems/2.4.5/gems/ruby-libvirt-0.7.1/ext/libvirt
/tmp/.mount_vagranOdaws5/usr/bin/ruby2.4 -r ./siteconf20200501-496369-1n26uv9.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/tmp/.mount_vagranOdaws5/usr/bin/$(RUBY_BASE_NAME)2.4
	--with-libvirt-include
	--without-libvirt-include
	--with-libvirt-lib
	--without-libvirt-lib
	--with-libvirt-config
	--without-libvirt-config
	--with-pkg-config
	--without-pkg-config
extconf.rb:73:in `<main>': libvirt library not found in default locations (RuntimeError)

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  xxx/.vagrant.d/gems/2.4.5/extensions/x86_64-linux/2.4.0/ruby-libvirt-0.7.1/mkmf.log

extconf failed, exit code 1
```

mkmf.log

```
"pkg-config --exists libvirt"
package configuration for libvirt is not found
```

```
pkg-config --exists libvirt && echo $?
0
pkg-config --list-all | grep libvirt
libvirt                        libvirt - libvirt library
libvirt-qemu                   libvirt-qemu - libvirt QEMU library
libvirt-lxc                    libvirt-lxc - libvirt LXC library
libvirt-admin                  libvirt-admin - libvirt admin library
```

**Comment by timhughes** [comment]
@ricfeatherstone this looks like you are missing the libvirt-dev/libvirt-devel package on you system 
> extconf.rb:73:in `<main>': libvirt library not found in default locations (RuntimeError)

have a look at https://github.com/vagrant-libvirt/vagrant-libvirt#installation and make sure you have all the correct packages installed

**Comment by ricfeatherstone** [comment]
Thanks but `Package libvirt-devel-5.6.0-6.fc31.x86_64 is already installed.`
I've been through installation and possible problems with installation in the docs and tried all the suggestions listed above apart from the rbenv one

**Comment by buckaroogeek** [comment]
Please see the solution in this thread: hashicorp/vagrant#11020 (comment). I have also submitted a pull request with fedora-specific updates to the installation instructions.  Vagrant 2.2.9 and the vagrant-libvirt plugin work once the ssh and kerberos (lib5kcrypto) libraries are added to the vagrant lib64 directory.

**Comment by electrofelix** [comment]
@AlexMax Outside of using the distro package, there has been a small section added on getting vagrant-libvirt working with the upstream provided vagrant package. It requires a bit of compiling of other packages. See #1107, based on this I believe should now be possible to have this work with the upstream. It is convoluted, so my recommendation is to try and use the distro provided vagrant first, if that doesn't work you can try using the docker based image https://github.com/vagrant-libvirt/vagrant-libvirt#using-docker-based-installation, which as it's relatively new may not have all of the right options in the readme to work in every sitution, and if neither of test work for you then try using the additional notes for installing on Fedora https://github.com/vagrant-libvirt/vagrant-libvirt#additional-notes-for-fedora-and-similar-linux-distributions

**Comment by electrofelix** [comment]
@ricfeatherstone suggest logging a separate issue as it appears to be something different to the original reason for this issue, and if you already have an I've missed it, apologies.

@grantral sorry had missed the message here originally, but since there were releases published after March, hopefully your issue has also been resolved.
