### ISSUE TITLE
 default: Waiting for domain to get an IP address

### ISSUE THREAD

**Issue by abeslam** [vagrant-libvirt/vagrant-libvirt#1084]
Hello everybody

i need help please

i have an issue witn a vm which starts and get stuck at this stage

**=> default: Waiting for domain to get an IP address**

I am using a Fedora 31 (system):
5.5.10-200.fc31.x86_64 #1 SMP Wed Mar 18 14:21:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

packages as folows:

vagrant-digitalocean-0.9.0-8.fc31.noarch
vagrant-sshfs-1.3.4-1.fc31.noarch
vagrant-libvirt-doc-0.0.45-3.fc31.noarch
vagrant-sshfs-doc-1.3.4-1.fc31.noarch
vagrant-digitalocean-doc-0.9.0-8.fc31.noarch
vagrant-2.2.6-1.fc31.noarch
vagrant-registration-doc-1.3.1-6.fc31.noarch
vagrant-hostmanager-1.8.9-3.fc31.noarch
vagrant-lxc-1.1.0-16.fc31.noarch
vagrant-adbinfo-doc-0.1.0-6.fc31.noarch
vagrant-adbinfo-0.1.0-6.fc31.noarch
vagrant-lxc-doc-1.1.0-16.fc31.noarch
vagrant-hostmanager-doc-1.8.9-3.fc31.noarch
vagrant-libvirt-0.0.45-3.fc31.noarch
vagrant-registration-1.3.1-6.fc31.noarch
vagrant-doc-2.2.6-1.fc31.noarch
vagrant-cachier-doc-1.2.1-6.fc31.noarch
vagrant-openstack-provider-doc-0.13.0-4.fc31.noarch
vagrant-openstack-provider-0.13.0-4.fc31.noarch
vagrant-cachier-1.2.1-6.fc31.noarch
libvirt-daemon-driver-storage-rbd-5.6.0-5.fc31.x86_64
libvirt-glib-2.0.0-4.fc31.x86_64
libvirt-daemon-config-nwfilter-5.6.0-5.fc31.x86_64
libvirt-admin-5.6.0-5.fc31.x86_64
libvirt-daemon-driver-storage-iscsi-direct-5.6.0-5.fc31.x86_64
vagrant-libvirt-doc-0.0.45-3.fc31.noarch
libvirt-gconfig-devel-2.0.0-4.fc31.x86_64
libvirt-sandbox-0.8.0-4.fc31.x86_64
libvirt-daemon-config-network-5.6.0-5.fc31.x86_64
libvirt-sandbox-libs-0.8.0-4.fc31.x86_64
libvirt-daemon-xen-5.6.0-5.fc31.x86_64
libvirt-daemon-5.6.0-5.fc31.x86_64
libvirt-daemon-driver-secret-5.6.0-5.fc31.x86_64
libvirt-bash-completion-5.6.0-5.fc31.x86_64
libvirt-cim-0.6.3-13.fc31.x86_64
libvirt-docs-5.6.0-5.fc31.x86_64
libvirt-daemon-driver-storage-iscsi-5.6.0-5.fc31.x86_64
libvirt-daemon-driver-interface-5.6.0-5.fc31.x86_64
libvirt-daemon-kvm-5.6.0-5.fc31.x86_64
libvirt-daemon-driver-vbox-5.6.0-5.fc31.x86_64
libvirt-glib-devel-2.0.0-4.fc31.x86_64
libvirt-5.6.0-5.fc31.x86_64
libvirt-wireshark-5.6.0-5.fc31.x86_64
libvirt-java-javadoc-0.4.9-15.fc31.noarch
libvirt-daemon-driver-network-5.6.0-5.fc31.x86_64
libvirt-daemon-driver-storage-scsi-5.6.0-5.fc31.x86_64
libvirt-daemon-driver-qemu-5.6.0-5.fc31.x86_64
rubygem-fog-libvirt-0.5.0-4.fc31.noarch
libvirt-gobject-2.0.0-4.fc31.x86_64
libvirt-daemon-lxc-5.6.0-5.fc31.x86_64
libvirt-designer-devel-doc-0.0.2-11.fc31.x86_64
libvirt-daemon-vbox-5.6.0-5.fc31.x86_64
libvirt-libs-5.6.0-5.fc31.x86_64
libvirt-daemon-driver-storage-logical-5.6.0-5.fc31.x86_64
libvirt-daemon-driver-nwfilter-5.6.0-5.fc31.x86_64
libvirt-daemon-driver-libxl-5.6.0-5.fc31.x86_64
libvirt-designer-devel-0.0.2-11.fc31.x86_64
libvirt-java-devel-0.4.9-15.fc31.noarch
libvirt-sandbox-devel-0.8.0-4.fc31.x86_64
libvirt-login-shell-5.6.0-5.fc31.x86_64
libvirt-daemon-driver-storage-disk-5.6.0-5.fc31.x86_64
libvirt-daemon-driver-storage-zfs-5.6.0-5.fc31.x86_64
libvirt-daemon-driver-storage-5.6.0-5.fc31.x86_64
vagrant-libvirt-0.0.45-3.fc31.noarch
libvirt-client-5.6.0-5.fc31.x86_64
libvirt-lock-sanlock-5.6.0-5.fc31.x86_64
libvirt-dbus-1.3.0-3.fc31.x86_64
libvirt-daemon-driver-storage-core-5.6.0-5.fc31.x86_64
rubygem-ruby-libvirt-0.7.1-6.fc31.x86_64
libvirt-gobject-devel-2.0.0-4.fc31.x86_64
libvirt-daemon-qemu-5.6.0-5.fc31.x86_64
libvirt-daemon-driver-nodedev-5.6.0-5.fc31.x86_64
libvirt-daemon-driver-lxc-5.6.0-5.fc31.x86_64
libvirt-java-0.4.9-15.fc31.noarch
libvirt-nss-5.6.0-5.fc31.x86_64
libvirt-daemon-driver-storage-sheepdog-5.6.0-5.fc31.x86_64
libvirt-daemon-driver-storage-gluster-5.6.0-5.fc31.x86_64
libvirt-designer-libs-0.0.2-11.fc31.x86_64
libvirt-designer-0.0.2-11.fc31.x86_64
libvirt-daemon-driver-storage-mpath-5.6.0-5.fc31.x86_64
libvirt-gconfig-2.0.0-4.fc31.x86_64
libvirt-devel-5.6.0-5.fc31.x86_64
libvirt-designer-vala-0.0.2-11.fc31.x86_64

runing vagrant up --debug:

DEBUG create_network_interfaces: Adapter not specified so found slot 0
 INFO create_network_interfaces: Setting up public interface using device virbr0 in mode bridge
 INFO create_network_interfaces: Creating network interface eth0 connected to network public.
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::AfterTriggerAction:0x000055998077b2c0>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::BeforeTriggerAction:0x000055998077b248>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::SetBootOrder:0x000055998077b220>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::AfterTriggerAction:0x00005599807ff138>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::BeforeTriggerAction:0x00005599807ff070>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::StartDomain:0x00005599807ff048>
 INFO interface: info: Starting domain.
 INFO interface: info: ==> default: Starting domain.
==> default: Starting domain.
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::AfterTriggerAction:0x000055998088cad8>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::BeforeTriggerAction:0x000055998088ca60>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::WaitTillUp:0x000055998088ca38>
DEBUG wait_till_up: Searching for IP for MAC address: 52:54:00:2e:f4:7a
 INFO interface: info: Waiting for domain to get an IP address...
 INFO interface: info: ==> default: Waiting for domain to get an IP address...
==> default: Waiting for domain to get an IP address...
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
^C INFO interface: warn: Waiting for cleanup before exiting...
 INFO interface: warn: ==> default: Waiting for cleanup before exiting...
==> default: Waiting for cleanup before exiting...

Log files:

journaclt -f

mars 29 15:06:35 localhost.localdomain kernel: device tap1 left promiscuous mode
mars 29 15:06:35 localhost.localdomain kernel: virbr0: port 2(tap1) entered disabled state
mars 29 15:06:35 localhost.localdomain audit: ANOM_PROMISCUOUS dev=tap1 prom=0 old_prom=256 auid=1000 uid=1000 gid=1000 ses=3
mars 29 15:06:35 localhost.localdomain avahi-daemon[907]: Withdrawing address record for fe80::fc42:feff:feb2:6407 on tap1.
mars 29 15:06:35 localhost.localdomain NetworkManager[1089]: <info>  [1585487195.9598] device (tap1): state change: disconnected -> unmanaged (reason 'unmanaged', sys-iface-state: 'removed')
mars 29 15:06:35 localhost.localdomain NetworkManager[1089]: <info>  [1585487195.9627] device (tap1): released from master device virbr0
mars 29 15:06:35 localhost.localdomain gnome-shell[2270]: Removing a network device that was not added
mars 29 15:06:41 localhost.localdomain tracker-store[2329599]: OK
mars 29 15:06:41 localhost.localdomain systemd[2086]: tracker-store.service: Succeeded.
mars 29 15:06:42 localhost.localdomain xdg-desktop-por[59812]: Failed to get application states: GDBus.Error:org.freedesktop.portal.Error.Failed: Could not get window list: Impossible d’appeler la méthode ; le serveur est mandataire d’un nom connu org.gnome.Shell sans propriétaire alors que le proxy a été construit avec le marqueur G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START
mars 29 15:06:48 localhost.localdomain salt-minion[1359]: [ERROR   ] DNS lookup or connection check of 'salt' failed.
mars 29 15:06:48 localhost.localdomain salt-minion[1359]: [ERROR   ] Master hostname: 'salt' not found or not responsive. Retrying in 30 seconds
mars 29 15:06:48 localhost.localdomain systemd-udevd[2330140]: Using default interface naming scheme 'v243'.
mars 29 15:06:48 localhost.localdomain systemd-udevd[2330140]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
mars 29 15:06:48 localhost.localdomain NetworkManager[1089]: <info>  [1585487208.5894] manager: (tap1): new Tun device (/org/freedesktop/NetworkManager/Devices/72)
mars 29 15:06:48 localhost.localdomain kernel: virbr0: port 2(tap1) entered blocking state
mars 29 15:06:48 localhost.localdomain kernel: virbr0: port 2(tap1) entered disabled state
mars 29 15:06:48 localhost.localdomain kernel: device tap1 entered promiscuous mode
mars 29 15:06:48 localhost.localdomain audit: ANOM_PROMISCUOUS dev=tap1 prom=256 old_prom=0 auid=1000 uid=1000 gid=1000 ses=3
mars 29 15:06:48 localhost.localdomain libvirtd[1655143]: Unable to open vhost-net. Opened so far 0, requested 1

libvirtd.log:

2020-03-28 15:43:01.658+0000: 3676792: info : virObjectUnref:349 : OBJECT_UNREF: obj=0x55b5f1c5d6e0
2020-03-28 15:43:01.658+0000: 3676792: info : virObjectUnref:351 : OBJECT_DISPOSE: obj=0x55b5f1c5d6e0
2020-03-28 15:43:01.658+0000: 3676792: info : virObjectUnref:349 : OBJECT_UNREF: obj=0x55b5f1c5ff90
2020-03-28 15:43:01.658+0000: 3676792: info : virObjectUnref:349 : OBJECT_UNREF: obj=0x55b5f1c5e240
2020-03-28 15:43:01.658+0000: 3676792: info : virObjectUnref:351 : OBJECT_DISPOSE: obj=0x55b5f1c5e240
2020-03-28 15:43:01.658+0000: 3676792: info : virObjectUnref:349 : OBJECT_UNREF: obj=0x55b5f1bc8900
2020-03-28 15:43:01.658+0000: 3676792: info : virObjectUnref:351 : OBJECT_DISPOSE: obj=0x55b5f1bc8900
2020-03-28 15:43:01.659+0000: 3676792: info : virObjectUnref:349 : OBJECT_UNREF: obj=0x55b5f1c5ec90
2020-03-28 15:43:01.659+0000: 3676792: info : virObjectUnref:349 : OBJECT_UNREF: obj=0x55b5f1c5fa90
2020-03-28 15:43:01.659+0000: 3676792: info : virObjectUnref:349 : OBJECT_UNREF: obj=0x55b5f1c5d420
2020-03-28 15:43:01.659+0000: 3676792: info : virObjectUnref:351 : OBJECT_DISPOSE: obj=0x55b5f1c5d420
2020-03-28 15:43:01.659+0000: 3676792: info : virObjectUnref:349 : OBJECT_UNREF: obj=0x55b5f1c5d4c0
2020-03-28 15:43:01.659+0000: 3676792: info : virObjectUnref:351 : OBJECT_DISPOSE: obj=0x55b5f1c5d4c0
2020-03-28 15:43:01.659+0000: 3676792: info : virObjectUnref:349 : OBJECT_UNREF: obj=0x55b5f1c5d5d0
2020-03-28 15:43:01.659+0000: 3676792: info : virObjectUnref:351 : OBJECT_DISPOSE: obj=0x55b5f1c5d5d0
2020-03-28 15:43:01.659+0000: 3676792: debug : virFileClose:114 : Closed fd 7

Any help would be very appreciated

Thank you

My Regards

#

**Comment by electrofelix** [comment]
Recommend taking a look at the Troubleshooting section https://github.com/vagrant-libvirt/vagrant-libvirt#troubleshooting-vms, which covers how to view the VM console so you can see what is causing the issue during boot. Frequently it's due to a problem with how the image was built assuming particularly network devices will exist. You can sometimes workaround this by explicitly setting MAC addresses hardcoded into the image in the Vagrantfile configuration

**Comment by darkn3rd** [comment]
I am getting the same issue, but with Ubuntu 18.04 guest.  There seems to have numerous people having this issue.

I connected to `vnc://localhost` and is shows vagrant login prompt.  I can login in with vagrant/vagrant.

In debug mode, is just hangs here forever.
 
```
INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
```

Not sure what is going on, how all of this works, but know it is not working. 

Image Built Using: https://github.com/jakobadam/packer-qemu-templates.git

**Comment by electrofelix** [comment]
@darkn3rd if you can login, you can investigate further as to why the network didn't automatically configure via DHCP. Often it's due to files left around from when the machine was first built that result in the Mac address from when it was built being used instead of the one generated for the VM when subsequently booted up

**Comment by electrofelix** [comment]
@abeslam as I haven't heard back, going to close this issue, if it's because of the templates https://github.com/jakobadam/packer-qemu-templates.git I'm going to try and address any issues in #1097 as that indicated those templates as the starting point.

@darkn3rd your issue may be different, there is another issue logged #1097 that is using the same templates, I'll try to bring up a VM based on it, but I'm report and results in the other issue as that as more information about an example config that should reproduce.

**Comment by electrofelix** [comment]
@darkn3rd and I just realised it was you that opened that issue, apologies for the delays in following up.
