### ISSUE TITLE
Allow declaring no inputs

### ISSUE THREAD

**Issue by radeksimko** [vagrant-libvirt/vagrant-libvirt#1092]
The plugin currently sets one default device (mouse):
https://github.com/vagrant-libvirt/vagrant-libvirt/blob/4598cfc2802b28dabd721aa0956c450a97ba8894/lib/vagrant-libvirt/config.rb#L735-L736
and it seems there is no way of disabling it other than by declaring another device.

The problem is that PS2 may not always be supported and this default behavior then leads to an error.

### Steps to reproduce
1. `vagrant up --provider=libvirt`

### Expected behaviour

Bring up a machine without PS2 mouse input.

### Actual behaviour

Error:

> Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: unsupported configuration: ps2 is not supported by this QEMU binary

### System configuration
**OS/Distro version:**:
MacOS Mojave (10.14.6)

**Libvirt version:**
`6.2.0` installed from Homebrew

**Output of `vagrant version; vagrant plugin list`:**
```
Installed Version: 2.2.7
Latest Version: 2.2.7
```
```
vagrant-libvirt (0.0.45, global)
```

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**
```
TODO: Don't have it handy at the moment - will update later if I get chance
```

**A Vagrantfile to reproduce the issue:**
```
Vagrant.configure("2") do |config|
  config.vm.box = "packer_qemu_libvirt.box"

  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "qemu"
    libvirt.kernel = File.expand_path("kernel-qemu-stretch")
    libvirt.cmd_line = "root=/dev/sda2 panic=1 rootfstype=ext4 rw"
    libvirt.dtb = File.expand_path("versatile-pb.dtb")
    libvirt.cpu_model = "arm1176"
    libvirt.cpu_mode = "custom"
    libvirt.cpu_fallback = "forbid"
    libvirt.memory = 256
    libvirt.machine_type = "versatilepb"
    libvirt.machine_arch = "armv6l"
    libvirt.emulator_path = "/usr/local/bin/qemu-system-arm"
    libvirt.random_hostname = true
    libvirt.qemu_use_session = true
    libvirt.socket = "/usr/local/var/run/libvirt/libvirt-sock"
  end
end
```

**Are you using upstream vagrant package or your distros package?**
Installed via Homebrew

**Comment by electrofelix** [comment]
@radeksimko sorry for the slow response, try adding the following config:
```
Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |libvirt|
    libvirt.inputs = []
  end
end
```

That will cause `@inputs` to not be `UNSET_VALUE` during finalize and prevent the XML generated from containing a mouse. I have noticed that locally when I do this, I still end up with a generic keyboard and mouse getting inserted by libvirt subsequently, so there may be something else needed to make sure libvirt doesn't do this when no inputs are defined, or it may not be necessary for systems that don't support the additional inputs.

**Comment by radeksimko** [comment]
Yes, that seemed to work 👍🏻 

Thank you.

**Comment by trinitronx** [comment]
I think this is still an issue with latest `vagrant-libvirt-0.7.1.pre.27` + `vagrant-2.2.19` + `libvirt0` version `6.0.0-0ubuntu8.15`.

With the following `Vagrantfile`:

```ruby
Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |libvirt|
  # [...SNIP...]

    # PS/2 Kbd & Mouse do not work on VM
    libvirt.inputs = []  # Force NO default PS/2 mouse
    libvirt.input :type => "tablet", :bus => "usb"
    libvirt.input :type => "keyboard", :bus => "usb"

  # [...SNIP...]
  end
  # [...SNIP...]
end
```

Still results in the extra PS/2 devices being declared.  This still causes problems when PS/2 is unsupported inside the VM.

The interesting part is that `VAGRANT_LOG=debug  vagrant up` displays the `libvirt` domain XML twice!  The first time, it looks correct, with no extra `<input ... bus='ps2'/>` XML elements.  The **_second time_** is when they are somehow automatically added:

```xml
<!--  Vagrant debug log lines before this were:
==> default: Creating shared folders metadata...
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::SetBootOrder:0x00007f7ccd2943d8>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::StartDomain:0x00007f7ccd2a6d08>
 INFO interface: info: Starting domain.
 INFO interface: info: ==> default: Starting domain.
==> default: Starting domain.
DEBUG start_domain: clock timers config changed
DEBUG start_domain: Starting Domain with XML:  -->
<domain type='kvm' xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'>
<!-- [...SNIP...] -->
  <devices>
    <!-- [...SNIP...] -->
    <input type='tablet' bus='usb'>
      <address type='usb' bus='0' port='1'/>
    </input>
    <input type='keyboard' bus='usb'>
      <address type='usb' bus='0' port='2'/>
    </input>
    <input type='mouse' bus='ps2'/>
    <input type='keyboard' bus='ps2'/>
    <!-- [...SNIP...] -->
  </devices>
<!-- [...SNIP...] -->
</domain>
```

I've checked the logs using `VAGRANT_LOG=debug vagrant up` , and found that it was evaluating the default `.box` `Vagrantfile` under `~/.vagrant.d/boxes/$VM_NAME_HERE/0/libvirt/Vagrantfile`.  At first, I _thought_ it was adding them from the missing `inputs = []` in `finalize!` for the original `Vagrantfile`.  However, `vagrant-libvirt` still adds those extra `<input ... bus='ps2'/>` lines, even after copying my project `Vagrantfile` to that location and making sure they were identical.

I'm not sure where they are coming from, but the only 2 `Vagrantfile` paths listed are the project's one and the default one for the vagrant `.box`.  The logs mention another `:home` location for the configuration loader, but no `Pathname:` class is mentioned for that:

```
DEBUG command: Getting target VMs for command. Arguments:
DEBUG command:  -- names: ["default"]
DEBUG command:  -- options: {:provider=>nil}
DEBUG command: Finding machine that match name: default
 INFO loader: Set "2860_machine_default" = []
 INFO loader: Loading configuration in order: [:home, :root, "2860_machine_default"]
ERROR loader: Unknown config sources: [:"2960_VM_NAME_HERE_libvirt"]
DEBUG loader: Loading from: root (cache)
DEBUG loader: Configuration loaded successfully, finalizing and returning
DEBUG push: finalizing
 WARN vagrantfile: Failed to locate VM_NAME_HERE with version 
 WARN vagrantfile: Performing lookup with initial values VM_NAME_HERE with version 
 [...SNIP...]
DEBUG environment: Using provider `libvirt` detected in configuration and usable.
 INFO environment: Getting machine: default (libvirt)
 INFO environment: Returning cached machine: default (libvirt)
[...SNIP...]
 INFO loader: Set "2860_machine_default" = []
 INFO loader: Loading configuration in order: [:home, :root, "2860_machine_default"]
ERROR loader: Unknown config sources: [:"2960_VM_NAME_HERE_libvirt"]
DEBUG loader: Loading from: root (cache)
DEBUG loader: Configuration loaded successfully, finalizing and returning
DEBUG push: finalizing
 INFO box_collection: Box found: VM_NAME_HERE (libvirt)
 INFO loader: Set :"2960_VM_NAME_HERE_libvirt" = ["#<Pathname:~/.vagrant.d/boxes/USERNAME_HERE-VAGRANTSLASH-VM_NAME_HERE/0/libvirt/Vagrantfile>"]
 INFO loader: Loading configuration in order: [:"2960_VM_NAME_HERE_libvirt", :home, :root, "2860_machine_default"]
DEBUG loader: Loading from: 2960_VM_NAME_HERE_libvirt (cache)
DEBUG loader: Loading from: root (cache)
DEBUG loader: Configuration loaded successfully, finalizing and returning
DEBUG push: finalizing
```

I even tried monkey-patching the class like so:

```ruby
# Monkey patch
module VagrantPlugins
  module ProviderLibvirt
    class Config < Vagrant.plugin('2', :config)
      @inputs = [] # Monkey-patch to force this to empty array
    end
  end
end
## Rest of Vagrantfile here... 
# [...SNIP...]
```

So, I'm not sure where those rogue `ps2` `input` devices are coming from.  The **_first time_** the XML is output, everything looks correct (right after `DEBUG create_domain: Creating Domain with XML:` in the log).  The **_second time_** is when `vagrant-libvirt` actually starts the VM / `domain`, and that's when the rogue `ps2` devices show up.  That second time is right after `DEBUG start_domain: Starting Domain with XML: ` in the logs.

### Workaround

I have been able to use the `qemuargs` to work around the issue, because they seem to override and actually work to enable keyboard & mouse inside the VM:

```ruby
Vagrant.configure("2") do |config|
  # [...SNIP...]
  config.vm.provider :libvirt do |libvirt|
    # [...SNIP...]
    # If libvirt.input settings don't work... these do!
    libvirt.qemuargs :value => "-device"
    libvirt.qemuargs :value => "usb-tablet"
    libvirt.qemuargs :value => "-device"
    libvirt.qemuargs :value => "usb-kbd"
  end 
end
```

**Comment by electrofelix** [comment]
Looks like I missed there was a need to add an entry to the merge function for inputs, hence it's dropping that it was set to [] already and repopulating it 

See https://github.com/vagrant-libvirt/vagrant-libvirt/blob/b3cf54a946600329d691f81cce32d7c407f8d88e/lib/vagrant-libvirt/config.rb#L1044-L1068

Need to monkey patch that function to merge inputs as well.

**Comment by arg0d** [comment]
Is this part of 0.12.2 release? I can't seem to remove the default ps2 inputs and replace them with usb only inputs.
```
    libvirt.inputs = []
    libvirt.input :type => "mouse", :bus => "usb"
    libvirt.input :type => "keyboard", :bus => "usb"
```

yields
```
    <input type='mouse' bus='usb'>
      <address type='usb' bus='0' port='1'/>
    </input>
    <input type='keyboard' bus='usb'>
      <address type='usb' bus='0' port='2'/>
    </input>
    <input type='mouse' bus='ps2'/>
    <input type='keyboard' bus='ps2'/>
```

**Comment by electrofelix** [comment]
@arg0d best to generate a debug log, I suspect the ps/2 entries must be coming from another Vagrantfile that is loaded as well, e.g. from the box. As the default behaviour is to only add one for the mouse if not already defined
https://github.com/vagrant-libvirt/vagrant-libvirt/blob/1783e762d59ace79a2f2f4db5e460e5a2a8f7592/lib/vagrant-libvirt/config.rb#L1076

**Comment by electrofelix** [comment]
I wonder if things have improved since and it's possible to provide another setting to disable other inputs if there is a mouse/keyboard just on a different bus?

**Comment by electrofelix** [comment]
https://documentation.suse.com/sles/12-SP5/html/SLES-all/cha-qemu-running.html suggests we should look at passing `--nodefaults`, you can add this to the qemu command line used by setting the qemuargs config input as shown https://vagrant-libvirt.github.io/vagrant-libvirt/examples.html#custom-qemu-arguments-and-environment-variables

It's not documented with the other config options

**Comment by arg0d** [comment]
I'm not sure if this is actually related, but I have found a way to make mouse/keyboard work for my VM. I used a similar trick as @trinitronx. I also had to disable usb controller to make mouse work.
```
libvirt.usb_controller :model => "none"
libvirt.qemuargs :value => "-usb"
libvirt.qemuargs :value => "-device"
libvirt.qemuargs :value => "usb-kbd"
libvirt.qemuargs :value => "-device"
libvirt.qemuargs :value => "usb-tablet"
```
