### ISSUE TITLE
How to obtain IP address of an ESXi VM?

### ISSUE THREAD

**Issue by rgl** [vagrant-libvirt/vagrant-libvirt#1099]
I'm trying to run ESXi inside a VM. So far I was able to [create the base vagrant box with packer](https://github.com/rgl/esxi-vagrant) and [start it with vagrant](https://github.com/rgl/esxi-vagrant/blob/master/example/Vagrantfile).

But I'm now stuck at the `Waiting for domain to get an IP address...` part (~~probably because there is no qemu agent inside the VM; also, there is no agent available for ESXi that I'm away of, so I cannot install it~~ oh this actually uses `/var/lib/libvirt/dnsmasq/virbr0.macs` and `/proc/net/arp`); but the VM was able to obtain an IP address from DHCP:

![image](https://user-images.githubusercontent.com/43356/80403105-effd4600-88b6-11ea-9655-8070fa1cb78a.png)

Do you have any advice on how to make it obtain the VM IP address?

I've tried to cross reference he VM mac address `52:54:00:05:cc:be` (as reported by libvirt) with:

`/var/lib/libvirt/dnsmasq/virbr0.macs`:
```json
  {
    "domain": "example_default",
    "macs": [
      "52:54:00:05:cc:be"
    ]
  },
```

BUT `/proc/net/arp` didn't have the expected MAC address:

```plain
IP address       HW type     Flags       HW address            Mask     Device
192.168.121.111  0x1         0x2         52:54:00:12:34:56     *        virbr0
```

Any idea why?

Please note that I'm able to `ssh root@192.168.121.111` and connect to the expected VM.

**Comment by rgl** [comment]
Oh this seems to be an ESXi feature... it just ignorea the current network interface MAC address and always uses the value of `/net/vmkernelnic/child[0000]/mac` key inside `/etc/vmware/esxi.conf`. If I change that value to the MAC address allocated by qemu, everything works fine. So to overcome this I had to hard-code the VM MAC address by using the `management_network_mac` vagrant-libvirt provider property, at least, until I find a better solution.

Please fell free to close this issue if you do not have anything else to add.

**Comment by electrofelix** [comment]
@rgl suggest updating the packer definition to delete the lines in the files after you build the image as part of the clean up phase, before packaging it up. Esx might populate it automatically subsequently. I'd guess that it would look to store the MAC with the same network device name across reboots so to get it to use the one provided automatically, need to get it to treat it as the first time.

https://communities.vmware.com/thread/198665

**Comment by rgl** [comment]
I've deleted the lines but ESXi will never use the qemu set MAC address; it always generates `00:50:56` prefixed MAC address :sob:

**Comment by abbbi** [comment]
hi,

i have only once attempted to use a packaged up ESXi image on with Terraform+libvirt and i think i experienced the same issue. It seems like the mac address used by the ESXi image is hard-coded somewhere in the ESXi configuration. That also meant i was unable to spin up multiple ESXi images on the same host bcs they battled each other for the DHCP leases.

I was able to solve this issue by resetting the ESXI Configuration via the ADMIN menu as one last manual step during packaging the image. I think there is an command line tool that can to the same, which could be called during provisioning with packer.

**Comment by rgl** [comment]
I finally was able to do it at https://github.com/rgl/esxi-vagrant/commit/545a8c18dad13082a4e80fd114b5a7fc3f8da9ea! :-)

I had to use the `local.sh` script to change the `vmk0` mac address to the `vmnic0` address (and restart the `vmk0` interface) and it now works.

Two VMs running:

![image](https://user-images.githubusercontent.com/43356/80574763-59d23880-89fa-11ea-9d3c-5e72a34690ec.png)

Now I have to find a way to make vagrant actually be able to execute scripts in this VM, as its now failing:

```
==> default: Creating shared folders metadata...
==> default: Starting domain.
==> default: Waiting for domain to get an IP address...
==> default: Waiting for SSH to become available...
==> default: Configuring and enabling network interfaces...
==> default: Running provisioner: shell...
    default: Running: inline script
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

But that's for another day :-)

**Comment by rgl** [comment]
Finally managed to get it working at https://github.com/rgl/esxi-vagrant!

Thanks for all the help!
