### ISSUE TITLE
please publish 0.1.0 in rubygems 

### ISSUE THREAD

**Issue by AntonioMeireles** [vagrant-libvirt/vagrant-libvirt#1109]
Hi all, 

now that 0.1.0 is out (great work!) please do not forget to publish it in rubygems 

Thanks in advance, congrats again for all your great and hard work,  and a great weekend!

All the best, 

António

**Comment by electrofelix** [comment]
Working on it, pulled the trigger before I realised I hadn't run it through the final tests

**Comment by electrofelix** [comment]
finally completed the tests with the VMs from vagrant-libvirt-qa and pushed the gem, sorry about the delay.
