### ISSUE TITLE
Help/Feature-Request: Host-only management network

### ISSUE THREAD

**Issue by Cyclic3** [vagrant-libvirt/vagrant-libvirt#1117]
### Requested behaviour
I have been trying to set up a CTF on vagrant. These VMs will be executing vulnerable and untrusted code as root, and so any protections set up on the guest side are worthless.

To this end, I need to stop boxes from interacting with each other through vagrant. Unfortunately, the management interface seems to be routing traffic between guests, allowing lateral movement between supposedly isolated boxes.

Is a form of host-only management network implemented? If not, is it planned?

### System configuration
**OS/Distro version:** Debian/Buster

**Libvirt version:** 5.0.0

**Output of `vagrant version; vagrant plugin list`:**
```
Installed Version: 2.2.3
vagrant-libvirt (0.0.45, system)
```

**Are you using upstream vagrant package or your distros package?**
Distro's package

**Comment by electrofelix** [comment]
@Cyclic3 it you set the `management_network_mode` to `none` this should provide the isolation desired, however it's possible that you will need to pick custom `management_network_name` and `management_network_address` to avoid issues with the default management network already running. Essentially don't handle modifying existing network definitions, so once a machine as the default management network created on it, tend to bump into issues. Instead by naming it uniquely for your environment (or perhaps by embedding the network address in the name?) it should ensure it can be brought in other host environments without issue.

https://github.com/vagrant-libvirt/vagrant-libvirt#management-network

Note I haven't tested this, just basing it off of looking at https://amoldighe.github.io/2017/12/20/kvm-networking/ for the host-only definition and what options into https://github.com/vagrant-libvirt/vagrant-libvirt/blob/master/lib/vagrant-libvirt/templates/private_network.xml.erb should result in the same output.

**Comment by Cyclic3** [comment]
Setting it to none made no difference. However, your suggestion of giving them separate names and addresses worked:
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"

  config.vm.define ("vm1") do |node|
    node.vm.provider "libvirt" do |libvirt|
      libvirt.management_network_mode = "none"
      libvirt.management_network_name = "vm1"
      libvirt.management_network_address = "192.168.255.0/30"
    end
  end

  config.vm.define ("vm2") do |node|
    node.vm.provider "libvirt" do |libvirt|
      libvirt.management_network_mode = "none"
      libvirt.management_network_name = "vm2"
      libvirt.management_network_address = "192.168.255.4/30"
    end
  end
end
```
Assigning disjoin subnets does seem a bit hacky to me, but I'm going to run with what I've got for now.

Thanks for the help!

**Comment by electrofelix** [comment]
@Cyclic3 based on your experience, and some quick checking here, it does appear that there isn't a way in libvirt to configure routing to prevent VMs on the same subnet from communicating with one another. Probably doesn't make sense when instead you can define separate subnets to prevent communication anyway.

Just be aware that use of `none` will also typically mean that it is not possible to access the internet from any of the machines brought up, so no `apt-get update`.
