### ISSUE TITLE
`vagrant destroy -f` does not delete all metadata

### ISSUE THREAD

**Issue by pvalena** [vagrant-libvirt/vagrant-libvirt#1132]
### Steps to reproduce
1. Create Vagranfile which changes `config.vm.box` based on ENV
2. Run vagrant up + halt + destroy
3. Switch ENV (if the issue does not occur on the first try GOTO 2.)

### Expected behaviour
If I run with changed box / image (based on ENV), f.e. centos/6 instead of centos/7; I'd expect vagrant to spin up correct instance.

### Actual behaviour
The box image and version is saved in `.vagrant/machines/default/libvirt/box_meta` even though the instance got destroyed and the metadata get's reused => wrong instance gets started.
This can be worked around when running vagrant destroy twice, or removing `.vagrant/` folder manually f.e..

### System configuration
**OS/Distro version:**: Fedora (Rawhide, F32, F33)

**Libvirt version:** libvirt-6.5.0-1.fc33.x86_64

**Output of `vagrant version; vagrant plugin list`:**  Installed Version: 2.2.9

Vagrant was unable to check for the latest version of Vagrant.
Please check manually at https://www.vagrantup.com
vagrant-libvirt (0.1.2, system)
vagrant-managed-servers (0.8.0, system)
vagrant-rsync-back (0.0.1, system)
vagrant-sshfs (1.3.5, system)
# The issue occurs  on various systems with different plugins installed

**Output of .... (shortened)**
```
# Following a up + destroy of  box `centos/6`
centos_version = 7
Bringing machine 'default' up with 'libvirt' provider...
==> default: Checking if box 'centos/6' version '2004.01' is up to date...
==> default: Creating image (snapshot of base box volume).
==> default: Creating domain with the following settings...
==> default:  -- Name:              c2r-vagrant_default
==> default:  -- Domain type:       kvm
==> default:  -- Cpus:              1
==> default:  -- Feature:           acpi
==> default:  -- Feature:           apic
==> default:  -- Feature:           pae
==> default:  -- Memory:            512M
==> default:  -- Management MAC:
==> default:  -- Loader:
==> default:  -- Nvram:
==> default:  -- Base box:          centos/6
 [ . . . ]
```
Full log: https://gist.github.com/pvalena/42d23810e975d5594117cc1647b3b28f
(Workaround: double `destroy`: [log](https://gist.github.com/pvalena/3b810979c8e7a6307a6b28a0538acd34))
I can supply a LOG with DEBUG on if you like.

**A Vagrantfile to reproduce the issue:**
```
# The one from example
centos_version = ENV["CENTOS"] || "7"

puts "centos_version = #{centos_version}"

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.box = "centos/"+centos_version
end
```

**Are you using upstream vagrant package or your distros package?**
 Distro

**Comment by electrofelix** [comment]
vagrant_libvirt doesn't create this file, it belongs to vagrant itself: https://github.com/hashicorp/vagrant/blob/c61f58049cb8c4c29bc4b61314e9e882aea843fc/plugins/commands/up/middleware/store_box_metadata.rb#L19-L29

Though I do see they have one provider that explicitly deletes the directory and recreates it due to collisions https://github.com/hashicorp/vagrant/commit/fe8fe55d1f10903de4f5751564bc3949bbec4e37, though that seems a bit like using a hammer. As this is something created by the up command it seems like it should be removed by the destroy command rather than having other plugins guess when to delete/recreate. It may well be that the fix for this in the destroy command could be extended to cover the above change that was introduced by https://github.com/hashicorp/vagrant/pull/9943

I'm aware that some plugins such as the vagant-cache could store additional data there (if you enabled the machine scoped cache) so there maybe others using it to cache between destroy/up runs where it might be valid, or at least undesirable for the provider to be deciding whether to delete/recreate this area.

I think best to log with vagrant at https://github.com/hashicorp/vagrant/issues, link back to this issue and I'll keep this open in case they indicate this should be removed by providers with an option.

**Comment by pvalena** [comment]
@electrofelix thanks for investigating!

It turns out the advice is to create [provider-specific action](https://github.com/hashicorp/vagrant/issues/11800#issuecomment-667254531) to clean up the machines folder, before some built-in action is created further on.

**Comment by electrofelix** [comment]
@paravz yeap, assigning to myself so that I remember to look at adding a fix for this.

**Comment by paravz** [comment]
perhaps ^^ was meant for @pvalena  ?

**Comment by electrofelix** [comment]
@paravz yes, apologies, sometimes when using the `@` it appears it doesn't start with using the nicks of people in the conversation by default.

@pvalena see above

**Comment by pvalena** [comment]
@electrofelix thanks!

**Comment by Jeansen** [comment]
What about the pool folder? I found out that when I destroy a vm, the pool folder still holds the image and I have to manually delete it. If I do not delete the pool image created from the first 'up', It will always be used in future vm creations with 'vagrant up'.

**Comment by pvalena** [comment]
> What about the pool folder? I found out that when I destroy a vm, the pool folder still holds the image and I have to manually delete it. If I do not delete the pool image created from the first 'up', It will always be used in future vm creations with 'vagrant up'.

That's the expected behaviour AFAIK. In Fedora, we advise (can't find the warning though; will check later) users to remove it themselves, if they don't need it anymore. I, f.e. run this:

```console
➜  vagrant box list
There are no installed boxes! Use `vagrant box add` to add some.
➜  vol-list --pool default | cut -d' ' -f2 | grep '\-VAGRANTSLASH\-' | xargs -rn1 virsh vol-delete --pool default
Vol centos-VAGRANTSLASH-6_vagrant_box_image_2004.01.img deleted

Vol centos-VAGRANTSLASH-7_vagrant_box_image_2004.01.img deleted

Vol debian-VAGRANTSLASH-stretch64_vagrant_box_image_9.12.0.img deleted

Vol fedora-VAGRANTSLASH-32-cloud-base_vagrant_box_image_32.20200422.0.img deleted

Vol fedora-VAGRANTSLASH-33-cloud-base_vagrant_box_image_33.20201019.0.img deleted
```

AFAIR, from last discussion: this is "out of hands" of vagrant-libvirt, as it's specific behaviour to libvirt, which "Vagrant" knows nothing about.

**Comment by Jeansen** [comment]
Oh, I see. Thanks for the details. But maybe it is worth a hint in the libvirt-pluin's documentation. At least for me it was not obvious and took me "some time" until I figured it out.

I think I'll put your one-liner in a trigger that runs after I destroy a vm.
