### ISSUE TITLE
NIC duplicates created when using vagrant-libvirt

### ISSUE THREAD

**Issue by Otterian** [vagrant-libvirt/vagrant-libvirt#1165]
### Steps to reproduce
1. Install Vagrant and Vagrant-Libvirt
2. Create a Vagrantfile with the following content:

```
# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

 config.vm.define :test do |test|
  test.vm.provider :libvirt do |libvirt|
  test.vm.box = "generic/ubuntu1804"
  test.vm.network :private_network, :network_name =>"internal", :ip =>"192.168.125.10"
  test.vm.hostname = "openstacktest"
  test.vm.provision "shell", path: "provision.sh"
   end
  end
end
```

3. Run ```vagrant up --provider=libvirt```

### Expected behaviour
A VM is created with the default SSH management interface, and one (1) other interface with IP 192.168.125.10

### Actual behaviour
Three (3) interfaces are created, where only one has IP 192.168.125.10, the rest has 192.168.125.0 (address conflict)

### System configuration
**OS/Distro version:**: Ubuntu 18.04

**Libvirt version:** 4.0.0

**Output of `vagrant version; vagrant plugin list`:**
vagrant-libvirt (0.2.1, global)

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**

[vagrant.log](https://github.com/vagrant-libvirt/vagrant-libvirt/files/5545629/vagrant.log)

**A Vagrantfile to reproduce the issue:**
```
# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

 config.vm.define :test do |test|
  test.vm.provider :libvirt do |libvirt|
  test.vm.box = "generic/ubuntu1804"
  test.vm.network :private_network, :network_name =>"internal", :ip =>"192.168.125.10"
  test.vm.hostname = "openstacktest"
  test.vm.provision "shell", path: "provision.sh"
   end
  end
end
```

**Are you using upstream vagrant package or your distros package?**
Upstream

NOTE this section of the debug log:
```
 INFO create_networks: Using vagrant-libvirt at 192.168.121.0/24 as the management network nat is the mode
DEBUG create_networks: In config found network type private_network options {:network_name=>"internal", :ip=>"192.168.125.10", :protocol=>"tcp", :id=>"d7aa51a6-67df-4e78-bd07-a5a70dc57bfc"}
DEBUG create_networks: In config found network type private_network options {:network_name=>"internal", :ip=>"192.168.125.10", :protocol=>"tcp", :id=>"b0c76337-d932-4d8a-9b9d-919655d56ab0"}
DEBUG create_networks: In config found network type private_network options {:network_name=>"internal", :ip=>"192.168.125.10", :protocol=>"tcp", :id=>"1a99878b-a479-469e-b969-e57776fa8672"}
DEBUG create_networks: In config found network type forwarded_port options {:guest=>22, :host=>2222, :host_ip=>"127.0.0.1", :id=>"ssh", :auto_correct=>true, :protocol=>"tcp"}
DEBUG create_networks: Searching for network with options {:iface_type=>:private_network, :network_name=>"vagrant-libvirt", :ip=>"192.168.121.0", :netmask=>"255.255.255.0", :dhcp_enabled=>true, :forward_mode=>"nat", :guest_ipv6=>"yes", :autostart=>false, :bus=>nil, :slot=>nil}
DEBUG create_networks: looking up network with ip == 192.168.121.0
DEBUG create_networks: Checking that network name does not clash with ip
DEBUG create_networks: Searching for network with options {:iface_type=>:private_network, :netmask=>"255.255.255.0", :dhcp_enabled=>true, :forward_mode=>"nat", :network_name=>"internal", :ip=>"192.168.125.10", :protocol=>"tcp", :id=>"d7aa51a6-67df-4e78-bd07-a5a70dc57bfc"}
DEBUG create_networks: looking up network with ip == 192.168.125.0
DEBUG create_networks: Checking that network name does not clash with ip
DEBUG create_networks: Searching for network with options {:iface_type=>:private_network, :netmask=>"255.255.255.0", :dhcp_enabled=>true, :forward_mode=>"nat", :network_name=>"internal", :ip=>"192.168.125.10", :protocol=>"tcp", :id=>"b0c76337-d932-4d8a-9b9d-919655d56ab0"}
DEBUG create_networks: looking up network with ip == 192.168.125.0
DEBUG create_networks: Checking that network name does not clash with ip
DEBUG create_networks: Searching for network with options {:iface_type=>:private_network, :netmask=>"255.255.255.0", :dhcp_enabled=>true, :forward_mode=>"nat", :network_name=>"internal", :ip=>"192.168.125.10", :protocol=>"tcp", :id=>"1a99878b-a479-469e-b969-e57776fa8672"}
DEBUG create_networks: looking up network with ip == 192.168.125.0
DEBUG create_networks: Checking that network name does not clash with ip
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::CreateNetworkInterfaces:0x00007f03a8c37820>
 INFO create_network_interfaces: Using vagrant-libvirt at 192.168.121.0/24 as the management network nat is the mode
DEBUG create_network_interfaces: In config found network type private_network options {:network_name=>"internal", :ip=>"192.168.125.10", :protocol=>"tcp", :id=>"d7aa51a6-67df-4e78-bd07-a5a70dc57bfc"}
DEBUG create_network_interfaces: In config found network type private_network options {:network_name=>"internal", :ip=>"192.168.125.10", :protocol=>"tcp", :id=>"b0c76337-d932-4d8a-9b9d-919655d56ab0"}
DEBUG create_network_interfaces: In config found network type private_network options {:network_name=>"internal", :ip=>"192.168.125.10", :protocol=>"tcp", :id=>"1a99878b-a479-469e-b969-e57776fa8672"}
DEBUG create_network_interfaces: In config found network type forwarded_port options {:guest=>22, :host=>2222, :host_ip=>"127.0.0.1", :id=>"ssh", :auto_correct=>true, :protocol=>"tcp"}
DEBUG create_network_interfaces: Adapter not specified so found slot 0
DEBUG create_network_interfaces: Found network by name
DEBUG create_network_interfaces: Adapter not specified so found slot 1
DEBUG create_network_interfaces: Found network by name
DEBUG create_network_interfaces: Adapter not specified so found slot 2
DEBUG create_network_interfaces: Found network by name
DEBUG create_network_interfaces: Adapter not specified so found slot 3
DEBUG create_network_interfaces: Found network by name
 INFO create_network_interfaces: Creating network interface eth0 connected to network vagrant-libvirt.
 INFO create_network_interfaces: Creating network interface eth1 connected to network internal.
 INFO create_network_interfaces: Creating network interface eth2 connected to network internal.
 INFO create_network_interfaces: Creating network interface eth3 connected to network internal.
```

If/when the VM actually comes up, I can see that it has three interfaces belonging to the 192.168.125.0 subnet, but only one with an allocatable IP address (192.168.125.10).

Is this intentional? Is there a caveat I'm not aware of? Is there an error in my Vagrantfile?

Any help is appreciated.

**Comment by electrofelix** [comment]
@Otterian the section of the debug log provided containing the multiple network interfaces being added is coming from https://github.com/vagrant-libvirt/vagrant-libvirt/blob/master/lib/vagrant-libvirt/util/network_util.rb#L91-L112, however that is just parsing the config.vm.networks provided by vagrant, so unless something has changed significantly it should only be getting a single private_network definition.

The only way I can see it having multiple definitions (outside of a bug in upstream vagrant) is if there were other private_network definitions specified in other Vagrantfile's that get merged in.

Typically the final config passed in is the combined result of the following:
* Vagrantfile from the vagrant box (see /home/testuser/.vagrant.d/boxes/generic-VAGRANTSLASH-ubuntu1804/3.1.4/libvirt/Vagrantfile)
* project Vagrantfile (see /home/testuser/openstacktest/Vagrantfile)
* user global Vagrantfile ~/.vagrant.d/Vagrantfile

I would suggest checking `~/.vagrant.d/Vagrantfile` to see if you have any additional network definitions. I'd be surprised if there was a stray one in /home/testuser/.vagrant.d/boxes/generic-VAGRANTSLASH-ubuntu1804/3.1.4/libvirt/Vagrantfile but probably no harm to check there as well.

**Comment by Otterian** [comment]
I looked in the box Vagrantfile, aswell as for the global Vagrantfile (which I couldn't find unfortunately), so I'm still very much clueless as to what could be causing this. I'll try reverting to an previous release of Vagrant - see if that eliminates the issue.

**Comment by electrofelix** [comment]
@Otterian I've done some experimenting and I can trigger the bug locally. If you switch your config to the following it goes away
```
Vagrant.configure("2") do |config|

  config.vm.define :test do |test|
    test.vm.box = "generic/ubuntu1804"
    test.vm.network :private_network, :network_name =>"internal", :ip =>"192.168.125.10"
    test.vm.hostname = "openstacktest"
    test.vm.provision "shell", path: "provision.sh"
  end
end
```

It appears to be due to when you wrap the standard vagrant options inside a provider block, it appears to trigger the network settings to get multiplied.

I'm not entirely sure why, might be a bug in vagrant itself, but the workaround seems to be to just avoid that approach.

**Comment by Otterian** [comment]
I see. Many thanks!

Here's what I've done so far:

- Reverted first to 2.0.0 - that broke the Ruby loader used by vagrant-share.
- Then moved on to 2.0.4, which is a version that is tested by the project's Travis CI. That caused Vagrant to complain:
==> test: Error when updating domain settings: undefined method `strip' for nil:NilClass
However, 2.0.4 gave me some very promising output prior to that error message, indicating that it had indeed discovered just one additional interface. Progress! Tried 2.1.0 afterwards, but still got the same error message, unfortunately.

**Comment by Otterian** [comment]
The output 2.0.4 gave me suggests very strongly that this is a bug that has been introduced in later versions of Vagrant. If only I had intricate knowledge of Ruby, and knew what version introduced this bug, we could probably locate the commit that introduced it and have them fix it upstream.

**Comment by Otterian** [comment]
I think I'll close this issue now. Perhaps put it the documentation that mixing options will cause strange issues?

Thanks for your help :)
