### ISSUE TITLE
What is the default host IP?

### ISSUE THREAD

**Issue by zilti** [vagrant-libvirt/vagrant-libvirt#1174]
What is the default host IP for vagrant-libvirt? I am running a development machine using Vagrant, and the XDebug running inside has to be able to connect to the host machine. For the default VirtualBox Vagrant, the host IP is always 10.0.2.2, but I haven't been able to figure out the equivalent for libvirt as provider. Are there special settings needed for this?

**Comment by electrofelix** [comment]
Assuming using the default of `192.168.121.0/24` as the management network, `192.168.121.1` should be the host machine, though whether you can connect or not is another question. May depend on firewall and whether libvirt sets up the correct routing, I haven't tested connecting back from the guest to the host that I can recall

**Comment by electrofelix** [comment]
Just confirmed locally, provided the host allows ssh connections on the management network, you can connect back from the guest to the host by using the first assignable IP address in the management network range. By default this should be 192.168.121.1.
