### ISSUE TITLE
Network Interface Order?

### ISSUE THREAD

**Issue by LeShaunJ** [vagrant-libvirt/vagrant-libvirt#1180]
This is more of a general question of interest than anything else... Why is `e(th|em|en)0` reserved for the Management Interface?

I understand why it has to be DHCP; I understand it's importance; but, I don't understand why I needs to be the first interface. It strikes me as odd; since the MGMT port/interface in general physical networking is normally set aside in it's own "realm" of sorts. It is rare to see it as the main, defacto interface.

I'm no stranger to automating `libvirt`; and, a MGMT interface is a much; though, in my own work such an interface is always in last last position (_first, only if not additional interfaces are configured by the end-user_); it is strict, exclusive, predictable; and, it is largely unknown by the end-user unless they're looking for it--even if it _does_ facilitate their primary method of accessing the server (_think, `vagrant ssh`_). Now obviously I don't know all the ins and outs of this plugin; but, this aspect definitely had me wondering. 

With that, I had made some edits to, `util/network_util.rb`, in attempt to get my preferred primary IP in the first position; this lead to vagrant "`Waiting for domain to get an IP address`" indefinitely. I knew it was erroneously doing so, as I was consoled into the VM, pinging-out successfully from both interfaces. At this point, I'm certain the MGMT interface's position is important to the whole setup; though, I know from my own experience with vanilla `libvirt`, that a MGMT interface's position doesn't necessarily halt one's ability for automation from the host, unless other factors are at play.

So yeah, I just wanted to know why the MGMT interface's position has been restricted to the top; and I guess, why you decided against pushing it to the end.

**Comment by electrofelix** [comment]
I'd have to dig into the history a bit to be sure, but the answer is probably a combination of convenience and consistency making the guest VM creation easier.

By using the first device for the mgmt network, libvirt boxes for vagrant need only require that they are configured to dhcp the first device. All subsequent network configuration would then be created by vagrant by using the mgmt network connection. To make it the last device, the VMs would need to arbitrarily enable and attempt to dhcp boot as many network devices as appear on first boot unless they could explicitly just dhcp the last device (seems like it would require a bit of scripting in the guest to achieve that). Now that might work these days, and it might be possible to set up the OS to continue as soon as one of those devices was successfully configured allowing it to bring up SSH which will be used for performing any tasks required for the guest configuration. But setting up the guest during initial creation to behave that way seems more prone to unexpected issues than if by default the guest need only focus on dhcp booting the first device, as that typically works out of the box with most distributions.

Subsequent additional network configuration can then be tailored by the writer of the Vagrantfile based on OS guest behaviour combined with how vagrant handles network configuration.

**Comment by LeShaunJ** [comment]
Ah I see; makes sense. Off the top of my head, I'd suggest that the additional networks be set as initially disabled, in order to establish the MGMT interface as the main guy during provisioning. All other can be brought up once it's received it's IP thereafter.

Of course, this is just a suggestion that doesn't have any bearing on what I'm doing with it; though, I can see this being something end-users would appreciate if only to keep expectations at bay.

Thanks for the quick response, and for the amazing work!

**Comment by electrofelix** [comment]
I don't think it's possible for vagrant-libvirt to control whether the other networks are enabled/disabled, because they are essentially configured by vagrant itself. This project does need to ensure the definitions for the network devices emulated hardware are created in the libvirt domain XML, however the configuration after boot and when that happens is managed by vagrant after vagrant-libvirt has established the ability to connect via SSH through the mgmt interface.

Possibly should look into whether the mgmt is between host and guest only, but at this stage it might break a lot of expected configurations where provisioning assumes connectivity outside of the host, so it would need to be a trivial fallback or easily switched back.

At moment with only 1 active maintainer it's probably a bit too much to consider tweaking the network implementation as is. That may change in the future.

**Comment by anarsen** [comment]
@LeShaunJ I came across your issue in the search for a solution to the very same problem. 

I noticed the `mgmt_attach` key on the libvirt provider: https://vagrant-libvirt.github.io/vagrant-libvirt/configuration.html
