### ISSUE TITLE
Version tagging not working when using the release zip

### ISSUE THREAD

**Issue by zaroth** [vagrant-libvirt/vagrant-libvirt#1181]
Steps to reproduce:
```
wget https://github.com/vagrant-libvirt/vagrant-libvirt/archive/0.3.0/vagrant-libvirt-0.3.0.tar.gz
tar xvf vagrant-libvirt-0.3.0.tar.gz
cd vagrant-libvirt-0.3.0/
gem build vagrant-libvirt.gemspec
```

Result: `vagrant-libvirt-0.gem`
Expected result: `vagrant-libvirt-0.3.0.gem`

This is a regression from 0.2.1, where if you replace the wget link with `https://github.com/vagrant-libvirt/vagrant-libvirt/archive/0.2.1/vagrant-libvirt-0.2.1.tar.gz` in the commands above, everything works and tags correctly. Most likely caused by #1161 by @electrofelix.

**Comment by electrofelix** [comment]
Not sure if I can replace the listed archives with ones generated to contain the version file at release time, but I can try. 

Otherwise is just having the alternative tarballs with the version file contained available under the assets section of each release at https://github.com/vagrant-libvirt/vagrant-libvirt/releases sufficient for your use case?

**Comment by electrofelix** [comment]
I might be able to do something about inserting the tag correctly for release tarballs based on https://git-scm.com/docs/gitattributes#_export_subst as apparently github uses git-archive behind the scenes.

**Comment by zaroth** [comment]
My problem showed when I tried to update the AUR package for Arch Linux - the packaging script ran into an unexpected filename and a simple version update wasn't enough, but it looked like a bug to me. If it's not a bug and the script needs to be changed instead, I guess that's fine, too. The script in question is here https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=vagrant-libvirt (I'm not the maintainer, although I mailed the 0.2.1 AUR PKGBUILD to maintainer already).

**Comment by electrofelix** [comment]
Technically this won't be fully fixed until the next release

**Comment by zaroth** [comment]
So, I just tried this using the new 0.4.0 release - the bug still occurs. Building from the `vagrant-libvirt-0.4.0.tar.gz` package results in `vagrant-libvirt-0.gem` being created.

**Comment by electrofelix** [comment]
@zaroth I downloaded https://github.com/vagrant-libvirt/vagrant-libvirt/archive/refs/tags/0.4.0.tar.gz locally as ~/Downloads/vagrant-libvirt-0.4.0.tar.gz and ran the following steps:
```
tar -xzf ~/Downloads/vagrant-libvirt-0.4.0.tar.gz
cd vagrant-libvirt-0.4.0/
# I use rvm to maintain multiple installs locally so I can test quickly, but I created an area from pristine here
rvm use ruby-2.6.5@vagrant-libvirt-release --create
VAGRANT_VERSION=v2.2.14 bundle install
VAGRANT_VERSION=v2.2.14 bundle exec rake build
```
and it results in getting a package ./pkg/vagrant-libvirt-0.4.0.gem


I've also tried the following:
```
wget https://github.com/vagrant-libvirt/vagrant-libvirt/archive/0.4.0/vagrant-libvirt-0.4.0.tar.gz
tar -xzf vagrant-libvirt-0.4.0.tar.gz
cd vagrant-libvirt-0.4.0/
gem build vagrant-libvirt.gemspec
```

And this produced the following output
```
WARNING:  description and summary are identical
WARNING:  open-ended dependency on contextual_proc (>= 0, development) is not recommended
  use a bounded requirement, such as '~> x.y'
WARNING:  open-ended dependency on simplecov (>= 0, development) is not recommended
  use a bounded requirement, such as '~> x.y'
WARNING:  open-ended dependency on simplecov-lcov (>= 0, development) is not recommended
  use a bounded requirement, such as '~> x.y'
WARNING:  open-ended dependency on fog-libvirt (>= 0.6.0) is not recommended
  if fog-libvirt is semantically versioned, use:
    add_runtime_dependency 'fog-libvirt', '~> 0.6', '>= 0.6.0'
WARNING:  open-ended dependency on rake (>= 0, development) is not recommended
  use a bounded requirement, such as '~> x.y'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: vagrant-libvirt
  Version: 0.4.0
  File: vagrant-libvirt-0.4.0.gem
```

Am I missing something in how this is working?

The magic is all down to the contents of lib/vagrant-libvirt/version.rb, you should see a constant in there:
```
GIT_ARCHIVE_VERSION = "a16c3f7898ed33fb38f936c956fa22bb6c91a8d2 tag: 0.4.0"
```

Essentially git archive is replacing a placeholder `"$Format:%H %D$"` in that file with a commit and it's description, which for releases contains the tag. It's then extracted and written to a file during the build process that is triggered by the action of simply retrieving the version in the vagrant-libvirt.gemspec file.
