### ISSUE TITLE
Docker based Installation does not work

### ISSUE THREAD

**Issue by pgillich** [vagrant-libvirt/vagrant-libvirt#1191]
### Steps to reproduce

Running the image by `docker run -it --rm ...`, as described on README.md, on a vanilla Linux (vagrant was never ran on the machine).

### Expected behaviour

vagrant starts without error, for example:

```
vagrant up master
Starting with UID: 1000, GID: 1001
Bringing machine 'master' up with 'libvirt' provider...
(...)
```

### Root causes

On a vanilla Linux install, the `~/.vagrant.d` does not exists, so the Docker will create it in root rights. If the `~/.vagrant.d` exists with root owner, the container cannot create `boxes`, `data`, `tmp` directories.

Another problem with the `docker run` command: the container cannot ssh to the VM, because the `--network host` is missing.

### Solutions

Extending the documentation by below comment:

Before first start of **Docker based Installation**, make sure, all needed directories exists and owned by you, for example:

```
mkdir -p ~/.vagrant.d/{boxes,data,tmp}
ls -la ~/.vagrant.d # All dirs must be owned by you
```

Adding `--network host` to the `docker run` command, for example:

```
docker run -it --rm --network host ...
```

### Improvement

The `docker run` command can be called by an alias, which may be added to `~/.bashrc`. Example:

```
alias vagrant='docker run -it --rm --network host -e LIBVIRT_DEFAULT_URI -v /var/run/libvirt/:/var/run/libvirt/ -v ~/.vagrant.d:/.vagrant.d -v $(pwd):$(pwd) -w $(pwd) vagrantlibvirt/vagrant-libvirt:latest vagrant'
```

### Actual behaviour

Instead of starting the vagrant, below output is printed out:

```
WARNING! Running as root, if this breaks, you get to keep both pieces
Starting with UID: 0, GID: 0
chown: invalid user: 'vagrant:users'
usermod: user 'vagrant' does not exist
```

After the user right issue is solved, vagrant, from the container, cannot ssh to the VM (cannot check the IP address), because it's not on the host network.

### System configuration

**OS/Distro version:** Lubuntu 20.04 (same on Lubuntu 18.04)

**Libvirt version:** 6.0.0-0ubuntu8.5

**Output of `vagrant version; vagrant plugin list`:**

```
Installed Version: 2.2.10
Latest Version: 2.2.14
```

```
vagrant-libvirt (0.3.0, global)
  - Version Constraint: 0.3.0
```

**Attach Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt >vagrant.log 2>&1`**

```
WARNING! Running as root, if this breaks, you get to keep both pieces
Starting with UID: 0, GID: 0
chown: invalid user: 'vagrant:users'
usermod: user 'vagrant' does not exist
```

**A Vagrantfile to reproduce the issue:**

Any Vagrantfile

**Are you using upstream vagrant package or your distros package?**

It's a documentation bug, so this repo should be changed.

**Comment by lostz** [comment]
same as me

**Comment by electrofelix** [comment]
Thanks, I probably forgot the network thing when I put the docs together and as I already had vagrant running locally wouldn't have seen the issue.

If you get a chance to create a PR update the docs for the network option and the alias that would help.

I'll have to rethink about the directory mounts. Possibly might just switch to asking for the user home to be mounted in as will need access to `~/.local/...` for anyone using user session or looking to access iso images from under they home path. That would allow creation of the various directories with the right uid/gid when starting from pristine as well

**Comment by pgillich** [comment]
I've created a PR: https://github.com/vagrant-libvirt/vagrant-libvirt/pull/1194
It adds a `ENV VAGRANT_DEFAULT_PROVIDER=libvirt` to Dockerfile, because it's practical to force it.

FYI, I need to use 2 Vagrant plugins, so I made patched the Dockerfile to build it, too. It's not the PR:
https://github.com/pgillich/kubeadm-vagrant/blob/master/Ubuntu/build_vagrant-libvirt.sh

**Comment by electrofelix** [comment]
@pgillich for the plugin installs I suspect you can just use a `FROM vagrantlibvirt/vagrant-libvirt` and perform the run of installing the 2 additional plugins. The reason that this project needs to do a slightly more convoluted approach is due to the need to compile and link against additional libraries. AFAIK neither vagrant-mutate nor vagrant-hostmanager need this, so the install doesn't need to occur in the same way.

**Comment by pgillich** [comment]
> @pgillich for the plugin installs I suspect you can just use a `FROM vagrantlibvirt/vagrant-libvirt` and perform the run of installing the 2 additional plugins. The reason that this project needs to do a slightly more convoluted approach is due to the need to compile and link against additional libraries. AFAIK neither vagrant-mutate nor vagrant-hostmanager need this, so the install doesn't need to occur in the same way.

I've created a new issue for using more plugins (which is the typical use case): https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1198
We can discuss about it there.

**Comment by mohd-akram** [comment]
Any update on this? Still getting this issue.

**Comment by pgillich** [comment]
> Any update on this? Still getting this issue.

You can build own Docker image, see: https://github.com/pgillich/kubeadm-vagrant/tree/master/Ubuntu#install-vagrant , which refers to my script: https://github.com/pgillich/kubeadm-vagrant/blob/master/Ubuntu/build_vagrant-libvirt.sh#L13

**Comment by ekeyme** [comment]
same as me
