### ISSUE TITLE
Warning message on box remove from vagrant-libvirt printed even when using virtualbox provider

### ISSUE THREAD

**Issue by filippog** [vagrant-libvirt/vagrant-libvirt#1196]
### Steps to reproduce
1. vagrant box remove --provider=virtualbox foobox
2.
3.

### Expected behaviour
No libvirt-related messages are printed when removing virtualbox boxes

### Actual behaviour
```
$ vagrant box add --provider=virtualbox test-testing testing.box
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'test-testing' (v0) for provider: virtualbox
    box: Unpacking necessary files from: file:///home/godog/src/vagrant-boxes/packer-virtualbox-vagrant/testing.box
    box: Successfully added box 'test-testing' (v0) for 'virtualbox'!
$ vagrant box list | grep -i test-testing
test-testing     (virtualbox, 0)
$ vagrant box remove --provider=virtualbox test-testing
Removing box 'test-testing' (v0) with provider 'virtualbox'...
Vagrant-libvirt plugin removed box only from your LOCAL ~/.vagrant/boxes directory
From Libvirt storage pool you have to delete image manually(virsh, virt-manager or by any other tool)
$
```

### System configuration
**OS/Distro version:**: Debian vagrant-libvirt	0.3.0-1

**Libvirt version:**  libvirt-daemon	5.0.0-4+deb10u1

**Output of `vagrant version; vagrant plugin list`:**

```
$ vagrant version; vagrant plugin list
Installed Version: 2.2.6

Vagrant was unable to check for the latest version of Vagrant.
Please check manually at https://www.vagrantup.com
vagrant-google (2.6.0, global)
vagrant-libvirt (0.3.0, system)
```

**Are you using upstream vagrant package or your distros package?**
Distro

**Comment by electrofelix** [comment]
looks like we should be checking the box format at https://github.com/vagrant-libvirt/vagrant-libvirt/blob/master/lib/vagrant-libvirt/action/remove_libvirt_image.rb#L12

**Comment by filippog** [comment]
I realized I didn't use latest Vagrant, with 2.2.14 I can't seem to reproduce this bug. Can you @electrofelix ?

**Comment by electrofelix** [comment]
Looks like something changed in Vagrant that prevents the hook from being ever called, so it's now even more broken since 2.2.11 but hadn't been noticed.
