### ISSUE TITLE
Windows 10 install problem : could not write value VagrantFeature to key

### ISSUE THREAD

**Issue by BadJony** [vagrant-libvirt/vagrant-libvirt#1215]
Windows 10 install problem : could not write value VagrantFeature to key

I tried all the solutions I found on the internet, but they still didn't work

**Comment by electrofelix** [comment]
I'm sorry but I don't understand the bug report, I don't see where such an error message could come from this project so I have to assume it must be from vagrant itself or somewhere else.

**Comment by RFinland** [comment]
same here

**Comment by electrofelix** [comment]
As mentioned before, I don't see how this is related to vagrant-libvirt, this is something on windows to do with permissions and vagrant itself trying to write to the registry which is not something that this project has any interaction with
