### ISSUE TITLE
Vagrant stucks on "Waiting for SSH to become available" when using remote libvirt with LIBVIRT_DEFAULT_URI

### ISSUE THREAD

**Issue by ElArtista** [vagrant-libvirt/vagrant-libvirt#1217]
When trying ```vagrant up``` a simple Vagrantfile on a remote libvirtd instance with the LIBVIRT_DEFAULT_URI set to ```qemu+ssh://beefyhost/system```, it gets stuck at "Waiting for SSH to become available", but the same Vagrantfile works flowlessly if scp'd in the remote and run from there

Running Arch Linux on both the local and remote machine
Using Vagrant 2.2.10 (I would be using the latest if it wasn't for #12202)

**Comment by ElArtista** [comment]
Just found out that its an access issue to the management network!
Couldn't we use SSH tunneling when specifying a `qemu+ssh` libvirt connection to tunnel traffic to the newly created vm instead of using the management interface?

**Comment by electrofelix** [comment]
That's absolutely what is supposed to be happening, see https://github.com/vagrant-libvirt/vagrant-libvirt/blob/d4d82d977309895644622ddea35bb3ed23399edb/lib/vagrant-libvirt/provider.rb#L71 , I think it got broken with the changes to support the LIBVIRT_DEFAULT_URI, when that is set the other config properties are not being set correctly, or the nc command used to proxy the connection may be hanging

**Comment by ElArtista** [comment]
What are the LIBVIRT_DEFAULT_URI changes that could cause the regression?
Also by quickly modifying `provider.rb`and adding a print, seems that `@machine.provider_config.host` is empty?

**Comment by ElArtista** [comment]
If I specify username and host manually along with connect_via_ssh flag it now works, but it hangs when trying to reconnect with the new key. Seems related to #921

**Comment by ElArtista** [comment]
Can confirm that if I change proxy_command here: https://github.com/vagrant-libvirt/vagrant-libvirt/blob/bb2b022d3fb58375984f1d96c6a41c6481465b51/lib/vagrant-libvirt/provider.rb#L76 to ```-W %h:%p``` instead of ```nc %h %p``` that I can successfully run my Vagrantfile.

I suppose that the next steps into making this work as expected are:
- Change proxy_command postfix payload from ```nc %h %p``` to ```-W %h:%p``` as proposed in #921
- Deconstruct LIBVIRT_DEFAULT_URI to obtain host, username and id_ssh_key_file values to avoid specifying them manually again (reverse of what happens here https://github.com/vagrant-libvirt/vagrant-libvirt/blob/bb2b022d3fb58375984f1d96c6a41c6481465b51/lib/vagrant-libvirt/config.rb#L703)
- Make username and id_ssh_key_file values and flags optional when constructing proxy_command (the user might be using ssh-agent or some ssh config that can allow them using just a name for the ssh connection like my case)
