### ISSUE TITLE
Ruby Gem rexml not builted-in

### ISSUE THREAD

**Issue by Ricky-Tigg** [vagrant-libvirt/vagrant-libvirt#1244]
**OS:** Fedora 34; **Components:** vagrant-libvirt-0.1.2-3.fc34.noarch, vagrant-2.2.9-6.fc34.noarch; **Vagrant image:** _generic/fedora33_.

```
$ vagrant up
Bringing machine 'default' up with 'libvirt' provider...
<internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- rexml/document (LoadError)
```
No component listed with "_rexml_" from output resulting from '`gem list --remote vagrant-`'. Work-around: **manual installation** of rubygem-rexml-3.2.4-147.fc34.noarch.

**Comment by electrofelix** [comment]
Not yet testing against ruby 3.0, not exactly straightforward, but should just have a few minor details to work out and the same PR should fix this.
