### ISSUE TITLE
 Unusual disk image size created

### ISSUE THREAD

**Issue by Ricky-Tigg** [vagrant-libvirt/vagrant-libvirt#1245]
**OS:** Fedora 34; **Components:** vagrant-libvirt-0.1.2-3.fc34.noarch, vagrant-2.2.9-6.fc34.noarch; **Vagrant image:** generic/fedora33.

Unusual disk image size created: 128 GiB; while the original source file size is 60 MiB:
```
$ vagrant up
Bringing machine 'default' up with 'libvirt' provider...
(...)
==> default:  -- Image:             /home/yk/.local/share/libvirt/images/fedora_default.img (128G)
```
```
$ cd ~/.local/share/libvirt/images/; file -b fedora_default.img
QEMU QCOW2 Image (v2), has backing file (path /home/yk/.local/share/libvirt/images/generic-VAGRANTSLASH-fedora33_vagrant_box_image_3.2.14.img), 137438953472 bytes
```
Size of the original file:
```
$ ls -lh fedora_default.img | cut -d' ' -f1-5
-rw-------. 1 yk yk 60M
```

**Comment by electrofelix** [comment]
It's most likely due to sparse disk usage. The disk image size is likely set to 128GB, while the actual data is only 60MB. During packing for a box to be transferred you can't use a sparse file, however when the image is uploaded it is given the configured disk image size by default and will set the file up with the configured size so the filesystem within can use the space as needed.

Should be possible to check the actual disk usage as opposed to the file size reported as they can be different.

**Comment by Ricky-Tigg** [comment]
Hello I investigated with `lsblk` which may not be the appropriate tool for the task; Spaces used by virtual machines are not reported there.

**Comment by electrofelix** [comment]
@Ricky-Tigg try using `qemu-img info <file>` to get the info:
```
qemu-img info /var/lib/libvirt/images/yk0-VAGRANTSLASH-ubuntu-xenial_vagrant_box_image_201606082.img
image: /var/lib/libvirt/images/yk0-VAGRANTSLASH-ubuntu-xenial_vagrant_box_image_201606082.img
file format: qcow2
virtual size: 300 GiB (322122547200 bytes)
disk size: 2.54 GiB
cluster_size: 65536
Format specific information:
    compat: 1.1
    compression type: zlib
    lazy refcounts: false
    refcount bits: 16
    corrupt: false
    extended l2: fals
```
If I use the `file -b <file>` I'll see the following:
```
QEMU QCOW2 Image (v3), 322122547200 bytes
```
While `ls -lh <file>` will show me:
```
-rwxr--r-- 1 qemu qemu 2.6G Dec 15 18:15 /var/lib/libvirt/images/yk0-VAGRANTSLASH-ubuntu-xenial_vagrant_box_image_201606082.img
```

Essentially it's all down to the virtual size, which the disk image is allowed to grow to, vs the actual usage on the host system. I'm guessing the defaults for `qemu-img create .. ` is optimized towards sparse image for efficient size, with some preallocation enabled for decent performance.  Some info available at https://www.jamescoyle.net/how-to/1810-qcow2-disk-images-and-performance and more at https://qemu.readthedocs.io/en/latest/system/images.html#cmdoption-qcow2-arg-compat

**Comment by Ricky-Tigg** [comment]
_Few words_ | As noticeable you do hard work along with every report you deal with. That's even a constant. How to thank you  as deserved. I wish i was a developer to help with such a challenging project even if it would be maintained by four permanent persons. As maintained by a single person –  you then – , it becomes quite inhuman. The new maintainer, if any, would have to be not only a developer but as brave as you are, That's so uncommon nowadays.

```
$ qemu-img info ~/.local/share/libvirt/images/fedora_default.img | sed 1d
file format: qcow2
virtual size: 128 GiB (137438953472 bytes)
disk size: 147 MiB
cluster_size: 65536
backing file: /home/yk/.local/share/libvirt/images/generic-VAGRANTSLASH-fedora33_vagrant_box_image_3.2.14.img
backing file format: qcow2
Format specific information:
    compat: 0.10
    compression type: zlib
    refcount bits: 16
```
The only singular choice made by Fedora is the use of an obsolete version of compat; version _1.1_ would be the only proper choice. You already figured out the reason for two different size values; then it referred to the principle of _sparse space allocation_. No issue then.
