### ISSUE TITLE
Using session rather than system, have to sudo virsh net-list --all first

### ISSUE THREAD

**Issue by brianjmurrell** [vagrant-libvirt/vagrant-libvirt#1258]
### Steps to reproduce
1. Stand up a Fedora 33 machine with vagrant-libvirt
2. Run `systemctl start libvirtd.socket`
3. Create any basic `Vagrantfile`
4. Run `vagrant up`

### Expected behaviour
Vagrant should start up

### Actual behaviour
```
An error occurred while executing the action on the 'vm3'
machine. Please handle this error then try again:

There was an error talking to Libvirt. The error message is shown
below:

Call to virDomainCreateWithFlags failed: internal error: /usr/libexec/qemu-bridge-helper --use-vnet --br=virbr0 --fd=37: failed to communicate with bridge helper: Transport endpoint is not connected
stderr=failed to get mtu of bridge `virbr0': No such device
```

If I run `sudo virsh net-list --all` before running `vagrant up` the error is avoided.

### System configuration
**OS/Distro version:** Fedora 33

**Libvirt version:** 6.6.0

**Output of `vagrant version; vagrant plugin list`:**
```
Installed Version: 2.2.9
vagrant-libvirt (0.1.2, system)
```
**Attach Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt >vagrant.log 2>&1`**
[vagrant-debug.txt](https://github.com/vagrant-libvirt/vagrant-libvirt/files/6377744/vagrant-debug.txt)

**A Vagrantfile to reproduce the issue:**
This is not `Vagrantfile` related.  Any minimal valid `Vagrantfile` will do.

**Are you using upstream vagrant package or your distros package?**
Distro

**Comment by electrofelix** [comment]
Since we reference some details around network interfaces from the domain, it might be that simply moving the line https://github.com/vagrant-libvirt/vagrant-libvirt/blob/master/lib/vagrant-libvirt/action.rb#L46 to before https://github.com/vagrant-libvirt/vagrant-libvirt/blob/master/lib/vagrant-libvirt/action.rb#L38 is sufficient.

Also would mean swapping the order of the two lines https://github.com/vagrant-libvirt/vagrant-libvirt/blob/master/lib/vagrant-libvirt/action.rb#L28-L29 to be consistent.

Essentially I think the API call at https://github.com/vagrant-libvirt/vagrant-libvirt/blob/d764a308b4ce78b3380620bdc5bc12da16106689/lib/vagrant-libvirt/action/create_networks.rb#L53-L55 would be equivalent. It does feel a bit like a libvirt bug, but at the same time I suspect it might not be surprising to assume that when defining a VM that is using networks that the network has been looked at first as it would be a dependency similar to the disks.

**Comment by electrofelix** [comment]
I've brought up a pristine instance of fedora 33 using the following vagrantfile:
```
# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure('2') do |config|
  config.ssh.shell = "/bin/sh"

  config.vm.define "test-fedora" do |c|
    c.vm.box = "generic/fedora33"
    
    c.vm.synced_folder ".", "/vagrant", disabled: true

    c.vm.provider "libvirt" do |libvirt, override|
      libvirt.memory = 2048
      libvirt.cpus = 2
      libvirt.nested = true
    end
  end
end
```
Bring up the guest
```
vagrant up
vagrant ssh
```

In the guest machine steps to install distro vagrant along with the latest vagrant-libvirt release
```bash
sudo dnf update -y && sudo dnf install -y @virtualization vagrant
sudo dnf remove -y --noautoremove vagrant-libvirt rubygem-racc
vagrant plugin install vagrant-libvirt
sudo systemctl start libvirtd
```

creating vagrantfile:
```bash
mkdir test
cd test
vagrant init generic/fedora33
```

I edited the vagrantfile to add the following block:
```ruby
  config.vm.provider "libvirt" do |lv|
    lv.qemu_use_session = true
  end
```
This is because the fedora packaged plugin changes the default for `qemu_use_session` from false to true, but for the install from upstream you need to explicitly set it to true. Can also just export `LIBVIRT_DEFAULT_URI=qemu:///session`, but this only works with more recent releases.

Then running:
```bash
vagrant status # check that the correct provider will be used
vagrant up
```

Results in the following output:
```
vagrant up
Bringing machine 'default' up with 'libvirt' provider...
==> default: Box 'generic/fedora33' could not be found. Attempting to find and install...
    default: Box Provider: libvirt
    default: Box Version: >= 0
==> default: Loading metadata for box 'generic/fedora33'
    default: URL: https://vagrantcloud.com/generic/fedora33
==> default: Adding box 'generic/fedora33' (v3.5.0) for provider: libvirt
    default: Downloading: https://vagrantcloud.com/generic/boxes/fedora33/versions/3.5.0/providers/libvirt.box
Download redirected to host: vagrantcloud-files-production.s3-accelerate.amazonaws.com
    default: Calculating and comparing box checksum...
==> default: Successfully added box 'generic/fedora33' (v3.5.0) for 'libvirt'!
==> default: Uploading base box image as volume into Libvirt storage...
==> default: Creating image (snapshot of base box volume).
==> default: Creating domain with the following settings...
==> default:  -- Name:              test_default
==> default:  -- Description:       Source: /home/vagrant/test/Vagrantfile
==> default:  -- Domain type:       kvm
==> default:  -- Cpus:              2
==> default:  -- Feature:           acpi
==> default:  -- Feature:           apic
==> default:  -- Feature:           pae
==> default:  -- Clock offset:      utc
==> default:  -- Memory:            2048M
==> default:  -- Management MAC:    
==> default:  -- Loader:            
==> default:  -- Nvram:             
==> default:  -- Base box:          generic/fedora33
==> default:  -- Storage pool:      default
==> default:  -- Image():     /home/vagrant/.local/share/libvirt/images/test_default.img, 128G
==> default:  -- Disk driver opts:  cache='default'
==> default:  -- Kernel:            
==> default:  -- Initrd:            
==> default:  -- Graphics Type:     vnc
==> default:  -- Graphics Port:     -1
==> default:  -- Graphics IP:       127.0.0.1
==> default:  -- Graphics Password: Not defined
==> default:  -- Video Type:        cirrus
==> default:  -- Video VRAM:        256
==> default:  -- Video 3D accel:    false
==> default:  -- Sound Type:	
==> default:  -- Keymap:            en-us
==> default:  -- TPM Backend:       passthrough
==> default:  -- TPM Path:          
==> default:  -- INPUT:             type=mouse, bus=ps2
==> default: Creating shared folders metadata...
==> default: Starting domain.
==> default: Waiting for domain to get an IP address...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 192.168.122.82:22
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
```

I've subsequently retested using the following to set up the guest after destroying so I'd use the distro packaged vagrant-libvirt instead of the latest release:
```bash
vagrant up
vagrant ssh
# in the guest this time don't remove the installed vagrant-libvirt to update.
sudo dnf update -y && sudo dnf install -y @virtualization vagrant
sudo systemctl start libvirtd
```

Then performed the same steps to create the vagrantfile, though this time I skipped adding the additional block since using the session is the default for the distro packaged version, and it came up with the following output:
```
Bringing machine 'default' up with 'libvirt' provider...
==> default: Box 'generic/fedora33' could not be found. Attempting to find and install...
    default: Box Provider: libvirt
    default: Box Version: >= 0
==> default: Loading metadata for box 'generic/fedora33'
    default: URL: https://vagrantcloud.com/generic/fedora33
==> default: Adding box 'generic/fedora33' (v3.5.0) for provider: libvirt
    default: Downloading: https://vagrantcloud.com/generic/boxes/fedora33/versions/3.5.0/providers/libvirt.box
Download redirected to host: vagrantcloud-files-production.s3-accelerate.amazonaws.com
    default: Calculating and comparing box checksum...
==> default: Successfully added box 'generic/fedora33' (v3.5.0) for 'libvirt'!
==> default: Uploading base box image as volume into Libvirt storage...
==> default: Creating image (snapshot of base box volume).
==> default: Creating domain with the following settings...
==> default:  -- Name:              test_default
==> default:  -- Domain type:       kvm
==> default:  -- Cpus:              2
==> default:  -- Feature:           acpi
==> default:  -- Feature:           apic
==> default:  -- Feature:           pae
==> default:  -- Memory:            2048M
==> default:  -- Management MAC:    
==> default:  -- Loader:            
==> default:  -- Nvram:             
==> default:  -- Base box:          generic/fedora33
==> default:  -- Storage pool:      default
==> default:  -- Image:             /home/vagrant/.local/share/libvirt/images/test_default.img (128G)
==> default:  -- Volume Cache:      default
==> default:  -- Kernel:            
==> default:  -- Initrd:            
==> default:  -- Graphics Type:     vnc
==> default:  -- Graphics Port:     -1
==> default:  -- Graphics IP:       127.0.0.1
==> default:  -- Graphics Password: Not defined
==> default:  -- Video Type:        cirrus
==> default:  -- Video VRAM:        256
==> default:  -- Sound Type:	
==> default:  -- Keymap:            en-us
==> default:  -- TPM Path:          
==> default:  -- INPUT:             type=mouse, bus=ps2
==> default: Creating shared folders metadata...
==> default: Starting domain.
==> default: Waiting for domain to get an IP address...
==> default: Waiting for SSH to become available...
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
```

A check with `vagrant status` confirmed it is up and running.

So either there is something subtly different about how the image is put together compared to the VM you are booting, or possibly this was a distro bug and they have since fixed it?

**Comment by electrofelix** [comment]
@brianjmurrell there appears to be a suggestion in #1405 that this has appeared in Fedora 35 as well, and the user solved it by running `sudo systemctl start virtnetworkd.service`.

I'm left with a sense that something is not triggering the start up of some libvirt networking in Fedora that either should be running before libvirt calls qemu-bridge-helper or should get started by it running and attempting to connect.

I wonder if there is an expectation that things talking to libvirt will perform a system connection to list the networks and if that is what then triggers a start of some additional services?

**Comment by electrofelix** [comment]
If someone who is encountering this and can reproduce, it would be useful for me to know if the following change works:
```
diff --git lib/vagrant-libvirt/action/create_networks.rb lib/vagrant-libvirt/action/create_networks.rb
index 37f176a..c16f13d 100644
--- lib/vagrant-libvirt/action/create_networks.rb
+++ lib/vagrant-libvirt/action/create_networks.rb
@@ -29,6 +29,13 @@ module VagrantPlugins
         end
 
         def call(env)
+          # Get a list of all (active and inactive) Libvirt networks.
+          # This potentially triggers a side effect to ensure networking is fully
+          # available for VMs using sessions
+          @available_networks = libvirt_networks(
+            env[:machine].provider.driver.system_connection.client
+          )
+
           if env[:machine].provider_config.qemu_use_session
             @app.call(env)
             return
```

@pvalena there is a small chance there is some hidden expectation that apps use the system connection to list networks for VMs before creating a VM that uses the session connection. In such a case the patch above may fix the bug at https://bugzilla.redhat.com/show_bug.cgi?id=2025202

If that patch solves the problem for someone that can reproduce, it would mean that it's probably a bad expectation in libvirt and upstream should correct, but I don't think it would be too bad for us to carry that change to workaround it.

**Comment by detwiler** [comment]
@electrofelix, as the reporter of the [Fedora 35 bug](https://bugzilla.redhat.com/show_bug.cgi?id=2025202) you mentioned above, I had an interest in trying your patch. Here is what I found, With the default Libvirt Modular Daemon configuration on Fedora 35, the patch resulted in the following error.

```
$ vagrant up
Bringing machine 'default' up with 'libvirt' provider...
==> default: Checking if box 'fedora/34-cloud-base' version '34.20210423.0' is up to date...
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.4.1/lib/vagrant-libvirt/util/network_util.rb:122:in `list_networks': Call to virConnectNumOfNetworks failed: Failed to connect socket to '/var/run/libvirt/virtnetworkd-sock-ro': Connection refused (Libvirt::RetrieveError)
	from /usr/share/vagrant/gems/gems/vagrant-libvirt-0.4.1/lib/vagrant-libvirt/util/network_util.rb:122:in `libvirt_networks'
	from /usr/share/vagrant/gems/gems/vagrant-libvirt-0.4.1/lib/vagrant-libvirt/action/create_networks.rb:30:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-hostmanager-1.8.9/lib/vagrant-hostmanager/action/update_all.rb:27:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builtin/provision.rb:80:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builder.rb:149:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `block in run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builder.rb:149:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `block in run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builder.rb:149:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `block in run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builtin/box_check_outdated.rb:93:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builder.rb:149:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `block in run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/machine.rb:246:in `action_raw'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/machine.rb:215:in `block in action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/environment.rb:614:in `lock'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/machine.rb:201:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/machine.rb:201:in `action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
```
The [default Fedora 35 `systemd` configuration](https://src.fedoraproject.org/rpms/fedora-release/blob/rawhide/f/90-default.preset#_65) does not enable/start the `virtnetworkd-ro.socket` despite that being [the recommendation from upstream Libvirt](https://libvirt.org/daemons.html#modular-systemd-integration). After starting the read-only version of the socket with `sudo systemctl start virtnetworkd-ro.socket` your patch worked! I also tried to run `vagrant up` without your patch, but with the read-only socket activated, and that resulted in the original error about no such device, `virbr0`.

**Comment by electrofelix** [comment]
That certainly suggests there are a couple of bugs:
* libvirt should activate the network when any call goes through that could reach the bridge helper
* Fedora should activate the socket by default

As long as fedora are happy to update the socket behaviour, I'm happy enough to carry the workaround, until such time as use of the other network APIs for libvirt will trigger the same behaviour without needing the explicit call

**Comment by electrofelix** [comment]
@detwiler From some tests with Fedora 34 as I don't have a 35 box handy, I'm wondering if the problem is that the sockets/services are configured to start on boot, **but are not** started immediately, so the service works as expected once the system is rebooted?

Likely explains why it's only encountered some of the time rather than consistently.

**Comment by electrofelix** [comment]
@detwiler it appears based on responses to the bugzilla ticket https://bugzilla.redhat.com/show_bug.cgi?id=2025202#c10 that Fedora doesn't support libvirt being usable after install until the machine is rebooted, and that this is driven at a policy level. While it may still be possible to start all the various services needed, it's on the user who installed to start them if they wish to use it immediately.

The previous occurrence of this was eliminated when I explicitly started libvirt as part of the installation steps at https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1258#issuecomment-965130175 and I have to wonder if the same would be true here.

If the machine is rebooted after install of the packages, do you experience the same issue without the patch above? Or is the problem completely gone?

**Comment by detwiler** [comment]
> @detwiler it appears based on responses to the bugzilla ticket https://bugzilla.redhat.com/show_bug.cgi?id=2025202#c10 that Fedora doesn't support libvirt being usable after install until the machine is rebooted, and that this is driven at a policy level. While it may still be possible to start all the various services needed, it's on the user who installed to start them if they wish to use it immediately.
> 
> The previous occurrence of this was eliminated when I explicitly started libvirt as part of the installation steps at [#1258 (comment)](https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1258#issuecomment-965130175) and I have to wonder if the same would be true here.

@electrofelix yes, this is essentially true. As mentioned in [this comment](https://bugzilla.redhat.com/show_bug.cgi?id=2025202#c6) on the bugzilla ticket, with Libvirt's new modular daemons setup, the responsibility for creating `virbr0` now lies with the `virtnetworkd` service. If `virbr0` exists by the time the `qemu-bridge-helper` gets called by Libvirt, then everything works fine. Basically, something has to cause the `virtnetworkd` service to come up, which creates `virbr0`. In the case of your patch, as long as `virtnetworkd-ro.socket` is active, it will cause `virtnetworkd` to come up and create `virbr0`. Without the patch, I'm just following the suggestion of enabling the `virtnetworkd` service with `systemctl enable virtnerworkd.service`, so that `virbr0` is always created on boot.

> If the machine is rebooted after install of the packages, do you experience the same issue without the patch above? Or is the problem completely gone?

I experience the same issue even after reboot, if nothing causes `virtnetworkd.service` to start and create `virbr0`. Enabling the `virtnetworkd` service so that it starts on boot and therefore creates `virbr0` is sufficient to eliminate the issue.

**Comment by electrofelix** [comment]
Ok, but that still means we should really need to land a patch, otherwise lots of people ar egoing to bump into this.

**Comment by electrofelix** [comment]
I think this is now solved both in that the original issue on Fedora 33/34 requires either a reboot or libvirtd to be restarted to work after install, and recent Fedora 35 will also require either a reboot or various sockets to be started after install and the patch that landed will then trigger the networking to start and resolve it there.

**Comment by tuupola** [comment]
FWIW Fedora also mentions starting libvirtd in their developer docs.

https://developer.fedoraproject.org/tools/vagrant/vagrant-libvirt.html

**Comment by electrofelix** [comment]
The docs should probably use `systemctl enable --now libvirtd` to ensure the service is started immediately rather than just after the next boot. Instructions do appear to be outdated both for the modular deamons approach and as the expectation is to be using session rather than system on Fedora.
