### ISSUE TITLE
vagrant-libvirt plugin won't install on ARM64

### ISSUE THREAD

**Issue by Hexawolf** [vagrant-libvirt/vagrant-libvirt#1259]
### Steps to reproduce

1. Use KVM-capable ARM64 hardware (AWS metal, Apple M1 or Pi 4)
2. Install ruby via `rvm` or `chruby` (2.7.3) or system package manager like `apt` (2.7.0p0)
3. Build Vagrant from sources (`bundle install; bundle --binstubs exec`)
4. Install dependencies as described in README.md.
5. Try to install the plugin with `exec/vagrant plugin install vagrant-libvirt`

I never succeeded in building it on x86_64 either way, but that does not concern me. Interestingly, `vagrant` (2.2.6) and `vagrant-libvirt` (0.0.45) from Ubuntu repos work, but they are way too outdated and have blocking bugs.

### Expected behaviour

vagrant-libvirt installs and works.

### Actual behaviour

Installation fails with errors. I'm attaching multiple logs:

- [vagrant-1.log](https://github.com/vagrant-libvirt/vagrant-libvirt/files/6379784/vagrant-1.log) is a basic attempt to install the plugin.
- [vagrant-2.log](https://github.com/vagrant-libvirt/vagrant-libvirt/files/6379785/vagrant-2.log) is an attempt to do so after removing `vagrant-spec` from Vagrant's Gemfile.
  - I can install `mini_portile2` and `nokogiri` manually, but Vagrant seems to use its own gem store at `~/.vagrant.d/gems`. I am not a Ruby programmer, nor do I know how Ruby package management works, so I have no idea how to work with this.
- [mkmf.log](https://github.com/vagrant-libvirt/vagrant-libvirt/files/6379783/mkmf.log), as advised by `vagrant-2.log`.

### System configuration

**OS/Distro version:** Ubuntu 20.04.2 LTS

**Architecture:** aarch64 (ARMv8.2-A)

**Libvirt version:** 6.0.0

**Output of `exec/vagrant version; exec/vagrant plugin list`:**

```
You appear to be running Vagrant outside of the official installers.
Note that the installers are what ensure that Vagrant has all required
dependencies, and Vagrant assumes that these dependencies exist. By
running outside of the installer environment, Vagrant may not function
properly. To remove this warning, install Vagrant using one of the
official packages from vagrantup.com.

Installed Version: 2.2.15
Latest Version: 2.2.15

[...]

No plugins installed.
```

**Output of `VAGRANT_LOG=debug exec/vagrant plugin install vagrant-libvirt >vagrant.log 2>&1`** attached as files `vagrant-1.log` and `vagrant-2.log` above due to enormous size.

**Comment by electrofelix** [comment]
Can you see if you can grab the contents of /home/elastio/.vagrant.d/gems/2.7.3/extensions/aarch64-linux/2.7.0/nokogiri-1.11.3/gem_make.out

Given the message:
```
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
```
and the output of `mkmf.log` doesn't appear to contain an error, I'm guessing there might be more info in the gem_make.out.

Unless it's a simple dependency issue I may not be able to help, simply because I don't know why nokogiri would refuse to build when getting installed via the vagrant plugin install.

**Comment by zzambers** [comment]
We are actually successfully using this plugin on aarch64 (where I also had to build vagrant myself). I also faced some problem building native extensions, which was nokogiri related (I don't remember exactly, it has been some time). Anyway I have found solution (workaround) to that problem (I wrote it to my notes). You can try it, to see, if it helps in your case:

export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
vagrant plugin install vagrant-libvirt

This was based on workaround from this bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1482641

**Comment by electrofelix** [comment]
@zzambers thanks, going to assume that will be sufficient to resolve the original issue. There isn't much that we can do if dependencies can't be installed on a target platform, but at least this will help anyone bumping into this issue now.

**Comment by Hexawolf** [comment]
@zzambers this got me through, thank you very much!

Now I am stuck on `Removing racc` step with following error:

```
Removing racc
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

Gem 'racc-1.5.2' is not installed in directory /home/hexawolf/.vagrant.d/gems/2.7.0
```

**Comment by electrofelix** [comment]
@Hexawolf what are you trying to execute to remove the gem? The `~/.vagrant.d/gems/2.7.0/` directory is managed by vagrant to allow it to ensure gems installed with a different ruby version used by vagrant don't conflict by using the same directory.

If you are having issues getting it clean I'd consider running `vagrant plugin expunge` and start again. Now sometimes I don't think it actually removes the gems, just that it wipes it's list of plugins from `~/.vagrant.d/plugins.json`, but then when you install a plugin afterwards it will re-process the entire set of the dependencies needed. If certain ones are not needed, they can get ignored and you may see the gem being left in the directory even though it's actually not getting used based on it no longer being pulled in.

If you really want to start with a clean area, delete `~/.vagrant.d/plugins.json` and `~/.vagrant.d/gems/2.7.0/` and then install your plugins from scratch. I think that should be enough to clean it without needing to delete any boxes downloaded already.

**Comment by Hexawolf** [comment]
@electrofelix I am not trying to remove anything manually, it is a step during `vagrant plugin install vagrant-libvirt` execution. I have tried fully removing `~/.vagrant.d` directory and installing it but it still failed with the same log snippet. No pointers to external logs whatsoever.

**Comment by electrofelix** [comment]
@Hexawolf I don't have an ARM64 to test this on, so I don't have any of the surrounding context.

If I test a pristine install using vagrant 2.2.13 I see the following:
```
NOKOGIRI_USE_SYSTEM_LIBRARIES=true VAGRANT_HOME=~/tmp/vagrant-test-install vagrant plugin install vagrant-libvirt
==> vagrant: A new version of Vagrant is available: 2.2.16 (installed version: 2.2.13)!
==> vagrant: To upgrade visit: https://www.vagrantup.com/downloads.html

Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Fetching formatador-0.2.5.gem
Fetching fog-core-2.2.4.gem
Fetching fog-json-1.2.0.gem
Fetching racc-1.5.2.gem
Building native extensions. This could take a while...
Fetching nokogiri-1.11.4-x86_64-linux.gem
Fetching fog-xml-0.1.3.gem
Fetching ruby-libvirt-0.7.1.gem
Building native extensions. This could take a while...
Fetching fog-libvirt-0.8.0.gem
Fetching vagrant-libvirt-0.4.1.gem
Installed the plugin 'vagrant-libvirt (0.4.1)'!
```

Can you run the same and share the full output as I don't follow where the `Removing racc` is coming from?

**Comment by Hexawolf** [comment]
@electrofelix 

```
$ vagrant plugin install vagrant-libvirt
You appear to be running Vagrant outside of the official installers.
Note that the installers are what ensure that Vagrant has all required
dependencies, and Vagrant assumes that these dependencies exist. By
running outside of the installer environment, Vagrant may not function
properly. To remove this warning, install Vagrant using one of the
official packages from vagrantup.com.

Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Fetching formatador-0.2.5.gem
Fetching fog-core-2.2.4.gem
Fetching fog-json-1.2.0.gem
Fetching racc-1.5.2.gem
Building native extensions. This could take a while...
Fetching mini_portile2-2.5.1.gem
Fetching nokogiri-1.11.4.gem
Building native extensions. This could take a while...
Fetching fog-xml-0.1.3.gem
Fetching ruby-libvirt-0.7.1.gem
Building native extensions. This could take a while...
Fetching json-2.5.1.gem
Building native extensions. This could take a while...
Fetching fog-libvirt-0.8.0.gem
Fetching vagrant-libvirt-0.4.1.gem
Removing racc
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

Gem 'racc-1.5.2' is not installed in directory /home/hexawolf/.vagrant.d/gems/2.7.0
```

**Comment by zzambers** [comment]
Unfortunately, I don't remember such an issue. That said, I would first probably just tried to erase ~/.vagrant.d to avoid possible side effects from previous attempts (but I guess you have probably already tried that). Other thing, I would try, is to build vagrant as "standalone" bundle (to avoid depending on system gems), which is, what I have done. I suspect, there may be some clash with system ruby gems or something (maybe). I can share steps done by my (from my notes), but that is probably all I can do for you, as my experience with ruby is very limited (actually only from using vagrant :) ).

Exact steps I have done were following (on RHEL-8, used on both x86_64 and aarch64 architectures):
```
# install build deps
sudo dnf install ruby-devel libxslt-devel libxml2-devel libvirt libvirt-devel
# install additional runtime deps
sudo dnf install qemu-img qemu-kvm libguestfs-tools bsdtar
# install bundler
gem install bundle
 
mkdir /home/tester/vagrant-2.2.16
cd /home/tester/vagrant-2.2.16
mkdir bin bundle
 
wget https://github.com/hashicorp/vagrant/archive/v2.2.16.tar.gz
tar -xf v2.2.16.tar.gz
 
cd vagrant-2.2.16

# OR: bundle install --standalone --path XXX
bundle config --local path /home/tester/vagrant-2.2.16/bundle
bundle install --standalone
 
bundle --binstubs /home/tester/vagrant-2.2.16/bin/
 
# NOTE: Don't remove unpacked vagrant sources! Scripts there are still necessary, bundle dir only contains deps.
 
cd /home/tester/vagrant-2.2.16/bin
# https://bugzilla.redhat.com/show_bug.cgi?id=1482641
export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
./vagrant plugin install vagrant-libvirt
./vagrant plugin install vagrant-sshfs
```

**Comment by electrofelix** [comment]
@zzambers thanks, I've just run through those steps, especially the standalone setting. I encountered a whole bunch of issues trying to use the the bundle install directly with the cloned repo and was reproducing what @Hexawolf  was experiencing, so definitely the use of `--standalone` is the main thing that was missing before.

My steps using rvm
```
# setup isolated test space
cd ~/tmp
mkdir vagrant-libvirt-test-install
rvm use --create ruby-2.6.5@vagrant-test
# once happy that the subsequent steps work, can remove these two and use the default VAGRANT_HOME
mkdir .vagrant.d
export VAGRANT_HOME=`pwd`/.vagrant.d

git clone https://github.com/hashicorp/vagrant
cd vagrant
git checkout v2.2.15
bundle config --local path `pwd`/bundle
bundle install --standalone
bundle --binstubs `pwd`/../bin/

cd ..
export PATH=`pwd`/bin:${PATH}
export NOKOGIRI_USE_SYSTEM_LIBRARIES=true

vagrant plugin install vagrant-libvirt
```

I guess the documentation at https://www.vagrantup.com/docs/installation/source should be updated to use the `--standalone` option with notes that without it installing any plugin that has native extensions appears to have issues.
