### ISSUE TITLE
Error occurred: VagrantPlugins::ProviderLibvirt::Action::HandleBoxImage::Open3

### ISSUE THREAD

**Issue by yamatoRT** [vagrant-libvirt/vagrant-libvirt#1305]
Hi all,
Having some issues getting vagrant-libvirt to work. I have tried to create VM with box contain two disks and it didn't work. I use vagrant-libvirt docker for create my VM.

### Steps to reproduce
1. Create alias  :
```bash
alias vagrant='
  mkdir -p ~/.vagrant.d/{boxes,data,tmp}; \
  docker run -it --rm \
    -e LIBVIRT_DEFAULT_URI \
    -v /var/run/libvirt/:/var/run/libvirt/ \
    -v ~/.vagrant.d:/.vagrant.d \
    -v $(pwd):$(pwd) \
    -w $(pwd) \
    --network host \
    vagrantlibvirt/vagrant-libvirt:latest \
    vagrant'
```
2. Set a attached Vagrantfile in current directory
3. vagrant up

### Expected behaviour
I should get a running libvirt VM

### Actual behaviour
Destroys the instance with uninitialized constant uninitialized constant VagrantPlugins::ProviderLibvirt::Action::HandleBoxImage::Open3 (NameError)

### System configuration
**OS/Distro version:**:
#56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021

**Libvirt version:**
```
vagrant-libvirt (0.5.1, global)
  - Version Constraint: 0.5.1
```
**Output of `vagrant version; vagrant plugin list`:**

**Attach Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt >vagrant.log 2>&1`**
[vagrant.log](https://github.com/vagrant-libvirt/vagrant-libvirt/files/6608932/vagrant.log)

**A Vagrantfile to reproduce the issue:**
```Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.box = "yamatoRT/tinycore-two-disks"
  config.vm.box_version = "0.0.3"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.nfs.functional = false
  config.ssh.insert_key = false
  config.vm.allow_fstab_modification = false
  config.ssh.shell = 'sh'
end
```

**Are you using upstream vagrant package or your distros package?**
Upstream

**Comment by electrofelix** [comment]
Looks like with certain versions of ruby/vagrant need to ensure the `require 'open3'` is at the top of the lib/vagrant-libvirt/action/handle_box_image.rb file. Not quite sure what it works for some and not others.

**Comment by electrofelix** [comment]
@yamatoRT released a bugfix which should fix this, the tagged version of the docker image should be available soon enough
