### ISSUE TITLE
vagrant-libvirt wont work with centos8 

### ISSUE THREAD

**Issue by kebairia** [vagrant-libvirt/vagrant-libvirt#1317]
i've a problem when i try to use vagrant-libvrit on CentOS8 
**Steps to reproduce**
1- installing vagrant using `sudo dnf -y install https://releases.hashicorp.com/vagrant/2.2.16/vagrant_2.2.16_x86_64.rpm`
2- installing `vagrant-libvirt` plugin using `CONFIGURE_ARGS="with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib64" vagrant plugin install vagrant-libvirt`
3- run `vagrant up` on existing project with libvirt provider
**Expected behaviour**
Should keep working,
**Actual behaviour**
Errors are shown
**System configuration**
OS/Distro version:: CentOS 8

libvirt version : Libvirtd (libvirt) 6.0.0

Output of vagrant version; vagrant plugin list:

`vagrant --version
Vagrant 2.2.16`
`vagrant plugin list
vagrant-libvirt (0.5.3, global)`

**Output**

`Bringing machine 'default' up with 'libvirt' provider...
/opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': /usr/lib64/libk5crypto.so.3: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b - /home/admin/.vagrant.d/gems/2.6.7/gems/ruby-libvirt-0.7.1/lib/_libvirt.so (LoadError)
	from /opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/admin/.vagrant.d/gems/2.6.7/gems/ruby-libvirt-0.7.1/lib/libvirt.rb:11:in `<top (required)>'
	from /opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/admin/.vagrant.d/gems/2.6.7/gems/fog-libvirt-0.8.0/lib/fog/libvirt.rb:4:in `<top (required)>'
	from /opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/admin/.vagrant.d/gems/2.6.7/gems/vagrant-libvirt-0.5.3/lib/vagrant-libvirt/driver.rb:1:in `<top (required)>'
	from /opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/admin/.vagrant.d/gems/2.6.7/gems/vagrant-libvirt-0.5.3/lib/vagrant-libvirt/provider.rb:29:in `driver'
	from /home/admin/.vagrant.d/gems/2.6.7/gems/vagrant-libvirt-0.5.3/lib/vagrant-libvirt/action/create_networks.rb:26:in `initialize'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:121:in `new'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:121:in `finalize_action'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:34:in `block in initialize'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:34:in `map'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:34:in `initialize'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/builder.rb:189:in `new'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/builder.rb:189:in `to_app'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/builtin/call.rb:52:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/builtin/box_check_outdated.rb:31:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/builder.rb:149:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `block in run'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `run'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/machine.rb:246:in `action_raw'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/machine.rb:215:in `block in action'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/environment.rb:614:in `lock'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/machine.rb:201:in `call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/machine.rb:201:in `action'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
`

**Comment by electrofelix** [comment]
Based on the error you'll need to follow the additional instructions for fedora and similar distros https://github.com/vagrant-libvirt/vagrant-libvirt#additional-notes-for-fedora-and-similar-linux-distributions

I presume there is no release packaged specifically for Centos? If not you can also look at using the docker image as described under https://github.com/vagrant-libvirt/vagrant-libvirt#using-docker-based-installation.

**Comment by electrofelix** [comment]
Assuming the instructions worked for you, this will automatically close in about 30 days, unless there is something else I've missed.
