### ISSUE TITLE
Dep ruby-libvirt broken with Vagrant 2.2.17 and Ruby >=3.0

### ISSUE THREAD

**Issue by rgl** [vagrant-libvirt/vagrant-libvirt#1322]
Vagrant 2.2.17 (see https://github.com/hashicorp/vagrant/issues/12445) upgraded Ruby 2.6.7 to 3.0.1 and this brake the build of the [libvirt-ruby dependency](https://gitlab.com/libvirt/libvirt-ruby).

This seems related to https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1269. In my case, I'm building this in Ubuntu 20.04.

For reference, this is the last bit of the build failure:

```
checking for libvirt/libvirt-lxc.h... yes
checking for virDomainLxcOpenNamespace() in -lvirt-lxc... yes
checking for virDomainLxcOpenNamespace() in libvirt/libvirt-lxc.h... yes
checking for virDomainLxcEnterNamespace() in libvirt/libvirt-lxc.h... yes
checking for virDomainLxcEnterSecurityLabel() in libvirt/libvirt-lxc.h... yes
creating extconf.h
creating Makefile

current directory: /home/rgl/.vagrant.d/gems/3.0.1/gems/ruby-libvirt-0.7.1/ext/libvirt
make DESTDIR\= clean

current directory: /home/rgl/.vagrant.d/gems/3.0.1/gems/ruby-libvirt-0.7.1/ext/libvirt
make DESTDIR\=
compiling _libvirt.c
compiling common.c
common.c:27:10: fatal error: st.h: No such file or directory
   27 | #include <st.h>
      |          ^~~~~~
compilation terminated.
make: *** [Makefile:245: common.o] Error 1

make failed, exit code 2

Gem files will remain installed in /home/rgl/.vagrant.d/gems/3.0.1/gems/ruby-libvirt-0.7.1 for inspection.
Results logged to /home/rgl/.vagrant.d/gems/3.0.1/extensions/x86_64-linux/3.0.0/ruby-libvirt-0.7.1/gem_make.out
```

**Comment by electrofelix** [comment]
It requires a release of the latest ruby-libvirt as that works based on the unit tests pulling it down. https://github.com/vagrant-libvirt/vagrant-libvirt/blob/4feb0424cd656115d7e428e1e8c35b37a9986c38/.github/workflows/unit-tests.yml#L96

Already logged https://gitlab.com/libvirt/libvirt-ruby/-/issues/4 asking for a new release, not sure what else I can do here.

**Comment by rgl** [comment]
I don't think we can do much more; but having this issue open would signal this as an ongoing problem that we have right now, so no one else would be surprised.

My current workaround is to downgrade to Vagrant 2.2.16.

I also commented in the libvirt-ruby issue you've mention.

**Comment by hswong3i** [comment]
Solution goes here: https://github.com/hashicorp/vagrant/issues/12445#issuecomment-876566065
```
$ CFLAGS="-I/opt/vagrant/embedded/include/ruby-3.0.0/ruby" vagrant plugin install vagrant-libvirt
```

**Comment by rgl** [comment]
Just tried vagrant 2.2.18 and this now works out of the box :-)

**Comment by Yajo** [comment]
For fedora 34:

```sh
sudo dnf install -y gcc libvirt libvirt-devel libxml2-devel make ruby-devel libguestfs-tools vagrant
CONFIGURE_ARGS="with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib64" CFLAGS="-I/usr/include/ruby/" vagrant plugin install vagrant-libvirt
```
