### ISSUE TITLE
machine_virtual_size has not real effect

### ISSUE THREAD

**Issue by metal3d** [vagrant-libvirt/vagrant-libvirt#1325]
### Steps to reproduce
1. Add VM machine_virtual_size = 30
2. vagrant up
3. see the disk size in VM

### Expected behaviour
Inside VM, the disk size should be 30Gb and not 4Gb

### Actual behaviour
When I lanch vagrant up, I can see:
```
-- Image:             /home/pafer/.local/share/libvirt/images/odoo-apache_myvm1.img (30G)
```
But inside the VM, a simple `df -h` command shows
```
    myvm1: /dev/vda1                                            4.0G  3.3G  707M  83% /
```

I understand that we must grow the volume inside the machine. But it limits the possibility to fill the disk at provision time. I need to pull a large git repository at startup. And for only one VM declared in the Vagrantfile.

### System configuration
**OS/Distro version:**:
Fedora 34

**Libvirt version:**
7.0.0

**Output of `vagrant version; vagrant plugin list`:**

```
Installed Version: 2.2.16

Vagrant was unable to check for the latest version of Vagrant.
Please check manually at https://www.vagrantup.com
vagrant-libvirt (0.4.1, system)
vagrant-mutate (1.2.0, global)
  - Version Constraint: > 0
 ```
**Tried with 0.5.3, same problem**

**Attach Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt >vagrant.log 2>&1`**
```
Delete this text and drag and drop the log file for github to attach and add a link here
```

**A Vagrantfile to reproduce the issue:**
```
Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
  config.vm.box = "rockylinux/8"
  config.vm.box_version = "4.0.0"

  (1..2).each do |i|
    config.vm.define "myvm#{i}" do |node|
      node.vm.provider :libvirt do |libvirt|
        libvirt.machine_virtual_size = 30
      end
      node.vm.provision :shell, inline: "hostnamectl set-hostname myvm#{i}"
    end
  end
end

```

**Are you using upstream vagrant package or your distros package?**
Distro package: vagrant-2.2.16-1.fc34.noarch

**Comment by electrofelix** [comment]
It changes the virtual disk size, since there are so many possible options around filesystem layout it's not feasible to predict how it should be grown so that is left up to the user to decide

From the docs
```
machine_virtual_size - Sets the disk size in GB for the machine overriding the default specified in the box. Allows boxes to defined with a minimal size disk by default and to be grown to a larger size at creation time. Will ignore sizes smaller than the size specified by the box metadata. Note that currently there is no support for automatically resizing the filesystem to take advantage of the larger disk.
```

Writing something that could do this correctly for all guests and OS's is beyond what is currently practical

**Comment by metal3d** [comment]
I fixed this by making some resize and force commands at install time :( that was not that easy

**Comment by abompard** [comment]
For the record I'm running this script at the beginning of my provisionning:

```
echo ", +" | sfdisk -N 4 -a --no-reread /dev/vda
partprobe
btrfs filesystem resize 1:max /
```

This works because on my Fedora image the root partition is number 4 and the filesystem is btrfs, you may need to adjust to your image.
