### ISSUE TITLE
How to prevent Domain Removal on provision failure?

### ISSUE THREAD

**Issue by salderma** [vagrant-libvirt/vagrant-libvirt#1328]
### Steps to reproduce
1. vagrant box with ansible (or ansible_local) provisioner
2. ansible playbook task fails
3. Result is `Removing Domain...` and `Deleting the machine folder`

### Expected behaviour
How can I troubleshoot the provision failure if the machine is removed?  I would expect, like with virtualbox provider that the machine would remain until destroyed by `vagrant destroy`

### Actual behaviour
Basically the provisioning has an error and vagrant is removing the VM making it difficult to troubleshoot the provisioning problem. I am converting my environment from virtualbox with ansible provisioner to libvirt with ansible_local, and a management box and management network to run the provisioning from.  So there is some ansible code changes required and could also be missing prereqs from the box build. It's impossible to troubleshoot w/o being able to use `vagrant ssh` to get on to the management machine.

### System configuration
Ubuntu 20.04 LTS

**Libvirt version:**
4.0.0-1

**Output of `vagrant version; vagrant plugin list`:**
vagrant-libvirt (0.5.3, global)
vagrant-mutate (1.2.0, global)

**Comment by electrofelix** [comment]
@salderma add `--no-destroy-on-error`, I thought there was an issue still open here, but must not have been.

I need to rework the handling of errors based on the response to https://github.com/hashicorp/vagrant/issues/12233#issuecomment-859949136, just haven't gotten to it yet.

**Comment by salderma** [comment]
@electrofelix Thank you very much, that does the trick, sorry if my searching missed the issue.

**Comment by electrofelix** [comment]
Sorry, I meant I couldn't find it either so it must not be around

**Comment by electrofelix** [comment]
Adding to my list of issues to try and fix sooner rather than later

**Comment by electrofelix** [comment]
@salderma I'm hopeful this is fixed, likely it'll need some additional testing to be absolutely sure, but at the very least it should move it in the right direction with only minor tweaks needed subsequently.

**Comment by electrofelix** [comment]
Looks like fix is incomplete.

**Comment by electrofelix** [comment]
@salderma follow up PR proved better under real tests, so this should be fixed on master and will be in the next release.
