### ISSUE TITLE
Not able to boot a mips vm

### ISSUE THREAD

**Issue by samip5** [vagrant-libvirt/vagrant-libvirt#1347]
### Steps to reproduce
1. Install Gentoo with an desktop environment
2. Install libvirt and vagrant with libvirt plugin
3. Try to provision an mips VM
4. Have it fail

### Expected behaviour
It should try to boot it up

### Actual behaviour
It errors with a wierd error from libvirt.

### System configuration
**OS/Distro version:**: Gentoo, latest portage tree as of today

**Libvirt version:** 7.3.0

**Output of `vagrant version; vagrant plugin list`:**
Installed Version: 2.2.9
Latest Version: 2.2.18
vagrant-libvirt (0.5.3, global)

**Attach Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt >vagrant.log 2>&1`:**
[vagrant.log](https://github.com/vagrant-libvirt/vagrant-libvirt/files/7149393/vagrant.log)

**A Vagrantfile to reproduce the issue:**
```
Vagrant.configure(2) do |config|
  config.vm.box = "generic/debian9"
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  config.vm.network :public_network,
    :dev => "vbr0",
    :mode => "bridge",
    :type => "bridge"


  config.vm.provider "libvirt" do |vb|
    vb.host = "home-srv"
    vb.username = "sm"
    vb.connect_via_ssh = true
    vb.memory = "2048"
    vb.machine_arch = "mips64"
    vb.machine_type = "malta"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y --force-yes qemu-system
    # See https://people.debian.org/~aurel32/qemu/mips/ for different archs
    wget -nv https://people.debian.org/~aurel32/qemu/mips/vmlinux-3.2.0-4-5kc-malta
    wget -nv https://people.debian.org/~aurel32/qemu/mips/debian_wheezy_mips_standard.qcow2
    sudo chown vagrant:vagrant vmlinux-3.2.0-4-5kc-malta
    sudo chown vagrant:vagrant debian_wheezy_mips_standard.qcow2
    sudo sh -c 'echo "qemu-system-mips64 -M malta -kernel $HOME/vmlinux-3.2.0-4-5kc-malta -hda $HOME/debian_wheezy_mips_standard.qcow2 -append "root=/dev/sda1 console=ttyS0" -nic tap -nographic\n" >> /etc/bash.bashrc'
  SHELL

end
```

**Are you using upstream vagrant package or your distros package?**
Technically neither, it's compiled from source according to distro ebuild.

**Comment by abbbi** [comment]
generic/debian9 is afaik an x86_64 image only. It wont work with mips, so:

**Comment by electrofelix** [comment]
I suspect even with a base machine of the right architecture it might not work. Looking at the main error `Call to virDomainDefineXML failed: XML error: No PCI buses available`.

adding `vb.graphics_type = 'none'` to the `config.vm.provider "libvirt" do |vb|` block might help get a bit further, but what will help most is if you could share the XML from libvirt for the created VM and we can see if there are stray references to PCI devices that should not be appearing.
