### ISSUE TITLE
Configuring provider uri per vm definition is not thread-safe

### ISSUE THREAD

**Issue by steve-todorov** [vagrant-libvirt/vagrant-libvirt#1358]
### Description

According to the [README.md](https://github.com/vagrant-libvirt/vagrant-libvirt#domain-specific-options):

> domain settings can be set for each domain separately in multi-VM environment

Since have a few hypervisor hosts where I need to provision a few slightly different VM configurations, I made the following `Vagrantfile`:

```
HYPERVISORS = {
  "hypervisor-host1" => [
    { hostname: "hh1-vm1", fqdn: "hypervisor-host1-hh1-vm1", mac: "52:54:00:9d:00:00", box_image: "generic/ubuntu2010" },
    { hostname: "hh1-vm2", fqdn: "hypervisor-host1-hh1-vm2", mac: "52:54:00:9d:00:01", box_image: "generic/ubuntu2010" },
  ],
  "hypervisor-host4" => [
    { hostname: "hh4-vm1", fqdn: "hypervisor-host4-hh1-vm1", mac: "52:54:00:9d:00:02", box_image: "generic/ubuntu2010" },
    { hostname: "hh4-vm2", fqdn: "hypervisor-host4-hh1-vm2", mac: "52:54:00:9d:00:03", box_image: "generic/ubuntu2010" },
  ]
}

Vagrant.configure(2) do |config|
  config.vagrant.plugins = ["vagrant-libvirt"]
  HYPERVISORS.each do |hypervisor, vms|
    vms.each do |vm|
      config.vm.define vm[:hostname] do |node|
        node.vm.box = vm[:box_image]
        node.vm.provider :libvirt do |domain|
          domain.driver = "kvm"
          domain.uri = "qemu+ssh://root@#{hypervisor}/system?mode=legacy&no_tty=1&sshauth=privkey,agent"
          domain.connect_via_ssh = true
          domain.username = "vagrant"
          domain.forward_ssh_port = true
        end
        node.ssh.host = vm[:fqdn]
        #node.vm.network "public_network", :dev => "br0", :mode => "bridge", :type => "bridge", :mac => vm[:mac]
      end
    end
  end
end
```

When you execute `vagrant up` you will notice that all configured VMs will end-up spinning on a single hypervisor depending on which one ended up last in the `foreach` loop (screenshot below). All of the provisioned boxes are configured correctly with all of the defined settings, but they are not provisioned on the correct host. This leads me to think there is an issue with the thread-safety of the `domain.uri` field. Unfortunately ruby is not my area of expertise as a developer and I cannot dig deeper into it :/

### Expected behaviour
When you use multi-vm environment, the `provider.uri` should be thread-safe.

### Actual behaviour
The `provider.uri` contains the last configured value.

![image](https://user-images.githubusercontent.com/2303663/134710283-522add08-195e-4e9e-bbbd-6ca15029d8f7.png)

### System configuration
**OS/Distro version:** 
`Ubuntu 21.10 (Impish Indri)`

**Libvirt version:** 
`libvirtd (libvirt) 7.6.0`

**Output of `vagrant version; vagrant plugin list`:** 
```
Vagrant: Installed Version: 2.2.14
vagrant-libvirt: 0.5.3
winrm: 2.3.6
winrm-fs: 1.3.5
winrm-elevated: 1.2.3
```
 
**Attach Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt >vagrant.log 2>&1`**
[vagrant.log](https://github.com/vagrant-libvirt/vagrant-libvirt/files/7227264/vagrant.log)

**A Vagrantfile to reproduce the issue:**
```
Insert Vagrantfile inside quotes here (remove sensitive data if needed)
```

**Are you using upstream vagrant package or your distros package?**
Distro

**Comment by electrofelix** [comment]
I don't have a multi machine env handy (I'm sure it's possible to put together by spinning up multiple VMs with nested virtualization enabled, just will be a while before I can sort it out), so if you could test whether the following modification to the driver.rb file works that would be useful:
```
diff --git lib/vagrant-libvirt/driver.rb lib/vagrant-libvirt/driver.rb
index 1ec5af2..af6a0e4 100644
--- lib/vagrant-libvirt/driver.rb
+++ lib/vagrant-libvirt/driver.rb
@@ -13,8 +13,8 @@ module VagrantPlugins
       # possibly this should be a connection pool using the connection
       # settings as a key to allow per machine connection attributes
       # to be used.
-      @@connection = nil
-      @@system_connection = nil
+      @connection = nil
+      @system_connection = nil
 
       def initialize(machine)
         @logger = Log4r::Logger.new('vagrant_libvirt::driver')
@@ -24,7 +24,7 @@ module VagrantPlugins
       def connection
         # If already connected to Libvirt, just use it and don't connect
         # again.
-        return @@connection if @@connection
+        return @connection if @connection
 
         # Get config options for Libvirt provider.
         config = @machine.provider_config
@@ -43,24 +43,24 @@ module VagrantPlugins
 
         @logger.info("Connecting to Libvirt (#{uri}) ...")
         begin
-          @@connection = Fog::Compute.new(conn_attr)
+          @connection = Fog::Compute.new(conn_attr)
         rescue Fog::Errors::Error => e
           raise Errors::FogLibvirtConnectionError,
                 error_message: e.message
         end
 
-        @@connection
+        @connection
       end
 
       def system_connection
         # If already connected to Libvirt, just use it and don't connect
         # again.
-        return @@system_connection if @@system_connection
+        return @system_connection if @system_connection
 
         config = @machine.provider_config
 
-        @@system_connection = Libvirt::open(config.system_uri)
-        @@system_connection
+        @system_connection = Libvirt::open(config.system_uri)
+        @system_connection
       end
 
       def get_domain(machine)
```

Essentially switch to instance variables from class variables. The alternative is relatively straight forward, would just need a hash for both variables and to use the machine id as the index. But it might be easier if Vagrant uses a separate instance of the provider per machine, rather than trying to be too smart about this.

**Comment by steve-todorov** [comment]
@electrofelix many thanks for the fast reply! I was trying to debug the code and also noticed the `driver.rb` file. Applying your changes solves the issue indeed!

![image](https://user-images.githubusercontent.com/2303663/134717309-63ed384d-1fa2-4f7d-9407-925bbd62957d.png)

**Comment by electrofelix** [comment]
I'll try to dig in to see why we have it as a class instance variable before landing that change, likely just a misunderstanding on my part at some point.

**Comment by steve-todorov** [comment]
Sure, let me know if you need me to test any further changes it in our environment for you and I'll be glad to do it :)
