### ISSUE TITLE
Vagrant up times out after a provisioner reboots the VM

### ISSUE THREAD

**Issue by terminaldweller** [vagrant-libvirt/vagrant-libvirt#1366]
### Steps to reproduce
Run the provided vagrantfile.

### Expected behaviour
The VM was expected to get provisioned.

### Actual behaviour
Provisioning should have completed successfully.

### System configuration
Linux hv0 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux

### Libvirt version:
5.0.0

### vagrant version:
```
Installed Version: 2.2.17
Latest Version: 2.2.18

To upgrade to the latest version, visit the downloads page and
download and install the latest version of Vagrant from the URL
below:

  https://www.vagrantup.com/downloads.html

If you're curious what changed in the latest release, view the
CHANGELOG below:

  https://github.com/hashicorp/vagrant/blob/v2.2.18/CHANGELOG.md
```
### vagrant plugin list;
```
vagrant-cachier (1.2.1, global)
  - Version Constraint: > 0
vagrant-libvirt (0.5.3, global)
  - Version Constraint: > 0
vagrant-mutate (1.2.0, global)
  - Version Constraint: > 0
```
### Attach Output of `VAGRANT_LOG=debug vagrant up --provider=libvirt >vagrant.log 2>&1`
https://gist.github.com/terminaldweller/717160794cea6062ae0e3018b1aa1b5d

### A Vagrantfile to reproduce the issue:
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y apache2
  SHELL
  config.vm.provision "shell", reboot: true, inline: <<-SHELL
    apt install -y vim
  SHELL
  config.vm.provision "shell", reboot: false, inline: <<-SHELL
    apt install -y tmux
  SHELL
end
```
### Are you using upstream vagrant package or your distros package?
Upstream

### The Issue
The problem here is that a time-out happens that is set to 2 seconds after a provisioner reboots the VM.

**Comment by electrofelix** [comment]
Looks like I need to move some checking to distinguish the VM running from being accessible separately from being running as the ssh info check waits until the machine is running to retrieve the IP address. This allows catching the timeout error looking for the IP address at the right level instead of it propagating up.

From some experimenting the following patch applied locally should get you past this issue:
```
diff --git lib/vagrant-libvirt/driver.rb lib/vagrant-libvirt/driver.rb
index 5d800cb..672aab6 100644
--- lib/vagrant-libvirt/driver.rb
+++ lib/vagrant-libvirt/driver.rb
@@ -137,7 +137,17 @@ module VagrantPlugins
         # TODO: terminated no longer appears to be a valid fog state, remove?
         return :not_created if domain.nil? || domain.state.to_sym == :terminated
 
-        domain.state.tr('-', '_').to_sym
+        state = domain.state.tr('-', '_').to_sym
+        if state == :running
+          begin
+            get_domain_ipaddress(machine, domain)
+          rescue Fog::Errors::TimeoutError => e
+            @logger.debug("Machine #{machine.id} running but no IP address available: #{e}.")
+            return :inaccessible
+          end
+        end
+
+        return state
       end
 
       private
```

I have some additional testing that I need to complete, but hopefully I should have a PR landed within the next couple of days to fix this.

**Comment by terminaldweller** [comment]
thank you very much
