### ISSUE TITLE
Podman example in README.md returns error

### ISSUE THREAD

**Issue by aramcap** [vagrant-libvirt/vagrant-libvirt#1373]
In the [README.md](https://github.com/vagrant-libvirt/vagrant-libvirt/blob/master/README.md), the bash example for Podman fails. They returns this error:

> Error: openat2 `vagrant/data`: No such file or directory: OCI runtime attempted to invoke a command that was not found

The code executed to obtain this error is copied from README.md (lines between 187 and 202):

```bash
vagrant(){
  podman run -it --rm \
    -e LIBVIRT_DEFAULT_URI \
    -v /var/run/libvirt/:/var/run/libvirt/ \
    -v ~/.vagrant.d/boxes:/vagrant/boxes \
    -v ~/.vagrant.d/data:/vagrant/data \
    -v $(realpath "${PWD}"):${PWD} \
    -w $(realpath "${PWD}") \
    --network host \
    --entrypoint /bin/bash \
    --security-opt label=disable \
    docker.io/vagrantlibvirt/vagrant-libvirt:latest \
      vagrant $@
}
```

I've solve it mapping the `.vagrant.d` root directory, thus:

```bash
vagrant(){
  podman run -it --rm \
    -e LIBVIRT_DEFAULT_URI \
    -v /var/run/libvirt/:/var/run/libvirt/ \
    -v ~/.vagrant.d:/.vagrant.d \
    -v $(realpath "${PWD}"):${PWD} \
    -w $(realpath "${PWD}") \
    --network host \
    --entrypoint /bin/bash \
    --security-opt label=disable \
    docker.io/vagrantlibvirt/vagrant-libvirt:latest \
      vagrant $@
}
```

Then, I propose change the lines between 187 and 202 in the [README.md](https://github.com/vagrant-libvirt/vagrant-libvirt/blob/master/README.md) file.

**Comment by ikke-t** [comment]
This ticket got closed a bit too soon: https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1357

**Comment by electrofelix** [comment]
@ikke-t try using `virsh -c qemu:///system list --all` as the user.

By default vagrant-libvirt will use `qemu:///system` to connect to libvirt, if you want them under your user session, export the env var `LIBVIRT_DEFAULT_URI=qemu:///session`, however note that there are more limitations around configuring the network when using the user session.

I am a little surprised that `virsh list` is defaulting the to the user session if `LIBVIRT_DEFAULT_URI` is not already set, though. Perhaps the distro has changed the default behaviour but not in a way that is easily detected. Could solve this possibly by using `LIBVIRT_DEFAULT_URI=$(virsh uri)` to ensure the connection uri passed is based on the default.

**Comment by javiroman** [comment]
Finally everything worked fine with (.bashrc):

```
vagrant(){
 podman run -it --rm --name vagrantlibvirt \
    -e LIBVIRT_DEFAULT_URI \
    -v /var/run/libvirt/:/var/run/libvirt/ \
    -v ~/.vagrant.d/boxes:/vagrant/boxes \
    -v ~/.vagrant.d/data:/vagrant/data \
    -v ~/.vagrant.d/tmp:/vagrant/tmp \
    -v $(realpath "${PWD}"):${PWD} \
    -w $(realpath "${PWD}") \
    --network host \
    --entrypoint /bin/bash \
    --security-opt label=disable \
    docker.io/vagrantlibvirt/vagrant-libvirt:latest \
    vagrant $@
}

```
