### ISSUE TITLE
Wrong nameserver in /etc/resolv.conf

### ISSUE THREAD

**Issue by PeterNerlich** [vagrant-libvirt/vagrant-libvirt#1380]
### Steps to reproduce
1. Ensure host is able to access internet and can resolve domain names
2. Start a machine with box `generic/ubuntu1804` using driver qemu (a nat network is created if it doesn't already exist)
3. Try to resolve domain names, e.g. `config.vm.provision 'shell', privileged: true, inline: "apt-get -q update"`

### Expected behaviour
The command is able to complete like it would on the host.

### Actual behaviour
The command fails because domain names cannot be resolved.

### System configuration
**OS/Distro version:**:

    $ lsb_release -a
    LSB Version:	1.4
    Distributor ID:	Arch
    Description:	Arch Linux
    Release:	rolling
    Codename:	n/a
    $ uname -a
    Linux ws-arch-tux 5.10.72-1-lts #1 SMP Sat, 09 Oct 2021 17:34:39 +0000 x86_64 GNU/Linux
    $ sudo pacman -Syu
    :: Synchronising package databases...
     core is up to date
     extra is up to date
     community                                    5.8 MiB  4.20 MiB/s 00:01 [########################################] 100%
     multilib is up to date
    :: Starting full system upgrade...
     there is nothing to do
    $ date -u
    Tue 12 Oct 09:29:25 UTC 2021
    $

**Libvirt version:**

    $ vagrant version
    Installed Version: 2.2.18
    Latest Version: 2.2.18
     
    You're running an up-to-date version of Vagrant!
    $ vagrant plugin list
    vagrant-libvirt (0.6.2, global)
      - Version Constraint: > 0
    vagrant-mutate (1.2.0, global)
      - Version Constraint: > 0
    vagrant-vbguest (0.30.0, global)
      - Version Constraint: > 0

**Attach Output of `VAGRANT_LOG=debug vagrant up --provider=libvirt >vagrant.log 2>&1`**
[vagrant.log](https://github.com/vagrant-libvirt/vagrant-libvirt/files/7329108/vagrant.log)

**A Vagrantfile to reproduce the issue:**
[Vagrantfile](https://github.com/vagrant-libvirt/vagrant-libvirt/files/7329147/Vagrantfile.txt)

**Are you using upstream vagrant package or your distros package?**
Distro

**Comment by PeterNerlich** [comment]
I am not sure that this is not just somehow a configuration error on my side.

A workaround for short lived vagrant machines is to copy the hosts `resolv.conf` at the start of provisioning:

	config.vm.provision "file", source: "/etc/resolv.conf", destination: "/home/vagrant/resolv.conf"
	config.vm.provision 'shell', privileged: true, inline:
		"mv /home/vagrant/resolv.conf /etc/resolv.conf"

I expect this to break whenever the hosts `resolv.conf` changes (e.g. when regenerated by NetworkManager), as it would have to be copied over again.

---

For VirtualBox [there seems to be a setting "enable dns proxy"/`natdnsproxy`](https://github.com/hashicorp/vagrant/blob/master/plugins/providers/virtualbox/action/sane_defaults.rb#L26) that fixes this somehow. Is there something similar for libvirt?

**Comment by redtux** [comment]
Hi, JFYI: I am having the same issue with `generic/ubuntu2004` on an Ubuntu 20.04 host, so the issue is rather related to the image than to @PeterNerlich's university network.

```
vagrant ssh -- host github.com
Host github.com not found: 2(SERVFAIL)

vagrant version; vagrant plugin list
Installed Version: 2.2.19
Latest Version: 2.2.19
 
You're running an up-to-date version of Vagrant!
vagrant-libvirt (0.7.0, global)
```

My workaround is overriding the nameserver in `/run/systemd/resolve/stub-resolv.conf` but as I am using dhcp in my opinion this should be handled by libvirt/dnsmasq (but than again I had to manually change settings via `virsh net-edit default`) or via vagrant.
