### ISSUE TITLE
CentOS 9 Stream Support

### ISSUE THREAD

**Issue by ooraini** [vagrant-libvirt/vagrant-libvirt#1429]
I was able to get it running using the following steps:

1.  Enable crb repository:
`sudo dnf config-manager  --set-enabled crb`
2. Add hashicorp repository:
`sudo dnf config-manager --add-repo https://rpm.releases.hashicorp.com/$release/hashicorp.repo`
3. Replace $releasever with 8:
`sudo sed -i 's/$releasever/8/g' /etc/yum.repos.d/hashicorp.repo`
4. Install packages:
`sudo yum install '@Virtualization Hypervisor' '@Virtualization Tools' '@Development Tools' 'libvirt-devel' 'vagrant'`
5. Install the plugin:
`vagrant plugin install vagrant-libvirt`

Did anyone face any issues with Stream 9?

I would like to submit a patch to update the README, but before, I want someone else to confirm that it's working for them too.

**Comment by electrofelix** [comment]
@ooraini can you have a look at adding CentOS 9 to the set of distros that installation is tested against in https://github.com/vagrant-libvirt/vagrant-libvirt-qa, that way it can act as a confirmation that the instructions are correct.

**Comment by web-engineer** [comment]
Presently trying this on Stream 9 and getting -

```
# dnf install '@Virtualization Hypervisor' '@Virtualization Tools' '@Development Tools' 'libvirt-devel' 'vagrant'
Last metadata expiration check: 0:39:51 ago on Fri 08 Jul 2022 11:28:47 BST.
No match for argument: libvirt-devel
```
Adding **--enablerepo=crb** fixes it tho.

```
dnf --enablerepo=crb install '@Virtualization Hypervisor' '@Virtualization Tools' '@Development Tools' 'libvirt-devel' 'vagrant'
vagrant plugin install vagrant-libvirt
```

This should get you running - just evaluating this myself ;)
