### ISSUE TITLE
forwarded_port feature with SSH tunneling does not work

### ISSUE THREAD

**Issue by BerkhanBerkdemir** [vagrant-libvirt/vagrant-libvirt#1439]
Hello,

I have been using `vagrant-libvirt` for 2 years without issue. Recently, I wanted to use `forwarded_port` feature. In the backend it uses SSH, but I had no chance to make it work. When I reach `localhost:3000`, I get a log file that only shows multiple of this line

```
channel 2: open failed: connect failed: Connection refused
```

I use Vagrant 2.2.3 with `vagrant-libvirt` 0.0.45 on Debian Buster. Current `Vagrantfile` what is created after `vagrant init` with removing comment line of the `forewarded_port`.

**Comment by electrofelix** [comment]
Please update the version of vagrant-libvirt being used, 0.0.45 was release in 2018 and there has been a lot of work done on improving the forwarding behaviour. Try retesting with 0.7.0

**Comment by ProjectInitiative** [comment]
I am not sure if this is the same issue, but it is similar. Running 0.7.0, the port forwarding works if a vagrant command is running. For instance, if I have a 5 VM cluster and I run `vagrant reload`, the tunnel is active and the port is forwarded until the full reload is complete. After vagrant exits, all ports and tunnels get dropped.

**Comment by electrofelix** [comment]
It's likely that port forwarding using the docker container would need to leave the container running as docker stopping will terminate and child processes started from within the container. No way around that.

I can't reproduce with a native install though and that would be different to this issue anyway as this is a out some failure to connect the forwarded port by the background ssh process that is running while you are saying it doesn't remain running at all
