### ISSUE TITLE
Create linked_image

### ISSUE THREAD

**Issue by TheLillo** [vagrant-libvirt/vagrant-libvirt#1446]
I can't create linked image when i specify the provider. Example:

instance.vm.provider "libvirt" do |libv|
      # Save space by creating a linked clone
      libv.linked_image = true
    end

With qemu-img is possible to create that. example:
qemu-img create -f qcow2 -b base-image.qcow2 linked-image.qcow2

Maybe the feature exist but i was not able to find. Can you help me?

**Comment by electrofelix** [comment]
By default when you create a machine using vagrant-libvirt the box image will be used as a base image by libvirt with changes written to a separate image. This saves the relevant space if you create multiple machines using the same box image as the same base will be used across all of them that use the same version of the box.

Perhaps if you can share what problem you are trying to solve?

**Comment by TheLillo** [comment]
Well, i didn't know that. Thank you for the answer
