### ISSUE TITLE
Cannot rename interface 'bridge4' to 'virbr1' on this platform: Function not implemented

### ISSUE THREAD

**Issue by alisnic** [vagrant-libvirt/vagrant-libvirt#1449]
**Describe the bug**

Error booting up a vagrant machine on Apple Silicon:

```
Error while activating network: Call to virNetworkCreate failed: Cannot rename interface 'bridge4' to 'virbr1' on this platform: Function not implemented
```

Every time I run vagrant up (with a destroy before that), a new bridge network is created on my pc:

```
bridge0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
bridge1: flags=8822<BROADCAST,SMART,SIMPLEX,MULTICAST> mtu 1500
bridge2: flags=8822<BROADCAST,SMART,SIMPLEX,MULTICAST> mtu 1500
bridge3: flags=8822<BROADCAST,SMART,SIMPLEX,MULTICAST> mtu 1500
bridge4: flags=8822<BROADCAST,SMART,SIMPLEX,MULTICAST> mtu 1500
```

**To Reproduce**
1. Use MacOS/ARM
1. Go to directory with `Vagrantfile`
2. Run `vagrant up`

**Expected behavior**
Vagrant is able to boot up vm without issues

**Screenshots**

**Versions (please complete the following information):**:
- Libvirt version: 8.1.0 (installed via `brew install libvirt --HEAD`)
- Vagrant version [output of `vagrant version`]: 2.2.19
- Vagrant flavour [Upstream or Distro]: built from source using instructions https://www.vagrantup.com/docs/installation/source
- Vagrant plugins versions (including vagrant-libvirt) [output of `vagrant plugin list`]:
  - vagrant-libvirt (0.7.0, global)

**Debug Log**

[debug.log](https://github.com/vagrant-libvirt/vagrant-libvirt/files/8068465/debug.log)

**A Vagrantfile to reproduce the issue:**

```ruby
Vagrant.configure(2) do |config|
  config.vm.provider "libvirt" do |v|
    v.driver = "qemu"
    v.features = []
    v.inputs = []
    v.machine_type = "virt"
    v.cpu_mode = "custom"
    v.cpu_model = "host"
    v.cpu_fallback = 'forbid'

    v.memory = 4096
    v.cpus = 1

    v.qemuargs :value => '-machine'
    v.qemuargs :value => 'highmem=off'
    v.qemuargs :value => '-accel'
    v.qemuargs :value => 'hvf'
  end

  config.vm.box = "javiervela/ubuntu20.04-arm64"
end
```

Somehow related to #1205

**Comment by electrofelix** [comment]
Likely something else is going wrong when configuring the default vagrant-libvirt network. The code is expecting bridge devices owned by libvirt to follow a particular naming convention, I wonder if this is different on MacOS though?

Can you run `virsh net-list --all` and then dump the XML of each one found so that can see what libvirt things the networks should be

**Comment by alisnic** [comment]
```
$ virsh net-list --all
 Name   State   Autostart   Persistent
----------------------------------------

```

Besides that, when I do vagrant destroy, I get an error that the default network does not exist

```
Error while removing network vagrant-libvirt. Call to virNetworkDestroy failed: Requested operation is not valid: network 'vagrant-libvirt' is not active.
```

**Comment by electrofelix** [comment]
So it's probably failing at the point of network creation with libvirt itself so the network definition never gets stored. Fun

Are you able to create any network definitions using libvirt directly? I don't know enough about its network behaviour on Mac OS but if it's possible to get a working XML definition then should be able to work out what vagrant-libvirt needs to do in order for it to supply the right definition when being brought up

**Comment by alisnic** [comment]
Will try to do that and will revert with any results. Thanks for pointes!

**Comment by alisnic** [comment]
I was able to define a simple bridge network in virsh:

```xml
<network>
    <name>bridged-network</name>
    <forward mode="bridge" />
    <bridge name="bridge0" />
</network>
```

NOTE: I used `bridge0` as name here, it is present in MacOS by default. Then I proceeded to create and activate it:

```bash
~/Play/libvirt-bug (0)
$ virsh net-define bridge.xml
Network bridged-network defined from bridge.xml

~/Play/libvirt-bug (0)
$ virsh net-list --all
 Name              State      Autostart   Persistent
------------------------------------------------------
 bridged-network   inactive   no          yes

~/Play/libvirt-bug (0)
$ virsh net-start bridged-network
Network bridged-network started

~/Play/libvirt-bug (0)
$ virsh net-list --all
 Name              State    Autostart   Persistent
----------------------------------------------------
 bridged-network   active   no          yes
```

I think the problem is not in the network bridge itself, but the fact that vagrant-libvirt issues a rename command for the bridge, which libvirt does not support on MacOS.

**Comment by electrofelix** [comment]
I think it's really that it's incorrectly determining the network name to use and shouldn't be attempting to trigger a rename.

**Comment by electrofelix** [comment]
It's also possible that the log doesn't get flushed before the exception is thrown and it gets discarded then, I've seen this quirk occur a few times before.

**Comment by alisnic** [comment]
Update. I slapped a bunch of puts statements in gem sources, and found out that indeed that code for creating a new network is not triggered, because a network is already found by vagrant-libvirt in 

https://github.com/vagrant-libvirt/vagrant-libvirt/blob/bb267e391049e22d872e5f700b5cd0aa2a4cdac7/lib/vagrant-libvirt/action/create_networks.rb#L59

Here is the definition of the network that is found:

```xml
<network ipv6='yes'>
  <name>vagrant-libvirt</name>
  <uuid>22f494c7-b3f7-41af-8f8a-b20f7af11249</uuid>
  <forward mode='nat'/>
  <bridge name='virbr1' stp='on' delay='0'/>
  <mac address='52:54:00:fe:cd:e9'/>
  <ip address='192.168.121.1' netmask='255.255.255.0'>
    <dhcp>
      <range start='192.168.121.1' end='192.168.121.254'/>
    </dhcp>
  </ip>
</network>
```

Which is strange, because virsh does not know about it (the only network that is listed is the one I created by hand):

```
$ virsh net-list --all
 Name              State    Autostart   Persistent
----------------------------------------------------
 bridged-network   active   no          yes
```

**Comment by alisnic** [comment]
Update 2: It seems that `virsh net-list --all` produces different output depending on the fact whether it is running with sudo or not 🤦 

```
$ sudo virsh net-list --all
Password:
 Name              State      Autostart   Persistent
------------------------------------------------------
 default           inactive   yes         yes
 vagrant-libvirt   inactive   no          yes
```

**Comment by alisnic** [comment]
update 3: vagrant-libvirt sees that network is present, but not active, and attempts to activate it in 

https://github.com/vagrant-libvirt/vagrant-libvirt/blob/bb267e391049e22d872e5f700b5cd0aa2a4cdac7/lib/vagrant-libvirt/action/create_networks.rb#L89

And finally, if I try to active this network using `virsh`, I get the same error:

```
$ sudo virsh net-start default
error: Failed to start network default
error: Cannot rename interface 'bridge12' to 'virbr0' on this platform: Function not implemented
```

So it seems this is a libvirt quirk. Let me know whether I should close this and open an issue in libvirt repo

**Comment by alisnic** [comment]
https://gitlab.com/libvirt/libvirt/-/issues/275

**Comment by electrofelix** [comment]
Ah, the old system vs session connection, sorry I had assumed that on Mac OS it would use the system connection by default.
In this case the following would have worked to show all of the networks as well.
```
virsh -c qemu:///system net-list --all
```

I suspect that the problem is related to the network XML trying to specify a network definition for the management interface that is not supported by the default network setup on Mac OS. And the attempting to rename the network is a side effect of libvirt getting confused and thinking that it should use bridgeX and rename it as opposed to creating a separate virbr0/virbr1 networks.

It does appear that libvirt on Mac OS is getting closer to working with the network stack.

**Comment by alisnic** [comment]
@electrofelix as a workaround, is there a way I can specify in Vagrantfile to not create any networks at all? I can use qemu port forwarding for now
