### ISSUE TITLE
No slim image available on docker hub

### ISSUE THREAD

**Issue by petracvv** [vagrant-libvirt/vagrant-libvirt#1454]
**Describe the bug**
The README (https://github.com/vagrant-libvirt/vagrant-libvirt/blob/master/README.md#using-the-container-image) mentions that there is a `-slim` image available for use cases where you don't need the whole toolchain installed. However, the docker hub organization only has the main image: https://hub.docker.com/u/vagrantlibvirt

**To Reproduce**
1. Try to pull the slim image with `docker pull docker.io/vagrantlibvirt/vagrant-libvirt-slim`
2. See that the image doesn't exist

**Expected behavior**
That the `vagrant-libvirt-slim` image exists on docker hub.

**Comment by electrofelix** [comment]
This is due to a slight misunderstanding, the `-slim` suffix refers to the tag rather than the image name

Try
```
docker pull docker.io/vagrantlibvirt/vagrant-libvirt:latest-slim
```

**Comment by petracvv** [comment]
Thanks! Yes that works. I guess the docs could be a bit more clear.

**Comment by electrofelix** [comment]
That's very true, I should add an example to cover this
