### ISSUE TITLE
Skip network deletion

### ISSUE THREAD

**Issue by rafutek** [vagrant-libvirt/vagrant-libvirt#1462]
I tuned the vagrant-libvirt network created by default adding `<domain name='loc' localOnly='yes'/>` to its config, so that I can access machines with domain names (bionic.loc for example). No need to edit /etc/hosts with some DNS config.
It works nicely until I destroy the machine, wich destroys the network.
Then I have to reconfiure the network...

Is it possible to skip that network deletion ? Maybe with an option `:libvirt__never_destroy` ?

The alternative is to use `virsh net-create --file vagrant-libvirt.xml` (with xml containing network config) before `vagrant up`, but it raises an error when I `vagrant destroy` :
> Error while removing network vagrant-libvirt. Call to virNetworkUndefine failed: Réseau non trouvé : no network with matching uuid '9fbac56b-aee7-4e14-8937-06cfef642703' (vagrant-libvirt).

**Comment by electrofelix** [comment]
I believe if you set `libvirt__domain_name` as described under https://github.com/vagrant-libvirt/vagrant-libvirt#private-network-options it wil set the domain as you need without needing to tune it and there-by avoid the need to be concerned with trying to preserve it across machine destroy calls.

Setting `libvirt__always_destroy` to false on the network will skip the destroy if you still need it, however I think the previous option mentioned is a better approach.

**Comment by rafutek** [comment]
Thanks ! I used the option `management_network_domain` instead.

**Comment by electrofelix** [comment]
Oh, yes, forgot it's the management network.
