### ISSUE TITLE
Unable to write to '/sys/fs/cgroup/cpuset/machine/qemu-1-adminwin2016.libvirt-qemu/emulator/cpuset.cpus': Permission denied

### ISSUE THREAD

**Issue by lixiaobing1** [vagrant-libvirt/vagrant-libvirt#1465]
kubevirt 0.55.0, libvirt 5.9, failed to write to cpuset.cpus， I have set privilege to true, so why fail as root, does it stat vm with user qemu?

{"component":"virt-launcher","kind":"","level":"error",
"msg":"Failed to start VirtualMachineInstance with flags 0.","name":"win2016","namespace":"admin","pos":"manager.go:889","reason":"virError(Code=38, Domain=54, Message='Unable to write to '/sys/fs/cgroup/cpuset/machine/qemu-1-adminwin2016.libvirt-qemu/emulator/cpuset.cpus': Permission denied')"

**Comment by lixiaobing1** [comment]
thx very much:)

**Comment by electrofelix** [comment]
@lixiaobing1 this looks like you've reported to the wrong project as this is for the vagrant-libvirt plugin for vagrant, while you're issue indicates it is about kubevirt which is an entirely different project.

**Comment by electrofelix** [comment]
As I don't believe there is anything actionable for this project, closing this.
