### ISSUE TITLE
Can't create VM - Call to virDomainDefineXML failed: invalid argument: could not get preferred machine

### ISSUE THREAD

**Issue by diademiemi** [vagrant-libvirt/vagrant-libvirt#1466]
**Describe the bug**
I'm unable to start any boxes with Vagrant using libvirt. I'm using Fedora 35 and have installed Vagrant using this https://developer.fedoraproject.org/tools/vagrant/vagrant-libvirt.html. Both running as user and root has this issue. 

**To Reproduce**
1. `vagrant init generic/centos7`
2. `vagrant up`

**Expected behavior**
The VM should start as normal

**Logs**
```
> vagrant up
Bringing machine 'default' up with 'libvirt' provider...
==> default: Checking if box 'generic/centos7' version '3.6.10' is up to date...
==> default: Creating image (snapshot of base box volume).
==> default: Creating domain with the following settings...
==> default:  -- Name:              test_default
==> default:  -- Domain type:       kvm
==> default:  -- Cpus:              2
==> default:  -- Feature:           acpi
==> default:  -- Feature:           apic
==> default:  -- Feature:           pae
==> default:  -- Clock offset:      utc
==> default:  -- Memory:            2048M
==> default:  -- Management MAC:    
==> default:  -- Loader:            
==> default:  -- Nvram:             
==> default:  -- Base box:          generic/centos7
==> default:  -- Storage pool:      default
==> default:  -- Image:             /home/user/.local/share/libvirt/images/test_default.img (128G)
==> default:  -- Disk driver opts:  cache='default'
==> default:  -- Kernel:            
==> default:  -- Initrd:            
==> default:  -- Graphics Type:     vnc
==> default:  -- Graphics Port:     -1
==> default:  -- Graphics IP:       127.0.0.1
==> default:  -- Graphics Password: Not defined
==> default:  -- Video Type:        cirrus
==> default:  -- Video VRAM:        256
==> default:  -- Sound Type:
==> default:  -- Keymap:            en-us
==> default:  -- TPM Backend:       passthrough
==> default:  -- TPM Path:          
==> default:  -- INPUT:             type=mouse, bus=ps2
Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: invalid argument: could not get preferred machine for /usr/bin/qemu-system-x86_64 type=kvm
```

**Versions (please complete the following information):**:
- Libvirt version: libvirt version: 7.6.0, package: 5.fc35 (Fedora Project, 2021-12-16-17:57:31
- Vagrant version [output of `vagrant version`]: 2.2.16
- Vagrant flavour [Upstream or Distro]: Distro
- Vagrant plugins versions (including vagrant-libvirt) [output of `vagrant plugin list`]:
```
> vagrant plugin list
vagrant-libvirt (0.4.1, system)
```

**Debug Log**
[vagrant.log](https://github.com/vagrant-libvirt/vagrant-libvirt/files/8286490/vagrant.log)

**A Vagrantfile to reproduce the issue:**
```
Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"
end
```

**Comment by electrofelix** [comment]
The error message suggests that likely the hypervisor modules are not loaded on your host machine, since it cannot use `kvm` for virtualization.

Unfortunately this isn't something that can be fixed from the plugin, you'll need to debug with your distro about ensuring QEMU and libvirt are working and verify that you can create a VM with virsh or virt-manager that can use `kvm`.

It may well be that just a reboot was needed.

Going to close as this appears to be an issue with libvirt + QEMU on the distro and until it can create and start virtual machines vagrant-libvirt won't be able to do anything.
