### ISSUE TITLE
Can't create nor destroy VM against libvirtd 8.1

### ISSUE THREAD

**Issue by MartinPotier** [vagrant-libvirt/vagrant-libvirt#1471]
**Describe the bug**
vagrant-libvirt doesn't seem to work against the new major version of libvirt

**To Reproduce**
1. `vagrant up`
``` console
/nix/store/622vvk062rvf1r20qh98mcs9wc0yil25-vagrant-2.2.19/lib/ruby/gems/2.7.0/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action/start_domain.rb:381:in `undefine': Call to virDomainUndefineFlags failed: End of file while reading data: Input/output error (Libvirt::Error)
```

**Expected behavior**
VM is created without any errors (as was the case against libvirtd 7.10.0)

**Versions (please complete the following information):**:
- Libvirt version: 8.1.0
- Vagrant version [output of `vagrant version`]: 2.2.19
- Vagrant flavour [Upstream or Distro]: Distro
- Vagrant plugins versions (including vagrant-libvirt) [output of `vagrant plugin list`]: vagrant-libvirt (0.7.0, system)

**Debug Log**
Attach Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt >vagrant.log 2>&1`

[vagrant.log](https://github.com/vagrant-libvirt/vagrant-libvirt/files/8322318/vagrant.log)

**A Vagrantfile to reproduce the issue:**
```
# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  #
  # Common Vagrant config
  #

  config.vm.box = "centos/8"

  # Don't sync the local dir (yet)
  config.vm.synced_folder ".", "/vagrant", disabled: true

  #
  # Common VirtualBox config
  #

  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true
    vb.memory = 2048
    vb.customize [ "modifyvm", :id, "--audio", "none" ]
  end

  #
  # Common Libvirtd config
  #

  config.vm.provider "libvirt" do |vb|
    vb.memory = 2048
  end

  #
  # Common ansible config
  #

  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "ansible/vm-provision-playbook.yml"

    ansible.groups = {
      "nix_service": [ "compute-node" ],
      "nix_service:vars" => {
        "nix_substituters" => "s3://some-s3-bucket?region=eu-central-1"
      }
    }
  end

  #
  # Systems
  #

  config.vm.define "compute-node" do |system|
  end
end
```

**Comment by abbbi** [comment]
Any libvirtd logs? Might well be an incompatiblity with ruby-libvirt. Doesnt look like and direct issue in vagrant-libvirt, more like one in the underlying components (ruby-> libvirt bindings <-> libvirtd incompatibility)

**Comment by electrofelix** [comment]
@MartinPotier I'd concur with @abbbi, vagrant-libvirt has the dependency change fog-libvirt -> ruby-libvirt, which is in turn compiled against libvirt. So if the version of libvirt on the host machine changes, there is a reasonable chance that it will require the ruby-libvirt dependency to be reinstalled in order to link against the newer library.

**Comment by electrofelix** [comment]
Assuming the above surmising by myself was correct, expecting this has been resolved for the reporter due to no further information.

**Comment by electrofelix** [comment]
Assuming the above surmising by myself was correct, expecting this has been resolved for the reporter due to no further information.
