### ISSUE TITLE
Crash: driver.rb:138  undefined method

### ISSUE THREAD

**Issue by hubiierik** [vagrant-libvirt/vagrant-libvirt#1472]
**Describe the bug**
Given `vagrant up --provider=libvirt` has been invoked and some (to me unknown) event causes the  vagrant domain to be lost
when I invoke a vagrant command like `vagrant status`
then I get the error message
```
root@a1dfd93e66e1:/# vagrant status
Traceback (most recent call last):
        14: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/bin/vagrant:231:in `<main>'
         ...
         1: from /root/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/provider.rb:98:in `state'
/root/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/driver.rb:138:in `state': undefined method `to_sym' for nil:NilClass (NoMethodError)
```
**Expected behavior**
```
root@a1dfd93e66e1:/# vagrant status
Current machine states:
ubuntu-win10              not created (libvirt)
The Libvirt domain is not created. Run `vagrant up` to create it
```

**Versions:**
- Libvirt version: `vagrant-libvirt (0.7.0, global)`
- Vagrant version [output of `vagrant version`]: `Installed Version: 2.2.19`
  
- Vagrant flavour [Upstream or Distro]: `https://releases.hashicorp.com/vagrant/2.2.19/vagrant_2.2.19_x86_64.deb`
- Vagrant plugins versions (including vagrant-libvirt) [output of `vagrant plugin list`]:
   - `vagrant-libvirt (0.7.0, global)` 

**Additional info**
This issue is not about the root cause of why the domain is lost.
This issue only focuses on a missing check in `.../lib/vagrant-libvirt/driver.rb:138`
The line is currently 
   `return :not_created if domain.nil? || domain.state.to_sym == :terminated`
but I propose that is should be
   `return :not_created if domain.nil? || domain.state.nil? || domain.state.to_sym == :terminated`

I am currently working around the issue by patching my vagrant installation:
```
root@a1dfd93e66e1:/# F='/root/.vagrant.d//gems/2.7.4/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/driver.rb'
root@a1dfd93e66e1:/# sed -i '138s/^.*$/        return :not_created if domain.nil? || domain.state.nil? || domain.state.to_sym == :terminated/' "${F}"
```

**Comment by electrofelix** [comment]
That looks to be a reasonable change, if you get a chance to put up a PR to make this I'll happily merge it.

Might be a little while before I get to it otherwise just due to not having enough free time at the moment

**Comment by ebaklund** [comment]
Thank you @electrofelix,

Looking further into the possible root cause of the crash, it seems to related to this `fog` issue:  https://github.com/fog/fog-libvirt/pull/103 
It looks like my Windows10 VM enters a `pmsuspended` state which `fog` does not have a translation for.
That my VM is suspended I can confirm with:
```
root@58d13def8623:/# virsh list 
 Id   Name                        State
-----------------------------------------------
 1    ubuntu-win10_ubuntu-win10   pmsuspended
```
I also had a look at the `fog-libvirt-0.9.0` implementation currently installed on my machine. Indeed the `pmsuspended` translation is missing.
I have reconsidered my proposal for code change and think it will be better to return `:unknown` than `: :not_created` when state translation has failed. That will create less misleading messages. Messages when the driver returns `:unknown` looks like this:
```
root@58d13def8623:/# vagrant status                        
Current machine states:
ubuntu-win10              unknown (libvirt)
translation missing: en.vagrant_libvirt.states.unknown
```
```
root@58d13def8623:/# vagrant global-status
id       name         provider state   directory                           
---------------------------------------------------------------------------
f23f5b2  ubuntu-win10 libvirt unknown /home/ubuntu-win10
```
I'll submit a PR for you to evaluate.

**Comment by ebaklund** [comment]
For whoever would be interested:
The command for waking up a VM in `pmsuspended` state is:
```
virsh dompmwakeup <VM-NAME>
```
