### ISSUE TITLE
@electrofelix All commands run successfully but `vagrant plugin install vagrant-libvirt` still output this error:

### ISSUE THREAD

**Issue by outbackdingo** [vagrant-libvirt/vagrant-libvirt#1476]
Yupp seeing this exact same issue right now, and the recommended fixes dont work!

@electrofelix All commands run successfully but `vagrant plugin install vagrant-libvirt` still output this error:

```
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Building native extensions. This could take a while...
Vagrant failed to install the requested plugin because it depends
on a library which is not currently installed on this system. The
following library is required by the 'vagrant-libvirt' plugin:

  libvirt

Please install the library and then run the command again.

```

I am on Fedora 35

_Originally posted by @JaneSoo in https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1403#issuecomment-973996896_

**Comment by electrofelix** [comment]
@outbackdingo I've run through the steps described in the other issue by using the Vagrantfile at https://github.com/vagrant-libvirt/vagrant-libvirt-qa to bring up a Fedora 35 test env using:
```
VAGRANT_LIBVIRT_DEPLOY=false VAGRANT_DEFAULT_PROVIDER=docker vagrant up fedora-35
vagrant ssh fedora-35
```

And then within that environment I've confirmed the following steps work:
```
dependencies=$(sudo dnf repoquery --qf "%{name}" $(for dep in $(sudo dnf repoquery --depends vagrant-libvirt 2>/dev/null | cut -d' ' -f1); do echo "--whatprovides ${dep} "; done) 2>/dev/null)
sudo dnf install @virtualization ${dependencies}
sudo dnf remove vagrant-libvirt
sudo systemctl enable --now libvirtd
vagrant plugin install vagrant-libvirt
```

and I see the following output:
```
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Fetching vagrant-libvirt-0.7.0.gem
Installed the plugin 'vagrant-libvirt (0.7.0)'!
```

The only difference was I needed to add `sudo dnf remove vagrant-libvirt` as I spotted the previous step was installing it as a weak dependency. However I don't believe that this would cause the above issue you describe, so I have to assume there was something else different.

Given these work, I consider this fixed, unless you can provide a more detailed set of instructions that allow reproducing.
