### ISSUE TITLE
vagrant up error talking to libvirt - unable to get index for interface eth0

### ISSUE THREAD

**Issue by cryptonaut01** [vagrant-libvirt/vagrant-libvirt#1477]
**Describe the bug**
I started with vagrant on a fresh ubuntu server 21.10 instance. Configured bridge br0 via yaml file. Now I am struggeling to distribute a first virt. box. How to tell vagrant to use that existing bridge ? vagrant up always creates a new network config on additional bridge virbr0 in nat mode, independent from what I configure within Vagrantfile config.

Error message:
==> linux: Starting domain.
There was an error talking to Libvirt. The error message is shown below:
Call to virDomainCreateWithFlags failed: Unable to get index for interface eth0: No such device

$ vagrant status
Current machine states:
linux                     shutoff (libvirt)
The Libvirt domain is not running. Run `vagrant up` to start it.

$ ip a
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master br0 state UP group default qlen 1000
    link/ether 68:1d:ef:25:a8:23 brd ff:ff:ff:ff:ff:ff
    altname enp1s0
    inet 192.168.2.156/24 brd 192.168.2.255 scope global eno1
       valid_lft forever preferred_lft forever
3: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 52:c7:b0:83:35:c2 brd ff:ff:ff:ff:ff:ff
    inet 192.168.2.156/24 brd 192.168.2.255 scope global br0
       valid_lft forever preferred_lft forever
    inet6 fe80::50c7:b0ff:fe83:35c2/64 scope link 
       valid_lft forever preferred_lft forever
11: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 52:54:00:dd:44:6e brd ff:ff:ff:ff:ff:ff
    inet 192.168.121.1/24 brd 192.168.121.255 scope global virbr0
       valid_lft forever preferred_lft forever

$ virsh net-dumpxml vagrant-libvirt
```
<network ipv6='yes'>
  <name>vagrant-libvirt</name>
  <uuid>e0b582d2-1f90-411c-a784-34a90d9786dd</uuid>
  <forward mode='nat'>
    <nat>
      <port start='1024' end='65535'/>
    </nat>
  </forward>
  <bridge name='virbr0' stp='on' delay='0'/>
  <mac address='52:54:00:dd:44:6e'/>
  <ip address='192.168.121.1' netmask='255.255.255.0'>
    <dhcp>
      <range start='192.168.121.1' end='192.168.121.254'/>
    </dhcp>
  </ip>
</network>
```

$ cat Vagrantfile
```
Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.provider "libvirt" do |hv|
   hv.cpus = "1"
   hv.memory = "1024"
  end
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder 'share/', "/share"
  config.vm.define "linux" do |linux| 
   linux.vm.network "public_network", bridge: "br0", ip: "192.168.2.157"
#   linux.vm.network "public_network" 
   linux.vm.hostname = "linux.local"
  end
```

**Versions (please complete the following information):**:
- Libvirt version: 7.6.0
- Vagrant version [output of `vagrant version`]: 2.2.14
- Vagrant flavour [Upstream or Distro]: generic/ubuntu2004
- Vagrant plugins versions (including vagrant-libvirt) [output of `vagrant plugin list`]: vagrant-libvirt (0.3.0, system)

**Comment by electrofelix** [comment]
I'm guessing you are using the distro provided packages for vagrant and vagrant-libvirt?

Although you put the following

> Vagrant flavour [Upstream or Distro]: generic/ubuntu2004

I'm guessing it's the distro package for both.

Could you try uninstalling the plugin and installing it directly via `vagrant plugin install vagrant-libvirt` as 0.7.0 has various fixes, as well as better debug output.

You'll need to generate a debug log and attach it when using the 0.7.0 release so I can see the XML that was sent to libvirt as well as also doing `virsh -c qemu:///system net-list` followed by `virsh -c qemu:///system net-dumpxml <network>` for each of the networks returned by the first command.

When you configure a bridge device sometimes you need to update libvirt config to remove old references, so as well as seeing what XML vagrant-libvirt is sending for the domain and network devices, it'll be useful to eliminate issues with what network configuration libvirt thinks should be in place.

**Comment by cryptonaut01** [comment]
Sorry for the weird format in initial post. Some parts where missing. Now it is corrected.
Regarding your questions: Yes. I used distro packages from fresh install: ubuntu server 21.10
As requested I removed and reinstalled vagrant-libvirt
```
$ vagrant plugin list
vagrant-libvirt (0.7.0, global)
```
This time I used a different syntax as found in a similar issue recorded here.
```
Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.provider "libvirt" do |hv|
   hv.cpus = "1"
   hv.memory = "1024"
  end
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder 'share/', "/share"
  config.vm.define "linux" do |linux| 
     linux.vm.network :public_network, :bridge => 'br0', :dev => 'eno1'
#   linux.vm.network "public_network", bridge: "br0", ip: "192.168.2.157"
#   linux.vm.network "public_network" 
   linux.vm.hostname = "linux.local"
  end
```
But issue is still present. no changes in xml vagrant-libvirt
```
$ virsh -c qemu:///system net-list
 Name              State    Autostart   Persistent
----------------------------------------------------
 host-bridge       active   yes         yes
 vagrant-libvirt   active   no          yes

$ virsh -c qemu:///system net-dumpxml vagrant-libvirt
<network ipv6='yes'>
  <name>vagrant-libvirt</name>
  <uuid>5dd6216b-7572-448b-b641-d062c8950ddc</uuid>
  <forward mode='nat'>
    <nat>
      <port start='1024' end='65535'/>
    </nat>
  </forward>
  <bridge name='virbr0' stp='on' delay='0'/>
  <mac address='52:54:00:60:e2:f6'/>
  <ip address='192.168.121.1' netmask='255.255.255.0'>
    <dhcp>
      <range start='192.168.121.1' end='192.168.121.254'/>
    </dhcp>
  </ip>
</network>
```
Debug log attached as well:
[vagrant.log](https://github.com/vagrant-libvirt/vagrant-libvirt/files/8482098/vagrant.log)

**Comment by cryptonaut01** [comment]
Update:
After some further research the virtual machine is finally running and accessible from outside.
Correct syntax to use the pre-configured bridge via ubuntu 21.10 netplan yaml is:
`node.vm.network "public_network", bridge: "br0", dev: "br0", ip: "x.x.x.x"`

I guess the vagrant-libvirt is always created as the internal network to access VM via vagrant ssh ?

**Comment by electrofelix** [comment]
@cryptonaut01 I've proposed a patch that I think would have helped where it will emit an error message similar to the following if the selected `:dev` does not exist on the host:
```
network configuration 0 for machine default is a public_network referencing host device 'eno1' which does not exist, consider adding ':dev => ....' referencing one of eth0, br-0325bc4e51e3, br-accb7f279af9
```

The filtering may require a bit of tweaking hence I've made it configurable.
