### ISSUE TITLE
Network configuration overwrites values set during provisioning since version 0.8.0

### ISSUE THREAD

**Issue by ErwinJanssen** [vagrant-libvirt/vagrant-libvirt#1479]
**Describe the bug**

Version 0.8.0 of vagrant-libvirt changes the order of the `vagrant up` steps: network configuration is now performed _after_ provisioning, instead of before as was the case in 0.7.0. The result is that network configuration that is set during provisioning (such as IP addresses) is overwritten, which then causes problems as this VM doesn't behave as expected.

**To Reproduce**

With version 0.7.0, provisioning is done after network configuration:

```shell
> vagrant up {hostname}
...
==> {hostname}: Configuring and enabling network interfaces...
==> {hostname}: Running provisioner: shell...
    {hostname}: Running: /tmp/vagrant-shell20220419-23449-138y8os
...
```

With version 0.8.0, these steps are reversed:

```shell
> vagrant up {hostname}
...
==> {hostname}: Running provisioner: shell...
    {hostname}: Running: /tmp/vagrant-shell20220419-10488-2kpxfu
==> {hostname}: Configuring and enabling network interfaces...
...
```

**Expected behavior**

The order of these steps should remain as it was in 0.7.0.

**Versions (please complete the following information):**:
- Libvirt version: 0.8.0
- Vagrant version [output of `vagrant version`]: 2.2.19
- Vagrant flavour [Upstream or Distro]: Arch Linux
- Vagrant plugins versions (including vagrant-libvirt) [output of `vagrant plugin list`]: vagrant-libvirt (0.8.0, global)

**Comment by electrofelix** [comment]
Thanks, yeah that's a bit of a mistake on my part, will need to either revert shortly or adjust where the provision action is scheduled.

**Comment by electrofelix** [comment]
@ErwinJanssen are you able to test the patch in #1480 locally to confirm that it works as expected for you?

It appears to fix the ordering for me, just looking for some additional confirmation before releasing.

**Comment by ErwinJanssen** [comment]
Thank you for the swift reply! The patch does indeed reverse the order of these steps to what it was in 0.7.0, and everything seem to work as expected again :slightly_smiling_face:

**Comment by electrofelix** [comment]
I'll try to release the point patch later today
