### ISSUE TITLE
Virtio 3D acceleration not working due to inability to disable TCP in Spice

### ISSUE THREAD

**Issue by DilithiumNitrate** [vagrant-libvirt/vagrant-libvirt#1482]
## Description
When I try to launch a virtual machine using the `virtio` graphics model and `video_accel3d` enabled, I get an error saying that this is incompatible with the options `-spice port/tls-port`. I do not know of any way to disable TCP listening in Spice in vagrant-libvirt, and if there is one, it should be included in the README. This has been mentioned in #1090 before, though the author of that issue – *incorrectly in my opinion* – marked it as duplicate.

## To Reproduce
Create a libvirt-based virtual machine using `video_type = 'virtio'`, `video_accel3d = true` and `graphics_type = 'spice'`.

### Expected behavior
The machine should start, and be accessible from virt-manager or another SPICE client running locally. Preferably, listening on TCP should be automatically disabled (equivalent setting in libvirt XML: `listen type="none"`) for Spice when Virtio 3D acceleration is enabled, or an Unix socket should be created and used (`listen type="socket"`).

## Full text of QEMU error
```
Call to virDomainCreateWithFlags failed: internal error: process exited while connecting to monitor: 2022-04-22T11:31:52.466946Z qemu-system-x86_64: SPICE GL support is local-only for now and incompatible with -spice port/tls-port
```

## Versions
- Libvirt version: 8.2.0, from Arch Linux's repos (8.2.0-4)
- Vagrant version: 2.2.19, from Arch's repos
- Vagrant plugins: only vagrant-libvirt, version 0.8.1

# Debug Log
[vagrant.log](https://github.com/vagrant-libvirt/vagrant-libvirt/files/8540648/vagrant.log)

## Vagrantfile
```rb
Vagrant.configure("2") do |config|
  config.vm.define :beta_vm do |beta_vm|
    beta_vm.vm.provider :libvirt do |v|
      v.memory = 2048
      v.cpus = 2
      v.video_type = 'virtio'
      v.video_accel3d = true
      v.graphics_gl = true
      v.graphics_type = 'spice'
      v.channel :type => 'unix', :target_name => 'org.qemu.guest_agent.0', :target_type => 'virtio'
      v.channel :type => 'spicevmc', :target_name => 'com.redhat.spice.0', :target_type => 'virtio'
      #v.graphics_autoport = 'no'
      v.cpuset = '14-15'
      v.cputopology :sockets => '1', :cores => '1', :threads => '2'
    end
    beta_vm.vm.box = "debian/bullseye64"
    beta_vm.vm.network "private_network", ip: "10.66.60.3"
    # beta_vm.vm.network "forwarded_port", guest: 80, host: 8881, protocol: "tcp"
  end
end
```
Note that removing the `v.channel` options changes nothing as far as the issue itself goes.

**Comment by DilithiumNitrate** [comment]
Thank you, this works to boot the virtual machine with `video_accel3d` on. However, for some reason the screen goes black once I log into an user on the virtual machine graphically (into Xfce, on Debian). TTY and the display manager work. Any idea why that might be?

**Comment by electrofelix** [comment]
I'm afraid as I haven't been using this functionality myself I don't know enough about how it should be configured.

If you happen to have a VM created with virt-manager that works as desired, if you could attach the domain XML to this issue, it should be possible to work out what is needed in the XML generated by vagrant-libvirt to match behaviour.

**Comment by andrewmackrodt** [comment]
The `-spice port/tls-port` error refers to requiring explicitly setting `<listen type="none"/>`, e.g.

```xml
    <graphics type="spice">
      <gl enable="yes"/>
      <listen type="none"/>
    </graphics>
```

**Comment by electrofelix** [comment]
@DilithiumNitrate got back to looking at this, appears to work correctly for a Fedora VM on Fedora 36.

![image](https://user-images.githubusercontent.com/912324/193432772-6b68f995-59ac-48dc-afab-05b9e6c24e8b.png)

and I've confirmed that 3d acceleration is enabled

![image](https://user-images.githubusercontent.com/912324/193432780-bf60b3c0-ed72-4e90-beb6-82364537dc54.png)

Based on this, I think the only change needed is to automatically add the channel when spice is enabled as the graphics type and default the graphics_ip and graphics_port to nil when video_accel3d is set to true.
