### ISSUE TITLE
vagrant-libvirt not working on CentOS 8 Stream.

### ISSUE THREAD

**Issue by corwin** [vagrant-libvirt/vagrant-libvirt#1537]
**Describe the bug**
After upgrading to CentOS 8 Stream and vagrant 2.2.19, vagrant-libvirt does not work.

**To Reproduce**
Install vagrant 2.2.19.
Build and install versions of libssh and libkrb5 as explained in the installation guide.
Run vagrant plugin install vagrant-libvirt.
In an existing project, run vagrant status.

**Expected behavior**
vagrant works

**Versions (please complete the following information):**:
- Libvirt version: 8.0.0
- Vagrant version [output of `vagrant version`]: 2.2.19
- Vagrant flavour [Upstream or Distro]: Upstream
- Vagrant plugins versions (including vagrant-libvirt) [output of `vagrant plugin list`]:
vagrant-host-shell (0.0.4, global)
vagrant-hosts (2.9.0, global)
vagrant-libvirt (0.9.0, global)

**Debug Log**
Attach Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt >vagrant.log 2>&1`

[vagrant.log](https://github.com/vagrant-libvirt/vagrant-libvirt/files/9296984/vagrant.log)

**Comment by evgeni** [comment]
```
/opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': /usr/lib64/libk5crypto.so.3: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b - /home/corwin/.vagrant.d/gems/2.7.4/gems/ruby-libvirt-0.8.0/lib/_libvirt.so (LoadError)
```

doesn't seem like you correctly fixed `libkrb5`?

https://github.com/theforeman/forklift/blob/master/roles/vagrant/tasks/vagrant_libvirt_el8.yml does the setup for my on CS8 and works just fine.

**Comment by electrofelix** [comment]
Did you try using the script from https://github.com/vagrant-libvirt/vagrant-libvirt-qa/blob/main/scripts/install.bash. I've yet to explicity test CentOS 8 stream, but the standard CentOS 8 works so I'd hope that the script does the right thing for stream as well
