### ISSUE TITLE
Impossible to start RISC-V machine

### ISSUE THREAD

**Issue by AlexTalker** [vagrant-libvirt/vagrant-libvirt#1538]
**Describe the bug**
So, I'm doing somewhat unorthodox usage of your plugin but it's practical at least.
I'm currently trying to box standard `Ubuntu` release for `RISC-V` (https://wiki.ubuntu.com/RISC-V) but the distro is irrelevant,
the platform, however, is.

I can successfully create the machine inside libvirt with the following config, created via `Virtual Machine Manager`(which probably used `virt-install`):
```xml
<domain type="qemu">
  <name>ubuntu22.04-riscv64</name>
  <uuid>bcb1625e-cba5-4f56-b0ce-c0ec87a3658a</uuid>
  <metadata>
    <libosinfo:libosinfo xmlns:libosinfo="http://libosinfo.org/xmlns/libvirt/domain/1.0">
      <libosinfo:os id="http://ubuntu.com/ubuntu/22.04"/>
    </libosinfo:libosinfo>
  </metadata>
  <memory unit="KiB">4194304</memory>
  <currentMemory unit="KiB">4194304</currentMemory>
  <vcpu placement="static">4</vcpu>
  <os>
    <type arch="riscv64" machine="virt">hvm</type>
    <kernel>/media/projects/arch/riscv/qemu/uboot.elf</kernel>
    <boot dev="hd"/>
    <bootmenu enable="yes"/>
  </os>
  <clock offset="utc"/>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <devices>
    <emulator>/usr/bin/qemu-system-riscv64</emulator>
    <disk type="file" device="disk">
      <driver name="qemu" type="raw"/>
      <source file="/media/projects/arch/riscv/qemu/box.img"/>
      <target dev="vda" bus="virtio"/>
      <address type="pci" domain="0x0000" bus="0x03" slot="0x00" function="0x0"/>
    </disk>
    <controller type="pci" index="0" model="pcie-root"/>
    <controller type="pci" index="1" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="1" port="0x8"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x01" function="0x0" multifunction="on"/>
    </controller>
    <controller type="pci" index="2" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="2" port="0x9"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x01" function="0x1"/>
    </controller>
    <controller type="pci" index="3" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="3" port="0xa"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x01" function="0x2"/>
    </controller>
    <controller type="pci" index="4" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="4" port="0xb"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x01" function="0x3"/>
    </controller>
    <controller type="pci" index="5" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="5" port="0xc"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x01" function="0x4"/>
    </controller>
    <controller type="pci" index="6" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="6" port="0xd"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x01" function="0x5"/>
    </controller>
    <controller type="pci" index="7" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="7" port="0xe"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x01" function="0x6"/>
    </controller>
    <controller type="scsi" index="0" model="virtio-scsi">
      <address type="pci" domain="0x0000" bus="0x02" slot="0x00" function="0x0"/>
    </controller>
    <controller type="virtio-serial" index="0">
      <address type="pci" domain="0x0000" bus="0x05" slot="0x00" function="0x0"/>
    </controller>
    <interface type="network">
      <mac address="52:54:00:81:2b:31"/>
      <source network="default"/>
      <model type="virtio"/>
      <address type="pci" domain="0x0000" bus="0x06" slot="0x00" function="0x0"/>
    </interface>
    <console type="pty">
      <target type="virtio" port="0"/>
    </console>
    <input type="keyboard" bus="virtio">
      <address type="pci" domain="0x0000" bus="0x07" slot="0x00" function="0x0"/>
    </input>
    <graphics type="spice" autoport="yes">
      <listen type="address"/>
      <image compression="off"/>
      <gl enable="no"/>
    </graphics>
    <audio id="1" type="none"/>
    <video>
      <model type="virtio" heads="1" primary="yes"/>
      <address type="pci" domain="0x0000" bus="0x04" slot="0x00" function="0x0"/>
    </video>
    <memballoon model="virtio">
      <address type="pci" domain="0x0000" bus="0x01" slot="0x00" function="0x0"/>
    </memballoon>
  </devices>
</domain>
```

However, if I try to do about the same thing via `Vagrantfile`, I get:
```
'riscv64' architecture is not supported by CPU driver
```

The issue seems to be that `riscv64` architecture isn't present in the following folder of libvirt ( https://github.com/libvirt/libvirt/tree/master/src/cpu ).
The presence of `/domain/cpu` is related to the error, since placing *any* kind of information in the section leads to variants of this error.
I peeked at `fog-libvirt` which you utilize and it seems that in their domain XML template, the CPU section is optional ( https://github.com/fog/fog-libvirt/blob/master/lib/fog/libvirt/models/compute/templates/server.xml.erb ).
I also tried to remove `cpu` section from your domain XML templates and it still failed since code in ( https://github.com/vagrant-libvirt/vagrant-libvirt/blob/main/lib/vagrant-libvirt/action/start_domain.rb#L86 ) brings back values from `Vagrantfile` configuration into the domain's XML when they're lacking in current libvirt domain XML from `fog-libvirt`, and specifying `nil` in `cpu_mode` isn't a valid option for your plugin currently it seems.
Considering that you advertise such classic stuff as `mips`, I suspect plugin won't work for them too, since `libvirt` recognizes `/domain/cpu` only for `x86`, `ARM`, `PowerPC` and `s390` architectures brands.
I successfully managed to run `ARM` stuff since, well, it's on the list above, so I didn't expected that such annoying problem will add-up.

In any case, if I keep domain created by your plugin after the error, after removing `/domain/cpu` section it functions fine, completely initializing and `vagrant ssh` works for me, so I'm pretty much done on my side aside from this annoying mishap.

**To Reproduce**
1. Try to run `RISC-V` box
2. Fail

**Expected behavior**

Box successfully runs and `/domain/cpu` section is optional
.
**Screenshots**

**Versions (please complete the following information):**:
- Libvirt version: 8.5.0
- Vagrant version [output of `vagrant version`]: from your official docker image
- Vagrant flavour [Upstream or Distro]:  you official docker image
- Vagrant plugins versions (including vagrant-libvirt) [output of `vagrant plugin list`]: the ones in your official docker image

**Debug Log**
Attach Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt >vagrant.log 2>&1`
```
Delete this text and drag and drop the log file for github to attach and add a link here
```

**A Vagrantfile to reproduce the issue:**
(from my `RISC-V` box)
```ruby
# frozen_string_literal: true

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Setup the default sync
  config.vm.synced_folder ".", "/vagrant", type: "rsync"

  # Options for Libvirt Vagrant provider.
  config.vm.provider :libvirt do |libvirt|

    # A hypervisor name to access. Different drivers can be specified, but
    # this version of provider creates KVM machines only. Some examples of
    # drivers are KVM (QEMU hardware accelerated), QEMU (QEMU emulated),
    # Xen (Xen hypervisor), lxc (Linux Containers),
    # esx (VMware ESX), vmwarews (VMware Workstation) and more. Refer to
    # documentation for available drivers (http://libvirt.org/drivers.html).
    libvirt.driver = 'qemu'
    # Prepare for running emulation instead of virtualization (H-extension)
    libvirt.emulator_path = '/usr/bin/qemu-system-riscv64'
    libvirt.machine_arch = 'riscv64'
    libvirt.machine_type = 'virt'
    # For U-boot built for QEMU (from AUR)
    libvirt.loader = '/usr/share/u-boot-qemu-bin/qemu-riscv64_smode/uboot.elf'

    # The name of the server, where Libvirtd is running.
    # libvirt.host = "localhost"

    # If use ssh tunnel to connect to Libvirt.
    libvirt.connect_via_ssh = false

    # The username and password to access Libvirt. Password is not used when
    # connecting via ssh.
    libvirt.username = 'root'
    #libvirt.password = "secret"

    # Libvirt storage pool name, where box image and instance snapshots will
    # be stored.
    libvirt.storage_pool_name = 'default'

    # Taken from aarch64 SUSE image
    libvirt.host = 'localhost'
    libvirt.uri = 'qemu:///system'
    libvirt.host = 'master'

    # Configure machine
    libvirt.cpus = 4
    # libvirt.cpu_mode = 'maximum'
    # libvirt.features = []

    # I/O
    libvirt.video_type = 'vga'
    libvirt.input :type => 'mouse', :bus => 'virtio'
    # Set a prefix for the machines that's different than the project dir name.
    #libvirt.default_prefix = ''
  end
end
```

**Comment by AlexTalker** [comment]
I'd like to note that `RISC-V` platform is officially supported by `libvirt` a few releases ago at least.

@electrofelix I probably could cook up a PR but I'd appreciate your guidance on how to handle this situation:
1. Add special meaning to `nil` value of some existing parameter(for example `cpu_mode`
2. Add dedicated parameter
3. Add new parameter value(for example, `Virtual Machine Manager` has `Hypervisor default` in drop-down selection which leads to lack of `/domain/cpu``

Thanks for your wondrous plugin in any case!

**Comment by AlexTalker** [comment]
I've published the box on http://mirrors.yetone.name/vagrant/ubuntu_riscv.box
Since it doesn't work until the fix is made, I put it there for now.

One like would need to re-pack it in case some defaults from `Vagrantfile` mess up with the debug.

**Comment by electrofelix** [comment]
Sorry, distracted trying to close out a bunch of other issues, only really looking at this one now.

I think it looks like we need to inspect the machine arch defined before attempting to set a default value for cpu_mode, might need a lookup table or something similar.

My guess is the fix would need to move the two lines for machine type and arch:
https://github.com/vagrant-libvirt/vagrant-libvirt/blob/414aef131d67157c56ce4da9ff0b117d464538e7/lib/vagrant-libvirt/config.rb#L879-L880
above where cpu_mode default is set, and change that to only set the default to host-model if the machine_arch is either nil or one of the architectures x86, ARM, PowerPC and s390 as you've mentioned. Then the template and start domain can both be modified to only set cpu mode if it's non nil.

I'm hesitant to change to mirror the hypervisor default as the default behaviour as that might unfortunately break existing vagrantfile's that have been relying on the current default of host-model.

So this is mostly option 1 from your suggestions, with the added change to try and set a better default using the machine_arch instead of needing it to be explicitly set to nil.

Does that sound reasonable to you?

**Comment by AlexTalker** [comment]
@electrofelix Yeah, sounds as reasonable approach. Would you kindly create the PR then since you're the more familiar with the codebase =) I was somewhat planning to but got swept away, so it's more likely that you can publish the fix faster than I can propose one 😆 

Thanks for cooperation.

**Comment by electrofelix** [comment]
Might take a little while, but I'll try to get to it

**Comment by electrofelix** [comment]
@AlexTalker would you be able to test the vagrant-libvirt plugin gem artifact attached to the PR https://github.com/vagrant-libvirt/vagrant-libvirt/pull/1633#issuecomment-1271414457 and see if it solves this issue for you?

**Comment by AlexTalker** [comment]
@electrofelix Oh, sorry, was a bit busy past few weeks. Could you please tell me how I could install your zip archived gem into plugin's docker image? I prefer to run it this way.
Then I surely can test it out.

**Comment by electrofelix** [comment]
@AlexTalker probably easier to just build the image locally, I'll have a look at whether it is possible to publish a built image to the github packages repo as well. If it is, should see a message appear on the PR indicating how to pull the docker image.

**Comment by AlexTalker** [comment]
@electrofelix So, trying to install your gem in latest image gave me this error:
```
# vagrant plugin install ./vagrant-libvirt-0.10.9.pre.32.gem
Installing the './vagrant-libvirt-0.10.9.pre.32.gem' plugin. This can take a few minutes...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

conflicting dependencies excon (= 0.92.4) and excon (= 0.92.5)
  Activated excon-0.92.5
  which does not match conflicting dependency (= 0.92.4)

  Conflicting dependency chains:
    excon (= 0.92.5), 0.92.5 activated

  versus:
    excon (= 0.92.4)

  Gems matching excon (= 0.92.4):
    excon-0.92.4
```

As I understand, `vagrant` has separate gem tree than the rest of the system, so that's somewhat awkward to deal with =)

**Comment by AlexTalker** [comment]
Okay,
```
/opt/vagrant/embedded/bin/gem install --install-dir /opt/vagrant/embedded/gems/2.3.0/ /tmp/vagrant-libvirt-0.10.9.pre.32.gem
```
seems to work nicely.

**Comment by AlexTalker** [comment]
@electrofelix Okay, it seems to work now without the need to edit the code:
![image](https://user-images.githubusercontent.com/3531127/198883523-4aeb141c-9705-4c0c-abb3-b1ef84bc24fc.png)
I did mainly the basic check of `vagrant up` and it took some time(emulation, yay!) but seems functional.
Thanks for taking your time to resolve this issue!

**Comment by AlexTalker** [comment]
@electrofelix I hope that you can publish the fix to the upstream soon, so I can discard the gem installation in favor of official Docker image =)

**Comment by electrofelix** [comment]
@AlexTalker once the pr merges the image tagged with 'edge' published to dockerhub will have the fix included

**Comment by electrofelix** [comment]
Or rather once the action https://github.com/vagrant-libvirt/vagrant-libvirt/actions/runs/3355840546/jobs/5560424557 is finished running
