### ISSUE TITLE
recent change to host_devices is too strict

### ISSUE THREAD

**Issue by al8ba** [vagrant-libvirt/vagrant-libvirt#1553]
I believe the recent change made here is too strict:
 
https://github.com/vagrant-libvirt/vagrant-libvirt/blob/591e151b13f9b520618854a245af2489de677352/lib/vagrant-libvirt/config.rb#L1216

This only permits hypervisor _interfaces_ to appear as devices when configuring networks, whereas it should also allow e.g. bridge devices.

I have a setup that until recently worked, where a VM configured a network like so:

```
  config.vm.network "public_network",
    :dev => 'purple',
    :type => 'bridge',
    auto_config: false
```

The device 'purple' used in the above is a bridge:

```
    $ virsh net-list
     Name              State    Autostart   Persistent
    ----------------------------------------------------
     blue              active   yes         yes
     vagrant-libvirt   active   yes         yes
     purple            active   yes         yes
```
```
$ virsh net-dumpxml purple
<network>
  <name>purple</name>
  <bridge name='purple' stp='off' delay='0'/>
  ...
</network>
```

However, the hypervisor itself has no interface on that particular bridge, so nothing about it appears here:

```
    $ virsh iface-list
     Name   State    MAC Address
    ------------------------------------
     blue   active   xx:xx:xx:xx:xx:xx
     eth0   active   xx:xx:xx:xx:xx:xx
     lo     active   00:00:00:00:00:00
```

As a result of the new check of device names against this interface list vagrant now refuses to bring up the VM. Formerly this worked just fine. It now gives this error:

    01:05:03  * network configuration 1 for machine test is a public_network referencing host device 'purple' which does not exist, consider adding ':dev => ....' referencing one of blue, eth0

It should be possible to attach interfaces on VMs to bridge networks, even if the hypervisor doesn't have an interface on the bridge itself. The check in host_devices should take this into account.

**Comment by electrofelix** [comment]
I thought mistakenly only host interfaces would be usable,  hadn't considered that a bridge for a public network might also use a libvirt bridge.

I'm guessing just combining the output of net-list including inactive networks should be sufficient to cover all possibilities, or will that still miss some?


AFAIK iface-list doesn't care if the hypervisor has an interface on the bridge or not as this should be the list of the host network devices, and will return the likes of docker0 if docker is installed (gets pruned from the list of usable ones as unlikely to be valid).

**Comment by al8ba** [comment]
Combining would work for my case.  Or should the check vary depending on the 'type' of the network? One wrinkle in just combining them is the subsequent check against `host_device_exclude_prefixes` which, if I read it correctly, defaults to `['docker', 'macvtap', 'virbr', 'vnet']` - I might want to configure a VM with a device attached to bridge `virbr17`...

**Comment by electrofelix** [comment]
My understanding is that would using a public network definition with a virbrX bridged network only possibly makes sense for a routed network, otherwise should just use a private network definition.

I'm guessing this would not be a common scenario and those that need it can adjust the config option for the filtered network devices to allow their usage as well.
