### ISSUE TITLE
When puppet present, it is not possible to install the plugin

### ISSUE THREAD

**Issue by JuliusLongmind** [vagrant-libvirt/vagrant-libvirt#1597]
**When puppet present, it is not possible to install the plugin**
On Manjaro when the puppet and the facter packages are installed, it is not possible to install the plugin.

**To Reproduce**
1. # sudo pacman -S puppet
2. # vagrant plugin install vagrant-libvirt
3. See error:
# vagrant plugin install vagrant-libvirt
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
/usr/lib/ruby/3.0.0/rubygems/resolver/conflict.rb:47:in `conflicting_dependencies': undefined method `request' for nil:NilClass (NoMethodError)
        from /usr/lib/ruby/3.0.0/rubygems/exceptions.rb:61:in `conflicting_dependencies'
        from /usr/lib/ruby/3.0.0/rubygems/exceptions.rb:55:in `initialize'
        from /usr/lib/ruby/3.0.0/rubygems/resolver.rb:193:in `exception'
        from /usr/lib/ruby/3.0.0/rubygems/resolver.rb:193:in `raise'
        from /usr/lib/ruby/3.0.0/rubygems/resolver.rb:193:in `rescue in resolve'
        from /usr/lib/ruby/3.0.0/rubygems/resolver.rb:191:in `resolve'
        from /usr/lib/ruby/3.0.0/rubygems/request_set.rb:411:in `resolve'
        from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/bundler.rb:591:in `internal_install'
        from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/bundler.rb:355:in `install'
        from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/plugin/manager.rb:138:in `block in install_plugin'
        from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/plugin/manager.rb:148:in `install_plugin'
        from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/plugins/commands/plugin/action/install_gem.rb:30:in `call'
        from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/action/warden.rb:48:in `call'
        from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/action/builder.rb:180:in `call'
        from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/action/runner.rb:101:in `block in run'
        from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/action/runner.rb:101:in `run'
        from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/plugins/commands/plugin/command/base.rb:14:in `action'
        from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/plugins/commands/plugin/command/install.rb:70:in `block in execute'
        from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/plugins/commands/plugin/command/install.rb:69:in `each'
        from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/plugins/commands/plugin/command/install.rb:69:in `execute'
        from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/plugins/commands/plugin/command/root.rb:66:in `execute'
        from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/cli.rb:67:in `execute'
        from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/environment.rb:301:in `cli'
        from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/bin/vagrant:248:in `<main>'
/usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:317:in `raise_error_unless_state': Unable to satisfy the following requirements: (Gem::Resolver::Molinillo::VersionConflict)

- `facter (= 3.14.24)` required by `user-specified dependency`
- `facter (>= 2.4.0, < 5)` required by `puppet-7.18.0`
        from /usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:299:in `block in unwind_for_conflict'
        from <internal:kernel>:90:in `tap'
        from /usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:297:in `unwind_for_conflict'
        from /usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:682:in `attempt_to_activate'
        from /usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:254:in `process_topmost_state'
        from /usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:182:in `resolve'
        from /usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolver.rb:43:in `resolve'
        from /usr/lib/ruby/3.0.0/rubygems/resolver.rb:190:in `resolve'
        from /usr/lib/ruby/3.0.0/rubygems/request_set.rb:411:in `resolve'
        from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/bundler.rb:591:in `internal_install'
        from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/bundler.rb:355:in `install'
        from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/plugin/manager.rb:138:in `block in install_plugin'
        from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/plugin/manager.rb:148:in `install_plugin'
        from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/plugins/commands/plugin/action/install_gem.rb:30:in `call'
        from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/action/warden.rb:48:in `call'
        from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/action/builder.rb:180:in `call'
        from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/action/runner.rb:101:in `block in run'
        from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/action/runner.rb:101:in `run'
        from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/plugins/commands/plugin/command/base.rb:14:in `action'
        from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/plugins/commands/plugin/command/install.rb:70:in `block in execute'
        from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/plugins/commands/plugin/command/install.rb:69:in `each'
        from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/plugins/commands/plugin/command/install.rb:69:in `execute'
        from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/plugins/commands/plugin/command/root.rb:66:in `execute'
        from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/cli.rb:67:in `execute'
        from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/environment.rb:301:in `cli'
        from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/bin/vagrant:248:in `<main>'

**Expected behavior**
The plugin should be installed without any error

**Versions (please complete the following information):**:
- Libvirt version: 8.7.0-1
- Vagrant version [output of `vagrant version`]: vagrant 2.3.0-7
- Vagrant flavour [Upstream or Distro]:  Manjaro 22.0.0
- Vagrant plugins versions (including vagrant-libvirt) [output of `vagrant plugin list`]: 
vagrant-libvirt (0.10.7, global)
vagrant-mutate (1.2.0, global)
- Packages are present and causing the issue:
Packages (2) facter-3.14.24-1  puppet-7.18.0-1

**Comment by electrofelix** [comment]
As vagrant-libvirt doesn't depend on either facter or puppet, and based on the error output there should be no problem with resolving the two facter specifications since `3.14.24` would satisfy `>= 2.4.0, < 5`:
```
facter (= 3.14.24) required by user-specified dependency
facter (>= 2.4.0, < 5) required by puppet-7.18.0
```

I suspect this is another occurrence of https://github.com/rubygems/rubygems/issues/5843

I'll leave it open for a little while longer, until I can do a test for other plugin installs as I suspect it's impacting any that cause a large enough resolution set if not impacting any install of a vagrant plugin.

**Comment by JuliusLongmind** [comment]
It seems it is a general issue, using any plugin related action I'm facing with this issue.

**Comment by electrofelix** [comment]
Thanks in that case going to close this with the assumption that you'll be watching the referenced issue. Manjaro might also be able to work around this by patching the gem spec in puppet to reduce the number of versions of facter considered acceptable.
