### ISSUE TITLE
Tag 0.10.7 has been added to a commit not on the main branch

### ISSUE THREAD

**Issue by dcermak** [vagrant-libvirt/vagrant-libvirt#1604]
The tag `0.10.7` does not point to a commit on main. I guess it has been force pushed away by accident? Could you please re-create that tag?

**Comment by electrofelix** [comment]
It appears that was the original push, seems I tagged the local commit rather than the final version that was merged to main.

Is it alright if once your fixes have merged if I tag the result as 0.10.8 and we go from there as the 0.10.7 has been tagged for a while?

**Comment by dcermak** [comment]
> Is it alright if once your fixes have merged if I tag the result as 0.10.8 and we go from there as the 0.10.7 has been tagged for a while?

Sure, works for me. Thank you!

**Comment by electrofelix** [comment]
I've tagged 0.10.8 and pushed up the corresponding gem, though I've managed to break the release workflow with a dependency update for part of it so I'll have to create the release entry in github manually in a little while.

I'll leave this open till I add the release entry.

**Comment by electrofelix** [comment]
Release page for 0.10.8 created and also fixed the issue that prevented it along with ensuring the release note generation is run on each merge to main to help generate a cache to reduce exceeding the github API limit from the release generation as well as catch any breakage quickly.
