### ISSUE TITLE
Fail to launch basic box - undefined method `pool_to_attributes' - NoMethodError

### ISSUE THREAD

**Issue by chdorb** [vagrant-libvirt/vagrant-libvirt#1685]
**Describe the bug**
Unable to start basic vagrant box with libvirt
Error:
```
/home/pdorbais/.vagrant.d/gems/3.0.4/gems/fog-libvirt-0.10.0/lib/fog/libvirt/requests/compute/list_pools.rb:39:in `find_pool_by_name': undefined method `pool_to_attributes' for #<Fog::Libvirt::Compute::Real:111420 @uri=#<Fog::Libvirt::Util::URI:0x00007fed30e784c8 @parsed_uri=#<URI::Generic qemu:/system>, @uri="qemu:///system"> @ip_command=" awk \\"/$mac/ {print \\\\$1}\\" /proc/net/arp " @client=#<Libvirt::Connect:0x00007fed30c5be60>> (NoMethodError)
```

**To Reproduce**
1. vagrant init ubuntu/focal64
2. vagrant up --provider=libvirt

**Expected behavior**
Running vagrant environment with libvirt provider

**Versions (please complete the following information):**:
- Libvirt version: 8.9.0
- Vagrant version [output of `vagrant version`]: 2.3.3 latest
```
Installed Version: 2.3.3
Latest Version: 2.3.3
 
You're running an up-to-date version of Vagrant!
```
- Vagrant flavour [Upstream or Distro]: Distro on archlinux 
- Vagrant plugins versions (including vagrant-libvirt) [output of `vagrant plugin list`]: 0.11.1 latest from today
```
vagrant-libvirt (0.11.1, global)
  - Version Constraint: > 0
```

**Debug Log**
Attach Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt >vagrant.log 2>&1`
`[vagrant.log](https://github.com/vagrant-libvirt/vagrant-libvirt/files/10141548/vagrant.log)

**A Vagrantfile to reproduce the issue:**
```
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
end
```

**Comment by electrofelix** [comment]
It was caused by a bug in fog-libvirt due to a mistake I made when submitting a PR there.

They gave already released a fix, but you'll need to reinstall the plugin. Trying to update it may be sufficient to pick up the 0.10.1 release of the fog-libvirt gem, but otherwise reinstalling the vagrant-libvirt plugin will resolve

**Comment by chdorb** [comment]
Yes it's all good, just had to uninstall/reinstall vagrant-libvirt plugin.
(By the way ubuntu/focal64 does not support libvirt but generic/ubuntu2004 does.)

Thanks @electrofelix !
