### ISSUE TITLE
graphics_port ignored and autoport missing from the XML request

### ISSUE THREAD

**Issue by grcancelliere** [vagrant-libvirt/vagrant-libvirt#1687]
**Describe the bug**
The `graphics_port` configuration from the Vagrantfile is ignored and the `<graphics>` XML node from the requests is missing the `autoport` key when `graphics_port` is set. Below are the different tries I made with the Vagrantfile at the end of the issue (as usual - is requested and + is result):

1. VM creation with `graphics_port = 5901`:
```
==> testlv: -    <graphics keymap="en-us" port="5901" type="vnc" websocket="-1">
==> testlv: +    <graphics autoport="no" keymap="en-us" port="5901" type="vnc" websocket="-1">
```

2. VM reload from `graphics_port = 5901` to `graphics_port = 5902`:
same as 1

3. VM reload with `graphics_port` deleted:
no difference between the request and the result

4. VM reload adding `graphics_port = 5901`:
```
==> testlv: -    <graphics keymap="en-us" port="-1" type="vnc" websocket="-1">
==> testlv: +    <graphics autoport="yes" keymap="en-us" port="-1" type="vnc" websocket="-1">
```

5. VM reload adding `graphics_autoport = "no"`:
same as 4

6. VM reload with `graphics_autoport = "yes"`:
same as 4

**To Reproduce**
1. Prepare an empty folder
3. Create a Vagrantfile with `graphics_port` different from the default
4. Execute `vagrant up` in the folder from step 1
5. See error

**Expected behavior**
The VNC port is set as per the Vagrantfile and the the XML received from libvirt is  how vagrant-libvirt created it.

**Versions (please complete the following information):**:
- Libvirt version: `8.10.0`
- Vagrant version [output of `vagrant version`]: `2.3.3`
- Vagrant flavour [Upstream or Distro]: Distro (Arch Linux)
- Vagrant plugins versions (including vagrant-libvirt) [output of `vagrant plugin list`]: `vagrant-libvirt (0.11.1, global)`

**Debug Log**
Attach Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt >vagrant.log 2>&1`
This is the output from a fresh `vagrant up` with the below Vagrantfile (i.e. step 1 from the description): [vagrant.tar.gz](https://github.com/vagrant-libvirt/vagrant-libvirt/files/10146963/vagrant.tar.gz)

**A Vagrantfile to reproduce the issue:**
```
Vagrant.configure("2") do |config|
  config.vm.define "testlv" do |testlv|
    testlv.vm.box = "archlinux/archlinux"
    testlv.vm.box_check_update = false
    testlv.vm.provider "libvirt" do |lv|
      lv.qemu_use_session = true
      lv.graphics_port = 5901
    end
  end
end
```

**Comment by electrofelix** [comment]
@grcancelliere I think I've fixed it all, but might be better if you can test with the gem added to #1693 PR [vagrant-libvirt-0.11.3.pre.2.gem.zip](https://nightly.link/vagrant-libvirt/vagrant-libvirt/actions/artifacts/468726474.zip). Can download unpack and install as a local gem in vagrant using `vagrant plugin install ./vagrant-libvirt-0.11.3.pre.2.gem`.

**Comment by grcancelliere** [comment]
@electrofelix after installing the local gem with your instructions all the cases from the description did not generate any error, so I agree with you this problem should be fixed, thanks!
