### ISSUE TITLE
vmxnet3 network model fails with iommu driver option is only supported for virtio devices

### ISSUE THREAD

**Issue by rgl** [vagrant-libvirt/vagrant-libvirt#1688]
**Describe the bug**

When using the `vmxnet3` network model, `vagrant up` fails with `Call to virDomainAttachDeviceFlags failed: unsupported configuration: iommu driver option is only supported for virtio devices`.

**To Reproduce**

1. `vagrant up`
2. See error

**Expected behavior**

Expected it to correctly define the libvirt domain.

**Versions (please complete the following information):**:

- Libvirt version: 8.0.0-1ubuntu7.3
- Vagrant version [output of `vagrant version`]: 2.3.3
- Vagrant flavour [Upstream or Distro]: Upstream
- Vagrant plugins versions (including vagrant-libvirt) [output of `vagrant plugin list`]: vagrant-libvirt (0.11.1, global)

**Debug Log**

```
DEBUG create_network_interfaces: Interface configuration: {:iface_type=>:private_network, :network_name=>"vagrant-libvirt", :ip=>"192.168.121.0", :netmask=>"255.255.255.0", :dhcp_enabled=>true, :forward_mode=>"nat", :guest_ipv6=>"yes", :autostart=>false, :bus=>nil, :slot=>nil, :driver_iommu=>false}
 INFO create_network_interfaces: Creating network interface eth0 connected to network vagrant-libvirt based on template interface.
DEBUG create_network_interfaces: Driver options: {:iommu=>"off"}
DEBUG create_network_interfaces: Attaching Network Device with XML:
<interface type="network">
  <alias name="ua-net-0"></alias>
  <source network="vagrant-libvirt"></source>
  <target dev="vnet0"></target>
  <alias name="net0"></alias>
  <model type="vmxnet3"></model>
  <driver iommu="off"></driver>
</interface>

ERROR warden: Error occurred: Error while attaching new device to domain. Call to virDomainAttachDeviceFlags failed: unsupported configuration: iommu driver option is only supported for virtio devices
```

**A Vagrantfile to reproduce the issue:**

```ruby
Vagrant.configure(2) do |config|
  config.vm.provider 'libvirt' do |lv, config|
    lv.nic_model_type = 'vmxnet3'
  end
end
```

**Comment by ipspace** [comment]
The same happens with `nic_model_type` set to `e1000`. The `<driver iommu>` should not be present when the `nic_model_type` is not `virtio`.

**Comment by ipspace** [comment]
Wow, that was super-fast. Thanks a million, testing... ;)

**Comment by electrofelix** [comment]
I still need to release it, hopefully shortly enough. Figured likely a few people would bump into it so worth a point patch release asap

**Comment by rbgarga** [comment]
@electrofelix I'm seeing the same problem with `e1000` nic and running vagrant-libvirt 0.11.2

**Comment by electrofelix** [comment]
@rbgarga I suspect #1702 fixed this fully, as my fix was only partial in the end

**Comment by rbgarga** [comment]
> @rbgarga I suspect #1702 fixed this fully, as my fix was only partial in the end

Awesome!  Thanks!
