### ISSUE TITLE
Network connection setup failed to bring up a multi-machine environment

### ISSUE THREAD

**Issue by yang-l** [vagrant-libvirt/vagrant-libvirt#1699]
**Describe the bug**

For a multi-machine environment setup, it is impossible to bring up all the guests with working network connections. It can only have one guest network connection working, e.g. either only bring up a single guest or only one guest connection is working if bring up multiple guests.

For example, this screenshot shows bring one guest first and then followed by bring up the second guest. And only the second guest is working via `vagrant ssh`

<img width="652" alt="Screen Shot 2022-12-18 at 9 51 31 PM" src="https://user-images.githubusercontent.com/5590810/208289589-1a9475c9-1a7f-4772-a5a8-88c261bb9f3b.png">

debug log files 
- bring up node1 [node1_up.log](https://github.com/vagrant-libvirt/vagrant-libvirt/files/10253486/node1_up.log)
- bring up node2 [node2_up.log](https://github.com/vagrant-libvirt/vagrant-libvirt/files/10253487/node2_up.log)
- `vagrant ssh` [vagrant_status.log](https://github.com/vagrant-libvirt/vagrant-libvirt/files/10253488/vagrant_status.log)

For another example, if bring up all the guests in one go, the `vagrant up` command is just hanging for very long time

<img width="642" alt="Screen Shot 2022-12-18 at 10 12 58 PM" src="https://user-images.githubusercontent.com/5590810/208290176-36375199-4ca9-4f80-804b-a18a962e483c.png">

The debug files shows it is hanging due to timeout

```
 INFO driver: Timeout at waiting for an ip address for machine node1
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO driver: Timeout at waiting for an ip address for machine node1
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO driver: Timeout at waiting for an ip address for machine node1
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO driver: Timeout at waiting for an ip address for machine node1
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO driver: Timeout at waiting for an ip address for machine node1
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
```
debug log file - [vagrant_up.log](https://github.com/vagrant-libvirt/vagrant-libvirt/files/10253501/vagrant_up.log)

Some extra information here

`ip addr` 

when no guest is up

```
$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether fc:34:97:66:27:64 brd ff:ff:ff:ff:ff:ff
    altname enp0s31f6
    inet 192.168.1.238/24 metric 100 brd 192.168.1.255 scope global dynamic eno1
       valid_lft 82097sec preferred_lft 82097sec
    inet6 fe80::fe34:97ff:fe66:2764/64 scope link
       valid_lft forever preferred_lft forever
3: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 52:54:00:13:11:62 brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0
       valid_lft forever preferred_lft forever
```

When one agent is up

```
$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether fc:34:97:66:27:64 brd ff:ff:ff:ff:ff:ff
    altname enp0s31f6
    inet 192.168.1.238/24 metric 100 brd 192.168.1.255 scope global dynamic eno1
       valid_lft 81998sec preferred_lft 81998sec
    inet6 fe80::fe34:97ff:fe66:2764/64 scope link
       valid_lft forever preferred_lft forever
3: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 52:54:00:13:11:62 brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0
       valid_lft forever preferred_lft forever
38: virbr1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 52:54:00:d2:78:46 brd ff:ff:ff:ff:ff:ff
    inet 192.168.121.1/24 brd 192.168.121.255 scope global virbr1
       valid_lft forever preferred_lft forever
39: vnet16: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master virbr1 state UNKNOWN group default qlen 1000
    link/ether fe:54:00:3f:95:3d brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fc54:ff:fe3f:953d/64 scope link
       valid_lft forever preferred_lft forever
40: macvtap10@eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 500
    link/ether aa:bb:cc:dd:ee:ff brd ff:ff:ff:ff:ff:ff
    inet6 fe80::a8bb:ccff:fedd:eeff/64 scope link
       valid_lft forever preferred_lft forever
```

When both guests are up

```
$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether fc:34:97:66:27:64 brd ff:ff:ff:ff:ff:ff
    altname enp0s31f6
    inet 192.168.1.238/24 metric 100 brd 192.168.1.255 scope global dynamic eno1
       valid_lft 81930sec preferred_lft 81930sec
    inet6 fe80::fe34:97ff:fe66:2764/64 scope link
       valid_lft forever preferred_lft forever
3: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 52:54:00:13:11:62 brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0
       valid_lft forever preferred_lft forever
38: virbr1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 52:54:00:d2:78:46 brd ff:ff:ff:ff:ff:ff
    inet 192.168.121.1/24 brd 192.168.121.255 scope global virbr1
       valid_lft forever preferred_lft forever
39: vnet16: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master virbr1 state UNKNOWN group default qlen 1000
    link/ether fe:54:00:3f:95:3d brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fc54:ff:fe3f:953d/64 scope link
       valid_lft forever preferred_lft forever
40: macvtap10@eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 500
    link/ether aa:bb:cc:dd:ee:ff brd ff:ff:ff:ff:ff:ff
    inet6 fe80::a8bb:ccff:fedd:eeff/64 scope link
       valid_lft forever preferred_lft forever
41: vnet17: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master virbr1 state UNKNOWN group default qlen 1000
    link/ether fe:54:00:09:ed:bd brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fc54:ff:fe09:edbd/64 scope link
       valid_lft forever preferred_lft forever
42: macvtap11@eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 500
    link/ether aa:bb:cc:dd:ee:00 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::a8bb:ccff:fedd:ee00/64 scope link
       valid_lft forever preferred_lft forever
```

`config.vm.network "forwarded_port"` was also tried for a couple of times, and still facing the same issue.

**To Reproduce**
1. `vagrant up` or `vagrant up node1` followed by `vagrant up node2`

**Expected behavior**
Both guests are up and able to be sshed via `vagrant ssh node1` and `vagrant ssh node2`

**Screenshots**
See the description

**Versions (please complete the following information):**:
- Libvirt version:
```
$ libvirtd --version
libvirtd (libvirt) 8.0.0
```
- Vagrant version [output of `vagrant version`]:
```
$ vagrant version
Installed Version: 2.2.19

Vagrant was unable to check for the latest version of Vagrant.
Please check manually at https://www.vagrantup.com
```
- Vagrant flavour [Upstream or Distro]: Ubuntu
- Vagrant plugins versions (including vagrant-libvirt) [output of `vagrant plugin list`]:
```
$ vagrant plugin list --local
vagrant-libvirt (0.11.2, local)
```

**Debug Log**
See the description

**A Vagrantfile to reproduce the issue:**
```
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure('2') do |config|
  config.vagrant.plugins = 'vagrant-libvirt'

  config.vm.box = 'generic/ubuntu2210'

  config.vm.define "node1" do |node|
    node.vm.network :public_network, :dev => 'eno1', :mac => 'aa:bb:cc:dd:ee:ff'
  end

  config.vm.define "node2" do |node|
    node.vm.network :public_network, :dev => 'eno1', :mac => 'aa:bb:cc:dd:ee:00'
  end
end
```

Note that - a `public_network` is created for each guest to allow other resources on the network to access the guests. However, even by removing the 2 `node.vm.network` line, the problem is still there.

**Comment by electrofelix** [comment]
I've seen this before, it looks like the new node is being detected as the same machine as when you bring them up in series, the dhcpclient on the second node gets the same address allocated as what was given to the first node.

Normally this means that the machine-id has been duplicated, however I can see that the generic boxes have a script to delete this https://github.com/lavabit/robox/blob/master/generic-libvirt.json#L3034, so it's a little unclear why it's occurring here.

When I bring up the two nodes using the generic/ubuntu2210 or generic/ubuntu2204 images I see the following for `virsh net-dhcp-leases`:
![image](https://user-images.githubusercontent.com/912324/208496977-6d0cb604-8f0d-42de-b8da-2669ce48086c.png)

When I bring up two debian/bullseye machines I see the following instead:
![image](https://user-images.githubusercontent.com/912324/208496831-3b270641-dfe2-4fff-8ef0-add118f9f4e7.png)

Having a look via virt-manager I can see that the machine-id is identical on each of the ubuntu2210 nodes. Looks like it's no longer sufficient to just delete /etc/machine-id, now need to wipe /var/lib/dbus/machine-id
![image](https://user-images.githubusercontent.com/912324/208498285-c14746df-8fc8-4b6f-8171-d04c8738b167.png)

lavabit/robox#257 suggests this should be fixed, but possibly hasn't been fully released.

**Comment by yang-l** [comment]
Hi @electrofelix , thanks for this information. We have made some provision scripts and orders, and we can boot up with 2 guests with different machine-id. So far we can access via `vagrant ssh` without problem. We will try this approach for a couple days, and will close this one if there is no more issue.

**Comment by electrofelix** [comment]
@yang-l looks like there just needs to be a release of robox as the latest images listed are 4.2.6, but you can see the fix for the machine-id isn't part of that https://github.com/lavabit/robox/compare/4.2.6...master

**Comment by electrofelix** [comment]
I'm going to close this, while the fix isn't yet released for the boxes, I expect it to appear and resolve the problem in the near future. In any case it's not possible to fix via this project.
