### ISSUE TITLE
Installation of vagrant-libvirt fails on Red Hat 9, cannot find installed libvirt.

### ISSUE THREAD

**Issue by katurian** [vagrant-libvirt/vagrant-libvirt#1716]
Describe the bug
Trying to install vagrant-libvirt fails on Red Hat 9 with the following error:

Vagrant failed to install the requested plugin because it depends
on a library which is not currently installed on this system. The
following library is required by the 'vagrant-libvirt' plugin:

  libvirt

Please install the library and then run the command again.
The same failure occurs if trying to download the .gem and installing locally.

libvirt is installed on the host machine. running whereis libvirt reveals the following:

libvirt: /usr/lib64/libvirt /etc/libvirt /usr/share/libvirt

To Reproduce

On a Red Hat 9 host with Vagrant and Libvirt installed, run sudo vagrant plugin install vagrant-libvirt
Expected behavior
The vagrant-libvirt plugin installs and vagrant works with provider Libvirt.

Versions (please complete the following information)::

Libvirt version: libvirt-8.5.0-7.el9_1.x86_64
Vagrant version [output of vagrant version]: 2.3.3
Vagrant flavour [Upstream or Distro]: Upstream from hashicorp.repo
Vagrant plugins versions (including vagrant-libvirt) [output of vagrant plugin list]: "No plugins installed."
Debug Log
Attach Output of VAGRANT_LOG=debug vagrant ... --provider=libvirt >vagrant.log 2>&1

[vagrant.log](https://github.com/vagrant-libvirt/vagrant-libvirt/files/10177726/vagrant.log)

A Vagrantfile to reproduce the issue:

No Vagrantfile involved in this bug.

I could not resolve this issue with https://vagrant-libvirt.github.io/vagrant-libvirt/installation.html#centos

**Comment by electrofelix** [comment]
@katurian the debug log needs to be of the command to install the plugin that fails, though in most cases where it's a failure to install the plugin the error message that appears usually references an `mkmf.log` log file and a `gem_make.out`. These are the files that are more important for this type of error and will indicate what the ruby-libvirt gem was unable to find when it was installed or what test compile step to check for libvirt failed.

Also please note that vagrant recommends against using `sudo vagrant plugin install vagrant-libvirt`, as that is attempting to install the plugin for root rather than for the current user. You need to run `vagrant plugin install vagrant-libvirt` as the user you want to use the plugin under.

**Comment by johnwmail** [comment]
$ cat ./.vagrant.d/gems/2.7.6/extensions/x86_64-linux/2.7.0/ruby-libvirt-0.8.0/mkmf.log 
"pkg-config --exists libvirt"
package configuration for libvirt is not found

I have the same issue on rhel8, thanks.

**Comment by johnwmail** [comment]
$ cat ./.vagrant.d/gems/2.7.6/extensions/x86_64-linux/2.7.0/ruby-libvirt-0.8.0/mkmf.log 
"pkg-config --exists libvirt"
| pkg-config --libs libvirt
=> "-lvirt \n"
"gcc -o conftest -I/opt/vagrant/embedded/include/ruby-2.7.0/x86_64-linux -I/opt/vagrant/embedded/include/ruby-2.7.0/ruby/backward -I/opt/vagrant/embedded/include/ruby-2.7.0 -I. -I/opt/vagrant/embedded/include -I/opt/vagrant/embedded/include   -I/opt/vagrant/embedded/include -I./include -O3 -std=c99 -fPIC conftest.c  -L. -L/opt/vagrant/embedded/lib -Wl,-rpath,/opt/vagrant/embedded/lib -L/opt/vagrant/embedded/lib -Wl,-rpath,/opt/vagrant/embedded/lib -L. -L/opt/vagrant/embedded/lib -L/opt/vagrant/embedded/lib64 -Wl,-rpath=/opt/vagrant/embedded/lib:/opt/vagrant/embedded/lib64 -fstack-protector-strong -rdynamic -Wl,-export-dynamic -L/opt/vagrant/embedded/lib  -Wl,-rpath,/opt/vagrant/embedded/lib     -Wl,-rpath,'/../lib' -Wl,-rpath,'/../lib' -lruby  -lm   -lc"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */

"gcc -o conftest -I/opt/vagrant/embedded/include/ruby-2.7.0/x86_64-linux -I/opt/vagrant/embedded/include/ruby-2.7.0/ruby/backward -I/opt/vagrant/embedded/include/ruby-2.7.0 -I. -I/opt/vagrant/embedded/include -I/opt/vagrant/embedded/include   -I/opt/vagrant/embedded/include -I./include -O3 -std=c99 -fPIC conftest.c  -L. -L/opt/vagrant/embedded/lib -Wl,-rpath,/opt/vagrant/embedded/lib -L/opt/vagrant/embedded/lib -Wl,-rpath,/opt/vagrant/embedded/lib -L. -L/opt/vagrant/embedded/lib -L/opt/vagrant/embedded/lib64 -Wl,-rpath=/opt/vagrant/embedded/lib:/opt/vagrant/embedded/lib64 -fstack-protector-strong -rdynamic -Wl,-export-dynamic -L/opt/vagrant/embedded/lib  -Wl,-rpath,/opt/vagrant/embedded/lib     -Wl,-rpath,'/../lib' -Wl,-rpath,'/../lib' -lruby -lvirt -lm   -lc"
//usr/lib64/libssh.so.4: undefined reference to `EVP_KDF_derive@OPENSSL_1_1_1b'
//usr/lib64/libssh.so.4: undefined reference to `EVP_KDF_ctrl@OPENSSL_1_1_1b'
//usr/lib64/libssh.so.4: undefined reference to `EVP_KDF_CTX_free@OPENSSL_1_1_1b'
//usr/lib64/libssh.so.4: undefined reference to `EVP_KDF_CTX_new_id@OPENSSL_1_1_1b'
collect2: error: ld returned 1 exit status
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */

package configuration for libvirt is not found


Hi, after installed libvirt-devel, I see this error message, thanks.

**Comment by electrofelix** [comment]
@johnwmail This looks like https://vagrant-libvirt.github.io/vagrant-libvirt/installation.html#loaderror-exceptions. I'm guessing the libraries have been updated so the instructions for CentOS 9 no longer work for RHEL 9 and will require following the additional steps for CentOS 8.

Presumably this is the source of the initial issue as well.

**Comment by katurian** [comment]
Thank you. I was able to install the plugin after running `export CONFIGURE_ARGS="with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib64"`. Closing.
