### ISSUE TITLE
when > 1 VM: 'Timeout at waiting for an ip address'

### ISSUE THREAD

**Issue by ezekieldas** [vagrant-libvirt/vagrant-libvirt#1735]
**Describe the bug**

When iterating through more than one VM, the first VM successfully completes yet the consecutive VMs will fail with
```
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO driver: Timeout at waiting for an ip address for machine haha95
```

I've looked at a number of similar issues here (vagrant-libvirt/vagrant-libvirt) as well as hashicorp/vagrant and hashicorp/packer. I've applied a number of parameters to my Packer and Vagrant configuration yet I seem to come around to the same results. My workaround for this issue is to do one machine at a time (eg, `vagrant up box1 && vagrant up box2`).

During the Vagrant build I've logged in to both boxes via `virt-manager` (please see provided screenshots) and I'm able to see all involved VMs with an ip address. I'm also able to ssh to each ip address from the hypervisor host.

The output of `for net in $(virsh net-list --name); do virsh net-dhcp-leases ${net}; done` only includes

```
 Expiry Time   MAC address   Protocol   IP address   Hostname   Client ID or DUID
-----------------------------------------------------------------------------------
 Expiry Time   MAC address   Protocol   IP address   Hostname   Client ID or DUID
-----------------------------------------------------------------------------------
 Expiry Time   MAC address   Protocol   IP address   Hostname   Client ID or DUID
-----------------------------------------------------------------------------------
 Expiry Time   MAC address   Protocol   IP address   Hostname   Client ID or DUID
-----------------------------------------------------------------------------------
 Expiry Time           MAC address         Protocol   IP address           Hostname   Client ID or DUID
------------------------------------------------------------------------------------------------------------------------------------------------
 2023-04-24 14:29:15   52:54:00:5e:a4:97   ipv4       192.168.121.156/24   haha95     ff:d7:6b:63:19:00:02:00:00:ab:11:8a:d8:0e:10:6b:64:20:b0
```
The artifacts I've included here are a pared down version of https://github.com/alvistack/vagrant-ubuntu.

Interestingly enough, if I run this against `alvistack/ubuntu-22.04` I have no issues. This occurs only when I run Vagrant against a custom Packer box.

**To Reproduce**

* Create Packer box with provided `packer.json` file
* Add completed box to Vagrant `vagrant box add output-vagrant/package.box --name my_ubuntu-22.04`
* Run vagrant with provided `Vagrantfile`: `VAGRANT_LOG=info vagrant up |& tee vagrant.out`

**Expected behavior**

Same results as using `alvistack/ubuntu-22.04`. More than 1 VM created via `vagrant up`

**Screenshots**
![va1](https://user-images.githubusercontent.com/2140070/234115847-604a7a21-1f83-4e4c-9d1e-603973832dec.jpg)

![va2](https://user-images.githubusercontent.com/2140070/234115873-bd02e892-a0f6-431a-9fb1-16e0fa5d6ea6.jpg)

**Versions (please complete the following information):**:
- Libvirt version:
```
# libvirtd -V
libvirtd (libvirt) 8.0.0
```
- Vagrant version [output of `vagrant version`]:
```
Installed Version: 2.3.4
Latest Version: 2.3.4
```
- Vagrant flavour [Upstream or Distro]:
I'm unsure what this means.

- Vagrant plugins versions (including vagrant-libvirt) [output of `vagrant plugin list`]:
```
vagrant plugin list
vagrant-libvirt (0.12.0, global)
```

- Packer version:
```
packer version
Packer v1.8.6
```

**Debug Log**

[vagrant.out.txt](https://github.com/vagrant-libvirt/vagrant-libvirt/files/11314655/vagrant.out.txt)

**A Vagrantfile to reproduce the issue:**

[Vagrantfile.txt](https://github.com/vagrant-libvirt/vagrant-libvirt/files/11314665/Vagrantfile.txt)
[Vagrantfile.yaml.txt](https://github.com/vagrant-libvirt/vagrant-libvirt/files/11314666/Vagrantfile.yaml.txt)

**The packer (and corresponding user-data) definition which created the box:**

[packer.json.txt](https://github.com/vagrant-libvirt/vagrant-libvirt/files/11314671/packer.json.txt)
[user-data.txt](https://github.com/vagrant-libvirt/vagrant-libvirt/files/11314672/user-data.txt)

**Comment by electrofelix** [comment]
Almost certain that this is caused due to dropping of one or both of the following lines
https://github.com/alvistack/vagrant-ubuntu/blob/ba4c8af39cc5fd32061e26f9f8f94daedfa96341/packer/ubuntu-22.04-libvirt/packer.json#LL67-L68

These ensure the machine id used for the DHCP client is uniquely generated. If you have 2 machines with the same id requesting addresses on boot the server will give the same address to both causing one to become inaccessible.

**Comment by ezekieldas** [comment]
Thanks for pointing that out. Yet in the 2nd screenshot it's evident there are two unique ip addresses taken. 

One thing I forgot to mention is that if I simply issue `ssh-keygen -A` and `systemctl restart sshd`, each VM will continue with success. 

With regards to what you've noted about machine-id though, I omitted that section due to it being dependent upon some a `provisioners` section calling ansible and doing a number of other things we don't feel are necessary. We can continue to dig, but would you happen to know of a means  where we can re-generate this machine-id without additional complexity?

**Comment by electrofelix** [comment]
The sysprep command also modifies the disk image contents to remove the existing host SSH keys. See default list of operations performed https://libguestfs.org/virt-sysprep.1.html#operations

Not sure if removing the seed file is used by systems to automatically trigger the host key regeneration or not. Bit rusty on that part.

I'd suggest restoring most of the post processor commands as besides the part injecting the firstboot script generated from a jinja2 template. The commands are all operating on the image file to customize it and shrink it to reduce the amount of space needed. (Making the kernel vminuz readable is typically needed by libguestfs used by some of the virt tools to perform operations on the image contents). The first boot script looks like all it's intended to do is ensure the hostname inside the VM reflects the name assigned by vagrant consistently.

**Comment by ezekieldas** [comment]
I've tried quite a few more things and continue to have trouble with this. One attempt at getting multiple boxes to build involved using https://github.com/lavabit/robox I simply followed the [Building a Box](https://github.com/lavabit/robox/#building-a-box) instructions with a very minor change of `headless: false` [and iso to be local](https://github.com/lavabit/robox/blob/783843b1e69cb8b3f5e73e3ade8c7964adada723/generic-libvirt.json#L5981):

`./robox.sh box generic-ubuntu2204-libvirt`

The resulting box presented strikingly issues as what I've reported above with `vagrant up.` The primary, and most fatal, symptom being sshd has no host keys and fails to start.

Any chance you could reproduce this? I was very surprised to see the same exact issue with a mostly untouched robox repository.

**Comment by ezekieldas** [comment]
I've also tried a minimalist approach in using the attached packer and vagrant files. These were created from scratch and involve only the bare minimum in box creation. I followed your suggestion above, "restoring most of the post processor commands" in this. With this I also end up with non-unique (same) machine-id, ssh being functional, yet only the first box being created. 

Here are the files I've used if you can reproduce: 
[vagrant-simple.tgz](https://github.com/vagrant-libvirt/vagrant-libvirt/files/11337999/vagrant-simple.tgz)

**Comment by ezekieldas** [comment]
I want to quickly note I believe I have something working. I'll provide details later but in short, I've used the following to get around this problem:

user-data:
```
  network:
      network:
          version: 2
          ethernets:
              eth0:
                 dhcp4: yes
                 dhcp-identifier: mac
```

Using the [virt-sysprep](https://github.com/alvistack/vagrant-ubuntu/blob/ba4c8af39cc5fd32061e26f9f8f94daedfa96341/packer/ubuntu-22.04-libvirt/packer.json#L68) line @electrofelix noted above, yet with the _omission_ of `-ssh-hostkeys`:

        "sudo virt-sysprep --operations defaults,-ssh-hostkeys,-ssh-userdir,-customize -a \"$_IMAGE.convert\"",

I'm unsure if it's one or both of these that allow each VM to get an address and allow sshd to function. I'll do some further testing soon and get back.

**Comment by ezekieldas** [comment]
Either approach noted above offers multiple dhcp addresses and/or sshd functionality. Closing this. Thanks for the insight @electrofelix!
