### ISSUE TITLE
Error message is misleading during installation

### ISSUE THREAD

**Issue by jkugler** [vagrant-libvirt/vagrant-libvirt#1744]
**Describe the bug**
I get an error about the libvirt library not being installed.

I tried both `vagrant plugin install vagrant-libvirt` as well as the method of pulling down the latest pre-release

**To Reproduce**
1. Install Vagrant 2.3.6
2. Open shell. As user, run `vagrant plugin install vagrant-librit`
3. Generates an error.

**Expected behavior**
Expect plugin to install.

**Screenshots**
```
$ vagrant plugin install vagrant-libvirt
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Fetching xml-simple-1.1.9.gem
Fetching nokogiri-1.15.2-x86_64-linux.gem
Fetching ruby-libvirt-0.8.0.gem
Building native extensions. This could take a while...
Vagrant failed to install the requested plugin because it depends
on a library which is not currently installed on this system. The
following library is required by the 'vagrant-libvirt' plugin:

  libvirt

Please install the library and then run the command again.
```
and
```
 $ vagrant plugin install vagrant-libvirt \
  --plugin-source https://jkugler:ghp_XXXXX@rubygems.pkg.github.com/vagrant-libvirt \
  --plugin-version "0.10.9.pre.62"
Installing the 'vagrant-libvirt --version '0.10.9.pre.62'' plugin. This can take a few minutes...
Fetching diffy-3.4.2.gem
Fetching formatador-1.1.0.gem
Fetching fog-core-2.3.0.gem
Building native extensions. This could take a while...
Vagrant failed to install the requested plugin because it depends
on a library which is not currently installed on this system. The
following library is required by the 'vagrant-libvirt' plugin:

  libvirt

Please install the library and then run the command again.
```

Some more experimentation revealed I needed the `libvirt-dev` package (this is Ubuntu). Once I did that, the install went off fine.

**Versions (please complete the following information):**:
- Libvirt version: 8.0.0
- Vagrant version [output of `vagrant version`]: 2.3.6
- Vagrant flavour [Upstream or Distro]: Upstream
- Vagrant plugins versions (including vagrant-libvirt) [output of `vagrant plugin list`]: latest

**Comment by electrofelix** [comment]
This is thrown by vagrant itself during when it is installing plugin dependencies. Unfortunately this means this project has no way of catching the error and displaying anything different:

Raised from
https://github.com/hashicorp/vagrant/blob/2092df529ae73bd0ae4d01e2d35c8952b9620988/lib/vagrant/plugin/manager.rb#L194

My guess is they added the error to make the output for when hashicorp/vagrant#11775 less verbose and easier to quickly see, however they pruned the output a little too much and might be receptive to the idea that it should say that the library or it's header files cannot be found as a hint. The actual package will vary from OS and specific distributions.

**Comment by jkugler** [comment]
Thanks for the quick update. I've opened a feature request with Vagrant. Thank you so much for maintaining a libvirt plugin!

https://github.com/hashicorp/vagrant/issues/13184
