### ISSUE TITLE
Not working mount_options of synced_folder using virtiofs

### ISSUE THREAD

**Issue by y-hashida** [vagrant-libvirt/vagrant-libvirt#1750]
Hi, project team!

## Describe
I specified owner and group in mount_options using virtiofs, but it does not change to the desired uid, gid.

I have checked with the following files.
Am I doing something wrong?

<br />

## Vagrantfile

```ruby
Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2204"
    config.vm.provider :libvirt do |libvirt|
        libvirt.cpus = 2
        libvirt.memory = 4096
        libvirt.memorybacking :access, :mode => "shared"
    end
    config.vm.synced_folder "./test",  "/mount_test",  type: "virtiofs", mount_options: ["uid=1001", "gid=1001"]
end
```
<br />

## Desirable state
The desired state is uid = 1001, gid = 1001.

```bash
vagrant@ubuntu2204:~$ ls -lhd /mount_test
drwxr-xr-x 2 1001 1001 4.0K Jul 15 17:10 /mount_test
```

<br />

## Actual state of occurrence

In fact, the uid and gid are not changed, and the owner and group remain vagrant.

```bash
vagrant@ubuntu2204:~$ ls -lhd /mount_test
drwxr-xr-x 2 vagrant vagrant 4.0K Jul 15 17:10 /mount_test
```

**Comment by electrofelix** [comment]
While I don't know if it works as desired, the correct format for the mount options is `mount_options: "uid=1001,gid=1001"`, it's not intended to be an array, rather a string that is passed as the value to the `-o` option of mount.

**Comment by y-hashida** [comment]
@electrofelix 
Thank you for your prompt reply!

I tried specifying "uid=1001,gid=1001" but got this error.

```bash
$ vagrant up 
Bringing machine 'default' up with 'libvirt' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* Shared folder mount options specified by 'mount_options' must
be an array of options.
```

I have checked with the following files.

```ruby
Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2204"
    config.vm.provider :libvirt do |libvirt|
        libvirt.cpus = 2
        libvirt.memory = 4096
        libvirt.memorybacking :access, :mode => "shared"
    end
    config.vm.synced_folder "./test",  "/mount_test",  type: "virtiofs", mount_options: "uid=1001,gid=1001"
end
```

It may indeed be correct to pass a string as the format of the linux mount command, but it seems that it needs to be in array format as an option in vagrant.

**Comment by electrofelix** [comment]
It's entirely possible that there is a mismatch between expectations here, and the end result is the mount options aren't being applied. I'd have to spend  some time looking into what exactly the mount ops resolve to at https://github.com/vagrant-libvirt/vagrant-libvirt/blob/448ed69f0ccbe8557157644a0ebd8809b35d5b71/lib/vagrant-libvirt/cap/mount_virtiofs.rb#L25

Since there is no debug log entry I'd hope that the line further down

**Comment by electrofelix** [comment]
Thug

**Comment by y-hashida** [comment]
I checked across the `puts opts` code and there is no `:mount_opts` key in the `opts`.

When I inserted the code `puts opts` for verification, I noticed that `opts` does not contain the :`mount_opts` key.

As a result, the `mount_opts` variable was an empty string.

**Comment by y-hashida** [comment]
After much investigation, it seems that the `mount -o` option does not work correctly with virtiofs.

>Known issues and limitations
>
>File-system mount options related to access time, such as noatime and strictatime, are not likely to work with virtiofs, and Red Hat discourages their use.

See: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/configuring_and_managing_virtualization/sharing-files-between-the-host-and-its-virtual-machines_configuring-and-managing-virtualization#:~:text=Known%20issues%20and%20limitations


We also looked at how the uid and gid are determined when mounted using virtiofs in vagrant-libvirt, and observed that they are determined by the uid and gid of the user when the `vagrant up` command is run on the host machine.


We also looked at how the uid and gid are determined when mounted using virtiofs in vagrant-libvirt, and observed that they are determined by the uid and gid of the host user.

For example
- If the user `test0` has a uid of `1000`, the mounted directory will be `1000:1000`.
  Note: (`1000` is the `vagrant` user/group, so `vagrant:vagrant`)
- If the user `test1` has uid `1001`, the mounted directory will be `1001:1001`.

I am still investigating whether this is caused by vagrant-libvirt or a virtiofs limitation.
If you know, I would appreciate it if you could let me know.

Also, if there is another way to specify uid and gid other than `mount -o`, I would appreciate it.

Thank you.

**Comment by y-hashida** [comment]
@electrofelix 

Upon additional investigation, I found the following method in a past issue to accomplish what I wanted to do

(explicitly specifying uid and gid)

https://github.com/vagrant-libvirt/vagrant-libvirt/issues/378#issuecomment-1277499557

And it seems to be inevitable that mount_options does not work with virtiofs, so I'll close this issue!

Sorry for all the trouble!
