### ISSUE TITLE
No image virtual size specified for box.

### ISSUE THREAD

**Issue by DarkevilPT** [vagrant-libvirt/vagrant-libvirt#1794]
![image](https://github.com/vagrant-libvirt/vagrant-libvirt/assets/3583885/6f4b42e9-19c8-47d9-85c1-2c98390678ec)
![image](https://github.com/vagrant-libvirt/vagrant-libvirt/assets/3583885/1f4d2f84-0cc6-490a-9398-194777c06bf5)

How can this be fixed?

**Comment by abbbi** [comment]
hi,

I think the problem might be that the metadata.json included in the box does not include
a virtual_size statement.

```
  ┆ ┆ ┆ def self.get_virtual_size(env)                                                                                                              
  ┆ ┆ ┆ ┆ # Virtual size has to be set for allocating space in storage pool.                                                                        
  ┆ ┆ ┆ ┆ box_virtual_size = env[:machine].box.metadata['virtual_size']                                                                             
  ┆ ┆ ┆ ┆ raise Errors::NoBoxVirtualSizeSet if box_virtual_size.nil?                                                                                
  ┆ ┆ ┆ ┆ return ByteNumber.from_GB(box_virtual_size)                                                                                                                                          
  ┆ ┆ ┆ end  
```

looking at the metadata.json from the box you provided:

```
 cat perk-VAGRANTSLASH-ubuntu-2204-arm64/20230416/libvirt/metadata.json 
{"format":"qcow2","provider":"libvirt"}
```

other boxes i have do include a metadat.json that provides the required setting:

```
cat debian-VAGRANTSLASH-testing64/20230501.1/libvirt/metadata.json 
{
  "provider"     : "libvirt",
  "format"       : "qcow2",
  "virtual_size" : 20
}
```
as discussed in https://github.com/jbowdre/vagrant-saltlab/issues/2 you can workaorund by setting the virtual size in the Vagrantfile?

**Comment by DarkevilPT** [comment]
I remember trying what he said and it didnt worked... I will eventually try this again.

**Comment by abbbi** [comment]
> I remember trying what he said and it didnt worked... I will eventually try this again.

you could also edit the metadata.json after extracting the image and add the virtual_size setting.

**Comment by abbbi** [comment]
I dont think there is a possible workaround via Vagrantfile, because vagrant-libvirt seems to expect this setting to be included in metadata.json.
