### ISSUE TITLE
vagrant-libvirt fails to bring machine up with ruby-libvirt 0.8.1

### ISSUE THREAD

**Issue by mrc0mmand** [vagrant-libvirt/vagrant-libvirt#1800]
**Describe the bug**

Earlier today our CI jobs that use Vagrant (and vagrant-libvirt) started suddenly failing when bringing up the test VMs:

```
==> archlinux_systemd_ci: Uploading base box image as volume into Libvirt storage...
==> archlinux_systemd_ci: Creating image (snapshot of base box volume).
==> archlinux_systemd_ci: Creating domain with the following settings...
==> archlinux_systemd_ci:  -- Name:              vagrant-arch-config.aH6_archlinux_systemd_ci
==> archlinux_systemd_ci:  -- Description:       Source: /root/systemd/vagrant-arch-config.aH6/Vagrantfile
...
==> archlinux_systemd_ci:  -- Image(vda):        /var/lib/libvirt/images/vagrant-arch-config.aH6_archlinux_systemd_ci.img, virtio, 120G
==> archlinux_systemd_ci:  -- Disk driver opts:  cache='default'
==> archlinux_systemd_ci:  -- Graphics Type:     vnc
==> archlinux_systemd_ci:  -- Video Type:        cirrus
==> archlinux_systemd_ci:  -- Video VRAM:        16384
==> archlinux_systemd_ci:  -- Video 3D accel:    false
==> archlinux_systemd_ci:  -- Keymap:            en-us
==> archlinux_systemd_ci:  -- TPM Backend:       emulator
==> archlinux_systemd_ci:  -- TPM Model:         tpm-crb
==> archlinux_systemd_ci:  -- TPM Version:       2.0
==> archlinux_systemd_ci:  -- INPUT:             type=mouse, bus=ps2
==> archlinux_systemd_ci:  -- RNG device model:  random
==> archlinux_systemd_ci:  -- Command line args: 
==> archlinux_systemd_ci:     -> value=-nographic, 
==> archlinux_systemd_ci:     -> value=-serial, 
==> archlinux_systemd_ci:     -> value=file:/tmp/vagrant-arch-serial-console.log, 
==> archlinux_systemd_ci: Removing domain...
==> archlinux_systemd_ci: Deleting the machine folder
Error while attaching new device to domain. Call to virDomainAttachDevice failed: Requested operation is not valid: domain is not running
```

I spent some time figuring out what exactly changed that caused this and it all boils down to today's 0.8.1 release of [ruby-libvirt](https://github.com/libvirt/libvirt-ruby/releases/tag/ruby-libvirt-0.8.1) - if I overwrite the ruby-libvirt files, that got pulled in with vagrant-libvirt, using stuff from 0.8.0, everything starts magically working again. I'm not really sure who to blame here, so apologies if I picked the wrong _target_.

**To Reproduce**
I reproduced this on both CentOS Stream 8 and CentOS Stream 9, following steps are from CentOS Stream 8.

```
# dnf -y install https://releases.hashicorp.com/vagrant/2.4.1/vagrant-2.4.1-1.x86_64.rpm
...
# dnf -y install gcc libguestfs-tools-c libvirt libvirt-devel libgcrypt make qemu-kvm ruby-devel
...
# export CONFIGURE_ARGS='with-ldflags="-L/opt/vagrant/embedded/lib64 -L/opt/vagrant/embedded/lib" with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib'
# export GEM_HOME=~/.vagrant.d/gems
# export GEM_PATH=$GEM_HOME:/opt/vagrant/embedded/gems
# export PATH=/opt/vagrant/embedded/bin:$PATH
# vagrant plugin install vagrant-libvirt
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Fetching xml-simple-1.1.9.gem
Fetching nokogiri-1.16.2-x86_64-linux.gem
Fetching ruby-libvirt-0.8.1.gem
Building native extensions. This could take a while...
Fetching formatador-1.1.0.gem
Fetching fog-core-2.4.0.gem
Fetching fog-xml-0.1.4.gem
Fetching fog-json-1.2.0.gem
Fetching fog-libvirt-0.12.0.gem
Fetching diffy-3.4.2.gem
Fetching vagrant-libvirt-0.12.2.gem
Installed the plugin 'vagrant-libvirt (0.12.2)'!
# mkdir testvm
# pushd testvm
# cat >Vagrantfile <<\EOF
Vagrant.configure("2") do |config|
  config.vm.box = "archlinux/archlinux"
  config.vm.synced_folder ".", "/vagrant", disabled: true
end
EOF
# systemctl start libvirtd.socket
# vagrant up --provider=libvirt
Bringing machine 'default' up with 'libvirt' provider...
==> default: Box 'archlinux/archlinux' could not be found. Attempting to find and install...
    default: Box Provider: libvirt
    default: Box Version: >= 0
==> default: Loading metadata for box 'archlinux/archlinux'
    default: URL: https://vagrantcloud.com/api/v2/vagrant/archlinux/archlinux
==> default: Adding box 'archlinux/archlinux' (v20240201.210938) for provider: libvirt (amd64)
    default: Downloading: https://vagrantcloud.com/archlinux/boxes/archlinux/versions/20240201.210938/providers/libvirt/amd64/vagrant.box
==> default: Successfully added box 'archlinux/archlinux' (v20240201.210938) for 'libvirt (amd64)'!
==> default: Uploading base box image as volume into Libvirt storage...
==> default: Creating image (snapshot of base box volume).
==> default: Creating domain with the following settings...
==> default:  -- Name:              testvm_default
==> default:  -- Description:       Source: /root/testvm/Vagrantfile
==> default:  -- Domain type:       kvm
==> default:  -- Cpus:              1
==> default:  -- Feature:           acpi
==> default:  -- Feature:           apic
==> default:  -- Feature:           pae
==> default:  -- Clock offset:      utc
==> default:  -- Memory:            512M
==> default:  -- Base box:          archlinux/archlinux
==> default:  -- Storage pool:      default
==> default:  -- Image(vda):        /var/lib/libvirt/images/testvm_default.img, virtio, 20G
==> default:  -- Disk driver opts:  cache='default'
==> default:  -- Graphics Type:     vnc
==> default:  -- Video Type:        cirrus
==> default:  -- Video VRAM:        16384
==> default:  -- Video 3D accel:    false
==> default:  -- Keymap:            en-us
==> default:  -- TPM Backend:       passthrough
==> default:  -- INPUT:             type=mouse, bus=ps2
==> default: Removing domain...
==> default: Deleting the machine folder
Error while attaching new device to domain. Call to virDomainAttachDevice failed: Requested operation is not valid: domain is not running
```

Now, to hotfix our CI, I used this very, _very_ ugly hack that downloads older ruby-libvirt on the side and just overwrites the files of the Vagrant's gem (I have no idea if there's a better way, but I hope there is). It's really ugly, but it does the trick:
```
# dnf -y install redhat-rpm-config
# TEMP_GEM="$(mktemp -d)"
# gem install -i "$TEMP_GEM" ruby-libvirt --version 0.8.0
Building native extensions. This could take a while...
Successfully installed ruby-libvirt-0.8.0
1 gem installed
# cp -rvf "$TEMP_GEM"/gems/ruby-libvirt-0.8.0/* ~/.vagrant.d/gems/*/gems/ruby-libvirt-0.8.*/
...
# rm -rf "$TEMP_GEM"
# vagrant up --provider=libvirt
Bringing machine 'default' up with 'libvirt' provider...
==> default: Checking if box 'archlinux/archlinux' version '20240201.210938' is up to date...
==> default: Creating image (snapshot of base box volume).
==> default: Creating domain with the following settings...
==> default:  -- Name:              testvm_default
...
==> default: Creating shared folders metadata...
==> default: Starting domain.
==> default: Domain launching with graphics connection settings...
==> default:  -- Graphics Port:      5900
==> default:  -- Graphics IP:        127.0.0.1
==> default:  -- Graphics Password:  Not defined
==> default:  -- Graphics Websocket: 5700
==> default: Waiting for domain to get an IP address...
==> default: Waiting for machine to boot. This may take a few minutes...
...
```

**Versions (please complete the following information):**:
- Libvirt version: libvirt-8.0.0-23.module_el8+785+dceced31.x86_64
- Vagrant version: 2.4.1
- Vagrant flavour: upstream
- Vagrant plugins versions (including vagrant-libvirt): 0.12.2

**Debug Log**
[log.txt](https://github.com/vagrant-libvirt/vagrant-libvirt/files/14211202/log.txt)

**A Vagrantfile to reproduce the issue:**
```Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.box = "archlinux/archlinux"
  config.vm.synced_folder ".", "/vagrant", disabled: true
end
```

**Comment by mrc0mmand** [comment]
I have a suspicion that the offending commit is https://github.com/libvirt/libvirt-ruby/commit/798c0ca0cefac5af53415ce0b05a2d36f76339be, and more specifically this part: https://github.com/libvirt/libvirt-ruby/commit/798c0ca0cefac5af53415ce0b05a2d36f76339be#diff-e8ba2e9be07f005ed8d56f70b6af98083ca276ed9c72003538b273e169d796ecL1307-L1321

If I'm reading the code right, previously it called `virDomainAttachDeviceFlags` if it was available even with flags == 0. With the change it now calls `virDomainAttachDevice` if flags == 0. But, according to the documentation [0] `virDomainAttachDevice` can be called _only_ on active domain, whereas `virDomainAttachDeviceFlags`, when called with flags == 0 (where 0 here means `VIR_DOMAIN_AFFECT_CURRENT` [1]), can be called on inactive domain.

@berrange: sorry for pinging you here, but since you're the author of the change can you shed some light into this?

[0] https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainAttachDevice
[1] https://libvirt.org/html/libvirt-libvirt-domain.html#VIR_DOMAIN_AFFECT_CURRENT

**Comment by berrange** [comment]
> If I'm reading the code right, previously it called virDomainAttachDeviceFlags if it was available even with flags == 0. With the change it now calls virDomainAttachDevice if flags == 0. But, according to the documentation [0] virDomainAttachDevice can be called only on active domain, whereas virDomainAttachDeviceFlags, when called with flags == 0 (where 0 here means VIR_DOMAIN_AFFECT_CURRENT [1]), can be called on inactive domain.

Yes, you're correct. In every case in libvirt  `virXXXFlags(0)` is equivalent to `virXXX()`, *except* for the Attach/Detach APIs where we had a historical design flaw, which I forgot about when changing the ruby. Please file a bug against libvirt-ruby for this

**Comment by mrc0mmand** [comment]
> > If I'm reading the code right, previously it called virDomainAttachDeviceFlags if it was available even with flags == 0. With the change it now calls virDomainAttachDevice if flags == 0. But, according to the documentation [0] virDomainAttachDevice can be called only on active domain, whereas virDomainAttachDeviceFlags, when called with flags == 0 (where 0 here means VIR_DOMAIN_AFFECT_CURRENT [1]), can be called on inactive domain.
> 
> Yes, you're correct. In every case in libvirt `virXXXFlags(0)` is equivalent to `virXXX()`, _except_ for the Attach/Detach APIs where we had a historical design flaw, which I forgot about when changing the ruby. Please file a bug against libvirt-ruby for this

Will do, thanks a lot for confirming this!

**Comment by mrc0mmand** [comment]
Filed as https://gitlab.com/libvirt/libvirt-ruby/-/issues/11 (I somehow completely missed the fact that the GH repo is a read-only mirror, whoops).

**Comment by mrc0mmand** [comment]
A fix for ruby-libivrt was merged (https://gitlab.com/libvirt/libvirt-ruby/-/merge_requests/31) and a new release was tagged (https://gitlab.com/libvirt/libvirt-ruby/-/tags/ruby-libvirt-0.8.2), so closing this as resolved.
