### ISSUE TITLE
Solaris11 host does not support "sync folder"

### ISSUE THREAD

**Issue by yogapugazh** [vagrant-libvirt/vagrant-libvirt#1820]
### Discussed in https://github.com/vagrant-libvirt/vagrant-libvirt/discussions/1819

<div type='discussions-op-text'>

<sup>Originally posted by **yogapugazh** May 20, 2024</sup>
Hi,

While trying to syncing folders between host and guest in the solaris host, it throws error

**Vagrant attempted to execute the capability 'mount_nfs_folder'
on the detect guest OS 'solaris11', but the guest doesn't
support that capability. This capability is required for your
configuration of Vagrant. Please either reconfigure Vagrant to
avoid this capability or fix the issue by creating the capability.**

Vagrantfile contains 
config.vm.synced_folder "./", "/vagrant", type: "nfs", mount_options: ['actimeo=2'], nfs_version: 4.1</div>

**Comment by abbbi** [comment]
i think you need to report this against the vagrant project, not vagrant-libvirt.
Vagrant has implemented the required capability for omnios (solaris community edition) see:

https://github.com/hashicorp/vagrant/issues/3280

As it seems to work for omnios, i think vagrant needs to be enhanced to do the same for solaris 11 
here and enable the capability accordingly. This cannot be done in vagrant-libvirt.

Currently vagrant only implements these capabilities for solaris 11, as seen in the list:

https://github.com/hashicorp/vagrant/tree/main/plugins/guests/solaris11/cap

Maybe its sufficient to use the same nfs folder stuff as for omnios where the nfs folder capability exists:

https://github.com/hashicorp/vagrant/tree/main/plugins/guests/omnios/cap
