### ISSUE TITLE
Reduce duplication between action_up and action_start

### ISSUE THREAD

**Issue by sciurus** [vagrant-libvirt/vagrant-libvirt#192]
We should be able to have action_up handle just the steps for creating a new domain, then call action_start. [Example](https://github.com/mitchellh/vagrant/blob/master/plugins/providers/virtualbox/action.rb#L297).

**Comment by infernix** [comment]
This is still relevant, flagging as enhancement.

**Comment by electrofelix** [comment]
I think I've taken care of this with #1410.
