### ISSUE TITLE
Can't install on Ubuntu 14.04

### ISSUE THREAD

**Issue by romu70** [vagrant-libvirt/vagrant-libvirt#229]
Hi,
Totally new to vagrant, and ruby, not a good start !

I'm trying to install vagrant-libvirt on Ubuntu 14.04. I first installed vagrant 1.6.4 through a download deb as the ubuntu package is pretty old (1.3.6).

The installation of the plugin fails when trying to install the ruby-libvirt plugin. Here is the trace:

```
user@vagrant:~$ sudo gem install ruby-libvirt -v '0.4.0'
Building native extensions.  This could take a while...
ERROR:  Error installing ruby-libvirt:
    ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from extconf.rb:1:in `<main>'


Gem files will remain installed in /var/lib/gems/1.9.1/gems/ruby-libvirt-0.4.0 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/ruby-libvirt-0.4.0/ext/libvirt/gem_make.out
```

And here, I'm stuck. Thanks for the help.

**Comment by slug** [comment]
If you still run into trouble, you might also need to install the 'libvirt-dev' package:
sudo apt-get install libvirt-dev
