### ISSUE TITLE
feature: option to set machine name

### ISSUE THREAD

**Issue by odigity** [vagrant-libvirt/vagrant-libvirt#289]
It would be nice to have a way to control tha name assigned to a machine on the host (the name that is used for the image file, and that shows up in Virtual Machine Manager).

For reference, see the second section (Virtual Machine Name) here demonstrating the same feature for the VirtualBox provider:

https://docs.vagrantup.com/v2/virtualbox/configuration.html

**Comment by odigity** [comment]
It's not perfect, but it's a big improvement.

What I want is complete control over the machine name so I can make it identical to the hostname.  I can get close by setting `default_prefix` to empty string, but there's no way currently to get rid of the leading underscore, which gets appended to the empty string before `env[:machine].name.to_s`.

It looks like it'd be an easy code change to skip the underscore when default_prefix is empty string (but not nil).  I could submit a PR if the maintainer is interested/willing.

**Comment by infernix** [comment]
@odigity please submit that PR, thanks :+1:

**Comment by pronix** [comment]
@odigity  @infernix  no one need it? where is PR ?

**Comment by infernix** [comment]
@pronix i'd like to see it, but @odigity was talking about a PR. I can look into it but have't had the time yet.

**Comment by brianjmurrell** [comment]
So, the suggestions above come close, but the one thing that cannot be changed is that an underscore (`_`) is always inserted between the `libvirt.default_prefix` and the name defined with `config.vm.define :name_you_want do ...`.

I'd opine that the underscore that is added between those two be eliminated and that if a user wants an underscore between `libvirt.default_prefix` and the name defined with `config.vm.define :name_you_want do ...` that they add that to the `libvirt.default_prefix`.

If you want to leave the underscore in when using the default value of the directory name, that is fine, but it also should be part of the default `libvirt.default_prefix`, not added between it and the `config.vm.define :name_you_want do ...`.

Would a PR implementing such be acceptable?

**Comment by electrofelix** [comment]
Just checking on issues and spotted this one, which appears has been fixed. Please let me know if it PR #885 is insufficient
