### ISSUE TITLE
Support separate storage pools for additional disks

### ISSUE THREAD

**Issue by pioro** [vagrant-libvirt/vagrant-libvirt#354]
Hello,
I have two disk pools and I would like to configure one as a default pool for OS system disks and other for data disks. According to documentation if ":path" is defined a non-default pool should be used but this is not a case.

Ex.
:path => 'pool_d2'

==> si:  -- Disks:         vdb(qcow2,40G)
==> si:  -- Disk(vdb):     /VM/d1/pool/pool_d2

I was trying to set :absolute_path but it doesn't work either.

Libvirt Provider:
- absolute volume paths like '/VM/d2/pool/si_u01.qcow2' not yet supported

regards,
Marcin

**Comment by pronix** [comment]
can you show your vagrantfile ?

**Comment by pioro** [comment]
Hello,

This is my vagrant file with path

Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "homeora65"

  config.vm.provider :libvirt do |libvirt|
	libvirt.storage_pool_name = "pool_d1"
        libvirt.memory=4096
        libvirt.cpus=2
        libvirt.storage :file, :size => '20G', :format => 'qcow2'
        libvirt.storage :file, :size => '5G', :format => 'qcow2', :path => "pool_d2"
        libvirt.storage :file, :size => '20G', :format => 'qcow2'
        libvirt.storage :file, :size => '20G', :format => 'qcow2'
  end

  config.vm.define :host do |host|
         host.vm.hostname = "targetkvm"
         host.vm.network :public_network, :dev => "br0", :mode => "bridge", :type => "bridge", :ip => "192.168.1.152"
         host.vm.network :private_network, :libvirt__network_name => "private", :ip => "10.10.10.152"
  end

end

**Comment by purpleidea** [comment]
@pioro I'm not sure I understand your question.
The system disks come as part of the vagrant base box. So using the Vagrantfile can't add a "system" disk... That already comes with the box.

**Comment by pioro** [comment]
Hi,

My image has only one system disk (vda) and that is OK. Wnat I need it to add additional disks like in my Vagrantfile (vdb, vdc, and so on). But all these new disk are added in same pool where system disk - pool_d1 in my case. I would like to use path to add disks in other disks pools.

Is it clear now ?

Marcin

**Comment by purpleidea** [comment]
@pioro Not entirely sure what you want to do and why, but with the information I have, I don't know the answer sorry.

Perhaps have a look at the code that handles the :disk feature, and if needed patch it.

Sorry I don't have a better answer, maybe someone else can understand.

Cheers,
James

**Comment by turkletron** [comment]
Same issue here.  Basically I have a KVM hypvervisor with 2 storage pools.  1 is spinning disk while the other is flash.  These need to be represented as separate disks inside the VM for the application I am working on.  Ideally during VM creation the virtual disks could be defined into specific storage pools.

**Comment by infernix** [comment]
What you're essentially asking for is a storage pool specification per additional disk. Right now we definitely do not support that. 

The only thing you could do now is symlink the created images to wherever you have your ssd or sata pool mounted.

I'll flag as enhancement, seems good to have but not trivial to implement I'm afraid.

**Comment by abbbi** [comment]
Im also in need of this feature, where is  the main culprit currently? is it the fog backend not supporting it?

**Comment by electrofelix** [comment]
I think this is resolved when connection is qemu:///system, qemu:///session requires some additional work, but I think that is a separate issue.
