### ISSUE TITLE
Error when importing box into libvirt storage: "internal error unable to parse qemu-img output"

### ISSUE THREAD

**Issue by wdennis** [vagrant-libvirt/vagrant-libvirt#441]
(Running with QEMU 2.3.94 & libvirt 0.9.9 with Vagrant 1.7.4 & vagrant-libvirt 0.0.30)

When I try to 'vagrant up' a libvirt box, I am getting the following error:

```
wdennis@ML-M6500:~/centos7-libvirt-vagrant$ vagrant up --provider=libvirt
Bringing machine 'test_vm' up with 'libvirt' provider...
==> test_vm: Uploading base box image as volume into libvirt storage...
/home/wdennis/.vagrant.d/gems/gems/fog-libvirt-0.0.2/lib/fog/libvirt/requests/compute/create_volume.rb:6:in `create_volume_xml': Call to virNetworkCreateXML failed: internal error unable to parse qemu-img output '' (Libvirt::Error)
```

(full stack trace at: http://pastie.org/10341731)

**Comment by choyj** [comment]
This problem just mysteriously appeared out of nowhere for me!  Every time I hit this problem I saw the following entry in my /var/log/syslog:

apparmor="DENIED" operation="exec" profile="/usr/sbin/libvirtd" name="/usr/local/bin/qemu-img" pid=60196 comm="libvirtd" requested_mask="x" denied_mask="x" fsuid=0 ouid=0
every time the error occurred.

Fixed this by adding the following line near the end of /etc/apparmor.d/usr.sbin.libvirtd:

/usr/local/bin/qemu-img rmix,

And then 'sudo service restart apparmor'.

**Comment by electrofelix** [comment]
@choyj /usr/bin/qemu-img would be the correct path for the system managed one that the apparmor already covers, I would look into where /usr/local/bin/qemu-img came from since that suggests a local install direct from source and would naturally be missing any apparmor configuration settings.

**Comment by choyj** [comment]
I was mostly interested in getting the thing running at the time rather than debugging how it got into this weird state.  But the trick here is to look at /var/log/syslog and see what's being blocked and unblock it.

**Comment by electrofelix** [comment]
@wdennis This seems like it was most likely caused by a security measure blocking execution and resulting in no output to be parsed.

Unless there is something else to add, going to close in two weeks.

**Comment by choyj** [comment]
I have no more to add here.  I forgot what I was even doing back then.  Feel free to close.

**Comment by wdennis** [comment]
Same as @choyj  - I have not used Vagrant with libvirt since 2015... I will close.
