### ISSUE TITLE
kvm/qemu TLS enforced.

### ISSUE THREAD

**Issue by cloudnull** [vagrant-libvirt/vagrant-libvirt#45]
When using the vagrant-libvirt the boot up process attempts to use TLS to connect to the system, even when libvirtd is running on localhost. 

``` stacktrace

 INFO connect_libvirt: Connecting to Libvirt (qemu://localhost/system?no_verify=1)
ERROR warden: Error occurred: Error while connecting to libvirt: Error making a connection to libvirt URI qemu://localhost/system?no_verify=1:
Call to virConnectOpen failed: Cannot read CA certificate '/etc/pki/CA/cacert.pem': No such file or directory
```

While this makes a lot of sense when running in production, this make attempting to use the plugin for development purposes difficult. I am not sure that this is necessarily an "issue", as I do recommend using TLS in production and it is likely that I am doing something wrong and or have something miss-configured within vagrant, however I feel like this should be something that can either be documented elsewhere and or a flag thrown to circumvent it, imo. 

Otherwise Fantastic Plugin and thanks for your hard work.

**Comment by narkisr** [comment]
Had the same issue on Ubuntu 14.04 all I had to do was to set the libvirt provider use the correct connection uri:

```ruby
     node.vm.provider :libvirt do |domain|
       domain.uri = 'qemu+unix:///system'
        domain.host = 'virtualized'
        domain.memory = 2048
        domain.cpus = 4
      end
```

I think that this indeed a bug since plugin tried to connect to qemu:///foo/system (foo is my instance name) which is considered to be remote.

**Comment by SaimonL** [comment]
Thank you narkisr you solution worked for me as well. I just wish this information was on the main git page. I know lots of people would like to test locally first and they will be new to qemu just like me.

**Comment by stephenfin** [comment]
Don't know if this is exactly the same issue, but I was able to resolve this by adding myself to the `libvirt` user group, as seen [here](http://wiki.libvirt.org/page/SSHSetup#3._Manage_group_membership). I also configured `polkit`, per the [Fedora documentation](https://fedoramagazine.org/running-vagrant-fedora-22/), though I'm not sure if this had any impact.

**Comment by LalatenduMohanty** [comment]
I think it is related. The user does not have access permission to access libvirt URI. So `sudo vagrant up` solved the issue for me.

```
$ vagrant up
Bringing machine 'default' up with 'libvirt' provider...
Error while connecting to libvirt: Error making a connection to libvirt URI qemu:///system?no_verify=1&keyfile=/home/vagrant/.ssh/id_rsa:
Call to virConnectOpen failed: authentication failed: no agent is available to authenticate
```

**Comment by devtosystems** [comment]
I need to run this box withou KVM because I have a conflict in my workspace with Android Emulator and "kvm is busy" bug, but... I not succeeded:

```bash
$ vagrant reload
Ignoring ruby-libvirt-0.7.0 because its extensions are not built.  Try: gem pristine ruby-libvirt --version 0.7.0
tosystems@localhost's password: 
==> default: Halting domain...
==> default: Starting domain.
==> default: Waiting for domain to get an IP address...
==> default: Waiting for SSH to become available...
@localhost's password: 
Permission denied, please try again.
@localhost's password: 
Permission denied, please try again.
@localhost's password: 
```


My Vagrantfile is below:

```bash
#!/bin/bash
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu-amd64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network :forwarded_port, guest: 80, host: 8084

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  ##config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  ##config.vm.network "public_network", ip: "192.168.1.5", bridge: "en1: Wi-Fi (AirPort)"

  config.ssh.private_key_path = "~/.ssh/id_rsa"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder "~/projects", "/home/vagrant/myprojects"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false

    # Customize the amount of memory on the VM:
    vb.memory = "2024"
  end


  ##config.ssh.proxy_command = "/usr/bin/ssh -A -t localhost nc %h %p"
  config.ssh.forward_agent = true

  config.vm.provider "libvirt" do |lv|
    # Display the libvirt configurations
    lv.driver = "qemu"
    
    # Libvirt Settings.
    lv.storage_pool_name = "default"
    lv.host = "localhost"
    #lv.username = "vagrant"
    
    lv.nested = true
    lv.connect_via_ssh = true
    lv.cpu_mode = "host-model"
    lv.memory = "2048"
 end

end
```

What's happening, please?

**Comment by pronix** [comment]
it is ssh connection

**Comment by devtosystems** [comment]
@pronix  I know that ssh connection.
The problem is that my private key is not password and vagrant box call the password.

**Comment by psachin** [comment]
@stephenfin 

Adding user to `libvirt` group solved the issue.

**Comment by nh2** [comment]
@psachin doesn't it have to be the `libvirtd` group, not `libvirt`?

**Comment by psachin** [comment]
@nh2 It is `libvirt` a-least in Fedora

```
[psachin@nubia ~]# getent group libvirt
libvirt:x:985:psachin
[psachin@nubia ~]# getent group libvirtd
[psachin@nubia ~]# 
```

**Comment by nh2** [comment]
Ah OK; in Ubuntu it seems to be `libvirtd` ([see here](https://help.ubuntu.com/lts/serverguide/libvirt.html)) but in Debian it seems to be `libvirt` ([see here](https://wiki.debian.org/KVM)). Quite confusing.

**Comment by aidda** [comment]
@francisrod01 was it solve? I had the same issue! my user currently in libvirtd groups!

**Comment by francisrod01** [comment]
No, I'm not use libvirt anymore.

**Comment by spiro** [comment]
> Ah OK; in Ubuntu it seems to be `libvirtd` ([see here](https://help.ubuntu.com/lts/serverguide/libvirt.html)) but in Debian it seems to be `libvirt` ([see here](https://wiki.debian.org/KVM)). Quite confusing.

For me in Ubuntu 18.04, it was libvert :D
