### ISSUE TITLE
virt-sysprep: unknown option `--no-logfile'.

### ISSUE THREAD

**Issue by Seeohelaien** [vagrant-libvirt/vagrant-libvirt#453]
When trying to package a box with "vagrant package --output name" this error message is displayed:

...
 INFO interface: info: ==> default: Image has backing image, copying image and rebasing ...
virt-sysprep: unknown option `--no-logfile'.
virt-sysprep: reset or unconfigure a virtual machine so clones can be made

 virt-sysprep [--options] -d domname

 virt-sysprep [--options] -a disk.img [-a disk.img ...]

A short summary of the options is given below.  For detailed help please
read the man page virt-sysprep(1).
...

This output appears to come from:
in file: vagrant-libvirt/lib/vagrant-libvirt/action/package_domain.rb
line 40:
`virt-sysprep --no-logfile --operations defaults,-ssh-userdir -a #{@tmp_img}`

$ virt-sysprep --version
virt-sysprep 1.20.11

running on RHEL6.4
I've been unable to find when the virt-sysprep API changed to or from having the --no-logfile option

**Comment by nvtkaszpir** [comment]
Same issue under Ubuntu 14.04 with ``virt-sysprep`` 1.24.5.
Also notice, that in my version there is no ``--options`` but ``--enable``.

Not to mention that it does not suppoert Windows guests.

**Comment by electrofelix** [comment]
Looks like this was added in 2013 see https://github.com/libguestfs/libguestfs/commit/7b825803520a5ba08eac5fe5d05b691cd33438b9.

Guessing it is no longer a problem at this stage.
