### ISSUE TITLE
Unable to configure `machine`

### ISSUE THREAD

**Issue by pravka** [vagrant-libvirt/vagrant-libvirt#494]
The docs state that `machine` is configurable, but I get an error when I attempt to do so:

```
Libvirt Provider:
* The following settings shouldn't exist: machine
```

I looked at the actions, and unless I'm mistaken, it doesn't appear this was ever implemented.

**Comment by infernix** [comment]
There's `machine_type` and `machine_arch` so this is probably referencing old documentation which was fixed. So closing.
