### ISSUE TITLE
owner in synced_folder causes mount to fail in guest Ubuntu Trusty

### ISSUE THREAD

**Issue by scfc** [vagrant-libvirt/vagrant-libvirt#503]
If `owner` is set to anything as in `README.md`'s example:

```
config.vm.synced_folder './', '/vagrant', type: '9p', disabled: false, accessmode: "squash", owner: "vagrant"
```

vagrant-libvirt will try to execute and fail on a Ubuntu Trusty image converted from https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box to libvirt:

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -t 9p -o trans=virtio,access=vagrant,version=9p2000.L '/vagrant' /vagrant

Stdout from the command:



Stderr from the command:

stdin: is not a tty
mount: wrong fs type, bad option, bad superblock on /vagrant,
       missing codepage or helper program, or other error
       In some cases useful info is found in syslog - try
       dmesg | tail  or so
```

`sudo dmesg | tail` shows:

```
[  929.295345] 9p: Installing v9fs 9p2000 file system support
[  945.457959] 9p: Unknown access argument vagrant
```

Manually mounting the volume without the `access=vagrant` option or amending `Vagrantfile` and running `vagrant reload` will make the mount succeed (I think; I'm running into permissions problems on the host then, so I couldn't confirm that it truly works).

I'm not sure where the capabilities of the filesystem driver are defined so that vagrant-libvirt could do The Right Thing™, but at least it should be mentioned in `README.md`.

**Comment by infernix** [comment]
This is a documentation error:
```
  access	there are four access modes.
			user  = if a user tries to access a file on v9fs
			        filesystem for the first time, v9fs sends an
			        attach command (Tattach) for that user.
				This is the default mode.
			<uid> = allows only user with uid=<uid> to access
				the files on the mounted filesystem
			any   = v9fs does single attach and performs all
				operations as one user
			client = ACL based access check on the 9p client
			         side for access validation
```

It should specify either `user` or an actual UID; _not_ a username.
