### ISSUE TITLE
HOST/GUEST communication : vagrant libvirt static address for GUEST / DHCP NAT

### ISSUE THREAD

**Issue by stephencooke** [vagrant-libvirt/vagrant-libvirt#517]
I like most have been finding the NAT/DHCP address and the guest inside getting a random address slightly getting in my way.

Is it possible to allocate the MAC address to a given IP in vagrants usage of dnsmasq.  it is possible on a normal dnsmasq setup as I use it allocate IP to the office.

Communication between the HOST and GUEST via bridged interfaces dont work for me.  Ideally using the NAT inferface would be ideal if the HOST could force an IP to the GUEST.

can we adjust the DHCP ranges per node?, ie force each node to use DHCP range of 1.

workaround for me is having to edit the HOST /etc/hosts with the new inside address for the GUEST. not ideal

**Comment by infernix** [comment]
Can you elaborate on why the private_network feature - where you can assign a static IP - doesn't solve your need? It is designed specifically for this use case.

As for the management network, in theory you could use a netmask of /30 like this:

```ruby
  config.vm.provider "libvirt" do |v|
    v.management_network_name = 'ptptest'
    v.management_network_address = "192.168.123.20/30"
end
```

The problem however is that this puts the gateway (and therefore host interface IP) at 192.168.123.21, but the dnsmasq config will still be set to give out addresses .21 and .22. I'm not sure if that's correct. The VM I tested with does get .22 assigned though so maybe dnsmasq is clever enough.  

Does that answer your question?

**Comment by infernix** [comment]
Closing this due to no further updates/info. Please free to update or reopen this ticket if required. Thanks!
