### ISSUE TITLE
Setting the Description value in libvirt

### ISSUE THREAD

**Issue by fbrier** [vagrant-libvirt/vagrant-libvirt#518]
How do you set the virtual machine Description so it shows up in virt-manager?

**Comment by fxkr** [comment]
You can't, currently. It would be easy to implement though. The patch would be very similar to bfea80d7891ab0703cf9228f6dbf259684d2c333.

(Disclaimer: not my project -> I don't know if someone would merge it.)

**Comment by fbrier** [comment]
Thank you.  I might take a SWAG at it.  If successful, I could try and implement #519.

**Comment by infernix** [comment]
This is not yet supported; I'll label this as an enhancement, it isn't much work to add this type of functionality.

**Comment by electrofelix** [comment]
Looks like it just requires a single element 'title' added to the domain XML -> https://libvirt.org/formatdomain.html#elementsMetadata

**Comment by rgl** [comment]
I'm submitted #1137. Please take a look and review it!
