### ISSUE TITLE
Ubuntu 15.10 

### ISSUE THREAD

**Issue by narkisr** [vagrant-libvirt/vagrant-libvirt#520]
Iv tried to set up Ubuntu 15.10 using vagrant librvirt with no success, iv taken a number of virtualbox based boxes and mutated them using vagrant mutate, still they are all stuck on:

```bash
 Waiting for domain to get an IP address...
```
Picking into the VM I can see that no nic is detected (though the VM does have them defined)

**Comment by narkisr** [comment]
BTW I know that Ubuntu had changed the way nic are being named so this might be related to that http://askubuntu.com/questions/689070/network-interface-name-changes-after-update-to-15-10-udev-changes

**Comment by varac** [comment]
i'm on ubuntu 15.10 as well, without any problems.
i just upgraded from vagrant 1.7.4 to 1.8, and it went well too. maybe you can give 1.8 a try ?

**Comment by gintsgints** [comment]
I  did upgrade vagrant to 1.8.1. and got error:
```
/home/gpolis/.vagrant.d/gems/gems/ruby-libvirt-0.6.0/lib/libvirt.rb:11:in `require': incompatible library version - /home/gpolis/.vagrant.d/gems/gems/ruby-libvirt-0.6.0/lib/_libvirt.so (LoadError)
```

**Comment by narkisr** [comment]
Try to uninstall the plugin and reinstall it (I had similar issues and that did the trick)

**Comment by narkisr** [comment]
regarding the original issue I had to build a custom box in which the old interface naming scheme is set see https://github.com/narkisr/ubuntu/commit/3c7902dc62543c898e7b2869e72ecaa46add7281#diff-efed037e09416a4d5a6a57dc2cdd64bb

**Comment by gintsgints** [comment]
I confirm that wih Vagrant 1.8.1 I get same error.

**Comment by devekko** [comment]
getting same errors with Xenial host

**Comment by devekko** [comment]
@narkisr I just built a box from your boxcutter fork and tried again and get errors

am new to libvirt and libvirt provider so, not for certain its specific to Vagrant, though I did build manually KVM vm no worries for networking

here is my Vagrantfile

'''
Vagrant.configure("2") do |config|

  # Tell Vagrant where would you like to start your VMs (you can also have a
  # specific per-VM configuration. Do not put this section in case you want to
  # start your VMs on the same host)
  config.vm.provider :libvirt do |libvirt|
    libvirt.host = '10.1.10.98'
    libvirt.username = 'devekko'
    libvirt.connect_via_ssh = true
  end

  # Here's our VM confguration
  config.vm.define :libvirt_trusty_vm do |machine|

    # It should be an Ubuntu 14.04 box
    machine.vm.box = "narkisir-trusty64"

    # With a public IP (it's optional)
    machine.vm.network :private_network
    machine.vm.network :public_network, :mode => "bridge", :type => "bridge"

    # With so much RAM and CPUs
    machine.vm.provider :libvirt do |domain|
      domain.memory = 2048
      domain.cpus = 2
    end

  end
end
'''

**Comment by narkisr** [comment]
@devekko what is your nic? you need to set a device:

```ruby
node.vm.network :public_network, :bridge => device , :dev => device
```

**Comment by devekko** [comment]
thanks

I try various 

#    machine.vm.network :public_network, use_dhcp_assigned_default_route: true, :dev => "enp2s0f0", :mode => "bridge", :type => "bridge"
     machine.vm.network :public_network, :dev => "enp2s0f0", :mode => "bridge", :type => "bridge"
#    machine.vm.network :public_network, use_dhcp_assigned_default_route: true

errors 

will investigate

**Comment by ericpulvino** [comment]
I'm getting the same error... when trying to boot a mutated Xenial box.

==> server1: Waiting for domain to get an IP address...

Just sits there forever.

Relavant section of the Vagrantfile for this VM --> https://gist.github.com/ericpulvino/763ada637afac1f8d940d3bbfd345605

**Comment by infernix** [comment]
The problem here is that likely the box images aren't sending out DHCP requests on the correct interface; additionally it may be the case that libvirt plugs in the nic in a different slot for various reasons which would then in turn change the interface naming inside the VM (which can cause this). 

For that last problem I've created a new issue #609 - in the meantime, when you mutate a box, make sure `net.ifnames=0 biosdevname=0` is in the kernels cmdline and dhcp is active on eth0 by default.

**Comment by narkisr** [comment]
Ubuntu versions above 15.10 use interface names which aren't ethX (eth0/1/2) vagrant does not cope with that. 

A workaround is to disable the new naming scheme in Ubuntu https://github.com/narkisr/ubuntu/commit/04d1802c7627cd241b983e84b2afa44a5872e90c

**Comment by infernix** [comment]
@narkisr i'm not sure vagrant can't handle it at all because I think it's fine for Fedora and RHEL for example:

https://github.com/mitchellh/vagrant/blob/master/plugins/guests/fedora/cap/configure_networks.rb

But it may need upstream patching for ubuntu/debian:

https://github.com/mitchellh/vagrant/blob/master/plugins/guests/debian/cap/configure_networks.rb

**Comment by narkisr** [comment]
Sure, didn't mean that Vagrant can't handle it, but instead that its not handling it correctly right now :)

Thanks
