### ISSUE TITLE
Enable travis CI

### ISSUE THREAD

**Issue by electrofelix** [vagrant-libvirt/vagrant-libvirt#549]
Since the travis CI should now work for vagrant-libvirt and I've got some more spec tests for WaitTillUp action lined up to be used as examples for additional spec tests for people to add, it might be useful to enable the travis CI for PR's.

Have it enabled on my fork, which is useful for me to catch any mistakes coming through from changes I plan to submit for PR's.

**Comment by infernix** [comment]
Will try to get this enabled.

**Comment by infernix** [comment]
Done!

**Comment by electrofelix** [comment]
Yay!
