### ISSUE TITLE
libvirt with debian/jessie64 cannot set hostname 

### ISSUE THREAD

**Issue by moozer** [vagrant-libvirt/vagrant-libvirt#603]
### Steps to reproduce
1. select image

   `vagrant init debian/jessie64`

2. set hostname in Vagrantfile

  ` config.vm.hostname = "testmachine"`

3. start it

  `vagrant up`

### Expected behaviour
The virtual machine should boot normaly at set its hostname to "testmachine"

### Actual behaviour
The machine boots, and when we get to the point about setting hostname it fails with the following message

The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

```
 hostname -f
 Stdout from the command:
 Stderr from the command:
 sudo: unable to resolve host jessie.raw
 stdin: is not a tty
 hostname: Name or service not known

```

Using `vagrant ssh`, I get the same behavior when issuing a `hostname -f` 

### System configuration
**OS/Distro version:**:
`$ uname -a`
> Linux lennart 4.2.0-0.bpo.1-amd64 #1 SMP Debian 4.2.6-1~bpo8+1 (2015-11-18) x86_64 GNU/Linux

It is mostly Debian/testing

**Libvirt version:**

`$ virsh --version`
> 1.2.21

**Output of `vagrant version; vagrant plugin list`:**
`$ vagrant version; vagrant plugin list`

```
 Installed Version: 1.7.4
 Latest Version: 1.8.1
  
 To upgrade to the latest version, visit the downloads page and
 download and install the latest version of Vagrant from the URL
 below:
 
   http://www.vagrantup.com/downloads.html
 
 If you're curious what changed in the latest release, view the
 CHANGELOG below:
 
   https://github.com/mitchellh/vagrant/blob/v1.8.1/CHANGELOG.md
 fog-libvirt (0.0.3)
   - Version Constraint: 0.0.3
 vagrant-libvirt (0.0.32)
 vagrant-share (1.1.5, system)
``` 

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**

My backbuffer in my terminal is not long enough.
How can I output both stderr and stdout in the same log file?

**A Vagrantfile to reproduce the issue:**
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.box = "debian/jessie64"
  config.vm.hostname = "testmachine"

end

```

**Are you using upstream vagrant package or your distros package?**
Distro from Debian/testing

**Comment by moozer** [comment]
To the core, is the problem that jessie.raw does not resolve.
/etc/hosts contains ip for "jessie" and hostname is "jessie.raw".

How can I circumvent that?

**Comment by infernix** [comment]
```
DEBUG guest: Searching for cap: change_host_name
DEBUG guest: Checking in: debian
DEBUG guest: Found cap: change_host_name in debian
 INFO guest: Execute capability: change_host_name [#<Vagrant::Machine: default (VagrantPlugins::ProviderLibvirt::Provider)>, "testmachine"] (debian)
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: hostname -f (sudo=true)
DEBUG ssh: stderr: sudo: unable to resolve host jessie.raw

DEBUG ssh: stderr: stdin: is not a tty

DEBUG ssh: stderr: hostname: 
DEBUG ssh: stderr: Name or service not known
DEBUG ssh: stderr: 

DEBUG ssh: Exit status: 1
ERROR warden: Error occurred: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

hostname -f

Stdout from the command:



sudo: unable to resolve host jessie.raw
```

This is a bug in the vagrant box image and should be reported to the Debian cloud team; it is not a vagrant or vagrant-libvirt issue.

**Comment by infernix** [comment]
fwiw, i talked to the debian cloud devs, they are aware of it and it'll be fixed sometime soon.

**Comment by moozer** [comment]
That was my impression also.

And thanks for the last addition - Can you tell med where I can find "the debian cloud devs"?

**Comment by babilen** [comment]
That would be https://wiki.debian.org/Teams/Cloud

**Comment by terceiro** [comment]
https://anonscm.debian.org/cgit/cloud/debian-vm-templates.git/ - vmdebootstrap-libvirt-vagrant

**Comment by terceiro** [comment]
the image on atlas was just updated. you need to delete it locally and download again, because we don't have proper versioning yet.

**Comment by infernix** [comment]
Thanks @terceiro!

**Comment by moozer** [comment]
it works, thanks.

**Comment by babilen** [comment]
Ta!
