### ISSUE TITLE
feature: support creation of virtio-serial channel for qemu-agent

### ISSUE THREAD

**Issue by shawnlower** [vagrant-libvirt/vagrant-libvirt#605]
### Steps to reproduce
1. Create Vagrant box using libvirt provider
2. Inspect libvirt XML for required channel definition
3. 

### Expected behaviour
The qemu-agent allows the host to communicate with a qemu guest agent running inside the VM, to perform tasks such as freezing/thawing of filesystems (useful for backups), and updating the guest time. 

vagrant-libvirt does not appear to support the creation of the serial communication channel necessary for utilizing the guest agent.

The minimum configuration should be something like:
```
<channel type='unix'>
  <target type='virtio' name='org.qemu.guest_agent.0'/>
</channel>
```
### Actual behaviour
The above XML needs to be added to the guest after launch, and requires the VMs to be shutdown.

### System configuration
**OS/Distro version:**:

**Libvirt version:**

**Output of `vagrant version; vagrant plugin list`:**

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**
```
 INFO global: Vagrant version: 1.8.2.dev
 INFO global: Ruby version: 2.2.5
 INFO global: RubyGems version: 2.4.8
 INFO global: VAGRANT_LOG="debug"
 INFO global: VAGRANT_INTERNAL_BUNDLERIZED="1"
```

**A Vagrantfile to reproduce the issue:**
```
Vagrant.configure(2) do |config|
    config.vm.provider :libvirt do |libvirt|
        libvirt.memory = 512
    end
    config.vm.define "master" do |master|
        master.vm.box = "fedora/23-cloud-base"
    end
    config.vm.define "node1" do |master|
        master.vm.box = "fedora/23-cloud-base"
    end
    config.vm.define "node2" do |master|
        master.vm.box = "fedora/23-cloud-base"
    end
end
```

**Are you using upstream vagrant package or your distros package?**
Not in Fedora 23, or upstream

**Comment by infernix** [comment]
Somewhat related to #597 but no, this is not currently implemented. Will tag as feature request.

**Comment by shawnlower** [comment]
So, I actually was able to get it to work in master with the following patch:

https://github.com/vagrant-libvirt/vagrant-libvirt/compare/master...shawnlower:shawnlower_add-guest-agent-support

Not sure how terrible that is, but it seems to work for both qemu-agent and #597 's issue.

**Comment by infernix** [comment]
Great, send a PR and I'll review/test soon-ish :+1:

**Comment by infernix** [comment]
Closing, fixed in above PR
