### ISSUE TITLE
Ubuntu 16.04 Boxes will not Boot.

### ISSUE THREAD

**Issue by ericpulvino** [vagrant-libvirt/vagrant-libvirt#607]
### Steps to reproduce
1. vagrant mutate boxcutter/ubuntu1604
2. vagrant init boxcutter/ubuntu1604
3. vagrant up --provider=libvirt

### Expected behaviour
The box should receive an IP and boot.

### Actual behaviour
The box gets stuck during the boot process, DHCP never completes and the box never boots. Similar to Issue #520 

(eric@xenial1)-(10:11 PM Tue May 31)->
-(17 files, 324Kb)--> vagrant up --provider=libvirt
Bringing machine 'default' up with 'libvirt' provider...
==> default: Creating image (snapshot of base box volume).
==> default: Creating domain with the following settings...
==> default:  -- Name:              eric_default
==> default:  -- Domain type:       kvm
==> default:  -- Cpus:              1
==> default:  -- Memory:            512M
==> default:  -- Management MAC:    
==> default:  -- Loader:            
==> default:  -- Base box:          boxcutter/ubuntu1604
==> default:  -- Storage pool:      default
==> default:  -- Image:             /var/lib/libvirt/images/eric_default.img (64G)
==> default:  -- Volume Cache:      default
==> default:  -- Kernel:            
==> default:  -- Initrd:            
==> default:  -- Graphics Type:     vnc
==> default:  -- Graphics Port:     5900
==> default:  -- Graphics IP:       127.0.0.1
==> default:  -- Graphics Password: Not defined
==> default:  -- Video Type:        cirrus
==> default:  -- Video VRAM:        9216
==> default:  -- Keymap:            en-us
==> default:  -- TPM Path:          
==> default:  -- INPUT:             type=mouse, bus=ps2
==> default:  -- Command line : 
==> default: Creating shared folders metadata...
==> default: Starting domain.
==> default: Waiting for domain to get an IP address...

### System configuration
**OS/Distro version:**:
Ubuntu 16.04

**Libvirt version:**
libvirtd (libvirt) 1.3.1

**Output of `vagrant version; vagrant plugin list`:**
(eric@xenial1)-(10:14 PM Tue May 31)->
-(17 files, 324Kb)--> vagrant version
Installed Version: 1.8.1
Latest Version: 1.8.1
 
You're running an up-to-date version of Vagrant!

(eric@xenial1)-(10:14 PM Tue May 31)->
-(17 files, 324Kb)--> vagrant plugin list
vagrant-cumulus (0.1)
vagrant-libvirt (0.0.33)
  - Version Constraint: 0.0.33
vagrant-mutate (1.1.0)
vagrant-share (1.1.5, system)

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**
https://gist.github.com/ericpulvino/1d90fa0c38275aad4bb6ec0ec452044c

**A Vagrantfile to reproduce the issue:**

```
Vagrant.configure(2) do |config|
  config.vm.box = "boxcutter/ubuntu1604"
end
```

**Are you using upstream vagrant package or your distros package?**
Upstream

**Comment by ericpulvino** [comment]
I was able to use virt-manager to enter the grub menu of the VM prior to boot and get into the recovery console. In the process of booting the machine I saw the following message on the Console.

![image](https://cloud.githubusercontent.com/assets/7875697/15698007/f1f68ff4-278d-11e6-9642-d03115516f11.png)

After hitting ctrl+c and continuing with the boot process, I was able to observe the following issues.

Essentially the box ships with default configuration for an interface that is not present -- enp0s3 but only the ens5 adapter exists. It sounds like this is a configuration item inside the VM. Here is the default /etc/network/interfaces file which references the non-existant enp0s3 adapter.
![image](https://cloud.githubusercontent.com/assets/7875697/15698017/1a099f7c-278e-11e6-937c-8e3f768d3093.png)

When I change enp0s3 to ens5 in the /etc/network/interfaces file then ifup the ens5 interface, the vagrant-libvirt boot process completes...

![image](https://cloud.githubusercontent.com/assets/7875697/15698083/d4cf4136-278e-11e6-86f1-bff2536b9f76.png)

I'm understanding the issue a bit better but I have no idea how to fix this... without rolling a custom box which should not be needed here.

I'm also not sure why this issue appears only for the libvirt/kvm hypervisor and not in other hypervisors like virtualbox where the initial boot process works just fine.

**Comment by ericpulvino** [comment]
Looks like there is a hierarchy to the naming scheme used by the kernel... specifically Libvirt/KVM is using Scheme2 but Ubuntu's base config is expecting Scheme3 --> https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Networking_Guide/ch-Consistent_Network_Device_Naming.html#sec-Naming_Schemes_Hierarchy

So Libvirt/KVM is giving more info about the NIC to Ubuntu than it has with Virtualbox which influences the kernel to select naming scheme 2. Ok... the problem is understood now. I think but what can be done about this? I imagine this could effect other OSes too but I have not seen it elsewhere with other Systemd OSes... so something must be different about Ubuntu.... but what?

**Comment by ericpulvino** [comment]
I was not aware that Hashicorp was allowing for provider=libvirt image storage, I feel like I had looked a while back and that wasn't possible. Anyways this is great... now to convince trusted groups to build images for the platform. I point customers to demos using pre-packed boxes and having boxes built by trusted sources helps to build customer confidence. Ironically I just use UDEV to rename interfaces anyways so the interface names don't really bother me because I immediately overwrite them /w Udev rules.

**Comment by ericpulvino** [comment]
Seems like this is more of a box configuration issue, would you agree? Admittedly I was not aware the vagrant-libvirt did not have support for predictable interface renaming perhaps that could be more prominently advertised. I would submit a documentation PR but something tells me you can articulate the supported features much better than I; a mere lowly user :)

**Comment by infernix** [comment]
The box needs to use ethX nic names which is set with `biosdevname=0 net.ifnames=0` on kernel cmdline (or otherwise hardcoded). So libvirt boxes are configured with this.

We need to add enpXsX support to vagrant-libvirt all the same though.

**Comment by infernix** [comment]
Closing out this one since the problem ultimately was in a misconfigured (mutated) box image where it did not activate dhcp on the VM NIC.
