### ISSUE TITLE
libvirt__host_ip /  libvirt__guest_ip :

### ISSUE THREAD

**Issue by stephencooke** [vagrant-libvirt/vagrant-libvirt#608]
### Steps to reproduce
1. unable to set a static to guest ip for private interface., no option exists
2. I am after a solution that allows for DHCP to be disabed, as it populates the guest with bad information and leaves a dhcp client running.  neither of which I want.
3.

### Expected behaviour
Tell us what should happen

be able to set a static address to the guest via a config setting

### Actual behaviour
Tell us what happens instead

### System configuration
**OS/Distro version:**:

**Libvirt version:**

**Output of `vagrant version; vagrant plugin list`:**

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**
```
Insert debug output inside quotes here (replace ... with whatever command you use to trigger the issue)
```

**A Vagrantfile to reproduce the issue:**
```
Insert Vagrantfile inside quotes here (remove sensitive data if needed)
```

**Are you using upstream vagrant package or your distros package?**
Upstream / Distro

**Comment by infernix** [comment]
Please read the documentation here: https://github.com/vagrant-libvirt/vagrant-libvirt#networks

The very first example is a static IP config.
