### ISSUE TITLE
Disable backing_file or support for VM image clone

### ISSUE THREAD

**Issue by sudhagarc** [vagrant-libvirt/vagrant-libvirt#614]
IMO, this is more an enhancement (or information) request. I tried to find the information online, but in vain and couldn't find a mailing list or forum to seek support on this, hence posting it here.

I'm looking for a way to setup multi machine VM environment using Vagrant on libvirt host. I noticed that by default libvirt provider uses backing_store for the VM image. This makes VM creation faster, but there are some performance penalties. I'm wondering whether there is an option to disable the backing_store so that initial creation could be slower, but there will not be any performance penalties. I would need this because I wasn't to setup a characterization environment where virtual machine's performance.

I appreciate any input.

### System configuration
**OS/Distro version:**:
1. Vagrant is invoked from CentOS 6.5
2. Libvirt host is CentOS 7.2.1511

**Libvirt version:**  1.2.17

**Output of `vagrant version; vagrant plugin list`:**
vagrant-libvirt (0.0.33)
vagrant-mutate (1.1.0)
vagrant-nodemaster (1.1.3)
  - Version Constraint: 1.1.3
vagrant-rekey-ssh (0.1.9)
vagrant-share (1.1.5, system)

**Comment by infernix** [comment]
This isn't possible for the box image but why isn't the interface to add additional disks enough? You have a lot more options there. Then simply mount those wherever and use those to test with.

**Comment by sudhagarc** [comment]
Thanks for the response, I have been looking at that as alternate option. Clone option makes the configuration simple for at least few cases.

**Comment by sudhagarc** [comment]
Adding additional disks will change the way VM disk is configured and this will differ from how the production VM image will look like. I'm trying to keep it as close as possible to production image.

On the other hand, I notice that VM created using Vagrant runs extremely slow. For e.g., it takes order of few minutes to reboot the VM [Shutdown alone took almost 4m 30s; It's almost 8m and VM is still booting]. Whereas a VM created using virsh from same qcow2 that was used to created box runs several times faster. I compared the XML for both these VMs and they look similar except for backingStore option in Vagrant. Both VMs are run on the same libvirt host with same cpu/mem configuration.

Is it possible to add a support to disable backingStore and in that case Vagrant can download/copy images for each VM spun? I understand that initial VM creation could be slow in this case, but saves lot of time afterwards. 

PS: I'm still trying to debug why Vagrant created VM is extremely slow as I'm unable to convince myself that backingStore could be creating such a performance drop.

**Comment by infernix** [comment]
I don't know why you are so slow and you haven't provided any logs, but with this Vagrantfile:

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure(2) do |config|

  config.vm.define "ubuntu-16.04" do |v|
    v.vm.hostname = "ubuntu-16.04"
    v.vm.box = "mkutsevol/xenial"
    v.vm.synced_folder ".", "/vagrant", disabled: true
    v.vm.provider :libvirt do |domain|
      domain.memory = 512
      domain.cpus = 1
    end
  end

end
```

I get these speeds (provided the box image was downloaded already:

time vagrant up:
```
Bringing machine 'ubuntu-16.04' up with 'libvirt' provider...
==> ubuntu-16.04: Creating image (snapshot of base box volume).
==> ubuntu-16.04: Creating domain with the following settings...
==> ubuntu-16.04:  -- Name:              vagrantbugs_ubuntu-16.04
==> ubuntu-16.04:  -- Domain type:       kvm
==> ubuntu-16.04:  -- Cpus:              1
==> ubuntu-16.04:  -- Memory:            512M
==> ubuntu-16.04:  -- Management MAC:    
==> ubuntu-16.04:  -- Loader:            
==> ubuntu-16.04:  -- Base box:          mkutsevol/xenial
==> ubuntu-16.04:  -- Storage pool:      default
==> ubuntu-16.04:  -- Image:             /var/lib/libvirt/images/vagrantbugs_ubuntu-16.04.img (9G)
==> ubuntu-16.04:  -- Volume Cache:      default
==> ubuntu-16.04:  -- Kernel:            
==> ubuntu-16.04:  -- Initrd:            
==> ubuntu-16.04:  -- Graphics Type:     vnc
==> ubuntu-16.04:  -- Graphics Port:     5900
==> ubuntu-16.04:  -- Graphics IP:       127.0.0.1
==> ubuntu-16.04:  -- Graphics Password: Not defined
==> ubuntu-16.04:  -- Video Type:        cirrus
==> ubuntu-16.04:  -- Video VRAM:        9216
==> ubuntu-16.04:  -- Keymap:            en-us
==> ubuntu-16.04:  -- TPM Path:          
==> ubuntu-16.04:  -- INPUT:             type=mouse, bus=ps2
==> ubuntu-16.04:  -- Command line : 
==> ubuntu-16.04: Creating shared folders metadata...
==> ubuntu-16.04: Starting domain.
==> ubuntu-16.04: Waiting for domain to get an IP address...
==> ubuntu-16.04: Waiting for SSH to become available...
    ubuntu-16.04: 
    ubuntu-16.04: Vagrant insecure key detected. Vagrant will automatically replace
    ubuntu-16.04: this with a newly generated keypair for better security.
    ubuntu-16.04: 
    ubuntu-16.04: Inserting generated public key within guest...
    ubuntu-16.04: Removing insecure key from the guest if it's present...
    ubuntu-16.04: Key inserted! Disconnecting and reconnecting using new SSH key...
==> ubuntu-16.04: Setting hostname...
==> ubuntu-16.04: Configuring and enabling network interfaces...

real	0m15.382s
user	0m2.681s
sys	0m0.108s
```

time vagrant halt:
```
==> ubuntu-16.04: Halting domain...

real	0m2.475s
user	0m1.402s
sys	0m0.052s
```

Not sure what you're doing wrong. This is on SSD, but still. Maybe you're not using KVM?

**Comment by sudhagarc** [comment]
Great! I was playing with various parameters and changed kvm to qemu. After change, the performance is far better and acceptable. Thanks a lot for the insight.
