### ISSUE TITLE
Autostart of management network

### ISSUE THREAD

**Issue by sudhagarc** [vagrant-libvirt/vagrant-libvirt#615]
Another question. 

How do I set the "management" (default: vagrant-libvirt) network to autostart via., configuration? I notice that domains (VMs) can be set to autostart (stated explicitly in Readme). I notice that it may be possible to do the same for network, though the option is unclear. I would appreciate some insight on the same. To summarize:
1. How do I set "management" network to autostart?
2. Is autostart option supported for public and private networks?
3. If so, how do I set the same for public/private networks?
### System configuration

**OS/Distro version:**:
1. Vagrant is invoked from CentOS 6.5
2. Libvirt host is CentOS 7.2.1511

**Libvirt version:** 1.2.17

**Output of `vagrant version; vagrant plugin list`:**
vagrant-libvirt (0.0.33)
vagrant-mutate (1.1.0)
vagrant-nodemaster (1.1.3)
Version Constraint: 1.1.3 vagrant-rekey-ssh (0.1.9) vagrant-share (1.1.5, system)

**Comment by infernix** [comment]
This question is for libvirt, but FYI: https://libvirt.org/sources/virshcmdref/html/sect-net-autostart.html and it can apply to any network. 

I suggest you get familiar with libvirt and virt-manager.

**Comment by sudhagarc** [comment]
Looks like I didn't express it properly. I understand, libvirt support it using "net-autostart". However, my question is how do I do it in Vagrant for the management network it creates for communication?

**Comment by infernix** [comment]
vagrant-libvirt makes libvirt networks. Vagrant doesn't make any networks. So, if you autostart the network that vagrant-libvirt creates (see `sudo virsh net-list`) you have what you want. You can't do that in Vagrant.

**Comment by sudhagarc** [comment]
When vagrant-libvirt is creating libvirt (management) network, is it possible to execute virsh net-autostart automatically on libvirt host? If so, can this support be added?

**Comment by infernix** [comment]
Why would you want to do that? You  a) don't need to do that when you use `vagrant up` and b) you can just run `virsh net-autostart foo` once and be done with it?

**Comment by sudhagarc** [comment]
I'm setting up a recreatable test environment for resiliency. So, I'll be power cycling one host, say A, and see how the App VMs in other host is detecting the failure and picking it up. When host A boots up, I want the VMs to be running again so they join the cluster, without manual intervention. 

This situation rules out option #a. I can certain do option #b automatically by adding this step in my ansible provisioner to set this up after all VMs are up. I want to avoid manual execution, because I want the scripts to be reusable within team and want to automate as much as possible. If this support can be added easily in vagrant-libvirt, it makes VM creation contained within vagrant and design will be simple. Since vagrant-libvirt supports autostart for domain (& perhaps, other network), I *thought* it could be easy. I could be wrong.

**Comment by infernix** [comment]
So guess what:

```ruby
              # Prepare a hash describing network for this specific interface.
              @interface_network = {
                name:             nil,
                ip_address:       nil,
                netmask:          @options[:netmask],
                network_address:  nil,
                bridge_name:      nil,
                created:          false,
                active:           false,
                autostart:        false,
                guest_ipv6:       @options[:guest_ipv6] || 'yes',
                libvirt_network:  nil
              }
```

That implies that you can just do:
```ruby
  config.vm.define :test_vm1 do |test_vm1|
    test_vm1.vm.network :private_network, :ip => "10.20.30.40", :autostart => true
  end
```

Evidently this isn't documented, but the support is there. It may be possible that it only applies when first creating the net, so delete it first and try then. If you can confirm I will update the docs.

**Comment by sudhagarc** [comment]
Looks like vagrant-libvirt network is created under the hood as management network. When I set autostart to other network, it did not take effect.

Before vagrant up:
```
[root@compute4 images]# virsh net-list
 Name                 State      Autostart     Persistent
----------------------------------------------------------
 default              active     yes           yes
```

After vagrant up:
```
[root@compute4 images]# virsh net-list
 Name                 State      Autostart     Persistent
----------------------------------------------------------
 default              active     yes           yes
 vagrant-libvirt      active     no            yes
```

However, I did a quick hack of following file:
```
lib/vagrant-libvirt/action/create_networks.rb

 51               # Prepare a hash describing network for this specific interface.
 52               @interface_network = {
 53                 name:             nil,
 54                 ip_address:       nil,
 55                 netmask:          @options[:netmask],
 56                 network_address:  nil,
 57                 bridge_name:      nil,
 58                 created:          false,
 59                 active:           false,
 60                 autostart:        true,   ### HACK: false -> true
 61                 guest_ipv6:       @options[:guest_ipv6] || 'yes',
 62                 libvirt_network:  nil
 63               }
```

Here is the result after vagrant up:
```
[root@compute4 images]# virsh net-list
 Name                 State      Autostart     Persistent
----------------------------------------------------------
 default              active     yes           yes
 vagrant-libvirt      active     yes           yes
```

Looks like the functionality exists, but there is no hook to configure for management network. Perhaps, adding a new configuration "management_network_autostart" would help?

**Comment by infernix** [comment]
I see what you mean; I will flag this as enhancement, shouldn't be too much work to support.
