### ISSUE TITLE
Can you port a fix to the issue #16 "Exception on virbr collision" from  adrahon/vagrant-kvm GitHub project?

### ISSUE THREAD

**Issue by lheinman** [vagrant-libvirt/vagrant-libvirt#617]
##  Steps to reproduce
1. Run [Running Kubernetes Locally with Vagrant](http://kubernetes.io/docs/getting-started-guides/vagrant/) with Virtual Box provider.
export KUBERNETES_PROVIDER=vagrant
./cluster/kube-up.sh
vagrant halt 
vagrant destroy -f
2. Rerun the steps above with libvirt provider.
export VAGRANT_DEFAULT_PROVIDER=libvirt
./cluster/kube-up.sh

### Expected behaviour
Expected KVM nodes to start.

### Actual behaviour
Got this error instead:
Error while activating network: Call to virNetworkCreate failed: internal error: Network is already in use by interface vboxnet0.

### System configuration
**OS/Distro version:**: 
Ubuntu 14.04.4 LTS, Trusty

**Libvirt version:**
1.2.2-0ubuntu13.1.17

**Output of `vagrant version; vagrant plugin list`:**
Installed Version: 1.8.4
Latest Version: 1.8.4
 
You're running an up-to-date version of Vagrant!
vagrant-libvirt (0.0.33)
vagrant-share (1.1.5, system)

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**
```
... Starting cluster using provider: vagrant
... calling verify-prereqs
... calling kube-up
Bringing machine 'master' up with 'libvirt' provider...
Bringing machine 'node-1' up with 'libvirt' provider...
==> master: Creating image (snapshot of base box volume).
==> master: Creating domain with the following settings...
==> master:  -- Name:              kubernetes-1.2.4bin_master
==> master:  -- Domain type:       kvm
==> master:  -- Cpus:              4
==> master:  -- Memory:            1280M
==> master:  -- Management MAC:    
==> master:  -- Loader:            
==> master:  -- Base box:          kube-fedora23
==> master:  -- Storage pool:      default
==> master:  -- Image:             /var/lib/libvirt/images/kubernetes-1.2.4bin_master.img (41G)
==> master:  -- Volume Cache:      none
==> master:  -- Kernel:            
==> master:  -- Initrd:            
==> master:  -- Graphics Type:     vnc
==> master:  -- Graphics Port:     5900
==> master:  -- Graphics IP:       127.0.0.1
==> master:  -- Graphics Password: Not defined
==> master:  -- Video Type:        cirrus
==> master:  -- Video VRAM:        9216
==> master:  -- Keymap:            en-us
==> master:  -- TPM Path:          
==> master:  -- INPUT:             type=mouse, bus=ps2
==> master:  -- Command line : 
==> master: Creating shared folders metadata...
Error while activating network: Call to virNetworkCreate failed: internal error: Network is already in use by interface vboxnet0.
```

**A Vagrantfile to reproduce the issue:**
```
https://github.com/kubernetes/kubernetes/blob/master/Vagrantfile
```

**Are you using upstream vagrant package or your distros package?**
Upstream

**Comment by infernix** [comment]
`Error while activating network: Call to virNetworkCreate failed: internal error: Network is already in use by interface vboxnet0.`

How about you stop (and perhaps remove) virtualbox first? Because that is the error here.

**Comment by lheinman** [comment]
>How about you stop (and perhaps remove) virtualbox first? Because that is the error here.
That's what I did before running vagrant with libvirt:
vagrant halt
vagrant destroy -f

**Comment by infernix** [comment]
That's not stopping virtualbox.

Try `/etc/init.d/virtualbox stop` or remove the package entirely and try again. This isn't a vagrant-libvirt problem.

**Comment by vorburger** [comment]
You can remove the interface vboxnet0 like this:

`VBoxManage hostonlyif remove vboxnet3`
