### ISSUE TITLE
Disk_Bus setting does not affect Additional Disks

### ISSUE THREAD

**Issue by ericpulvino** [vagrant-libvirt/vagrant-libvirt#621]
I have been able to work around this behavior by setting the 'bus' setting on the additional disks as they are created. Filing this mostly for awareness of the unexpected behavior.

### Steps to reproduce
1. Use the disk_bus entry to apply globally to all domains.
2. Create an additional disk.
3. Dump the xml for a domain and see that the additional disk has not had the bus modified.

### Expected behaviour
Setting disk_bus should affect all Disks created, including additional disks, not just those specified with a box file entry.

### Actual behaviour
Instead the additional disk has no modifications performed to the bus used by the disk, it remains set to the default value.

### System configuration
**OS/Distro version:**:
Ubuntu 16.04

**Libvirt version:**
libvirtd (libvirt) 1.3.1

**Output of `vagrant version; vagrant plugin list`:**

```
vagrant version; vagrant plugin list
Installed Version: 1.8.4
Latest Version: 1.8.4
 
You're running an up-to-date version of Vagrant!
vagrant-cumulus (0.1)
vagrant-libvirt (0.0.33)
  - Version Constraint: 0.0.33
vagrant-mutate (1.1.0)
vagrant-share (1.1.5, system)

```

**DUMPXML output for Disk Section**
In the below example I also had a BOX image applied to this VM which is unlike the provided example Vagrantfile. This example shows the disparity a bit better.

```
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2'/>
      <source file='/var/lib/libvirt/images/topology_converter_visa_pxehost.img'/>
      <backingStore type='file' index='1'>
        <format type='qcow2'/>
        <source file='/var/lib/libvirt/images/yk0-VAGRANTSLASH-ubuntu-xenial_vagrant_box_image_201604262.img'/>
        <backingStore/>
      </backingStore>
      <target dev='vda' bus='sata'/>
      <boot order='2'/>
      <alias name='sata0-0-0'/>
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
    </disk>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2'/>
      <source file='/var/lib/libvirt/images/topology_converter_visa_pxehost-vdb.qcow2'/>
      <backingStore/>
      <target dev='vdb' bus='virtio'/>
      <boot order='3'/>
      <alias name='virtio-disk1'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x04' function='0x0'/>
    </disk>
```

**A Vagrantfile to reproduce the issue:**
```
# Created by Topology-Converter v4.2.0_dev
#    using topology data from: ./pxe_topology.dot
#    NOTE: in order to use this Vagrantfile you will need:
#       -Vagrant(v1.8.1+) installed: http://www.vagrantup.com/downloads
#       -Cumulus Plugin for Vagrant installed: $ vagrant plugin install vagrant-cumulus
#       -the "helper_scripts" directory that comes packaged with topology-converter.py
#        -Libvirt Installed -- guide to come
#       -Vagrant-Libvirt Plugin installed: $ vagrant plugin install vagrant-libvirt
#       -Boxes which have been mutated to support Libvirt -- see guide below:
#            https://community.cumulusnetworks.com/cumulus/topics/converting-cumulus-vx-virtualbox-vagrant-box-gt-libvirt-vagrant-box
#       -Start with \"vagrant up --provider=libvirt --no-parallel\n")

# Check required plugins
REQUIRED_PLUGINS_LIBVIRT = %w(vagrant-libvirt vagrant-mutate)
exit unless REQUIRED_PLUGINS_LIBVIRT.all? do |plugin|
  Vagrant.has_plugin?(plugin) || (
    puts "The #{plugin} plugin is required. Please install it with:"
    puts "$ vagrant plugin install #{plugin}"
    false
  )
end

Vagrant.configure("2") do |config|

  config.vm.provider :libvirt do |domain|
    # increase nic adapter count to be greater than 8 for all VMs.
    domain.nic_adapter_count = 55
    domain.disk_bus = 'sata'
  end

  ##### DEFINE VM for pxehost #####
  config.vm.define "pxehost" do |device|
    device.vm.hostname = "pxehost"
    
    # disabling sync folder support on all VMs
    #   see note here: https://github.com/pradels/vagrant-libvirt#synced-folders
    device.vm.synced_folder '.', '/vagrant', :disabled => true
    device.vm.provider :libvirt do |v|
      v.storage :file, :size => '100G', :type => 'qcow2'
      v.boot 'hd'
      v.boot 'network'
      v.memory = 500
    end
    device.vm.synced_folder ".", "/vagrant", disabled: true

    # NETWORK INTERFACES
      # link for eth1 --> server:eth1
      device.vm.network "private_network",
            :mac => "443839000002",
            :libvirt__tunnel_type => 'udp',
            :libvirt__tunnel_local_ip => '127.0.0.1',
            :libvirt__tunnel_local_port => '9001',
            :libvirt__tunnel_ip => '127.0.0.1',
            :libvirt__tunnel_port => '8001',
            :libvirt__iface_name => 'eth1',
            auto_config: false
  end
end
```

**Are you using upstream vagrant package or your distros package?**
Upstream

**Comment by infernix** [comment]
Documentation states that you should specify bus for additional disks, like so:

```ruby
      v.storage :file, :size => '100G', :type => 'qcow2', :bus => 'sata'
```

The use of a different type disk bus for box disk vs additional disks is legitimate so I don't see why this behaviour should be changed?

**Comment by ericpulvino** [comment]
I think this is more of a documentation bug. i.e. the documentation:

"disk_bus - The type of disk device to emulate. Defaults to virtio if not set. Possible values are documented in libvirt's description for target."

Does not mention that it applies only to disks associated with box images,

"disk_bus - The type of disk device to emulate. Defaults to virtio if not set. Possible values are documented in libvirt's description for target. NOTE: this option applies only to disks associated with a box image. To set the bus type on additional disks, see the [Additional Disks](#additional-disks) section."

**Comment by infernix** [comment]
So looking at the code:

```ruby

      def _handle_disk_storage(options={})
        options = {
          :device => _get_device(@disks),
          :type => 'qcow2',
          :size => '10G',	# matches the fog default
          :path => nil,
          :bus => 'virtio'
        }.merge(options)

```

The only thing we could do is refer to `disk_bus` (which defaults to virtio) instead of defaulting to hardcoded virtio. But I'm reluctant to change defaults like this as they may break existing deployments.

I can definitely update the docs though. In a parallel universe where I have a lot of free time I have already rewritten it, but alas =)
