### ISSUE TITLE
machine_virtual_size docs: potentially redundant note.

### ISSUE THREAD

**Issue by DStape** [vagrant-libvirt/vagrant-libvirt#625]
The 'machine_virtual_size' option documentation currently contains the following note:

"Note that currently there is no support for automatically resizing the filesystem to take advantage of the larger disk."

After setting this option, my Ubuntu Vagrant box's filesystem was automatically resized. I don't currently have the time to dig into the code and see where this support was added, however it looks like that note is now potentially redundant.

 I created PR #624 to remove this note.

**Comment by infernix** [comment]
This isn't the case. Your box image may do this, but most box images do not.

**Comment by DStape** [comment]
OK, fair enough.
