### ISSUE TITLE
Failed to start centos7: ssh authentication failed

### ISSUE THREAD

**Issue by sebastian-philipp** [vagrant-libvirt/vagrant-libvirt#636]
Hi, after installing Vagrant + vagrant-libvirt, I cannot completely start a centos7 VM. After replacing insecure SSH Keys, vagrant mentioned it wants to reconnect. ```AGRANT_LOG=debug``` revealed:

```
INFO ssh: SSH not up: #<Vagrant::Errors::SSHAuthenticationFailed: SSH authentication failed! This is typically caused by the public/private
keypair for the SSH user not being properly set on the guest VM. Please
verify that the guest VM is setup with the proper public key, and that
the private key path for Vagrant is setup properly as well.>
```

I was able to open the virt-manager console and executed 

```
service sshd status -l
<snip>
Authentication refused: bad ownership or modes for /home/vagrant/.ssh/authorized_keys
```
FYI, authorized_keys has -rw-rw-r--

At this point, vagrant up won't continue.

**OS/Distro version:**: Ubuntu 16.04

**Libvirt version:** 1.3.1

**Output of `vagrant version; vagrant plugin list`:** 
```
Installed Version: 1.8.5
Latest Version: 1.8.5
 
You're running an up-to-date version of Vagrant!
vagrant-libvirt (0.0.33)
vagrant-share (1.1.5, system)
```

**A Vagrantfile to reproduce the issue:**
```
$ vagrant init centos/7
```

**Are you using upstream vagrant package or your distros package?**
Upstream

**Edit**: ```chmod 600 .ssh/authorzized_keys``` fixed the issue

**Comment by pronix** [comment]
and  ?

**Comment by sebastian-philipp** [comment]
Then, is this a bug in the centos7 box or in vagrant?

**Comment by pronix** [comment]
it is normal behaviour for ssh.

**Comment by sebastian-philipp** [comment]
I don't think that messing up the .ssh/authorzized_keys permissions is a feature

**Comment by sebastian-philipp** [comment]
It was a vagrant bug: https://github.com/mitchellh/vagrant/issues/7610

**Comment by Helenbj** [comment]
Adding bellow two lines to Vagrantfile I can figure it out.
```
config.ssh.username = "vagrant"
config.ssh.password = "vagrant"
```
