### ISSUE TITLE
Allow per machine connection Settings.

### ISSUE THREAD

**Issue by diffuse** [vagrant-libvirt/vagrant-libvirt#637]
Enable per machine connection settings.  

Issue:
I currently have 8 Linux servers that are all running libvirtd.  I attempted to launch one VM per Hypervisor with my Vagrantfile.  However, it appears that the libvirt uri option cannot not be configured per machine.  If I specify a different uri string for each machine, they still all end up on the same hypervisor.

It would be extremely useful to allow for a Vagrantfile to launch machines across multiple hypervisors.

**Comment by diffuse** [comment]
I should have done this earlier....

After inspecting how vagrant-libvirt is handling libvirt connections, there is a quick way to enable supporting multiple hypervisors from a single Vagrantfile.  In driver.rb, in def connection, if @@connection already exists, then the connection handle is returned.  If the line is remove, then it would allow per machine libvirt URI.  The downside is, the connection doesn't get reused if the connection is the same.

**Comment by infernix** [comment]
As per #582 Vagrant was never designed for this so shoehorning this into vagrant-libvirt really doesn't sound like a great idea. The standing recommendation is to just use multiple Vagrantfiles.

**Comment by diffuse** [comment]
That's a shame.  I have a fix for this.  It changes @@connnections to a hashmap where config.uri is the key, and the value contains the connection.

This allows me to cache the connection and also supports multiple hypervisor targets in a single vagrant file.  The change is only a few lines of code and works very well in my environment.

**Comment by infernix** [comment]
Would it work with all supported features? Shared folders, port forwarding and so on?

**Comment by diffuse** [comment]
Yep.  It works exactly the same.  It just allows you to set a uri per machine.  Total its about 4-5 lines of code.  It also respects the connection caching that was already implemented.

**Comment by infernix** [comment]
@diffuse send a PR and we can review, though not sure if this doesn't ultimately create more problems than it solves. @pronix will have to weigh in on this.
