### ISSUE TITLE
multicast on public interface

### ISSUE THREAD

**Issue by toanju** [vagrant-libvirt/vagrant-libvirt#650]
Currently there is no way to set the attribute trustGuestRxFilters='yes' (details see [1]) for public network interfaces (macvtap). Hence Multicast does not work on these interfaces.

Workaround: manual edit (sudo virsh edit domain) and vagrant reload

[1] http://www.libvirt.org/formatdomain.html#elementsNICSDirect

**Comment by infernix** [comment]
I've flagged as enhancement; feel free to send a PR!
