### ISSUE TITLE
libvirt provider blocks do not assign identifiers and merge storage/cdrom device configuration correctly

### ISSUE THREAD

**Issue by electrofelix** [vagrant-libvirt/vagrant-libvirt#655]
Issue #651, while caused by configuration error also showed that opening multiple provider blocks to define storage devices do not result in them being combined in a manner a user would likely expect, which resulted in duplicate devices being defined and conflicting with the previous definitions.

There is a limitation that adding any storage devices to a vm configuration must be done within a single provider block, using subsequent blocks will add disks that replace the previous block and result in an exception at domain creation time due to duplicate storage devices.
### Steps to reproduce
1. Create Vagrantfile with multiple separate libvirt provider blockers adding storage devices
2. Bring machines up with `vagrant up`
### Expected behaviour

test vm brought up with 3 additional disks of sizes 10GB, 20GB and 30GB respectively
### Actual behaviour

Attempt to define all 3 disks as vdb and fail due to duplicate disk definitions

```
Call to virDomainCreateWithFlags failed: XML error: target 'vdb' duplicated for disk sources '/var/lib/libvirt/images/vagrant-libvirt_test-vdb.qcow2' and '/var/lib/libvirt/images/vagrant-libvirt_test-vdb.qcow2'
```
### System configuration

**OS/Distro version:**: Fedora 23

**Libvirt version:** 0.0.35

**Output of `vagrant ... --provider=libvirt`**

```
Bringing machine 'test' up with 'libvirt' provider...
==> test: Box 'fedora/24-cloud-base' could not be found. Attempting to find and install...
    test: Box Provider: libvirt
    test: Box Version: >= 0
==> test: Loading metadata for box 'fedora/24-cloud-base'
    test: URL: https://atlas.hashicorp.com/fedora/24-cloud-base
==> test: Adding box 'fedora/24-cloud-base' (v20160621) for provider: libvirt
    test: Downloading: https://atlas.hashicorp.com/fedora/boxes/24-cloud-base/versions/20160621/providers/libvirt.box
==> test: Successfully added box 'fedora/24-cloud-base' (v20160621) for 'libvirt'!
==> test: Uploading base box image as volume into libvirt storage...
==> test: Creating image (snapshot of base box volume).
==> test: Creating domain with the following settings...
==> test:  -- Name:              vagrant-libvirt_test
==> test:  -- Domain type:       kvm
==> test:  -- Cpus:              1
==> test:  -- Memory:            512M
==> test:  -- Management MAC:    
==> test:  -- Loader:            
==> test:  -- Base box:          fedora/24-cloud-base
==> test:  -- Storage pool:      default
==> test:  -- Image:             /var/lib/libvirt/images/vagrant-libvirt_test.img (41G)
==> test:  -- Volume Cache:      default
==> test:  -- Kernel:            
==> test:  -- Initrd:            
==> test:  -- Graphics Type:     vnc
==> test:  -- Graphics Port:     5900
==> test:  -- Graphics IP:       127.0.0.1
==> test:  -- Graphics Password: Not defined
==> test:  -- Video Type:        cirrus
==> test:  -- Video VRAM:        9216
==> test:  -- Keymap:            en-us
==> test:  -- TPM Path:          
==> test:  -- Disks:         vdb(qcow2,10G), vdb(qcow2,20G), vdb(qcow2,30G)
==> test:  -- Disk(vdb):     /var/lib/libvirt/images/vagrant-libvirt_test-vdb.qcow2
==> test:  -- Disk(vdb):     /var/lib/libvirt/images/vagrant-libvirt_test-vdb.qcow2 Not created - using existed.
==> test:  -- Disk(vdb):     /var/lib/libvirt/images/vagrant-libvirt_test-vdb.qcow2 Not created - using existed.
==> test:  -- INPUT:             type=mouse, bus=ps2
==> test:  -- Command line : 
==> test: Creating shared folders metadata...
==> test: Starting domain.
There was an error talking to Libvirt. The error message is shown
below:

Call to virDomainCreateWithFlags failed: XML error: target 'vdb' duplicated for disk sources '/var/lib/libvirt/images/vagrant-libvirt_test-vdb.qcow2' and '/var/lib/libvirt/images/vagrant-libvirt_test-vdb.qcow2'
```

**A Vagrantfile to reproduce the issue:**

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "fedora/24-cloud-base"

  config.vm.define :test do |test|
    test.vm.provider :libvirt do |domain|
      domain.storage :file, :size => '10G'  # vdb
    end
    test.vm.provider :libvirt do |domain|
      domain.storage :file, :size => '20G'  # vdc
    end
    test.vm.provider :libvirt do |domain|
      domain.storage :file, :size => '30G'  # vdd
    end
  end
end
```

**Are you using upstream vagrant package or your distros package?**
Upstream

Issue can be traced to a combination of config allocating the block device identifier at assignment time and merge of the array between blocks not considering device identifiers need to be unique.

Configuration determining the block device identifier at assignment time:
https://github.com/vagrant-libvirt/vagrant-libvirt/blob/master/lib/vagrant-libvirt/config.rb#L395-L398 (cdrom)
https://github.com/vagrant-libvirt/vagrant-libvirt/blob/master/lib/vagrant-libvirt/config.rb#L410-L416 (disk)

Merge between different provider configuration blocks (currently incorrectly leaving out cdrom), which combines the array from both blocks where the first device in each block will have the same identifier, thus resulting in the same device being identified multiple times:
https://github.com/vagrant-libvirt/vagrant-libvirt/blob/master/lib/vagrant-libvirt/config.rb#L587-L593

Solution will likely involve changing to assign the device id during the finalize! call:
https://github.com/vagrant-libvirt/vagrant-libvirt/blob/master/lib/vagrant-libvirt/config.rb#L544-L545
and combining this with changing the merge to account for the same identifier being used to allow for explicit overwriting of a previous disk settings, and validate checking that disks/cdroms all have unique identifiers before attempting to bring the machine up.

**Comment by huikang** [comment]
had the same issue with the vagrantfile

```
if hostname.include? "storage"
		config.vm.provider :libvirt do |libvirt|
                    libvirt.storage :file, :size => SECOND_DISK_SIZE, :type => 'raw', :path => 'disk2.img', :device => 'vdc'
                end
```

Any update to this bug?

**Comment by electrofelix** [comment]
While the fix I've put together takes care of disks/cdroms device assignment, there are still a number of other config options that also need the same logic applied with some tests added:
- cpufeatures
- inputs
- channels
- pcis
- usbs
- redirdevs
- redirfilters

Additionally the storage devices need to have controllers looked at, since depending on the bus used they should be given different letters ide => hdX, scsi => sdX, virtio => vdX

Hopefully the basic fix for just this particular issue contains just enough tests to be copied for other devices to allow the correct merging behaviour to be applied to all settings.
