### ISSUE TITLE
Can't vagrant up or destroy "domain about to create is already taken"

### ISSUE THREAD

**Issue by ryanlerch** [vagrant-libvirt/vagrant-libvirt#658]
In some cases, i have found that some of my vagrant-libvirt setups get into a state where i get the following message when trying to `vagrant destroy`

    Name `vagrantbox_default` of domain about to create is already taken. Please try to run  `vagrant up` command again.

And then get the same message when trying the recommendation of running `vagrant up`

What usually has happened is that i have either removed the `.vagrant` directory, or interputed a `vagrant destroy` before it has fully completed.

To fix this, i just go into virt-manager, and remove the VM (domain) that still exists, in the above example, that would be:  `vagrantbox_default`

### Steps to reproduce
1. `vagrant up` to create and provision
2. `rm -rf .vagrant`

### Expected behaviour
Not sure what the best solution is here -- maybe a better error message that there may be a VM still sticking around that vagrant-libvirt doesnt know about becuase the .vagrant directory is missing. Or maybe even providing an option when this happens to allow the user to delete the VM / domain.

**Comment by schade** [comment]
You make no mention of which provider you are using in your vagrantfile when you get this error message. With a chef provider I would suggest using the vagrant-butcher plugin instead of a common vagrant destroy command; I'm unsure what works as well with other providers.

**Comment by pronix** [comment]
if name is taken - vagrant can only report, as it is.

**Comment by ryanlerch** [comment]
Thanks!

There were two main things that confused me about the current error message: 

* It has the words "about to create", even when trying to destroy
* the use of "domain". I know this is a libvirt term, but it confused me as a newbie as to what domain mean in this instance.

cheers,
ryanlerch

**Comment by Fridus** [comment]
Hi,

How to delete the domain name for recreated it again ?

**Comment by narfman0** [comment]
```
virsh list --all
virsh undefine (id | name)
```

**Comment by chrisspen** [comment]
Why was this closed? I'm also getting this error, and it's perplexing. Why can't vagrant destroy a VM that it created? If you have to run `vagrant up` first...why can't Vagrant automatically do this in order to destroy the VM?

**Comment by ralphbean** [comment]
> It has the words "about to create", even when trying to destroy

This confused me too.  :)

**Comment by chrisspen** [comment]
I think this error happens when the file, storing the metadata that identifies the VM, is removed. Vagrant essentially doesn't recognize the existing VM as the one it created, even though the name is identical. If I manually delete the VM, then Vagrant can create/destroy normally.

**Comment by frgomes** [comment]
@chrisspen : I had the same problem.

I solved by running virt-manager and removing the machines via the GUI it provides.
It's a couple of years I don't use these tools... but I would expect to see via virsh whatever you can see in the GUI provided by virt-manager.

**Comment by dhilst** [comment]
I solved by removing the machine and volume with `virsh`

```
sudo virsh list --all
# get the machine name
sudo virsh destroy <THE_MACHINE>
sudo virsh undefined <THE_MACHINE>
sudo virsh vol-list default
# get the volume name
sudo virsh vol-delete --pool default <THE_VOLUME>
```

**Comment by kimduksoo** [comment]
sudo virsh list --all
# get the machine name
sudo virsh destroy <THE_MACHINE>
sudo virsh undefine <THE_MACHINE>
sudo virsh vol-list default
# get the volume name
sudo virsh vol-delete --pool default <THE_VOLUME>

**Comment by gangsta** [comment]
For Fedora users, or force undefine you need following.

To install virsh.
```bash
sudo dnf groupinfo virtualization
sudo dnf install @virtualization 
```
To remove domain.
```bash
virsh list --all
virsh destroy <THE_MACHINE> 
virsh undefine <THE_MACHINE> --snapshots-metadata --managed-save
virsh vol-list default
virsh vol-delete --pool default <THE_VOLUME>
```

**Comment by abyxcos** [comment]
> @chrisspen : I had the same problem.
> 
> I solved by running `virt-manager` and removing the machines via the GUI it provides.
> 
> **EDIT:** Several problems arise from wrong permissions. In my case in particular I've relocated `/var/lib/libvirt` to another drive, making a symlink to it but I forgot to assign the correct permissions. Also, I guess my user must belong to group `libvirt` (or whatever it might be, depending on the Linux distribution).. but I'm not plenty sure. I'm not going to revert it all back now just to test and bump against the wall.
> 
> Find below a shell script which automagically installs `vagrant` and `libvirt` on Debian Stretch: https://github.com/frgomes/debian-scripts/blob/master/install-libvirt.sh

I just hit this message as caused by a permissions error on moving the libvirt storage directory. The command should probably be a little more informative about what the actual error is, at least in the case of permissions.

**Comment by gonzaloetjo** [comment]
My only solution was to go to `/var/lib/libvirt/qemu` and delete all related domains.
