### ISSUE TITLE
Remote libvirt host

### ISSUE THREAD

**Issue by luqasz** [vagrant-libvirt/vagrant-libvirt#661]
Hi.

I was wondering if it is possible to use `vagrant-libvirt` with libvirt on a remote machine.
```
osx <-> WAN/LAN <-> libvirt host (KVM) <-> vagrant instance
```
I want to use this scenario to offload ansible testing to a dedicated host.

So far I've used virsh to define and start a instance with macvtap as primary public interface. I couldn't get its IP address through virsh. I am wondering how to get ansible to connect to new instances.

**Comment by pronix** [comment]
yes, it is possible
https://github.com/vagrant-libvirt/vagrant-libvirt#provider-options
