### ISSUE TITLE
0.0.36 release

### ISSUE THREAD

**Issue by stephenfin** [vagrant-libvirt/vagrant-libvirt#663]
Not an issue, per se, but is there an ETA on a 0.0.36 release? I'd like to start using the NUMA topology features locally and hopefully push for the Fedora RPM to be bumped from 0.0.32.

### Steps to reproduce
N/A.

### Expected behaviour
N/A.

### Actual behaviour
N/A.

### System configuration
N/A.

**Comment by infernix** [comment]
@pronix probably not a bad idea given the new fog/ruby versions. Thought?

**Comment by pronix** [comment]
2 hours

**Comment by infernix** [comment]
Done!
