### ISSUE TITLE
Permission issues with NFS mount

### ISSUE THREAD

**Issue by stephenfin** [vagrant-libvirt/vagrant-libvirt#665]
I'm running [DevStack](http://docs.openstack.org/developer/devstack/) in the `/vagrant` folder. This is shared via NFS as the default sharing strategy seems to be one way only.

When I run `./stack.sh` it executes the below command:

```
++lib/tempest:configure_tempest:176         sudo install -d -o vagrant /vagrant/stack/tempest/etc
install: cannot change owner and permissions of '/vagrant/stack/tempest/etc': Operation not permitted
```

(running the command manually causes the same issue).

I imagine I need some special NFS configuration, but for the life of me I can't figure out what.
### Steps to reproduce
1. Run `vagrant up` with an NFS provider
2. Execute `sudo install -d -o vagrant <some_directory>`
### Expected behaviour

The command should pass.
### Actual behaviour

I get an error message:

```
install: cannot change owner and permissions of '/vagrant/stack/tempest/etc': Operation not permitted
```
### System configuration

**OS/Distro version:**:
Fedora 24

**Libvirt version:**
libvirtd (libvirt) 1.3.3.2

**Output of `vagrant version; vagrant plugin list`:**

```
$ vagrant version; vagrant plugin list
Installed Version: 1.8.1
Latest Version: 1.8.6

To upgrade to the latest version, visit the downloads page and
download and install the latest version of Vagrant from the URL
below:

  http://www.vagrantup.com/downloads.html

If you're curious what changed in the latest release, view the
CHANGELOG below:

  https://github.com/mitchellh/vagrant/blob/v1.8.6/CHANGELOG.md
vagrant-libvirt (0.0.32, system)
```

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**
N/A

**A Vagrantfile to reproduce the issue:**

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "fedora/24-cloud-base"
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider :libvirt do |domain|
    # basic config
    domain.memory = 8192
    domain.cpus = 2

    # nested virt config
    domain.cpu_mode = 'host-passthrough'
    domain.nested = true

    # other config
    domain.volume_cache = 'none'
  end

  # It seems necessary to use NFS, per
  # https://github.com/vagrant-libvirt/vagrant-libvirt/issues/557
  config.vm.synced_folder '.', '/vagrant', type: 'nfs', nfs_udp: false, nfs_version: 4

  config.vm.provision :shell, :path => "install.sh", privileged: false
end
```

```
#!/usr/bin/env bash
mkdir /vagrant/testdir
sudo install -d -o vagrant /vagrant/testdir
```

**Are you using upstream vagrant package or your distros package?**
Distro

**Comment by infernix** [comment]
Have you tried adding `no_root_squash`? see https://drpebcak.svbtle.com/nfs-configuration-with-vagrant

**Comment by infernix** [comment]
Closing this due to no further updates/info. Please free to update or reopen this ticket if required. Thanks!
