### ISSUE TITLE
net-ssh deprecated timeout causes vagrant up to hang ( command never returned )

### ISSUE THREAD

**Issue by arcadian09** [vagrant-libvirt/vagrant-libvirt#681]
### Steps to reproduce
1. vagrant up
2. vagrant halt
   3.vagrant up ( 2nd time)

Note: reason for 2nd run is because the process hungs in the timout is deprecated, the vm is up and running but the command is never returned.
### Expected behaviour

Warning message should be ommited.
### Actual behaviour

/usr/share/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:84:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
### System configuration

**OS/Distro version:**:
Fedora/24

**Libvirt version:**
libvirtd (libvirt) 1.3.3.2

**Output of `vagrant version; vagrant plugin list`:**
Vagrant 1.8.1
vagrant-libvirt (0.0.32, system)

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**

```
Additional subcommands are available, but are either more advanced
or not commonly used. To see all subcommands, run the command
`vagrant list-commands`.

 INFO environment: Running hook: environment_unload
 INFO loader: Set :root = ["#<Pathname:/home/oleg/git-hub/ansible/ansiblebook/ch06/playbook/Vagrantfile>"]
DEBUG loader: Populating proc cache for #<Pathname:/home/oleg/git-hub/ansible/ansiblebook/ch06/playbook/Vagrantfile>
DEBUG loader: Load procs for pathname: /home/oleg/git-hub/ansible/ansiblebook/ch06/playbook/Vagrantfile
 INFO loader: Loading configuration in order: [:home, :root]
DEBUG loader: Loading from: root (evaluating)
DEBUG provisioner: Provisioner defined: 
DEBUG provisioner: Provisioner defined: 
DEBUG loader: Configuration loaded successfully, finalizing and returning
DEBUG push: finalizing
 INFO host: Autodetecting host type for [#<Vagrant::Environment: /home/oleg/git-hub/ansible/ansiblebook/ch06/playbook>]
DEBUG host: Trying: arch
DEBUG host: Trying: darwin
DEBUG host: Trying: freebsd
DEBUG host: Trying: gentoo
DEBUG host: Trying: redhat
 INFO host: Detected: redhat!
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 2 hooks defined.
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x0055e5327b5008>
```

**A Vagrantfile to reproduce the issue:**

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # ssh settings
  config.ssh.insert_key = false
    config.ssh.forward_agent = true
    config.ssh.private_key_path = ["/home/oleg/.ssh/id_rsa_arcadian.pub", "~/.vagrant.d/insecure_private_key"]
  config.vm.provision "file", source: "/home/oleg/.ssh/id_rsa_arcadian.pub", destination: "~/.ssh/authorized_keys"
  config.vm.provision "shell", inline: <<-EOC
    sudo sed -i -e "\\#PasswordAuthentication yes# s#PasswordAuthentication yes#PasswordAuthentication no#g" /etc/ssh/sshd_config
    sudo systemctl restart sshd.service
    EOC

  #config.vm.hostname = "centos-oleg"


    config.vm.define "centos-oleg" do |centos|
      #centos.vm.box = "uvsmtid/centos-7.0-minimal"
    centos.vm.box = "centos/7"
    centos.vm.network "private_network", ip: "192.168.120.120"
        config.vm.hostname = "centos-oleg"
  end

    # remove nfs directory host to guest
  config.vm.synced_folder ".", "/vagrant", disabled: true

    # in case default libvirt is not set environmentally
  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = 'kvm'
  end

end

```

**Are you using upstream vagrant package or your distros package?**
Distro

Note: issue has been addressed and fix available with net-ssh 3.0.2 the warning is fixed.
https://github.com/welaika/wordmove/issues/270

Ideally (if possible) to use the 3.0.2 net--ssh with vagrant?

**Comment by arcadian09** [comment]
Was able to resolve the issue: warning message of deprecated session.rb and hanging of the initialization of the VM when performing vagrant up for second or later times.

Fix was not of my own but of the net-ssh project, I picked and merged the changes to address the issue.

Files modified:
server_version.rb
session.rb

Commits used to merge in the fix:
https://github.com/net-ssh/net-ssh/commit/5224ce73ff7ef2e39a00760e3f7a87d542f44bd2
and
https://github.com/net-ssh/net-ssh/commit/1a47e19b10914aa7638a550d410ea4bb8c0563c9

Thanks,

**Comment by arcadian09** [comment]
Small update, warning messages have gone but control never returns after executing vagrant up for a second time. Issue is still existent.

**Comment by infernix** [comment]
Can you post a full debug log with the actual issue? I'm not seeing it in your previously posted logs?

Secondly, can you `ssh -l vagrant x.x.x.x` to the actual box IP when Vagrant reports the timeout? e.g. can you independently verify that the box is reachable over ssh?

**Comment by arcadian09** [comment]
Pasting the error I think is responsible:
`DEBUG ssh: == Net-SSH connection debug-level log END ==
 INFO ssh: SSH not up: #<Vagrant::Errors::SSHAuthenticationFailed: SSH authentication failed! This is typically caused by the public/private keypair for the SSH user not being properly set on the guest VM. Please verify that the guest VM is setup with the proper public key, and that the private key path for Vagrant is setup properly as well.>
`
and here are two files with debug on vagrant up 1st time and 2nd run which loops.
[up_debug.txt](https://github.com/vagrant-libvirt/vagrant-libvirt/files/613795/up_debug.txt)

[up_after_halt_debug.txt](https://github.com/vagrant-libvirt/vagrant-libvirt/files/613796/up_after_halt_debug.txt)

**Comment by infernix** [comment]
Well, this is not a net-ssh problem, but some issue with whatever you're trying to do with the private keys. For example:

```
E, [2016-11-25T13:39:25.559192 #14134] ERROR -- net.ssh.authentication.key_manager[2b26173cab28]: could not load private key file `/home/oleg/.ssh/id_rsa_arcadian.pub': ArgumentError (Could not parse PKey: no start line)
```
You're passing in a public key where a private key is expected.

Can you reproduce if you leave all of this out:
```
    config.ssh.insert_key = false
    config.ssh.forward_agent = true
    config.ssh.private_key_path = ["/home/oleg/.ssh/id_rsa_arcadian.pub", "~/.vagrant.d/insecure_private_key"]
  config.vm.provision "file", source: "/home/oleg/.ssh/id_rsa_arcadian.pub", destination: "~/.ssh/authorized_keys"
  config.vm.provision "shell", inline: <<-EOC
    sudo sed -i -e "\\#PasswordAuthentication yes# s#PasswordAuthentication yes#PasswordAuthentication no#g" /etc/ssh/sshd_config
    sudo systemctl restart sshd.service
    EOC
```

**Comment by arcadian09** [comment]
Oh my, you are right...not sure how this got through. I removed the public and passed the private instead. issue resolved.

My bad, sorry about that. Issue was on my part.

thank you @infernix
