### ISSUE TITLE
README.md for Debian users

### ISSUE THREAD

**Issue by chaim1221** [vagrant-libvirt/vagrant-libvirt#682]
In the documentation (README.md) there is a section about "Possible problems" on Debian that includes another line of `apt` installs. I really recommend merging this into the above lines for Debian/Ubuntu installs. I have never, ever, had this package work OOTB without adding that line.

I can submit a pull request with the change if people think this is generally a good idea. If my idea is crap and I'm just not doing something else right, someone should tell me that too. ;)

**Comment by infernix** [comment]
Better docs are always welcome :+1:

**Comment by pronix** [comment]
debian users can use centos or fedora :)
