### ISSUE TITLE
Unable to start box with ipv6_guest as true

### ISSUE THREAD

**Issue by aanm** [vagrant-libvirt/vagrant-libvirt#685]
### Steps to reproduce
1. start a vagrant box with a similar configuration as:

```
            node.vm.network "private_network", ip: "192.168.33.1",
                :libvirt__network_name => "my-network",
                :libvirt__guest_ipv6 => true,
                :libvirt__dhcp_enabled => false
```
### Expected behaviour
No errors

### Actual behaviour
Error occurred while creating new network: Call to virNetworkDefineXML failed: XML error: Invalid ipv6 setting 'true' in network "my-network"

### System configuration
**OS/Distro version:**: 4.8.4-200.fc24.x86_64

**Libvirt version:** libvirtd (libvirt) 1.3.3.2

**Output of `vagrant version; vagrant plugin list`:**
$ vagrant version 
Installed Version: 1.8.1
Latest Version: 1.8.6
$ vagrant plugin list
vagrant-libvirt (0.0.36)

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**
```
ERROR vagrant: #<VagrantPlugins::ProviderLibvirt::Errors::CreateNetworkError: Error occurred while creating new network: Call to virNetworkDefineXML failed: XML error: Invalid ipv6 setting 'true' in network 'my-network'.>
ERROR vagrant: Error occurred while creating new network: Call to virNetworkDefineXML failed: XML error: Invalid ipv6 setting 'true' in network 'my-network'.
ERROR vagrant: /home/aanm/.vagrant.d/gems/gems/vagrant-libvirt-0.0.36/lib/vagrant-libvirt/action/create_networks.rb:318:in `rescue in create_private_network'
/home/aanm/.vagrant.d/gems/gems/vagrant-libvirt-0.0.36/lib/vagrant-libvirt/action/create_networks.rb:313:in `create_private_network'
```

**Are you using upstream vagrant package or your distros package?**
Distro

**Comment by adidenko** [comment]
Got the same error, steps to reproduce:
```
git clone https://github.com/cilium/cilium
cd cilium
VAGRANT_DEFAULT_PROVIDER=libvirt IPV4=1 K8S=1 NUM_NODES=3 contrib/vagrant/start.sh
```

**Comment by infernix** [comment]
A bit silly, but this should be:
```
                :libvirt__guest_ipv6 => 'yes',
```
It does not take boolean. The XML in `lib/vagrant-libvirt/templates/private_network.xml.erb` gets rendered as:
```
<network ipv6='<%= @guest_ipv6 %>'>
```
And according to https://libvirt.org/formatnetwork.html#elementsMetadata this takes only `yes` or `no`.

I will update the readme reflecting this.
