### ISSUE TITLE
Added some documentation and code for the puppetlab beaker testing framework.

### ISSUE THREAD

**Issue by sathlan** [vagrant-libvirt/vagrant-libvirt#687]
This is not an issue.

I just wanted to let you know that I've added some functionalities to the puppetlab libvirt vagrant plugin and some documentation. You can find more information [in this pull request](https://github.com/puppetlabs/beaker/pull/1222).

Thanks for the great work.

Bye.

**Comment by infernix** [comment]
Thanks! :+1:
