### ISSUE TITLE
Nokogiri version conflict installing libvirt plugin

### ISSUE THREAD

**Issue by znmeb** [vagrant-libvirt/vagrant-libvirt#689]
### Steps to reproduce
1. Install Vagrant from HashiCorp.
2. Run `vagrant plugin update`.
3. Enter `vagrant plugin install libvirt`.

### Expected behaviour
The plugin should be installed.

### Actual behaviour
```
$ vagrant -v
Vagrant 1.8.7
$ vagrant plugin update
Updating installed plugins...
All plugins are up to date.
$ vagrant plugin install libvirt
Installing the 'libvirt' plugin. This can take a few minutes...
The plugin(s) can't be installed due to the version conflicts below.
This means that the plugins depend on a library version that conflicts
with other plugins or Vagrant itself, creating an impossible situation
where Vagrant wouldn't be able to load the plugins.

You can fix the issue by either removing a conflicting plugin or
by contacting a plugin author to see if they can address the conflict.

Vagrant could not find compatible versions for gem "nokogiri":
  In Gemfile:
    libvirt was resolved to 0.1.0, which depends on
      nokogiri (~> 1.4.3)

    vagrant (= 1.8.7) was resolved to 1.8.7, which depends on
      nokogiri (= 1.6.7.1)
```

### System configuration
**OS/Distro version:**:
Ubuntu 16.04.1 LTS
**Libvirt version:**
1.3.1-1ubuntu10.5
**Output of `vagrant version; vagrant plugin list`:**
```
$ vagrant version; vagrant plugin list
Installed Version: 1.8.7
Latest Version: 1.8.7
 
You're running an up-to-date version of Vagrant!
vagrant-share (1.1.5, system)
```
**Are you using upstream vagrant package or your distros package?**
Upstream

**Comment by znmeb** [comment]
I managed to get this to install by

1. Cloning this repo.
2. Installing the Ubuntu 16.04.1 LTS build dependencies.
3. Running `rake build`.
4. Doing `vagrant plugin install pkg/vagrant-libvirt*.gem`.

So I suppose you can close this.

**Comment by infernix** [comment]
We have instructions for this in the readme, but automated install testing for every distro is still on my todo list :)

**Comment by hurricanehrndz** [comment]
Where in the readme are these instructions?
