### ISSUE TITLE
Crash in raid6_pq module after mutating and attempting to boot Ubuntu images

### ISSUE THREAD

**Issue by pontillo** [vagrant-libvirt/vagrant-libvirt#704]
I just hit [Launchpad bug #1524069](https://launchpad.net/bugs/1524069) while trying to use an Ubuntu Xenial image (running on an Ubuntu Xenial host on an Intel i7-4710MQ CPU).

Ideally, `vagrant-libvirt` should employ the workaround described in the Launchpad bug by default. (Use "Hypervisor default" as the host CPU configuration, rather than copying the host CPU configuration.)

### Steps to reproduce
Install vagrant 1.8.7 from the official `.deb`. Install `vagrant-libvirt`. Install `vagrant-mutate`. Then run the following commands (in an empty directory):

    vagrant box add ubuntu/xenial64
    vagrant mutate ubuntu/xenial64 libvirt
    export VAGRANT_DEFAULT_PROVIDER=libvirt
    vagrant init ubuntu/xenial64
    vagrant up

### Expected behaviour
The virtual machine should boot normally.

### Actual behaviour
The virtual machine crashes with the backtrace mentioned in the Launchpad bug.

### System configuration
**OS/Distro version:**: Ubuntu 16.04 LTS ("Xenial")

**Libvirt version:** 1.3.1

**Output of `vagrant version; vagrant plugin list`:**

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**
    Installed Version: 1.8.7
    Latest Version: 1.9.1
 
    To upgrade to the latest version, visit the downloads page and
    download and install the latest version of Vagrant from the URL
    below:

      https://www.vagrantup.com/downloads.html

    If you're curious what changed in the latest release, view the
    CHANGELOG below:

      https://github.com/mitchellh/vagrant/blob/v1.9.1/CHANGELOG.md
    vagrant-libvirt (0.0.36)
    vagrant-mutate (1.2.0)
    vagrant-share (1.1.6, system)

**A Vagrantfile to reproduce the issue:**
```
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
end
```

**Are you using upstream vagrant package or your distros package?**
Upstream

**Comment by infernix** [comment]
Sorry, but this is a bug that is not caused by vagrant-libvirt so to apply a workaround in the vagrant-libvirt code for a problem far removed for it will not happen.

You can change your Vagrantfile for this specific box/distro issue based on the documentation:

https://github.com/vagrant-libvirt/vagrant-libvirt#domain-specific-options
or
https://github.com/vagrant-libvirt/vagrant-libvirt#cpu-features

**Comment by pontillo** [comment]
Thanks; for the record, I could work around this by adding the following to the Vagrantfile:

```
  config.vm.provider :libvirt do |libvirt|
    libvirt.cpu_mode = "host-passthrough"
  end
```

However, there seems to be a separate issue; it now stops at `==> default: Waiting for domain to get an IP address...`. If I get a change to triage this, I'll file that issue separately.

**Comment by infernix** [comment]
you won't need to, i can already tell that because of your mutate your eth0 nic is either nonexistant or not requesting dhcp addresses. I strongly recommend not mutating but using a libvirt image: https://atlas.hashicorp.com/boxes/search?utf8=%E2%9C%93&sort=&provider=libvirt&q=xenial

**Comment by pontillo** [comment]
Thanks again. Though I would rather create my own images, so I can have complete trust in them. (But doing so from scratch looks like it could be a little annoying, so I understand why you would suggest that.)
