### ISSUE TITLE
Create a 0.0.37 release

### ISSUE THREAD

**Issue by ekohl** [vagrant-libvirt/vagrant-libvirt#714]
It would be great if a 0.0.37 release was made which includes https://github.com/vagrant-libvirt/vagrant-libvirt/pull/678. Currently 0.0.36 is not useable for me so I have to locally apply the patch.

**Comment by infernix** [comment]
Done!

**Comment by ekohl** [comment]
Thanks!

**Comment by ekohl** [comment]
I don't see it yet on rubygems.org and no tag on github either. How long does that usually take?

**Comment by pronix** [comment]
hello.
today evening.
