### ISSUE TITLE
Vagrant up fails due to ssh error

### ISSUE THREAD

**Issue by chrisspen** [vagrant-libvirt/vagrant-libvirt#725]
### Steps to reproduce
1.  Run the commands:

    vagrant init stephenpearson/ubuntu-16.04
    vagrant plugin install vagrant-libvirt
    vagrant up --provider=libvirt

2. Hangs at step, "==> default: Waiting for SSH to become available...".
3. Viewing the VM in "Virtual Machine Manager" UI shows the VM has been created just fine, and I can login from a terminal, and ping the host, and the host can ping the VM, and the ssh daemon is running. However, Vagrant is unable to connect via the `vagrant ssh` command. I can also connect from the host by running `vagrant ssh`.

### System configuration
**OS/Distro version:**: Ubuntu 16.04

**Libvirt version:** 1.3.1

**Output of `vagrant version; vagrant plugin list`:**

    Installed Version: 1.8.1
    Latest Version: 1.9.1
     
    To upgrade to the latest version, visit the downloads page and
    download and install the latest version of Vagrant from the URL
    below:

      http://www.vagrantup.com/downloads.html

    If you're curious what changed in the latest release, view the
    CHANGELOG below:

      https://github.com/mitchellh/vagrant/blob/v1.9.1/CHANGELOG.md
    vagrant-cachier (1.2.1)
    vagrant-libvirt (0.0.37)
    vagrant-share (1.1.6, system)

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**

    DEBUG ssh: Checking whether SSH is ready...
    DEBUG ssh: Checking key permissions: /home/chris/.vagrant.d/insecure_private_key
     INFO ssh: Attempting SSH connection...
     INFO ssh: Attempting to connect to SSH...
     INFO ssh:   - Host: 192.168.121.72
     INFO ssh:   - Port: 22
     INFO ssh:   - Username: vagrant
     INFO ssh:   - Password? false
     INFO ssh:   - Key Path: ["/home/chris/.vagrant.d/insecure_private_key"]
    DEBUG ssh: == Net-SSH connection debug-level log START ==
    DEBUG ssh: D, [2017-01-17T22:13:54.143057 #23509] DEBUG -- net.ssh.transport.session[17792f4]: establishing connection to 192.168.121.72:22
    D, [2017-01-17T22:13:54.159707 #23509] DEBUG -- net.ssh.transport.session[17792f4]: connection established
    I, [2017-01-17T22:13:54.159833 #23509]  INFO -- net.ssh.transport.server_version[1778a70]: negotiating protocol version
    D, [2017-01-17T22:13:55.552660 #23509] DEBUG -- net.ssh.transport.server_version[1778a70]: remote is `SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.1'
    D, [2017-01-17T22:13:55.552750 #23509] DEBUG -- net.ssh.transport.server_version[1778a70]: local is `SSH-2.0-Ruby/Net::SSH_3.0.2 x86_64-linux'
    D, [2017-01-17T22:13:55.662959 #23509] DEBUG -- socket[1778fc0]: read 976 bytes
    D, [2017-01-17T22:13:55.663186 #23509] DEBUG -- socket[1778fc0]: received packet nr 0 type 20 len 972
    I, [2017-01-17T22:13:55.663280 #23509]  INFO -- net.ssh.transport.algorithms[1773ca0]: got KEXINIT from server
    I, [2017-01-17T22:13:55.663399 #23509]  INFO -- net.ssh.transport.algorithms[1773ca0]: sending KEXINIT
    D, [2017-01-17T22:13:55.663574 #23509] DEBUG -- socket[1778fc0]: queueing packet nr 0 type 20 len 1684
    D, [2017-01-17T22:13:55.663667 #23509] DEBUG -- socket[1778fc0]: sent 1688 bytes
    I, [2017-01-17T22:13:55.663711 #23509]  INFO -- net.ssh.transport.algorithms[1773ca0]: negotiating algorithms
    D, [2017-01-17T22:13:55.663992 #23509] DEBUG -- net.ssh.transport.algorithms[1773ca0]: negotiated:
    * kex: diffie-hellman-group14-sha1
    * host_key: ssh-rsa
    * encryption_server: aes128-ctr
    * encryption_client: aes128-ctr
    * hmac_client: hmac-sha1
    * hmac_server: hmac-sha1
    * compression_client: none
    * compression_server: none
    * language_client: 
    * language_server: 
    D, [2017-01-17T22:13:55.664022 #23509] DEBUG -- net.ssh.transport.algorithms[1773ca0]: exchanging keys
    D, [2017-01-17T22:13:55.666445 #23509] DEBUG -- socket[1778fc0]: queueing packet nr 1 type 30 len 268
    D, [2017-01-17T22:13:55.666577 #23509] DEBUG -- socket[1778fc0]: sent 272 bytes
    D, [2017-01-17T22:13:56.107296 #23509] DEBUG -- socket[1778fc0]: read 848 bytes
    D, [2017-01-17T22:13:56.107441 #23509] DEBUG -- socket[1778fc0]: received packet nr 1 type 31 len 828

    DEBUG ssh: == Net-SSH connection debug-level log END ==
     INFO ssh: SSH not up: #<Vagrant::Errors::NetSSHException: An error occurred in the underlying SSH library that Vagrant uses.
    The error message is shown below. In many cases, errors from this
    library are caused by ssh-agent issues. Try disabling your SSH
    agent or removing some keys and try again.

    If the problem persists, please report a bug to the net-ssh project.

    could not verify server signature>

**A Vagrantfile to reproduce the issue:**

    # -*- mode: ruby -*-
    # vi: set ft=ruby :

    Vagrant.configure(2) do |config|
      config.vm.box = "stephenpearson/ubuntu-16.04"
      config.vm.provider :libvirt do |libvirt|
        libvirt.driver = "qemu"
        libvirt.memory = 4096
        libvirt.cpus = 2
      end
    end

I researched the error's suggestion about the ssh-agent, but I have no success process running.

**Comment by infernix** [comment]
Can you try with `vagrant init debian/jessie64`?

**Comment by electrofelix** [comment]
Tested on vagrant 1.8.7, no problems (wasn't bothered about testing someone else's image in this case as the author of the image works in the same company as me.

```
vagrant up --provider libvirt
Bringing machine 'default' up with 'libvirt' provider...
==> default: Creating image (snapshot of base box volume).
==> default: Creating domain with the following settings...
==> default:  -- Name:              test-upstream_default
==> default:  -- Domain type:       kvm
==> default:  -- Cpus:              1
==> default:  -- Memory:            512M
==> default:  -- Management MAC:    
==> default:  -- Loader:            
==> default:  -- Base box:          stephenpearson/ubuntu-16.04
==> default:  -- Storage pool:      default
==> default:  -- Image:             /var/lib/libvirt/images/test-upstream_default.img (40G)
==> default:  -- Volume Cache:      default
==> default:  -- Kernel:            
==> default:  -- Initrd:            
==> default:  -- Graphics Type:     vnc
==> default:  -- Graphics Port:     5900
==> default:  -- Graphics IP:       127.0.0.1
==> default:  -- Graphics Password: Not defined
==> default:  -- Video Type:        cirrus
==> default:  -- Video VRAM:        9216
==> default:  -- Keymap:            en-us
==> default:  -- TPM Path:          
==> default:  -- INPUT:             type=mouse, bus=ps2
==> default:  -- Command line : 
==> default: Creating shared folders metadata...
==> default: Starting domain.
==> default: Waiting for domain to get an IP address...
==> default: Waiting for SSH to become available...
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Automatic installation for Landrush IP not enabled
==> default: Configuring and enabling network interfaces...
==> default: Rsyncing folder: /home/user/tmp/test-upstream/ => /vagrant
==> default: Rsyncing folder: /home/user/tmp/test-upstream/.vagrant/machines/default/cache/ => /tmp/vagrant-cache
==> default: Configuring cache buckets...
$ vagrant ssh default
Welcome to Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-45-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

0 packages can be updated.
0 updates are security updates.


vagrant@vagrant:~$
```

**Comment by NIPE-SYSTEMS** [comment]
I think these comments should rather be posted here: https://github.com/net-ssh/net-ssh/issues/63

My comments on the mentioned issue:

* https://github.com/net-ssh/net-ssh/issues/63#issuecomment-341977026
* https://github.com/net-ssh/net-ssh/issues/63#issuecomment-341980928

I've provided some portions of my shell script that I use to configure/setup/provision the host (which runs on Arch). Please head there for more info, don't want to spam this thread with redundancy :)

> What's interesting: This issue happens only to the ArchLinux box. I've tested the boxes centos/7 and debian/jessie64 and both work fine (ssh works, does not hang). These box-images might be created in a different way. I could not find any documentation on how the CentOS and Debian boxes are generated.
> 
> Another possibility is that the versions of the ssh server are very recent. So there might be an issue with compatibility?

`vagrant up --provider=libvirt` hangs, but `vagrant ssh` works in a seperate terminal while the other hangs at `vagrant up...` ("Waiting for SSH to become available...")

Do you need more information to investigate this? How can I help you?

Thank you very much!!

**Comment by Helenbj** [comment]
My case is same to you, with bellow two lines I can figure is out.
```
config.ssh.username = "vagrant"
config.ssh.password = "vagrant"
```
