### ISSUE TITLE
create a custom libvirt box files (clearing down /etc/udev/rules.d/70-persistent-net.rules on el6)

### ISSUE THREAD

**Issue by stephencooke** [vagrant-libvirt/vagrant-libvirt#727]
### Steps to reproduce
1. Create a VM using virt-manager based on Centos6.8

My issue is I cant find any definitive details on what to do about defined network cards.

If I leave a nic in the box before creating and have this defined as NAT device with a mac.

2. Create metadata.json
```
{
    "provider": "libvirt",
    "format": "qcow2",
    "virtual_size": 90
}
```
3. Create basic Vagrant file
```
    Vagrant.require_plugin "vagrant-libvirt"
    Vagrant.configure("2") do |config| 
    config.vm.box = "centos68" 
        #  config.vm.define :test_vm do |test_vm| 
        #   test_vm.vm.network :bridged, :adapter => 1 
        #  end 
    config.vm.provider :libvirt do |libvirt| 
         end 
    end 
```
4. Package the box libvirt style
```
tar -cvf centos68.box Vagrantfile box.img  metadata.json
```
5. Add the box
```
vagrant box add centos68 ./centos68.box
```
### Expected behaviour
Tell us what should happen
vagrant up --provision nodename

creates a box

### Actual behaviour
Tell us what happens instead
vagrant doesnt setup eth0 and fails
Cant assign IP to eth0 and fails

### System configuration
**OS/Distro version:**:
centos7.2 host. / centos68 guest
**Libvirt version:**
libvirtd --version 
libvirtd (libvirt) 2.0.0

**Output of `vagrant version; vagrant plugin list`:**
1.8.4

vagrant-libvirt (0.0.37)
vagrant-share (1.1.6, system)
vagrant-tagprovision (0.2.2)

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**
```
gives far to much away about other servers on libvirt, so cant post it.

it basically doesnt to get an IP so timesout , then removes the VM

```

**A Vagrantfile to reproduce the issue:**  : This one of our basic ones that just creates a git shell runner that usess just the NAT interface.
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

###############
# Requirements:
# vagrant plugin install vagrant-libvirt
###############


# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.7.2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	platformname = "stggitrun"
	hostname = "gitlabrunner1"
  config.vm.box = "centos68"
  
  config.ssh.pty = true
  
  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 2
    libvirt.memory = 2048
    #libvirt.storage :file, :size => "90G", :type => "raw"
  end

  config.vm.define :gitlab_runner1 do |gitlab_runner1|
    gitlab_runner1.vm.hostname = "#{hostname}"
       
    gitlab_runner1.vm.provision "puppet" do |puppet|
	  puppet.hiera_config_path = "hiera.yaml"
      puppet.module_path = "modules"
      puppet.options = "--parser future" # --verbose
      puppet.facter = {
        "runner" => 1 , "platform" => "#{platformname}" 
      }
    end
  end
end
```

**Are you using upstream vagrant package or your distros package?**
Upstream / Distro
Downloaded from Vagrant 1.8.4
1.8.4 was the last known stable version for me, I have to many servers to upgrade every new release.

The above creates the box file , however the eth0 interface doesnt get setup by vagrant.  

With a NAT setup , this writes an entry into , this needs to be cleared down during the vagrant image create or before in prep of the box.

```
/etc/udev/rules.d/70-persistent-net.rules
```
What does /etc/sysconfig/network-scripts/ifcfg-eth0 need to say?  If you put a MAC address in there, then when the box gets build it doesnt find that for eth0 and fails.

When you login to the VM via virt-manager , you can see that eth0 isnt being started as it is defined with an  invalid mac

The above failed when data was left around in the origin vm used to create the centos68 image.
```
/etc/udev/rules.d/70-persistent-net.rules
```
On boot up this is written based on what udev finds.  any old refs to eth0 can caused vagrant to fail to define eth0 correctly.

Working with leaving a nic defined in libvirt and basic networking defining no MAC's
```
rm -f /etc/sysconfig/network-scripts/ifcfg-eth{0,1,2,3}
cat > /etc/sysconfig/network-scripts/ifcfg-eth0 <<EOF
DEVICE="eth0"
TYPE="Ethernet"
ONBOOT="yes"
BOOTPROTO="dhcp"

EOF
```

I am finding debuging this interesting and lmporting the image that vagrant creates show that the issue is with this as it doesnt get eth0.   so lets see what clearing udev net rules does.  If this image boots and gets ip, then I am happy that anything based on it will work.

trick is getting the right info and removing the right info from the upstream origin vm image.

clearing down `/etc/udev/rules.d/70-persistent-net.rules` of any known MAC's seems to work. on el6

**Comment by stephencooke** [comment]
The above failed when data was left around in the origin vm used to create the centos68 image.

clearing down `/etc/udev/rules.d/70-persistent-net.rules` of any known MAC's seems to work.

On boot up this is written based on what udev finds.  any old refs to eth0 can caused vagrant to fail to define eth0 correctly.

Working with leaving a nic defined in libvirt and basic networking defining no MAC's
```
rm -f /etc/sysconfig/network-scripts/ifcfg-eth{0,1,2,3}
cat > /etc/sysconfig/network-scripts/ifcfg-eth0 <<EOF
DEVICE="eth0"
TYPE="Ethernet"
ONBOOT="yes"
BOOTPROTO="dhcp"

EOF
```

**Comment by infernix** [comment]
This is fairly common when creating images for any kind of system (for example https://scotch.io/tutorials/how-to-create-a-vagrant-base-box-from-an-existing-one or https://unix.stackexchange.com/questions/110496/cloned-linux-system-and-etc-udev-rules-d-70-persistent-net-rules), but the conclusion here is that this is not an issue of vagrant-libvirt but one of preparing a distro for use in an image, and each distro will have its own set of changes.

So since this isn't vagrant-libvirt specific I'll leave this here for people searching it through Google.
