### ISSUE TITLE
Error saving the server: Call to virDomainDefineXML failed: internal error: no supported architecture for os type 'hvm'

### ISSUE THREAD

**Issue by shlomisd** [vagrant-libvirt/vagrant-libvirt#740]
Hi,
after adding to the file: `cord/build/Vagrantfile` the value QEMU:
```
  config.vm.define "corddev" do |d|
    d.ssh.forward_agent = true
    d.vm.box = "ubuntu/trusty64"
    d.vm.hostname = "corddev"
    d.vm.network "private_network", ip: "10.100.198.200"
    d.vm.provision :shell, path: "scripts/bootstrap_ansible.sh"
    d.vm.provision :shell, inline: "PYTHONUNBUFFERED=1 ansible-playbook /cord/build/ansible/corddev.yml -c local"
    d.vm.provider "virtualbox" do |v|
      v.driver = "qemu"
      v.memory = 2048
    end
    d.vm.provider :libvirt do |v, override|
      v.driver = "qemu"
      v.memory = 2048
      override.vm.synced_folder "..", "/cord", type: "nfs"
    end
  end

```

Still when running the cord-in-cox script. getting this Error:
```
+ sudo su root -c 'vagrant up elastic --provider libvirt'
Bringing machine 'elastic' up with 'libvirt' provider...
==> elastic: Creating image (snapshot of base box volume).
==> elastic: Creating domain with the following settings...
==> elastic:  -- Name:              build_elastic
==> elastic:  -- Domain type:       kvm
==> elastic:  -- Cpus:              1
==> elastic:  -- Memory:            4096M
==> elastic:  -- Management MAC:
==> elastic:  -- Loader:
==> elastic:  -- Base box:          ubuntu/trusty64
==> elastic:  -- Storage pool:      default
==> elastic:  -- Image:             /var/lib/libvirt/images/build_elastic.img (40G)
==> elastic:  -- Volume Cache:      default
==> elastic:  -- Kernel:
==> elastic:  -- Initrd:
==> elastic:  -- Graphics Type:     vnc
==> elastic:  -- Graphics Port:     5900
==> elastic:  -- Graphics IP:       127.0.0.1
==> elastic:  -- Graphics Password: Not defined
==> elastic:  -- Video Type:        cirrus
==> elastic:  -- Video VRAM:        9216
==> elastic:  -- Keymap:            en-us
==> elastic:  -- TPM Path:
==> elastic:  -- INPUT:             type=mouse, bus=ps2
==> elastic:  -- Command line :
Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: internal error: no supported architecture for os type 'hvm'
```

Always the Domain type is kvm:
`==> elastic:  -- Domain type:       kvm`

Also after changed in file: ` ./.vagrant.d/gems/gems/vagrant-libvirt-0.0.35/lib/vagrant-libvirt/templates/domain.xml.erb`
the `machine_type` , from HVM to QEMU, still have the same Error.

I'm running the CORD-IN-BOX, over VM with Ubuntu 14.04 server.
The CPU doesn't support KVM.  

The Vagrant version after update:
```
root@cord1:~/cord/build# vagrant version
Installed Version: 1.8.5
Latest Version: 1.9.1

```

**Comment by infernix** [comment]
I cannot reproduce. Please post a full debug log as indicated in the issue reporting template.

**Comment by shlomisd** [comment]
[vagrant debug.txt](https://github.com/vagrant-libvirt/vagrant-libvirt/files/853223/vagrant.debug.txt)

[cord installation fail.txt](https://github.com/vagrant-libvirt/vagrant-libvirt/files/853228/cord.installation.fail.txt)

Thanks.

**Comment by electrofelix** [comment]
@shlomisd The fact that the memory was also not overridden suggested to me that either your config was either incorrect or not being applied.

A quick look at https://github.com/opencord/cord/blob/973c90ad89679f0af0be13cb0266904b91ba5d68 /Vagrantfile and I noticed that you are overriding the definition of the `corddev` machine, but the error is with the `elastic` machine.

You need to override the definition for all machines, not just corddev.
