### ISSUE TITLE
package and create_box.sh fail for images with a size of 1T or more

### ISSUE THREAD

**Issue by uniqx** [vagrant-libvirt/vagrant-libvirt#743]
### Steps to reproduce
1. get an instance with an image size of 1T or bigger.
    This is how to get the image we've been working with:

       vagrant mutate https://f-droid.org/jessie64.box libvirt
       
       cat << EOF > Vagrantfile
       Vagrant.configure("2") do |config|
           config.vm.box = "jessie64"
           config.vm.provider = "libvirt"
       end
       EOF

       vagrant up

2. run qemu-img on the related image

       qemu-img info /var/lib/libvirt/images/jessie64_vagrant_box_image_0.img

    and take a look a the `virtual size` of the output

       image: /var/lib/libvirt/images/jessie64_vagrant_box_image_0.img
       file format: qcow2
       virtual size: 1.0T (1099511627776 bytes)
       disk size: 2.0G
       cluster_size: 65536
       Format specific information:
           compat: 1.1
           lazy refcounts: false
           refcount bits: 16
           corrupt: false

3. Take a look at the parsers for this output. Especially as they only parse for size in `'G'`, even thou `qemu-img` outputs the virtual size for this particular image in `'T'`.
    * https://github.com/vagrant-libvirt/vagrant-libvirt/blob/0.0.37/lib/vagrant-libvirt/action/package_domain.rb#L43
    * https://github.com/vagrant-libvirt/vagrant-libvirt/blob/0.0.37/tools/create_box.sh#L91

### Expected behaviour
Get an actual working box when running either `vagrant package` or `create_box.sh` for images with virtual size >= 1.0T

### Actual behaviour
`virtual_size` in `metadata.json` is set to an invalid value, resulting in a not bootable box.

**Libvirt version:** 0.0.37

**Comment by infernix** [comment]
Obvious bug, thanks for reporting it.
