### ISSUE TITLE
Randomly kicked out of VM and unable to vagrant ssh back into the VM

### ISSUE THREAD

**Issue by pgporada** [vagrant-libvirt/vagrant-libvirt#755]
### Steps to reproduce
1. Use the version of vagrant-libvirt and vagrant that I have specified below
2. Use a centos7 guest
3. `vagrant ssh` to the guest
4. Wait to be kicked out
5. Be unable to `vagrant ssh`
6. Have to access the VMs through `virsh console`

### Expected behavior
I should not randomly be kicked out of a vagrant box and then be unable to `vagrant ssh` back into it.

### Actual behaviour
```
phil@desktappy:~/myproj $ vagrant ssh somevm
phil@desktappy:~/myproj $ vagrant ssh somevm
phil@desktappy:~/myproj $ vagrant ssh somevm
```

I can use `virsh` and console into the VM just fine. I RANDOMLY access it via vagrant ssh after the issue occurs. This happens with some frequency. I've not seen any excessive RAM usage, I/O usage, or network traffic when this happens.

### System configuration
**OS/Distro version:**: Ubuntu 16.10

**Libvirt version:**
```
ii  libvirt-bin                                 2.1.0-1ubuntu9.1                             amd64        programs for the libvirt library
ii  libvirt-clients                             2.1.0-1ubuntu9.1                             amd64        Programs for the libvirt library
ii  libvirt-daemon                              2.1.0-1ubuntu9.1                             amd64        Virtualization daemon
ii  libvirt-daemon-system                       2.1.0-1ubuntu9.1                             amd64        Libvirt daemon configuration files
ii  libvirt-dev:amd64                           2.1.0-1ubuntu9.1                             amd64        development files for the libvirt library
ii  libvirt0:amd64                              2.1.0-1ubuntu9.1                             amd64        library for interfacing with different virtualization systems
```

**Output of `vagrant version; vagrant plugin list`:**
```
Installed Version: 1.9.3
Latest Version: 1.9.3
 
You're running an up-to-date version of Vagrant!
vagrant-libvirt (0.0.37)
vagrant-share (1.1.7, system)
vagrant-vbguest (0.13.0)
```

**Are you using upstream vagrant package or your distros package?**
Upstream

**Comment by infernix** [comment]
And why do you think this is a vagrant-libvirt problem and not a host OS or guest OS problem? You are giving us nothing to go on here - not even a debug log of any kind or a Vagrantfile with a box specification - what do you expect us to tell you?

I suggest you check your host syslogs and guest syslogs when this happens. My guess is that something is interacting with your libvirt guest network.

**Comment by pgporada** [comment]
Seems to be a libvirt error. Never seen it before, only since starting to use vagrant-libvirt. Sorry. I apologize.

During one of the oddities, this is thrown into the host OS syslog.
```
Apr  6 17:33:55 desktappy libvirtd[3431]: message repeated 2 times: [ End of file while reading data: Input/output error]
```
