### ISSUE TITLE
last vagrant-libvirt release would not install on RHEL/CENTO7 

### ISSUE THREAD

**Issue by vmindru** [vagrant-libvirt/vagrant-libvirt#772]
### Steps to reproduce
1.  install clean Centos7 or RHEL7
2.  install the latest vagrant 
3.  attempt vagrant plugin install vagrant-libvirt
4.  or you can also attempt gem install vagrant-libvirt

the result 

[root@srv ~]# gem install vagrant-libvirt
ERROR:  Error installing vagrant-libvirt:
        xmlrpc requires Ruby version >= 2.3.
[root@srv ~]# vagrant plugin install vagrant-libvirt
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:
xmlrpc requires Ruby version >= 2.3.
[root@srv ~]# 

### Expected behaviour

gem installs 

### Actual behaviour

gem fails to install due to included xmlrpc dep. 

### System configuration
**OS/Distro version:**:
Centos7 
**Libvirt version:**

libvirt-2.0.0-10.el7.x86_64

**Output of `vagrant version; vagrant plugin list`:**

ansible (0.2.2)
hitimes (1.2.4)
nio4r (2.0.0)
vagrant-share (1.1.7, system)

**Are you using upstream vagrant package or your distros package?**
Distro

**Comment by vmindru** [comment]
ok this actually seems to boil down to fog-core update https://rubygems.org/gems/fog-core/versions/1.44.0  that introduces xmlrpc deps. 

VM

**Comment by vmindru** [comment]
https://github.com/vagrant-libvirt/vagrant-libvirt/pull/771 will fix this.

**Comment by vmindru** [comment]
@pronix thanks for merging #771 , will you create a new gem release to fix faulty  https://rubygems.org/gems/vagrant-libvirt/versions/0.0.38 ?

**Comment by pronix** [comment]
@vmindru done

**Comment by vmindru** [comment]
@pronix thank's a TON!  for both releases. We can build now. Cheers!
