### ISSUE TITLE
Unsupported XML configs?

### ISSUE THREAD

**Issue by polarathene** [vagrant-libvirt/vagrant-libvirt#776]
I currently use virt-manager GUI to setup my VMs with libvirt. For GPU passthrough and some other tweaks I need to edit the XML directly. I am looking into migrating my config into being managed by this plugin, glancing over the docs some elements don't seem to be supported. 

Is there a possibility to support them or assuming behind the scenes a libvirt xml is created at `/etc/libvirt/qemu` should I manually add these tweaks myself?

Here are some of the tweaks:

### qemu commandline
This element lets you pass on CLI args to the final qemu command that libvirt creates(at least that's my understanding of what happens), the example is setting up audio routing from the guest to my host(an audio device still needs to be set such as ICH9).

```
  <qemu:commandline>
    <qemu:env name='QEMU_AUDIO_DRV' value='pa'/>
    <qemu:env name='QEMU_PA_SAMPLES' value='1024'/>
    <qemu:env name='QEMU_AUDIO_TIMER_PERIOD' value='150'/>
    <qemu:env name='QEMU_PA_SERVER' value='/run/user/1000/pulse/native'/>
  </qemu:commandline>
```

Supporting this element requires the domain element to be changed like this 

```
<domain type='kvm' xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'>
```

### vendor_id for nvidia hardware

In addition to hiding kvm which is mentioned in the docs, this change is also required, there isn't a specific value to use, so long as it's not whatever value(s) the driver rejects:

```
<hyperv>
      <relaxed state='on'/>
      <vapic state='on'/>
      <spinlocks state='on' retries='8191'/>
      <vendor_id state='on' value='1234567890ab'/>
</hyperv>
```

### clock offset (hpet)
```
  <clock offset='localtime'>
    <timer name='rtc' tickpolicy='catchup' track='guest'/>
    <timer name='pit' tickpolicy='delay'/>
    <timer name='hpet' present='yes'/>
    <timer name='hypervclock' present='yes'/>
  </clock>
```

Slightly different from the defaults I think. I originally had an issue with my host where resuming from suspend broke the `tsc` timesource falling back to `hpet` which was disabled by default iirc. Sometimes it's useful to disable `hpet` but this caused immense stuttering/lag when running the VM without `tsc` available, a BIOS update after contacting the vendor fixed that, not everyone may be as lucky to get a BIOS update so being able to enable hpet would be useful.

### Suspend to Disk (release hardware)

```
  <pm>
    <suspend-to-mem enabled='yes'/>
    <suspend-to-disk enabled='yes'/>
  </pm>
```

Not sure about this one on the docs, virsh suspend and managedsave are mentioned instead of dompmsuspend. With these elements I can suspend like a traditional system(resources not freed) or hibernate(suspend to disk) which will free the memory and GPU back to the system for the host or another VM to use. The command is `virsh dompmsuspend vm_name disk` or `mem` instead of `disk` for suspend instead of hibernate. This requires qemu guest agent to be installed on guest along with the channel added(this seems supported). Starting the VM normally will resume, I'm not sure how this differs to the currently supported methods, but the one I mention I know works with hardware passthrough, iirc suspending or at least online state snapshots complained when the VM had PCI devices attached.

---

I've not done CPU pinning or hugepages, but presumably some support for this may be needed to? Alternatively, if I could provide an existing XML that this plugin uses as a base and modifies, that'd work too?

**Comment by infernix** [comment]
All of it is technically possible, but until someone submits a PR for it, it's not likely to happen. Most of the features you mention are quite a rarity for the common use case (vms on headless servers), and the suspension would have to be compatible somehow with upstream vagrant.

I do not think your use case (pci passthrough of a windows VM) is a good fit for Vagrant to begin with, so I'm closing this with a wontfix, but you're free to submit PRs.

**Comment by polarathene** [comment]
@infernix a headless server might use a GPU for compute workloads such as machine learning. CPU pinning is useful if you run several VMs and want to ensure only specific VMs have access to certain CPU cores, especially useful on multi-socket servers where you need to be aware of NUMA for performance reasons. Hugepages iirc are useful for when passing through devices(network cards for better network performance for example).

I have a variety of VMs not just Windows with a GPU. Linux dev environments tailored to each project is another kind and having much better performance and access to hardware(Leap motion over USB where redirection fails to deliver as much I/O bandwidth needed vs USB controller passthrough) is important. Another is a NAS which has special disk config(not image file based) where virsh/XML libvirt config is required.

Using Vagrant to manage the various VMs is what I thought it'd be useful for instead of the current manual way I have atm with my root owned XML configs.

**Comment by infernix** [comment]
Those are still uncommon use cases :) but welcome to submit PRs!

**Comment by polarathene** [comment]
> Those are still uncommon use cases :)

For users who choose libvirt over other hypervisors? Or users of this specific plugin?

No worries, if I have time to want to use the plugin with these features I'll look into adding the support and submitting PRs.

**Comment by ju2wheels** [comment]
I dont think the env part of this is as far fetched a use case as it sounds. The plugin already supports USB passthrough. If you are using vagrant for IoT development testing with a USB camera passthrough for example, being able to pass through the env vars as described above is the only way to get a workable MIC from the camera.

Currently struggling with getting audio in the vagrant box w/pulseaudio working myself.
