### ISSUE TITLE
vagrant up hangs on ssh

### ISSUE THREAD

**Issue by aidda** [vagrant-libvirt/vagrant-libvirt#780]
I did vagrant up --provision libvirt and it hangs on:

default: Waiting for SSH to become available...
I can do vagrant ssh. it works! but I can't understand why vagrant up hangs on ssh mode. I delete all the machine from my local. build again. doesnt solve an issue. Also, reinstall plugins doesn't help. Also, delete the .vagrant file from my repo! I remove inscure-keypair from .vagrant.d I did vagrant reload

The issue is this error actually:

An action 'up' was attempted on the machine 'default',
but another process is already executing an action on the machine.
Vagrant locks each machine for access by only one process at a time.
Please wait until the other Vagrant process finishes modifying this
machine, then try again.

If you believe this message is in error, please check the process
listing for any "ruby" or "vagrant" processes and kill them. Then
try again.
I killed all ruby and vagrant process but doesn't help Vagrant version: 1.9.4 vagrant-libvirt version: 0.0.37 ubuntu 16.04

This is Vagrantfile:
```

Vagrant.configure("2") do |config|

  config.vm.box = "libvirt2"
  config.vm.provider :libvirt do |libvirt|
    libvirt.uri = "qemu+unix:///system"
    libvirt.driver = "qemu"
    libvirt.host = "10.20.30.40"
    #libvirt.nested = true
    libvirt.connect_via_ssh = false
    libvirt.username = "root"
  #  libvirt.password = "vagrant"
    libvirt.id_ssh_key_file= "/home/aida/Documents/chef-repo/.chef/aida.pem"
end

end

```

and this is `vagrant up -debug`
```

==> default: Starting domain.
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::WaitTillUp:0x007f32e093c8e8>
DEBUG wait_till_up: Searching for IP for MAC address: 52:54:00:46:ff:e6
 INFO interface: info: Waiting for domain to get an IP address...
 INFO interface: info: ==> default: Waiting for domain to get an IP address...
==> default: Waiting for domain to get an IP address...
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
```

**Comment by infernix** [comment]
Let me guess, your libvirt host is remote?

Can the ip of the box where you run `vagrant ` even ping the ip of the vagrant VM over on host `10.20.30.40`? I guess not?

**Comment by infernix** [comment]
Closing this due to no further updates/info. Please free to update or reopen this ticket if required. Thanks!
