### ISSUE TITLE
New box created using create_box.sh - gets stuck at Waiting for domain to get an IP address...

### ISSUE THREAD

**Issue by mmeroberts** [vagrant-libvirt/vagrant-libvirt#784]
I used qemu-convert to get an image of a running libvirt image that had been created using vagrant-libvirt.  I then used the create_box.sh from the tools directory of this project.

The Vagrantfile is:
```

Vagrant.configure("2") do |config|
    config.vm.box = "LM"
    config.vm.provider :libvirt do |libvirt|
       libvirt.uri = 'qemu+unix:///system'
       libvirt.host = "LM"
       libvirt.cpus = "4"
       libvirt.memory = "8192"
       libvirt.cpu_mode = "host-passthrough"
    end
end
```

I only get this when I have tried to create a box from another image.  I have several other vagrant-libvirt environments running and I have used boxes from the web - but so far I have failed to get any I have created to get beyond this point.

```
DEBUG wait_till_up: Searching for IP for MAC address: 52:54:00:d5:6c:74
 INFO interface: info: Waiting for domain to get an IP address...
 INFO interface: info: ==> default: **Waiting for domain to get an IP address...**
==> default: Waiting for domain to get an IP address...
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
```

**Comment by tomaskrizek** [comment]
You can try to debug it by configuring VNC and connecting to it.

Vagrantfile
```ruby
# Allow remote connections to VNC server
libvirt.graphics_type = "vnc"
libvirt.graphics_ip = "0.0.0.0"
```

Connect to it with

```bash
remote-viewer vnc://127.0.0.1:5900
```

You should be able to see where it hangs up. In my case, I discovered `auditd.service` occasionally failed to start and delayed the boot by about 3 minutes.

**Comment by mmeroberts** [comment]
Thanks

**Comment by eighthave** [comment]
@uniqx and I run into this from time to time, but mostly handle it by timing out and retrying. 
We have a full working process for making vagrant boxes entirely with KVM, no VirtualBox needed.  It also works in nested KVM, so the whole process can run in a KVM guest.  For more info, see: #788

**Comment by infernix** [comment]
My guess is that the NIC of the guest does not come up because you did not remove any static mappings for MAC to ethX/ensX interfaces, and therefore the guest does not send out dhcp requests on the first NIC.

For debian types, check `/etc/udev/rules.d/*-persistent-net.rules`; for centos types clear any MAC= out of /etc/sysconfig/network-scripts.
