### ISSUE TITLE
Vagrant Up

### ISSUE THREAD

**Issue by chishankar** [vagrant-libvirt/vagrant-libvirt#786]
### Steps to reproduce
1.  So I imported an Instructions folder from GitHub onto desktop
2. I used to be able to do Vagrant Up and start up an Ubunt 64-bit OS in Virtual Box
3. Now when I go to the instructions directory with the vagrant file and vagrant up
I get something like this:

```
`/opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/util/platform.rb:37:in `downcase': invalid byte sequence in UTF-8 (ArgumentError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/util/platform.rb:37:in `block in wsl?'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/util/silence_warnings.rb:8:in `silence!'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/util/platform.rb:35:in `wsl?'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/bin/vagrant:123:in `<main>'`\

```
How can this be fixed?

**Comment by infernix** [comment]
Please follow the instructions when creating an issue.

Either way, that is a Vagrant error, not a vagrant-libvirt error.
