### ISSUE TITLE
port working vagrant/KVM box creation to vagrant-libvirt

### ISSUE THREAD

**Issue by eighthave** [vagrant-libvirt/vagrant-libvirt#788]
For the f-droid.org infrastructure, @uniqx and I had to port our whole VirtualBox setup to KVM so that we could run weekly rebuilds on https://jenkins.debian.net.  We have the whole process working pretty well and running at least once a week from scratch.  We were already using vagrant, so vagrant-libvirt was an obvious choice.  We are not Ruby programmers at all, so anything that wasn't working in vagrant-libvirt, we got working in Python wrappers.  We would love to help get this integrated into vagrant-libvirt, where it belongs!

The process we have working is running entirely in a KVM/Bochs VM, so this is building a box via a nested KVM guest:
* convert vagrant Debian/jessie base box built with VirtualBox to KVM with vagrant-mutate
* provision the whole "buildserver" KVM guest using `vagrant up --provision`
* converting the "buildserver" KVM guest to a vagrant box
* importing the "buildserver" KVM box
* running builds in a vagrant machine with snapshots to restore state.

This whole process happens here:
* https://gitlab.com/fdroid/fdroidserver/blob/master/makebuildserver
* https://gitlab.com/fdroid/fdroidserver/blob/master/fdroidserver/vmtools.py

The whole test run is here:
* https://gitlab.com/fdroid/fdroidserver/blob/master/jenkins-build-makebuildserver
* https://jenkins.debian.net/job/reproducible_setup_fdroid_build_environment/

We're working Debian/stretch for the most part, using vagrant 1.9.1 and vagrant-libvirt 0.0.37 from there.  I don't think the latest version of vagrant-libvirt changes the parts of the process that we are running.

**Comment by infernix** [comment]
> convert vagrant Debian/jessie base box built with VirtualBox to KVM with vagrant-mutate
Why? There are native `debian/jessie64` and `debian/stretch64` libvirt boxes on Atlas

Maybe I'm missing something here, but what exactly do you want to integrate?

**Comment by eighthave** [comment]
The initial box that this process starts with all works fine.  Like you
said, libvirt boxes are already available.  What needs fixing is a bunch
of steps in creating a new box when running entirely in KVM (i.e. never
using VirtualBox for any step of the process).

* `vagrant package` is the biggest missing step.
* `vagrant snapshot` is also missing

@uniqx ended up implementing most of this, so he can add more.  Neither
of us know Ruby at all, and we're working on a Python project, so we
hacked together the whole process in Python/libvirt, often wrapping
`vagrant`.  That's what the _vmtools.py_ file is.  So that logic should
be included in vagrant-libvirt really.

**Comment by infernix** [comment]
i see.

vagrant package is supported, but is probably rough; how didn't that work out for you?

vagrant snapshot is pending in #529

**Comment by uniqx** [comment]
As I recall the main issue with `vagrant package` we encountered is already solved: #743.

Another issue we are having is that `vagrant up` sometimes just does not get past the point of  configuring a working ssh connection. So we have a makeshift workaround in place which just calls halt and up once more. I'm speculating that this is somehow related to our way of taking snapshots. So I very much looking forward official snapshot support.

**Comment by electrofelix** [comment]
I think what is pending here is just adding native snapshot support, closing in favour of #529. If I've missed that something else besides snapshots is still needed please ping me to re-open this.
