### ISSUE TITLE
option to configure a domain name per network

### ISSUE THREAD

**Issue by brianjmurrell** [vagrant-libvirt/vagrant-libvirt#792]
One can add a `<domain name='example.com' localOnly='yes'/>` type stanza to a libvirt network configuration to have that network's _dnsmasq_ answer DNS queries for that network as is blogged about [here](https://liquidat.wordpress.com/2017/03/03/howto-automated-dns-resolution-for-kvmlibvirt-guests-with-a-local-domain/).

This would be very useful.

Barring actually implementing this, a similar option to #791 for networks would be a useful stop-gap.

**Comment by electrofelix** [comment]
Actually I'd find that feature very handy as it would remove a requirement on using vagrant-hostmanager locally and make a container with vagrant/vagrant-libvirt easier to use.

I'll try to see what's required over the next week, but it's probably as easy as adding a domain option to the network config options and updating the associated template. Trickier might be restricting usage to additional networks (should not be allowed for the management one i'd say, as too easy to conflict with multiple setups), and catching attempting to redefine a network used by another set of vm's.

**Comment by infernix** [comment]
PRs are welcome! :)

**Comment by hugoboos** [comment]
Hi, created https://github.com/vagrant-libvirt/vagrant-libvirt/pull/833. First attempt, work in progress, feedback is welcome.

**Comment by syndbg** [comment]
I think this can be closed @infernix since #833 is done
