### ISSUE TITLE
vagrant up --provider=libvirt errors!

### ISSUE THREAD

**Issue by bigbigbanana** [vagrant-libvirt/vagrant-libvirt#795]
When i run vagrant up --provider=libvirt,i got the following results,i want to ask how to fix it?The pictures i uploaded shows the version of vagrant,vagrant plugin and libvirtd.
![2017-07-05 16-22-34](https://user-images.githubusercontent.com/24928429/27937696-9cb89c4a-62eb-11e7-88be-be484dae2e6d.png)
![2017-07-05 16-26-43](https://user-images.githubusercontent.com/24928429/27937725-c98b5730-62eb-11e7-82a2-79a84dcd0b02.png)

**Comment by electrofelix** [comment]
@bigbigbanana the picture uploaded shows a failed kernel build, did you mean to reference a different one?

**Comment by bigbigbanana** [comment]
@electrofelix 
Sorry,the picture i uploaded before was wrong,now i have re-uploaded it,could u tell me what's wrong with it.Thanks very much!

**Comment by infernix** [comment]
You're going to have to translate that qemu-img response, I can't read it.

**Comment by liufeng11** [comment]
@bigbigbanana Hvae you solved this problem that you described? I got the same problem as you, if you have solved it, could you please tell me some details to solve it?

**Comment by liufeng11** [comment]
@infernix  The problem of qemu-img is that  "Internal error, cannot resolve qemu-img. output the result: (libvirt error) " I got the similar problem as him, the detail are as follows when I execute "vagrant up --provider=libvirt " :[==> default: Creating image (snapshot of base box volume).
/root/.vagrant.d/gems/2.3.4/gems/fog-libvirt-0.4.0/lib/fog/libvirt/requests/compute/create_volume.rb:6:in `create_volume_xml': Call to virStorageVolCreateXML failed: internal error：sub process（/usr/local/bin/qemu-img create -f qcow2 -b /var/lib/libvirt/images/ubuntu-VAGRANTSLASH-xenial64_vagrant_box_image_20170822.0.0.img -o backing_fmt=qcow2 /var/lib/libvirt/images/rkt_default.img 10485760K）Exit status 126: libvirt:  error : cannot execute binary file  /usr/local/bin/qemu-img: permission dennied (Libvirt::Error)]

**Comment by infernix** [comment]
Closing this due to no further updates/info. Please free to update or reopen this ticket if required. Thanks!
