### ISSUE TITLE
vagrant up stucks on reconnecting by ssh

### ISSUE THREAD

**Issue by ntff** [vagrant-libvirt/vagrant-libvirt#796]
1. I expect `vagrant up` will succeed.
2. Instead, `vagrant up` stuck on 'Disconnecting and reconnecting using new SSH key...'.
3. I have a host with Debian, as I hope, equivalent (updated) to the latest Debian 9.0 now.
```shell
host:~$ dpkg -l | egrep "qemu|libvirt"
ii  ipxe-qemu                            1.0.0+git-20161027.b991c67-1      all          PXE boot firmware - ROM images for qemu
ii  libvirt-clients                      3.0.0-4                           amd64        Programs for the libvirt library
ii  libvirt-daemon                       3.0.0-4                           amd64        Virtualization daemon
ii  libvirt-daemon-system                3.0.0-4                           amd64        Libvirt daemon configuration files
ii  libvirt-glib-1.0-0:amd64             1.0.0-1                           amd64        libvirt GLib and GObject mapping library
ii  libvirt0                             3.0.0-4                           amd64        library for interfacing with different virtualization systems
ii  python-libvirt                       3.0.0-2                           amd64        libvirt Python bindings
ii  qemu-kvm                             1:2.8+dfsg-6                      amd64        QEMU Full virtualization on x86 hardware
ii  qemu-system-common                   1:2.8+dfsg-6                      amd64        QEMU full system emulation binaries (common files)
ii  qemu-system-x86                      1:2.8+dfsg-6                      amd64        QEMU full system emulation binaries (x86)
ii  qemu-utils                           1:2.8+dfsg-6                      amd64        QEMU utilities
```
Host is running vms, using qemu-kvm and libvirt, one of  such vms is where I run vagrant (created with official debian/stretch64 box, just for example):
```shell
vagrant@stretch:~$ dpkg -l | egrep "vagrant|libvirt"
ii  libvirt-clients                3.0.0-4                        amd64        Programs for the libvirt library
ii  libvirt-daemon                 3.0.0-4                        amd64        Virtualization daemon
ii  libvirt-daemon-system          3.0.0-4                        amd64        Libvirt daemon configuration files
ii  libvirt0                       3.0.0-4                        amd64        library for interfacing with different virtualization systems
ii  python-libvirt                 3.0.0-2                        amd64        libvirt Python bindings
ii  ruby-libvirt                   0.7.0-1                        amd64        Ruby bindings for libvirt
ii  vagrant                        1.9.1+dfsg-1                   all          Tool for building and distributing virtualized development environments

vagrant@stretch:~$ vagrant version
Installed Version: 1.9.1

vagrant@stretch:~$ vagrant plugin list
vagrant-libvirt (0.0.40)
```

`vagrant up` stucks.
[vagrant_up.txt](https://github.com/vagrant-libvirt/vagrant-libvirt/files/1131497/vagrant_up.txt)

After I interrupt it with Ctrl+C, following is traced:
[stack.txt](https://github.com/vagrant-libvirt/vagrant-libvirt/files/1131507/stack.txt)

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.provider :libvirt do |libvirt|
        libvirt.host = "192.168.121.1"
        libvirt.username = "virsh"
        libvirt.storage_pool_name = "default"
        libvirt.connect_via_ssh = true
        libvirt.graphics_type = "spice"
        libvirt.graphics_passwd = "deault"
    end
    config.vm.synced_folder ".", "/vagrant",
        disabled: true
    config.vm.box = "debian/jessie64"
end
```

I tried to deploy jessie64 and stretch64 boxes with the same result.

I install libvirt and vagrant from distro package, but vagrant-libvirt plugin with `vagrant plugin install ...`.

As far as I understand, besides the serious impact on complex multi-host configurations deployment, as a simplest consequences of this - hostname is not set inside a vm.

**Comment by aetherith** [comment]
@ntff I'm working with a similar host to you and am seeing the same problem. I have found a partial work around in setting `config.ssh.insert_key = false` in my Vagrantfile. This gets the setup past the issue and has the domain boot, but it does create the issue of the VM running the default insecure Vagrant SSH key.

**Comment by infernix** [comment]
Why are you defining libvirt.host, libvirt.uername? are you connecting to a remote libvirt server?

**Comment by ntff** [comment]
I do.

**Comment by infernix** [comment]
Can you reproduce it with a local libvirt setup?

**Comment by ntff** [comment]
I'll try.

**Comment by ntff** [comment]
I couldn't reproduce it with local libvirt setup.

As I don't have a configuration with local libvirt, I configured it inside my remote libvirt (nested-like configuration). I could play with both, remote and local configurations. Local configuration works perfectly. With remote configuration I rather hit into the problem:
```
/usr/lib/ruby/vendor_ruby/net/ssh/transport/server_version.rb:44:in `write': Broken pipe (Errno::EPIPE)
        from /usr/lib/ruby/vendor_ruby/net/ssh/transport/server_version.rb:44:in `negotiate!'
        from /usr/lib/ruby/vendor_ruby/net/ssh/transport/server_version.rb:32:in `initialize'
...
```
I think it's because everything runs much slower inside vm.
I could workaround it by hacking wait_for.rb in fog-core lib (for some reason, it's not enough alone - I also had to uninstall all netcat-packages). This cannot be counted as as pure problem appearance, but still I attach my configuration (just remove libvirt.host, etc, where marked in Vagrantfile for your local libvirt) if you'll need it.
[vagrant-test.zip](https://github.com/vagrant-libvirt/vagrant-libvirt/files/1209052/vagrant-test.zip)

**Comment by ntff** [comment]
You'll need to run
```
vagrant hostmanager
```
after vms creation.

**Comment by Vogtinator** [comment]
We have the same issue on openSUSE Tumbleweed here - the reason is an updated version of netcat.
Downgrading it to a version where the ```-N``` option does not exist fixes this issue.

**Comment by ntff** [comment]
I have two configurations, one that works well and other that stucks on ssh reconnect.

Indeed, they have different versions of netcat on server. One that works has 1.105 (in debian),
and one that doesn't work has version 1.130 installed.

**Comment by ntff** [comment]
The following updated Vagrantfile solves the problem for me.

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.provider :libvirt do |libvirt, override|
    libvirt.host = "server"
    libvirt.username = "vagrant"
    libvirt.connect_via_ssh = true
    libvirt.driver = "qemu"
    libvirt.management_network_name = "vagrant-libvirt-new"
    libvirt.management_network_address = "192.168.124.0/24"
    override.ssh.proxy_command = "ssh server -l vagrant nc -N %h %p"
  end

  config.vm.synced_folder ".", "/vagrant",
    disabled: true

  config.vm.box = "debian/stretch64"
  config.vm.hostname = "vagrant-remote"
end
```

Here is the line that does the trick:
```ruby
override.ssh.proxy_command = "ssh server -l vagrant nc -N %h %p"
```

The difference is that `-N` flag added.

As far as I understand libvirt library itself is responsible for composing `proxy_command`.
Code is in `src/rpc/virnetsocket.c` (can be found in bundle https://libvirt.org/sources/libvirt-3.7.0.tar.xz), in `virNetSocketNewConnectSSH` function.

There is already a code that checks if `nc` takes `-q` option:
```c
    virCommandAddArgFormat(cmd,
         "'if '%s' -q 2>&1 | grep \"requires an argument\" >/dev/null 2>&1; then "
             "ARG=-q0;"
         "else "
             "ARG=;"
         "fi;"
         "'%s' $ARG -U %s'",
         quoted, quoted, path);
```
same can be done for `-N` flag.

**Comment by ntff** [comment]
As far as I understand even latest libvirt-3.7.0 doesn't solve the problem.

**Comment by ntff** [comment]
`nc -N` in `netcat-openbsd` looks as equivalent to `nc -q0` in `netcat-traditional'.

`libvirt` supports `-q0` and so, `netcat-traditional`, but doesn't support `-N`, which makes `netcat-openbsd` support incomplete.

**Comment by ntff** [comment]
I was wrong saying it is a problem in libvirt library.

**Comment by mcandre** [comment]
On my machine, `config.ssh.insert_key = false` in the base Vagrantfile appears to be insufficent for building a libvirt box that can then ssh.
