### ISSUE TITLE
--parallel option

### ISSUE THREAD

**Issue by hahattan** [vagrant-libvirt/vagrant-libvirt#809]
Is vagrant-libvirt supporting ``--parallel`` option ? 

I expect the ``--parallel`` can accelerate the boot up time, but after doing some experiments, the total execution time and the output message while running ``vagrant up --provider=libvirt --parallel`` don't have obvious difference.

**Comment by infernix** [comment]
As far as I know parallel is the default; try comparing to --no-parallel.
