### ISSUE TITLE
Vagrant destroy doesn't stop port forwarding ssh connections

### ISSUE THREAD

**Issue by dmeloni-radarservices** [vagrant-libvirt/vagrant-libvirt#813]
### Steps to reproduce
1. create a VM with port forwarding
2. vagrant destroy

### Expected behaviour
All ssh tunnels used to expose ports should be killed/stopped

### Actual behaviour
These ssh process linger around and in case of a fast cycle (vagrant destroy && vagrant up) the ports will not be correctly bound by ssh the ports are already in use.

When the machine is running (pgrep -a ssh):
```
sh -c ssh -o User=vagrant -o Port=22 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ForwardX11=no -o IdentityFile='"/tmp/test/.vagrant/machines/default/libvirt/private_key"' -L localhost:6666:192.168.121.143:6666 -N 192.168.121.143
ssh -o User=vagrant -o Port=22 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ForwardX11=no -o IdentityFile="/tmp/test/.vagrant/machines/default/libvirt/private_key" -L localhost:6666:192.168.121.143:6666 -N 192.168.121.143
```

After it has been destroyed without halting first  (pgrep -a ssh)
```
ssh -o User=vagrant -o Port=22 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ForwardX11=no -o IdentityFile="/tmp/test/.vagrant/machines/default/libvirt/private_key" -L localhost:6666:192.168.121.143:6666 -N 192.168.121.143
```

As you can notice the shell has terminated but the ssh process hasn't.

### System configuration
**OS/Distro version:**: Debian/stretch (9) 

**Libvirt version:** 3.0.0-4

**Output of `vagrant version; vagrant plugin list`:**
Vagrant: 1.9.1
vagrant-cachier (1.2.1)
  - Version Constraint: > 0
vagrant-libvirt (0.0.37)
  - Version Constraint: > 0

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**
Both destroy and halt were executed from a clean vagrant up
[debug_destroy.txt](https://github.com/vagrant-libvirt/vagrant-libvirt/files/1298542/debug_destroy.txt)
[debug_halt.txt](https://github.com/vagrant-libvirt/vagrant-libvirt/files/1298541/debug_halt.txt)

**A Vagrantfile to reproduce the issue:**
```
Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.box = "debian/stretch64"
  config.vm.network 'forwarded_port', host: 6666, guest: 6666, protocol: 'tcp'
end
```

**Are you using upstream vagrant package or your distros package?** Distro

**Comment by dmeloni-radarservices** [comment]
Apparently actions/forward_ports.rb uses the method spawn to execute the ssh command, running it using a shell,  then it saves the PID of the shell itself instead of the ssh subprocess. the same, but with an additional indirection happends in case of sudo.

**Comment by norpol** [comment]
Hi, we are still running into this issue. Any chance this change might make this into a release soon? :-)
