### ISSUE TITLE
Private Network creation fails when IP set for host.

### ISSUE THREAD

**Issue by kristvanbesien** [vagrant-libvirt/vagrant-libvirt#816]
### Steps to reproduce
1. Add a private network to the instance: 
      nd.vm.network :private_network, type: "dhcp", libvirt__forward_mode: "none", libvirt__host_ip: "192.168.20.20"
2. Vagrant up

### Expected behaviour
A private network is created with network address 192.168.20.2/24, and the host is started with an interface in that network.

### Actual behaviour
 I get the following error:
Error occurred while creating new network: Call to virNetworkDefineXML failed: internal error: range 172.28.128.1 - 172.28.128.254 is not entirely within network 192.168.20.2/24.

### System configuration
Fedora 25
Libvirt 2.2.1
Vagrant 1.9.5 (from distro)

vagrant plugin list
landrush (1.2.0)
  - Version Constraint: > 0
vagrant-hostmanager (1.8.7)
  - Version Constraint: > 0
vagrant-libvirt (0.0.40)
  - Version Constraint: > 0
vagrant-share (1.1.8)
  - Version Constraint: > 0

**Comment by kristvanbesien** [comment]
Note: If I just use 
nd.vm.network :private_network, type: "dhcp", libvirt__forward_mode: "none"
everything works, but I lose control over the IP address associated to the private network.

**Comment by infernix** [comment]
You will need current master of vagrant-libvirt and specify `libvirt__network_address` as well.  see https://github.com/vagrant-libvirt/vagrant-libvirt/commit/b00816680a495d5f47f8b1bc4421b227562d8cfc

**Comment by bhaventank** [comment]
I face the same problem on vagrant-libvirt 0.12.2 (latest)
[user@localhost ]$ vagrant plugin list
vagrant-libvirt (0.12.2, global)
vagrant-share (2.0.0, global)

**extract from Vagrantfile**
    domainname.vm.network :private_network,
      :type => "dhcp",
      :libvirt__network_address => '10.20.30.0'

**Error on 'vagrant up'**
Error occurred while creating new network: Call to virNetworkDefineXML failed: internal error: range 10.20.30.1 - 10.20.30.0 is not entirely within network 10.20.30.1/32.
