### ISSUE TITLE
Possible to change default box directory

### ISSUE THREAD

**Issue by hahattan** [vagrant-libvirt/vagrant-libvirt#817]
Is it possible to change the default directory(``/var/lib/libvirt/images``) which stores the box image and the COW vm image ?

The reason is that I want to use FUSE to trace the I/O activity of VM booting up. And how FUSE did that is by mounting the original directory to another place and trace all activities on that place. (so I want to change the default directory to here)

Thanks.

**Comment by daks** [comment]
I'm quite sure this is not dependent of this plugin, but instead depends of the libvirt storage pools configuration.
You can verify in /etc/libvirt/storage/, but to modify it, I think you need to use 'virsh' commandline tool, or 'virt-manager'

**Comment by hahattan** [comment]
I see.
Thanks for the help

**Comment by electrofelix** [comment]
@hahattan You can create a storage pool and then tell the plugin to use that for any VM's via the `storage_pool_name` attribute for libvirt connection.

What would obviously be nice, would be the ability to have the plugin create the storage pool for you automatically as long as you specified a path that was writeable by the user.
