### ISSUE TITLE
cannot start vm in centos 7

### ISSUE THREAD

**Issue by naseemansar** [vagrant-libvirt/vagrant-libvirt#821]
[root@cent6 ~]# vagrant up --provider=libvirtd
No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which
is available for free on all major platforms.

If you believe you already have a provider available, make sure it
is properly installed and configured. You can see more details about
why a particular provider isn't working by forcing usage with
`vagrant up --provider=PROVIDER`, which should give you a more specific
error message for that particular provider.
[root@cent6 ~]# export VAGRANT_DEFAULT_PROVIDER=libvirt
[root@cent6 ~]# echo $VAGRANT_DEFAULT_PROVIDER=libvirt
libvirt=libvirt
[root@cent6 ~]# vagrant up
The provider 'libvirt' could not be found, but was requested to
back the machine 'default'. Please use a provider that exists.
[root@cent6 ~]# vagrant plugin list
vagrant-share (1.1.5, system)
[root@cent6 ~]#

**Comment by infernix** [comment]
`--provider=libvirt`, not `libvirtd`

**Comment by electrofelix** [comment]
Also your list of plugins indicates you have not installed vagrant-libvirt.
