### ISSUE TITLE
Using remote host

### ISSUE THREAD

**Issue by moozer** [vagrant-libvirt/vagrant-libvirt#826]
I am trying to "vagrant up" to a remote host.

I can spin up a VM, but I get stuck where it wait for "SSH to become available". It gets the correct IP address.

The "vagrant-libvirt" network on both my local machine and on the remote host is 192.168.121.0/24. If I change vagrant-libvirt on the remote host (to e.g. 192.168.122.0/24), I get an error saying that the ip range is wrong.

In order for my local machine to handle routing properly to "vagrant-libvirt" on the remote host, I must have different IP addresses on the two subnets. 

My guess is that it could be done using a different "management_network_name" when connecting remotely. 
The description at https://github.com/vagrant-libvirt/vagrant-libvirt#management-network is insufficient for me to create a working config and I have been unable to find an example online.

Questions:
1) How do you set up subnets when using vagrant-libvirt on a remote server?
2) Can you supply an example or link of using "management_network_name" to change the management network?

```
cat Vagrantfile
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "debian/stretch64"

  config.vm.provider :libvirt do |libvirt|
    libvirt.uri = "qemu+ssh://beast/system"
  end
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # run a script
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "vanilla.yml"
  end

end
```

**Comment by termonio** [comment]
I had a similar problem and also suspected the problem to be related with the management network.
However, the issue went away when I did not use a URI as in Virtual Machine Manger or `virsh`
but list `host`, `username`, etc. one by one in the `Vagrantfile`:

```
config.vm.provider :libvirt do |libvirt|
    libvirt.host = "hostname"
    libvirt.username = "auser"
    libvirt.driver = "kvm"
    libvirt.connect_via_ssh = true
    libvirt.id_ssh_key_file = "/home/auser/.ssh/id_rsa"
end
```

Whenever I used `libvirt.uri = "qemu+ssh://host/system"` I got stuck in SSH becoming available.

As far as networking is concerned, I just use a `config.vm.network "public_network", :dev => "br0", :type => "bridge"` and let this network receive its IP from a DHCP server in my net. Obviously, this needs a corresponding entry in `/etc/network/interfaces` in the Debian KVM/Vagrant image. This setup results in two networks: the management network in one subnet (automatically created) and the public network in another subnet.

**Comment by moozer** [comment]
I though that you local machine must have access to the management network. 
Do you have access the the libvirt-vagrant network from your local machine?

And I found a solution for my case. 
1) add "libvirt.uri" to the default values, ie. put it in  ~/.vagrant.d/Vagrantfile
2) specificy a new management network and ip range that the local machine doesn't use already
3) set up a tunnel to the new management network to make the new ip available (I did this using wireguard9

Alternatively, you might have success with a bridged network and set a static route (or use dynamic routing).

This has the very cool feature of using a remote host completely transparently and it works for generic Vagrantfiles also.


My defaults for Vagrantfile
```
➜ cat .vagrant.d/Vagrantfile 
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.provider :libvirt do |libvirt|
    # oetherwise it defaults to qemu://localhost/system?...

    # run locally
    # libvirt.uri = "qemu:///system"

    # run on beast
    libvirt.uri = "qemu+ssh://beast/system"
    libvirt.management_network_name = "vagrant-beast"
    libvirt.management_network_address = "192.168.122.0/24"
  end

  config.vm.synced_folder ".", "/vagrant", type: "nfs", nfs_version: 4, nfs_udp: false

end

```
