### ISSUE TITLE
Failure to boot vm's when ipv6 is disabled on host

### ISSUE THREAD

**Issue by jdonofrio728** [vagrant-libvirt/vagrant-libvirt#834]
### Steps to reproduce
1. On a Linux based machine, disable ipv6 support (I did this through GRUB command line, ipv6.disable=1 )

2.Boot a libvirt based vm

### Expected behaviour
VM should boot as normal

### Actual behaviour
```
Error while activating network: Call to virNetworkCreate failed: internal error: Failed to apply firewall rules /sbin/ip6tables --table filter --insert FORWARD --in-interface virbr1 --jump REJECT: ip6tables v1.6.0: can't initialize ip6tables table `filter': Address family not supported by protocol
Perhaps ip6tables or your kernel needs to be upgraded.
.

```

### System configuration
**OS/Distro version:**:
Ubuntu 16.04
**Libvirt version:**
1.3.1
**Output of `vagrant version; vagrant plugin list`:**
```
Installed Version: 2.0.0
Latest Version: 2.0.1
 
To upgrade to the latest version, visit the downloads page and
download and install the latest version of Vagrant from the URL
below:

  https://www.vagrantup.com/downloads.html

If you're curious what changed in the latest release, view the
CHANGELOG below:

  https://github.com/mitchellh/vagrant/blob/v2.0.1/CHANGELOG.md
```
vagrant-libvirt (0.0.40)
vagrant-share (1.1.9, system)
  - Version Constraint: > 0
```

```

```
**Output of `VAGRANT_LOG=debug vagrant up --provider=libvirt`**
https://gist.github.com/jdonofrio728/1780c04d12bf07fbf390142aa373b4ef

**A Vagrantfile to reproduce the issue:**
```
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_check_update = true
  config.vm.define "sandbox-01" do |c|
    c.vm.hostname = "sandbox-01"
    c.vm.network "private_network", ip: "#{private_network}.100"
  end
end

```

**Are you using upstream vagrant package or your distros package?**
Upstream

**Comment by infernix** [comment]
This is not due to vagrant-libvirt since it is libvirt itself that applies any iptables rules, so I don't think we can do anything here. I bet you will see the same result when using just virsh/virt-manager.

**Comment by patryk4815** [comment]
I had similar issue. 
Solved by using: `cp /bin/true /sbin/ip6tables`
 💯  💯  💯  💯 ⚠️ ⚠️ ⚠️ ⚠️
