### ISSUE TITLE
machine discovery with remote libvirtd

### ISSUE THREAD

**Issue by keyolk** [vagrant-libvirt/vagrant-libvirt#844]
I'm using vagrant with vagrant-libvirt with remote libvirtd host.
its like ...
```
vagrant client - libvirtd host - vm 
```

from above,
is there a way to get virtual machines dns records ?
I'm using [sshuttle](https://github.com/apenwarr/sshuttle) to make proxy between client/libvirtd.
by using this I can access remote machine by IP but not by its name.

I saw dnsmasq is running on libvirtd host,
but cant access using dig on host machine : ( 
```
$ virsh -c qemu:///system net-dumpxml vagrant-libvirt
<network connections='3'>
  <name>vagrant-libvirt</name>
  <uuid>9b800a3a-c203-8767-7bac-629004f0bfc3</uuid>
  <forward mode='nat'/>
  <bridge name='virbr1' stp='on' delay='0' />
  <mac address='52:54:00:6C:E1:BD'/>
  <ip address='192.168.121.1' netmask='255.255.255.0'>
    <dhcp>
      <range start='192.168.121.1' end='192.168.121.254' />
    </dhcp>
  </ip>
</network>
$ dig @192.168.121.1 vm-0 // failed ...
```
it is accessible from VM only.

and [landrush](https://github.com/vagrant-landrush/landrush) seems doesn't fit my case.

Anyone can inform me what I have to check more ?

I'm using below Vagrantfile
```
INSTANCE_PREFIX="centos7"

$num_instance = 3
$box = "centos/7"

$vm_cpus = 2
$vm_memory = 1024

Vagrant.configure("2") do |config|

  def customize(config)
    config.vm.box = $box
    config.ssh.insert_key = true
    config.ssh.forward_agent = true
    config.ssh.forward_x11 = true

    config.vm.provider :libvirt do |libvirt|
      libvirt.driver = "kvm"
      libvirt.host = "remote"
      libvirt.username = "user"
      libvirt.storage_pool_name = "default"
      libvirt.connect_via_ssh = "true"
    end
  end

  $num_instance.times do |i|
    config.vm.define "#{INSTANCE_PREFIX}-#{i}" do |target|
      customize target
      instance_index = i
      target.vm.hostname = "#{INSTANCE_PREFIX}-#{instance_index}"
    end
  end

end

```

**Comment by pronix** [comment]
I think require patch.
https://liquidat.wordpress.com/2017/03/03/howto-automated-dns-resolution-for-kvmlibvirt-guests-with-a-local-domain/

**Comment by electrofelix** [comment]
You can put together a custom network specification as suggested. Dig against the default vagrant-libvirt domain should work though, however I've found that there can be issues with hostnames.

Suggest running the following and see what hostname was used to register the IP address as this will have occurred before vagrant has set the hostname:
```
virsh net-dhcp-leases vagrant-libvirt
```

As this is a multiple machine setup, and the same box is used, it's likely the same hostname will appear for all three machines.

What you need to do, is add a provision step to execute a release and renew of the dhcp lease after the machine has been brought up. Doing this in debian can be done via the following:
```
sudo dhclient -v -r ens5; sudo dhclient -v ens5
```
Not sure what the equivalent in CentOS will be, as you only want to release the lease and renew. Maybe network-manager is smart enough these days for a network restart not to remove the network, but just refresh it instead?

Once that succeeds, then should find that use of `dig @192.168.121.1 vm-0` will work as expected.

Assuming this should be sufficient to resolve, so going to close for now and can ping me to reopen if this is insufficient.
