### ISSUE TITLE
Does vagrant-libvirt automatically adds a private network  to every vm?

### ISSUE THREAD

**Issue by mleone87** [vagrant-libvirt/vagrant-libvirt#846]
### Steps to reproduce
1. Create a custom nat network on the system
2. Create a Vagrant test vm with public network created above
3. ssh to vm

### Expected behaviour
ip addr should show only the eth0 interface attached to custom nat network

### Actual behaviour
ip addr show an interface attached to a nat network called vagrant-libvirt network and another interface that is attached to my custom network

### System configuration
**OS/Distro version:**:
Arch Linux latest updates

**Libvirt version:**
3.10.0
**Output of `vagrant version; vagrant plugin list`:**
Installed Version: 2.0.1
Latest Version: 2.0.1
 
You're running an up-to-date version of Vagrant!
vagrant-libvirt (0.0.40)
vagrant-mutate (1.2.0)
vagrant-rekey-ssh (0.1.9)

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**
```
---

```

**A Vagrantfile to reproduce the issue:**
```
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"

  # Public host bridge
  config.vm.network "public_network", type: "bridge",
      dev: "virbr10",
      mode: "bridge",
      network_name: "public-network"
  # Standard configuration for all VMs
  config.vm.provider :libvirt do |libvirt|
      libvirt.memory = 1024
      libvirt.volume_cache = "writeback"
      libvirt.graphics_type = "spice"
      libvirt.video_type = "qxl"
  end

  # admin VM
  config.vm.define "node-admin", primary: true do |admin|
      admin.vm.hostname = "node-admin"
  end
end

```

**Are you using upstream vagrant package or your distros package?**
Uptream

**Comment by infernix** [comment]
Yes, it always adds a management network in order for vagrant to interact with the VM. See https://github.com/vagrant-libvirt/vagrant-libvirt#management-network
