### ISSUE TITLE
`virStorageVolGetInfo failed` when running `vagrant up` in parallel

### ISSUE THREAD

**Issue by evgeni** [vagrant-libvirt/vagrant-libvirt#850]
### Steps to reproduce
1. run `vagrant up <something>` in parallel (with different boxes)

### Expected behaviour
all boxes are up

### Actual behaviour
Sometimes, you end up with:

```
Call to virStorageVolGetInfo failed: Storage volume not found: no storage vol with matching path '/var/lib/libvirt/images/some_image.img'
```

where `some_image` is the disk for another `vagrant up` that is currently running.

### System configuration
**OS/Distro version:**:
RHEL7

**Libvirt version:**
1.2.17

**Output of `vagrant version; vagrant plugin list`:**
Installed Version: 1.8.1
Latest Version: 2.0.1
vagrant-libvirt (0.0.33)
vagrant-share (1.1.5, system)

**Are you using upstream vagrant package or your distros package?**
Upstream

Sorry, I currently have no good reproducer. Will try to build you one as time permits.

**Comment by infernix** [comment]
Does it happen with `vagrant up --no-parallel` as well? 

Can you post any debug logs?

**Comment by evgeni** [comment]
The first try with `--no-parallel` of course worked... Will do a couple more and also add `VAGRANT_LOG=debug` and post these logs here.

**Comment by evgeni** [comment]
So I can (quite reliably) reproduce this on my RHEL box with the following `Vagrantfile`:

```
Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true
  (0..99).to_a.each do |id|
    config.vm.define "box#{id}" do |box|
      box.vm.box = "centos/7"
      box.vm.hostname = "box#{id}.vagrant.example.com"
    end
  end
end
```

and then just starting multiple VMs in parallel (bash: `for i in {0..3}; do vagrant up box${i} & done`)

that is with:
* RHEL 7.2
* libvirt 1.2.17 (with plain dir storage)
* vagrant 1.8.1
* vagrant-libvirt 0.0.33
* fog-core-1.40.0  fog-json-1.0.2  fog-libvirt-0.0.3  fog-xml-0.1.2
* ruby-libvirt-0.6.0

**Comment by evgeni** [comment]
[vagrant.debug.log](https://github.com/vagrant-libvirt/vagrant-libvirt/files/1638594/vagrant.debug.log) from the above box, with `VAGRANT_LOG=debug`, doing 4 `vagrant up` in parallel.

**Comment by evgeni** [comment]
and the same `Vagrantfile` does not trigger the issue on my Fedora 27 workstation with:

* vagrant-1.9.8
* vagrant-libvirt-0.0.40
* libvirt-3.7.0
* ruby-libvirt-0.7.0
* fog-libvirt-0.3.0

**Comment by electrofelix** [comment]
0.0.33 is quite an old version of vagrant-libvirt, I've recall a patch for the storage code sometime after  then to fix parallel behaviour, suggest you update and retest.

**Comment by electrofelix** [comment]
Given that going from vagrant-libvirt-0.0.33 to vagrant-libvirt-0.0.40 resulted in the issue disappearing, it seems like simply upgrading vagrant-libvirt was the answer with the original issue.

Been able to bring up 8 of the machines in parallel without issue with recent vagrant-libvirt:
```
vagrant up --parallel --provider libvirt box1 box2 box3 box4 box5 box6 box7 box8
```

So assuming this is no longer an issue.
