### ISSUE TITLE
vagrant-libvirt does not honour the 'config.ssh.keys_only' directive.

### ISSUE THREAD

**Issue by bashims** [vagrant-libvirt/vagrant-libvirt#856]
### Steps to reproduce
1. vagrant up with a Vagrant file that specifies 'config.ssh.keys_only'
2. 
3.

### Expected behaviour
Port forwards work when config.ssh.keys_only is true.

### Actual behaviour
Vagrant fails to honour the  'config.ssh.keys_only' directive and let's ssh delegate to the ssh_agent which can lead to the ssh client exceeding sshd's MaxAuthTries. The ssh client aborts with a ""Too many Authentication Failures for user..." error.

### System configuration
**OS/Distro version:**: Fedora 27

**Libvirt version:** vagrant-libvirt-0.0.40-3.fc27.noarch

**Output of `vagrant version; vagrant plugin list`:**
vagrant version ; vagrant plugin list
Installed Version: 1.9.8
Latest Version: 2.0.2
 
To upgrade to the latest version, visit the downloads page and
download and install the latest version of Vagrant from the URL
below:

  https://www.vagrantup.com/downloads.html

If you're curious what changed in the latest release, view the
CHANGELOG below:

  https://github.com/mitchellh/vagrant/blob/v2.0.2/CHANGELOG.md
vagrant-libvirt (0.0.40, system)
vagrant-sshfs (1.3.0)

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**
```
Insert debug output inside quotes here (replace ... with whatever command you use to trigger the issue)
```

**A Vagrantfile to reproduce the issue:**
```
Insert Vagrantfile inside quotes here (remove sensitive data if needed)
```

**Are you using upstream vagrant package or your distros package?**
Distro

**Comment by pronix** [comment]
thnks. merged.
