### ISSUE TITLE
private_network not getting ip address for normal user.

### ISSUE THREAD

**Issue by pawaanv** [vagrant-libvirt/vagrant-libvirt#876]
### Steps to reproduce
1. i am having vagrant file 

2.when i run vagant up both the one and two are created and running but defined ip address are not visible.
vagrant ssh one 
[vagrant@one ~]$ ip a
lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
 eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 52:54:00:e1:9b:0b brd ff:ff:ff:ff:ff:ff
    inet 192.168.121.160/24 brd 192.168.121.255 scope global dynamic eth0
       valid_lft 3407sec preferred_lft 3407sec
    inet6 fe80::5054:ff:fee1:9b0b/64 scope link 
       valid_lft forever preferred_lft forever
 eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN qlen 1000
    link/ether 52:54:00:57:1b:2c brd ff:ff:ff:ff:ff:ff

3.Further investigating found that  ifcfg-eth1 is owned by vagrant rather than root 

 $vagrant ssh one 
Last login: Mon Mar 26 16:46:13 2018 from 192.168.121.1
[vagrant@one ~]$ stat /etc/sysconfig/network-scripts/ifcfg-eth1
  File: ‘/etc/sysconfig/network-scripts/ifcfg-eth1
  Size: 215       	Blocks: 8          IO Block: 4096   regular file
Device: fd00h/64768d	Inode: 100663375   Links: 1
Access: (0600/-rw-------)  Uid: ( 1000/ vagrant)   Gid: ( 1000/ vagrant)
Context: unconfined_u:object_r:user_tmp_t:s0
Access: 2018-03-26 16:42:58.845292755 +0000
Modify: 2018-03-26 16:42:57.797303125 +0000
Change: 2018-03-26 16:42:58.692294269 +0000
 Birth: -

When i do  vm one gets ip 192.168.121.100 as expected 
[vagrant@one network-scripts]$ sudo su
[root@one network-scripts]# ifup eth1 
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 52:54:00:e1:9b:0b brd ff:ff:ff:ff:ff:ff
    inet 192.168.121.160/24 brd 192.168.121.255 scope global dynamic eth0
       valid_lft 3210sec preferred_lft 3210sec
    inet6 fe80::5054:ff:fee1:9b0b/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 52:54:00:57:1b:2c brd ff:ff:ff:ff:ff:ff
    inet 192.168.121.100/24 brd 192.168.121.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fe57:1b2c/64 scope link 
       valid_lft forever preferred_lft forever

### Expected behaviour
Tell us what should happen
vagrant ssh one 
[root@one] ip a 
 ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 52:54:00:e1:9b:0b brd ff:ff:ff:ff:ff:ff
    inet 192.168.121.160/24 brd 192.168.121.255 scope global dynamic eth0
       valid_lft 3210sec preferred_lft 3210sec
    inet6 fe80::5054:ff:fee1:9b0b/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 52:54:00:57:1b:2c brd ff:ff:ff:ff:ff:ff
    inet 192.168.121.100/24 brd 192.168.121.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fe57:1b2c/64 scope link 
       valid_lft forever preferred_lft forever

### Actual behaviour
[vagrant@one ~]$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 52:54:00:e1:9b:0b brd ff:ff:ff:ff:ff:ff
    inet 192.168.121.160/24 brd 192.168.121.255 scope global dynamic eth0
       valid_lft 3407sec preferred_lft 3407sec
    inet6 fe80::5054:ff:fee1:9b0b/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN qlen 1000
    link/ether 52:54:00:57:1b:2c brd ff:ff:ff:ff:ff:ff

### System configuration
**OS/Distro version:**:
vm's 
[vagrant@one network-scripts]$ cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core)

Host system:
cat /etc/redhat-release 
Korora release 26 (Bloat)

**Libvirt version:**
libvirtd --version 
libvirtd (libvirt) 3.2.1

**Output of `vagrant version; vagrant plugin list`:**

 vagrant --version 
Vagrant 1.9.1

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**
DEBUG ssh: == Net-SSH connection debug-level log END ==
 INFO ssh: SSH is ready!
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute:  (sudo=false)
DEBUG ssh: Exit status: 0
 INFO wait_till_up: Time for SSH ready: 34.833014249801636
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::ForwardPorts:0x000055f78a2cb9b0>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::SetHostname:0x000055f78a266ce0>
 INFO warden: Calling IN action: #<Proc:0x000055f78a266c68@/usr/share/vagrant/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO warden: Calling IN action: #<VagrantPlugins::HostsUpdater::Action::UpdateHosts:0x000055f78a5b46b8>
 INFO interface: info: [vagrant-hostsupdater] Checking for host entries
 INFO interface: info: ==> two: [vagrant-hostsupdater] Checking for host entries
==> two: [vagrant-hostsupdater] Checking for host entries
 INFO interface: info: [vagrant-hostsupdater] Writing the following entries to (/etc/hosts)
 INFO interface: info: ==> two: [vagrant-hostsupdater] Writing the following entries to (/etc/hosts)
==> two: [vagrant-hostsupdater] Writing the following entries to (/etc/hosts)
 INFO interface: info: [vagrant-hostsupdater]   192.168.121.101  two.vagrant.box  # VAGRANT: 51d7f4038e383eb20fdf6f990a7ff22c (two) / bba66a10-18a4-4de2-ba20-30937a9e1b97
 INFO interface: info: ==> two: [vagrant-hostsupdater]   192.168.121.101  two.vagrant.box  # VAGRANT: 51d7f4038e383eb20fdf6f990a7ff22c (two) / bba66a10-18a4-4de2-ba20-30937a9e1b97
==> two: [vagrant-hostsupdater]   192.168.121.101  two.vagrant.box  # VAGRANT: 51d7f4038e383eb20fdf6f990a7ff22c (two) / bba66a10-18a4-4de2-ba20-30937a9e1b97
 INFO interface: info: [vagrant-hostsupdater] This operation requires administrative access. You may skip it by manually adding equivalent entries to the hosts file.
 INFO interface: info: ==> two: [vagrant-hostsupdater] This operation requires administrative access. You may skip it by manually adding equivalent entries to the hosts file.
==> two: [vagrant-hostsupdater] This operation requires administrative access. You may skip it by manually adding equivalent entries to the hosts file.
 INFO warden: Calling OUT action: #<VagrantPlugins::HostsUpdater::Action::UpdateHosts:0x000055f78a5b46b8>
 INFO warden: Calling OUT action: #<Proc:0x000055f78a266c68@/usr/share/vagrant/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO interface: info: Setting hostname...
 INFO interface: info: ==> two: Setting hostname...
==> two: Setting hostname...
DEBUG ssh: Checking whether SSH is ready...
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute:  (sudo=false)
DEBUG ssh: Re-using SSH connection.
 INFO ssh: SSH is ready!
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute:  (sudo=false)
DEBUG ssh: Exit status: 0
 INFO wait_till_up: Time for SSH ready: 35.21959400177002
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::ForwardPorts:0x000055f78a51e0a0>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::SetHostname:0x000055f78a4c3c40>
 INFO warden: Calling IN action: #<Proc:0x000055f78a4c3bc8@/usr/share/vagrant/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO warden: Calling IN action: #<VagrantPlugins::HostsUpdater::Action::UpdateHosts:0x000055f78a92f0b8>
 INFO interface: info: [vagrant-hostsupdater] Checking for host entries
 INFO interface: info: ==> one: [vagrant-hostsupdater] Checking for host entries
==> one: [vagrant-hostsupdater] Checking for host entries
 INFO interface: info: [vagrant-hostsupdater] Writing the following entries to (/etc/hosts)
 INFO interface: info: ==> one: [vagrant-hostsupdater] Writing the following entries to (/etc/hosts)
==> one: [vagrant-hostsupdater] Writing the following entries to (/etc/hosts)
 INFO interface: info: [vagrant-hostsupdater]   192.168.121.100  one.vagrant.box  # VAGRANT: e6e371b9651b7d04614f4f2b5d1e7fbf (one) / a1658e85-f8b2-4e02-952f-9076a5e975b9
 INFO interface: info: ==> one: [vagrant-hostsupdater]   192.168.121.100  one.vagrant.box  # VAGRANT: e6e371b9651b7d04614f4f2b5d1e7fbf (one) / a1658e85-f8b2-4e02-952f-9076a5e975b9
==> one: [vagrant-hostsupdater]   192.168.121.100  one.vagrant.box  # VAGRANT: e6e371b9651b7d04614f4f2b5d1e7fbf (one) / a1658e85-f8b2-4e02-952f-9076a5e975b9
 INFO interface: info: [vagrant-hostsupdater] This operation requires administrative access. You may skip it by manually adding equivalent entries to the hosts file.
 INFO interface: info: ==> one: [vagrant-hostsupdater] This operation requires administrative access. You may skip it by manually adding equivalent entries to the hosts file.
==> one: [vagrant-hostsupdater] This operation requires administrative access. You may skip it by manually adding equivalent entries to the hosts file.
 INFO warden: Calling OUT action: #<VagrantPlugins::HostsUpdater::Action::UpdateHosts:0x000055f78a92f0b8>
 INFO warden: Calling OUT action: #<Proc:0x000055f78a4c3bc8@/usr/share/vagrant/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO interface: info: Setting hostname...
 INFO interface: info: ==> one: Setting hostname...

**A Vagrantfile to reproduce the issue:**
# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  
config.vm.define :one do |one|
one.vm.box = "centos/7"
one.vm.box_check_update = false
one.vm.network  "forwarded_port", guest: 80, host: 8080
one.vm.network  "private_network", ip: "192.168.121.100"
   one.vm.hostname = "one.vagrant.box"
  # config.vm.network "public_network"
  # config.vm.synced_folder "../data", "/vagrant_data"
config.vm.provider :libvirt do |libvirt|
	  libvirt.uri = "qemu:///system"
          libvirt.connect_via_ssh = false     # also needed
          libvirt.username = "root"
          libvirt.storage_pool_name = "default"
          libvirt.memory = "420"
          libvirt.driver = "kvm"
end 
end

     config.vm.define :two do |two|
     two.vm.box = "centos/7"
     two.vm.box_check_update = false
     two.vm.network   "forwarded_port", guest: 80, host: 8081
     two.vm.network  "private_network", ip: "192.168.121.101"
     two.vm.hostname = "two.vagrant.box"

   config.vm.provider :libvirt do |libvirt|
	  libvirt.uri = "qemu:///system"
          libvirt.connect_via_ssh = false     # also needed
          libvirt.username = "root"
          libvirt.storage_pool_name = "default"
          libvirt.memory = "420"
          libvirt.driver = "kvm"
end 
end 
end

```

**Are you using upstream vagrant package or your distros package?**
Upstream / Distro
yes

**Comment by electrofelix** [comment]
Sorry for the long delay in someone commenting.

Unfortunately this is due to vagrant itself, as it is what configures the network interfaces within each guest rather than vagrant-libvirt. I'm guessing at the time there was some bug in how it created the config files and executed them to update the networks within the guests.

If it's still an issue, you'll have to log it with vagrant itself.
