### ISSUE TITLE
Example of how to add block devices to vagrant-libvirt configuration

### ISSUE THREAD

**Issue by spease** [vagrant-libvirt/vagrant-libvirt#879]
Currently I'm using vagrant-host-shell to run
```
config.vm.provision :host_shell do |host_shell|
  host_shell.inline = "sudo virsh attach-disk VM_NAME /dev/sdX"
end
```

Is there a way to do this more elegantly with vagrant-libvirt?

**Comment by windowsrefund** [comment]
I'm wondering the same thing but thought I'd provide the correct syntax in the event anyone needs this work-around
```
config.vm.provision :host_shell do |host_shell|
  host_shell.inline = "sudo virsh attach-disk VM_NAME /dev/sdX vdb"
end
```
The VM will now have /dev/sdX from the host available as /dev/vdb

**Comment by electrofelix** [comment]
I believe a solution for #246 and maybe #690 would resolve this as it would allow connecting different storage types. Until then, general hackier will be required. You could maybe use vagrant triggers to help coordinate doing the attach/detach operations. Maybe some of the discussion in #1250 might also be useful for this scenario.

Going to close this in favour of the others as I think a solution covering one or more of them will solve this.

**Comment by windowsrefund** [comment]
Yep, just discovered triggers. This is a better approach than using the host_shell plugin since actions can be defined before and after various stages of the workflow. For example, I've got 3 disks setup with persistent names via udev rules. Each already contains a single formatted partition. Each of the nodes in the block below will use 1 of these partitions. I can now do this:

```
(1..3).each do |i|
  config.vm.define "kworker#{i}" do |node|
  ...
    node.trigger.after :up do |trigger|
      trigger.info = "Attach /dev/toshiba#{i}1"
      trigger.run = {inline: "virsh attach-disk kvm_kworker#{i} /dev/toshiba#{i}1 vdb"}
    end

    node.trigger.before :destroy do |trigger|
      trigger.info = "Detach /dev/toshiba#{i}1"
      trigger.run = {inline: "virsh detach-disk kvm_kworker#{i} vdb"}
    end
  end
end
```
