### ISSUE TITLE
vm metada not deleting after running `vagrant destroy`

### ISSUE THREAD

**Issue by jlozadad** [vagrant-libvirt/vagrant-libvirt#880]
### Steps to reproduce
1. download https://github.com/ANXS/postgresql
2. do `vagrant up` and wait for provision to finish. Then do `vagrant destroy`
3. Get error:
```
vagrant up --provider=libvirt
Bringing machine 'anxs' up with 'libvirt' provider...
==> anxs: Box 'centos/7' could not be found. Attempting to find and install...
    anxs: Box Provider: libvirt
    anxs: Box Version: >= 0
==> anxs: Loading metadata for box 'centos/7'
    anxs: URL: https://vagrantcloud.com/centos/7
==> anxs: Adding box 'centos/7' (v1802.01) for provider: libvirt
    anxs: Downloading: https://vagrantcloud.com/centos/boxes/7/versions/1802.01/providers/libvirt.box
    anxs: Download redirected to host: cloud.centos.org
==> anxs: Successfully added box 'centos/7' (v1802.01) for 'libvirt'!
==> anxs: Creating image (snapshot of base box volume).
Volume for domain is already created. Please run 'vagrant destroy' first.
```

### Expected behaviour
should start a new vm and not give the error.

### Actual behaviour
get this error:
```
Volume for domain is already created. Please run 'vagrant destroy' first. 
I have to go under ~/.vagrant.d/boxes and delete  them in there and also in ~/.vagrant.d/data/machine-index/*
```
### System configuration
**OS/Distro version:**: `Fedora 27`

**Libvirt version:`libvirt-3.7.0-4.fc27.x86_64 `

**Output of `vagrant version; vagrant plugin list`:**
2.0.3
vagrant-libvirt (0.0.43)
vagrant-mutate (1.2.0)

**Output of `vagrant-libvirt (0.0.43)
vagrant-mutate (1.2.0)
`**
```
https://pastebin.com/zRKkMsKe
```

**A Vagrantfile to reproduce the issue:**
https://github.com/ANXS/postgresql/blob/master/Vagrantfile
```
Insert Vagrantfile inside quotes here (remove sensitive data if needed)
```

**Are you using upstream vagrant package or your distros package?**
Upstream

**Comment by electrofelix** [comment]
I can't reproduce this with a recent vagrant-libvirt, and I also haven't seen this come up before where after destroy you can't create expect where the destroy failed with an exception. So I'm going to assume that either there was some unusual state, or we've managed to fix the underlying issue somewhere along the way.
