### ISSUE TITLE
USB Redirection option not available in guest

### ISSUE THREAD

**Issue by ju2wheels** [vagrant-libvirt/vagrant-libvirt#892]
### Steps to reproduce
1. Create Ubuntu Server Packer image
2. Start Packer image using vagrant-lib with attached usb via section like:
```
ansible_test.vm.provider :libvirt do |libvirt|
    libvirt.channel target_name: 'com.redhat.spice.0', target_type: 'virtio', type: 'spicevmc'
    (1..2).each do
        libvirt.redirdev type: 'spicevmc'
    end
    libvirt.redirfilter allow: 'yes', product: '0x' + VAGRANT_USB_PRODUCT_ID, vendor: '0x' + VAGRANT_USB_VENDOR_ID
end
```

### Expected behaviour
The attached USB device should be viewable via lsusb.

### Actual behaviour
No device is listed.

### System configuration
**OS/Distro version:**:
Ubuntu 16.04

**Libvirt version:**
1.3.1

**Output of `vagrant version; vagrant plugin list`:**
vagrant version;vagrant plugin list
Installed Version: 2.1.1
Latest Version: 2.1.1
 
You're running an up-to-date version of Vagrant!
vagrant-libvirt (0.0.43)

**Are you using upstream vagrant package or your distros package?**
Upstream

Other:

I know this is not a provider issue, but im trying to understand what vagrant-libvirt/libvirt in general require in the guest in order for USB redirection option to work. Im certain its not a provider issue because I manually created a Ubuntu server instance with virt-manager in similar manner to the preseed Packer generated one, and the manually created instance has the option to 'Redirect USB Device' from the virt-manager menu, but the Packer created one does not. I believe this is why my device isnt being redirected in but the README doesnt state whats required in the guest for USB redirection to work.

Can you shed any light on what functionality in the guest is required for USB redirection to work? Whether its a particular package or other system configuraiton?

**Comment by ju2wheels** [comment]
Ok, I determined its not my Packer instance and how it was setup at all, but rather that the USB Redirection option is not available without a spice server and the only way to get that is to set the graphics type to spice. Once I did that, then the 'Redirect USB Device' option on the virt-manager menu becomes available to redirect a USB device.

Now the only problem I am having is that the USB device is not automatically redirected into the instance unless I manually do it from the menu despite the fact that I have the redirect filter listed above.

I have tried libvirt.usb but that does nothing (I suspect it may be due to the apparmor errors I am getting on Ubuntu 16.04 host but I am not sure).

**Comment by ju2wheels** [comment]
I guess my only option for now is to attach the device using this method:

https://stackoverflow.com/questions/28913978/can-not-attach-usb-device-using-virsh

Any chance we can get the redir to automatically do this?

**Comment by ju2wheels** [comment]
OK so Ive found that the `libvirt.usb` method generates apparmor errors similar to this on Ubuntu 16.04:

```
[145094.563996] audit: type=1400 audit(1525882457.360:1634): apparmor="DENIED" operation="open" profile="libvirt-de40bc0e-7c1e-44e1-b61d-29aa9801a8dc" name="/run/udev/data/+usb:1-1.4:1.1" pid=11029 comm="qemu-system-x86" requested_mask="r" denied_mask="r" fsuid=64055 ouid=0
[145094.564109] audit: type=1400 audit(1525882457.360:1635): apparmor="DENIED" operation="open" profile="libvirt-de40bc0e-7c1e-44e1-b61d-29aa9801a8dc" name="/run/udev/data/+usb:1-1.2:1.0" pid=11029 comm="qemu-system-x86" requested_mask="r" denied_mask="r" fsuid=64055 ouid=0
[145094.564158] audit: type=1400 audit(1525882457.360:1636): apparmor="DENIED" operation="open" profile="libvirt-de40bc0e-7c1e-44e1-b61d-29aa9801a8dc" name="/run/udev/data/+usb:1-6:1.0" pid=11029 comm="qemu-system-x86" requested_mask="r" denied_mask="r" fsuid=64055 ouid=0
[145094.564207] audit: type=1400 audit(1525882457.360:1637): apparmor="DENIED" operation="open" profile="libvirt-de40bc0e-7c1e-44e1-b61d-29aa9801a8dc" name="/run/udev/data/+usb:2-1:1.0" pid=11029 comm="qemu-system-x86" requested_mask="r" denied_mask="r" fsuid=64055 ouid=0
[145094.564257] audit: type=1400 audit(1525882457.361:1638): apparmor="DENIED" operation="open" profile="libvirt-de40bc0e-7c1e-44e1-b61d-29aa9801a8dc" name="/run/udev/data/c189:129" pid=11029 comm="qemu-system-x86" requested_mask="r" denied_mask="r" fsuid=64055 ouid=0
[145094.564305] audit: type=1400 audit(1525882457.361:1639): apparmor="DENIED" operation="open" profile="libvirt-de40bc0e-7c1e-44e1-b61d-29aa9801a8dc" name="/run/udev/data/c189:7" pid=11029 comm="qemu-system-x86" requested_mask="r" denied_mask="r" fsuid=64055 ouid=0
```

I found some Apparmor rules in the upstream [libvirt repo](https://github.com/libvirt/libvirt/blob/master/examples/apparmor/libvirt-qemu#L40) that made those errors go away, in particular:

```
# libusb needs udev data about usb devices (~equal to content of lsusb -v)
  /run/udev/data/c16[6,7]* r,
  /run/udev/data/c18[0,8,9]* r,
  /run/udev/data/+usb* r,
```
Unfortunately, even with that, the USB device wont show up inside the instance. So now im in the position where doing USB passthrough with the above rules no longer throws apparmor errors, but its behavior is the same as USB redirected over spice where neither seems to want to automatically attach the USB device into the instance so its available when the instance boots.

**Comment by davidscaife** [comment]
Have you seen it show up in the VM at all, or is it just automatic redirection that isn't working? Depending on what USB device you're attaching, you may need to use the `libvirt.usb_controller` option to enable USB2/USB3 device usage. The default configuration only has a USB 1 controller. (The virt-manager default configuration, on the other hand, uses `nec-xhci` for its controller last time I checked, which allows USB 3, so this could be a difference worth looking into.)

**Comment by davidscaife** [comment]
A mate ran into a similar issue and pointed me to #729 which is likely also related, given that you're using "redirfilter" here. The redirfilter property is currently broken as discussed in that issue. I've thrown up a PR at #909 to address it.

**Comment by ju2wheels** [comment]
Thought I had replied to this, sorry for delay. It only affects automatic redirection, it does show up in the VM when done manually once it boots.

Ill give that patch a go once the PR is merged.

Thanks,

**Comment by ju2wheels** [comment]
OK good news and bad news after testing 0.0.45 on my machine. Basically, #909 does exactly what it says it should do, except unless im missing something its not at all what I expected.

So the USB redirect filter is not actually activating/selecting the USB devices you specify for passthrough, its merely limiting/filtering the list of selectable USB devices as seen from the picture below now that #909 is merged and working properly:

![screenshot from 2018-10-26 13-41-45](https://user-images.githubusercontent.com/396211/47584172-78e49b80-d927-11e8-84bb-c4ddea660b1b.png)

So the grayed out unselectable items werent that way before #909 because the redirfilter wasnt working correctly, but now that it is, all it seems to do is limit the list. How do we actually get it to select an item as well so that we dont have to do that step manually?

**Comment by davidscaife** [comment]
Hmm. Having played a bit more with the various forms of USB redirection over the past months, it seems to me that the only way to get a USB to attach to the box on boot via the Vagrantfile is by using `libvirt.usb`. Did you try using this in conjunction with `libvirt.usb_controller`?

Spice redirection is more targeted at hot-plugging, since you need a client like virt-viewer or virt-manager to do the actual redirection (and once you close the viewer, your USB will detach with it). It's a completely separate mechanism to the `libvirt.usb` option, which lasts for the lifetime of the VM. Also, Spice doesn't seem to need the `libvirt.usb_controller` parameter (in case you're wondering why it might be needed for `libvirt.usb` when you're already able to connect a USB through the viewer).

I guess to sum up, please (re)try the `libvirt.usb`/`libvirt.usb_controller` combo. If that fails (and it really shouldn't, this is what it's for...), the only other workarounds I have are to "script" it, either by using  `virsh attach-device` (requires `libvirt.usb_controller`) or using e.g. `virt-viewer --spice-usbredir-redirect-on-connect=...` (requires spice)

**Comment by ju2wheels** [comment]
@davidscaife OK, ill give that a go next week.

Appreciate the input,
Thanks

**Comment by ju2wheels** [comment]
Closing. The explicit usb controller and .usb passthrough worked for me now.

Thanks @davidscaife
