### ISSUE TITLE
vagrant package creates a box that once added consumes large disk space

### ISSUE THREAD

**Issue by emorrp1** [vagrant-libvirt/vagrant-libvirt#896]
Probably related to #111, but this appears to be a different stage in the process. To reclaim space in my home directory, I had to manually resize the QCOW box.img:

    qemu-img create -f qcow2 -o preallocation=metadata box.img 10G
    virt-resize ~/.vagrant.d/boxes/unstable/0/libvirt/box.img box.img

### Steps to reproduce
1. vagrant up
2. vagrant provision
3. vagrant halt
4. vagrant package --output unstable.box
5. vagrant box add --name unstable unstable.box

### Expected behaviour
```
-rw-r--r-- 1 emorrp1 emorrp1 386M May 30 21:14 unstable.box
386M	unstable.box
-rw-r--r-- 1 emorrp1 emorrp1 11G May 30 21:53 ~/.vagrant.d/boxes/unstable/0/libvirt/box.img
1.2G		~/.vagrant.d/boxes/unstable/0/libvirt/box.img
```

### Actual behaviour
```
-rw-r--r-- 1 emorrp1 emorrp1 386M May 30 21:14 unstable.box
386M	unstable.box
-rw-r--r-- 1 emorrp1 emorrp1 9.2G May 30 21:53 ~/.vagrant.d/boxes/unstable/0/libvirt/box.img
9.2G		~/.vagrant.d/boxes/unstable/0/libvirt/box.img
```

### System configuration
**OS/Distro version:**:
Debian Stretch

**Libvirt version:**
3.0.0-4+deb9u3

**Output of `vagrant version; vagrant plugin list`:**
Installed Version: 1.9.1
vagrant-libvirt (0.0.37, system)
vagrant-mutate (1.2.0, system)

**A Vagrantfile to reproduce the issue:**
```
$upgrade = <<-EOF
        sed --in-place s/stretch/unstable/ /etc/apt/sources.list /etc/hostname /etc/hosts
        apt update
        apt full-upgrade --assume-yes
        apt autoremove --assume-yes
        apt clean
        dd if=/dev/zero of=/EMPTY bs=1M || true
        rm --force /EMPTY
EOF

Vagrant.configure('2') do |config|
  config.vm.box = 'debian/stretch64'
  config.vm.provision :shell, inline: $upgrade
end
```

**Are you using upstream vagrant package or your distros package?**
Distro

**Comment by electrofelix** [comment]
#1195 fixed this by adding use of virt-sparsify during the packaging, sorry hadn't spotted the related issue at the time it was merged. Should be available since the 0.4.0 release.
