### ISSUE TITLE
Question: Is there a way to forgo the 'sudo' prompt when using NFS

### ISSUE THREAD

**Issue by nickgarber** [vagrant-libvirt/vagrant-libvirt#897]
### Expected behaviour

Ideally, the documentation (with all appropriate warnings) would mention some work-around to skip the sudo prompts. The end-user could then decide if this is a reasonable to make in their case.

In my case I think I'd be OK with it because it would make the creation of VMs via vagrant more of a push-button operation. (Though this of course depends on how gnarly the work-around is.)

### Actual behaviour
`sudo` prompt for each instantiation of each VM. 
This is more of a papercut than a functionality problem but it would be a big usability improvement for me if there were a way around it.

I appreciate that it's possible to set the windows to a longer time, but I wonder if there's a more granular approach. For example is there a command that vagrant-libvirt uses, that I could add to sudo file to simply allow it to succeed without the prompts?

Thanks for the project. `vagrant-libvirt` on linux makes for the the _best_ vagrant experience available IMO. 

### System configuration
**OS/Distro version:**: 
CentOS 7

**Libvirt version:**
vagrant-libvirt (0.0.43)
**Output of `vagrant version; vagrant plugin list`:**

```
Installed Version: 2.0.0
Latest Version: 2.1.1

To upgrade to the latest version, visit the downloads page and
download and install the latest version of Vagrant from the URL
below:

  https://www.vagrantup.com/downloads.html

If you're curious what changed in the latest release, view the
CHANGELOG below:

  https://github.com/mitchellh/vagrant/blob/v2.1.1/CHANGELOG.md
landrush (1.2.0)
  - Version Constraint: > 0
vagrant-libvirt (0.0.43)
  - Version Constraint: > 0
vagrant-share (1.1.9, system)
  - Version Constraint: > 0
vagrant-triggers (0.5.3)
  - Version Constraint: > 0
```

**Are you using upstream vagrant package or your distros package?**
_Upstream_ (RPM installed from https://www.vagrantup.com/downloads.html )

**Comment by dabreese00** [comment]
I don't know if this is related to anything libvirt-specific.  It looks like the section "Root Privilege Requirement" on [this page](https://www.vagrantup.com/docs/synced-folders/nfs.html) might be of interest to you.  If I'm reading right, it seems to give the type of work-around you're looking for.

**Comment by nickgarber** [comment]
Yup, that sure looks like what I'm asking for! Thanks for the helping hand  👍
