### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by qazokm** [vagrant-libvirt/vagrant-libvirt#898]
Given the last release was 5 months ago, would it be possible to get a new release sometime soon?

**Comment by mulmschneider** [comment]
Wondering the same - my vagrant box requires https://github.com/vagrant-libvirt/vagrant-libvirt/pull/869 .
Anything we can do to help get a release made?

**Comment by mxl** [comment]
Guys, please make a new release.

**Comment by kromanow94** [comment]
I'd like that too.

**Comment by syndbg** [comment]
I think this can be closed since https://github.com/vagrant-libvirt/vagrant-libvirt/releases is more up-to-date nowadays.
