### ISSUE TITLE
Unable to connect vagrant VM from my laptop 

### ISSUE THREAD

**Issue by ghost** [vagrant-libvirt/vagrant-libvirt#904]
Issue: 
From my MacBook, I can't connect to the VMs in the Vagrant. Not sure ... what did do wrong :( 

kylix3511-My-MacBook$vagrant --version 
Vagrant 2.1.2
kylix3511-My-MacBook$

Following is the vagrant VM Details 

vagrant@ansiblec:/home/vagrant$ssh ansiblec
Last login: Mon Jul 30 11:31:55 2018 from 10.0.2.2
vagrant@ansiblec:/home/vagrant$ifconfig 
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.2.15  netmask 255.255.255.0  broadcast 10.0.2.255
        ether 08:00:27:0f:ad:8c  txqueuelen 1000  (Ethernet)
        RX packets 6201  bytes 5176863 (4.9 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2250  bytes 324295 (316.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.56.100  netmask 255.255.255.0  broadcast 192.168.56.255
        inet6 fe80::a00:27ff:fe65:cbf4  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:65:cb:f4  txqueuelen 1000  (Ethernet)
        RX packets 2  bytes 120 (120.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 678 (678.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 90  bytes 12910 (12.6 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 90  bytes 12910 (12.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vagrant@ansiblec:/home/vagrant$route 
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         gateway         0.0.0.0         UG    100    0        0 eth0
10.0.2.0        0.0.0.0         255.255.255.0   U     100    0        0 eth0
192.168.56.0    0.0.0.0         255.255.255.0   U     101    0        0 eth1
vagrant@ansiblec:/home/vagrant$

This is the ssh failure details: 

kylix3511-My-MacBook~> ssh -vvv vagrant@10.0.2.15
OpenSSH_7.6p1, LibreSSL 2.6.2
debug1: Reading configuration data /Users/kylix3511/.ssh/config
debug1: /Users/kylix3511/.ssh/config line 2: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 48: Applying options for *
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to 10.0.2.15 port 22.
^C⏎
kylix3511-My-MacBook~> ssh -vvv vagrant@192.168.56.100
OpenSSH_7.6p1, LibreSSL 2.6.2
debug1: Reading configuration data /Users/kylix3511/.ssh/config
debug1: /Users/kylix3511/.ssh/config line 2: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 48: Applying options for *
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to 192.168.56.100 port 22.
^C⏎
kylix3511-My-MacBook~>

**Comment by electrofelix** [comment]
@kylix3511 please include your `Vagrantfile` and the output from bringing it up. I'd usually recommend looking at the local firewall to make sure that connections are allowed to `10.0.2.0/255.255.255.0` and `192.168.56.0/255.255.255.0`, and maybe turn it into a debug mode to see what connections are attempted on these addresses spaces.

**Comment by electrofelix** [comment]
Closing as no further response.
