### ISSUE TITLE
Update dependency on fog-core to 2.1.0?

### ISSUE THREAD

**Issue by johanneskastl** [vagrant-libvirt/vagrant-libvirt#905]
Hi all,

currently there is a dependency for fog-core in an older version:
> ~> 1.43.0

[https://github.com/vagrant-libvirt/vagrant-libvirt/blob/master/vagrant-libvirt.gemspec#L33](https://github.com/vagrant-libvirt/vagrant-libvirt/blob/master/vagrant-libvirt.gemspec#L33)
[https://github.com/vagrant-libvirt/vagrant-libvirt/blob/master/vagrant-libvirt.gemspec#L41](https://github.com/vagrant-libvirt/vagrant-libvirt/blob/master/vagrant-libvirt.gemspec#L41)
[https://github.com/vagrant-libvirt/vagrant-libvirt/blob/master/vagrant-libvirt.gemspec#L50](https://github.com/vagrant-libvirt/vagrant-libvirt/blob/master/vagrant-libvirt.gemspec#L50)

Current version of fog-core is 2.1.0, which is not allowed due to the pessimistic dependency. Could this be updated to something recent? Release 2.0.0 of fog-core is from January 2018. Or could this be rewritten to at least allow version bigger than 1.43?

Kind Regards,
Johannes

**Comment by electrofelix** [comment]
Looks like this will be solved by #970
