### ISSUE TITLE
instll error 

### ISSUE THREAD

**Issue by qth1991** [vagrant-libvirt/vagrant-libvirt#910]
my OS is  CentOS7.3 x64, and vagrant version is 2.1.2 
![default](https://user-images.githubusercontent.com/39185602/44127554-686be834-a070-11e8-92fc-e47f9ffd390a.png)

**Comment by electrofelix** [comment]
@qth1991 This says  that vagrant is having problems connecting to https://gems.hashicorp.com which suggests either proxy or firewall issues, you need to fix your environment as the error message suggests, and we can't help you there.
