### ISSUE TITLE
error

### ISSUE THREAD

**Issue by qth1991** [vagrant-libvirt/vagrant-libvirt#912]
![tim 20180816211905](https://user-images.githubusercontent.com/39185602/44210999-7c76dc00-a19a-11e8-939d-b7e68926b66d.png)

**Comment by electrofelix** [comment]
@qth1991 please include all of the information as mentioned in the new issue template, otherwise we'll just have to close this.

**Comment by electrofelix** [comment]
Don't know how to reproduce, and no subsequent info provided so closing.
