### ISSUE TITLE
SCSI disk not visible as block device (centos 7.3 and higher)

### ISSUE THREAD

**Issue by rmestrum** [vagrant-libvirt/vagrant-libvirt#917]
The scsi disk 1 add to the VM using this plugin are not visible in de guest OS as block devices.
Normal virtio disk are visible after adding. 
Rebooting the vm does not solve te problem. Removing the hardware and readding the same device (using the already avaible image file) manually as scsi device, the disk is available as block device.

### Steps to reproduce
1.  server.vm.provider :libvirt do |libvirt|
        libvirt.storage :file, :size => '10M'
        libvirt.storage :file, :size => '20M', :bus => 'scsi'
        libvirt.storage :file, :size => '30M', :cache => 'unsafe', :bus => 'scsi'
    end
2.` vagrant up `
3.` fdisk -l | grep dev` (on the guest os)

### Expected behaviour
The scsi disk is available as block device in the guest OS

### Actual behaviour
The scsi disk is NOT available as block device in the guest OS

### System configuration
**OS/Distro version:**:
Host OS: Fedora 26
Guest OS: Centos 7.3 and higher (with rhel 6.9 there are no problems)

**Libvirt version:**
3.2.1

**Output of `vagrant version; vagrant plugin list`:**
11:06 $ vagrant version; vagrant plugin list
Installed Version: 2.1.2
Latest Version: 2.1.4
 
To upgrade to the latest version, visit the downloads page and
download and install the latest version of Vagrant from the URL
below:

  https://www.vagrantup.com/downloads.html

If you're curious what changed in the latest release, view the
CHANGELOG below:

  https://github.com/hashicorp/vagrant/blob/v2.1.4/CHANGELOG.md
vagrant-hostmanager (1.8.9)
vagrant-librarian-puppet (0.6.0)
vagrant-libvirt (0.0.43)
vagrant-puppet-install (5.0.0)
vagrant-share (1.1.9)

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**
```
Insert debug output inside quotes here (replace ... with whatever command you use to trigger the issue)
```

**A Vagrantfile to reproduce the issue:**
```
Insert Vagrantfile inside quotes here (remove sensitive data if needed)
```

**Are you using upstream vagrant package or your distros package?**
Upstream

**Comment by electrofelix** [comment]
We are using scsi locally without any issues in the device showing up. If this works with RHEL 6.9 and fails with a newer client, then it's highly unlikely an issue with vagrant-libvirt or even libvirt, but more likely an issue with your image not containing or loading the correct kernel modules. Similarly suggested by https://unix.stackexchange.com/questions/234928/scsi-disk-not-shown-up-during-rhel7-os-installation/234933#234933

**Comment by rmestrum** [comment]
Yes that is true. But when add the disks manually the are recognized.
I noticed that the disks that are added manually are using the virtio-scsi controller instead of the standard scsi controller the plugin is using.
