### ISSUE TITLE
Readme link to Atlas no longer available

### ISSUE THREAD

**Issue by heyakyra** [vagrant-libvirt/vagrant-libvirt#918]
The readme says: 

> You can find more libvirt ready boxes at [Atlas](https://atlas.hashicorp.com/boxes/search?provider=libvirt). 

But that link redirects to terraform now.  

### Steps to reproduce
1. Read the Readme
2. Find the link to Atlas
3. Follow it

### Expected behaviour
Find [more libvirt ready boxes](https://app.vagrantup.com/boxes/search?provider=libvirt)! 

### Actual behaviour
redirected to [404 not found on app.terraform.io](https://app.terraform.io/boxes/search?provider=libvirt)

### System configuration
**OS/Distro version:**:

**Libvirt version:**

**Output of `vagrant version; vagrant plugin list`:**

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**
```
Insert debug output inside quotes here (replace ... with whatever command you use to trigger the issue)
```

**A Vagrantfile to reproduce the issue:**
```
Insert Vagrantfile inside quotes here (remove sensitive data if needed)
```

**Are you using upstream vagrant package or your distros package?**
Upstream / Distro

**Comment by electrofelix** [comment]
#971 fixed this.
