### ISSUE TITLE
The vagrant-libvirt plugin is required. Please install it with:

### ISSUE THREAD

**Issue by rkitindi** [vagrant-libvirt/vagrant-libvirt#919]
### Steps to reproduce
1. The vagrant-libvirt plugin is required. Please install it with: vagrant plugin install vagrant-libvirt

2. We are installing vagarant-libvirt

Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Installed the plugin 'vagrant-libvirt (0.0.43)'!

3. We are trying to start VM with vagarant  up, same message is coming back
The vagrant-libvirt plugin is required. Please install it with:
$ vagrant plugin install vagrant-libvirt

### Expected behaviour
After installing vagarant-libvirt, we should be able to start VM

### Actual behaviour
We keep receiving message "The vagrant-libvirt plugin is required. Please install it with:"

### System configuration
**OS/Distro version:**:

**Libvirt version:** 1.3.1

**Output of `vagrant version; vagrant plugin list`:**
The vagrant-libvirt plugin is required. Please install it with:
$ vagrant plugin install vagrant-libvirt
vagrant-libvirt (0.0.43, global)
vagrant-mutate (1.2.0, global)

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**
```
Insert debug output inside quotes here (replace ... with whatever command you use to trigger the issue)
```

**A Vagrantfile to reproduce the issue:**
```
Insert Vagrantfile inside quotes here (remove sensitive data if needed)
```

**Are you using upstream vagrant package or your distros package?**
Upstream / Distro

**Comment by electrofelix** [comment]
The debug output doesn't show it emitting the error message you reported, can you reproduce this?

**Comment by electrofelix** [comment]
Assuming no longer occuring.
