### ISSUE TITLE
How to add kernel option to Vagrantfile

### ISSUE THREAD

**Issue by Helenbj** [vagrant-libvirt/vagrant-libvirt#920]
When I run vagrant up --provider libvirt, I have problem

> Call to virDomainCreateWithFlags failed: internal error: process exited while connecting to monitor: 2018-09-12T11:32:25.240178Z qemu-system-x86_64: -append only allowed with -kernel option

I want to ask how to add kernel option to Vagrantfile, as you list in README.md 

> kernel - To launch the guest with a kernel residing on host filesystems. Equivalent to qemu -kernel.

I cannot get the possible values can be set for kernel option.

**Comment by davidscaife** [comment]
The kernel option would be expecting a path to a kernel binary, but I suspect there may be something else going on here. The error seems familiar (though I don't recall when I've encountered it), and it's relatively rare that you'd need to specify a path to the kernel on the host - it's more likely to be an issue with the configuration. Can you post your Vagrantfile?

**Comment by electrofelix** [comment]
Sorry it's taken so long to follow up on this.

The values should be as what is show at https://libvirt.org/formatdomain.html#direct-kernel-boot.

I'll try to run a test locally soon to check that a basic example works.
