### ISSUE TITLE
Cleanup leftover libvirt entries

### ISSUE THREAD

**Issue by mcandre** [vagrant-libvirt/vagrant-libvirt#933]
When a libvirt-backed Vagrant box is destroyed with `vagrant destroy`, libvirt continues to keep around a bunch of hefty files and pools and whatnot.

Is there a way that vagrant-libvirt could add a hook to `vagrant destroy` to cleanup more of these entries? Or could there be at least a `vagrant libvirt clean` command offered for users to automate this operation?

**Comment by electrofelix** [comment]
I think this is covered by #85, technically I think it's possible, just a fair amount of work as also need to solve a some issues around locking to ensure not removing stuff that was just added or needed by another machine.

Probably better to keep everything in the same issue though.
