### ISSUE TITLE
Taking snapshots using virt-manager

### ISSUE THREAD

**Issue by evopen** [vagrant-libvirt/vagrant-libvirt#936]
### System configuration
**OS/Distro version:**: 
Manjaro
kernel 4.19

**Libvirt version:**
0.0.45

Hello. 
I'm wondering that there is no mention of taking snapshot via virt-manager since sahara is not a very good solution. Is it recommended? 
I got `==> default: Error when updating domain settings: Call to virDomainUndefineFlags failed: Requested operation is not valid: cannot delete inacti
ve domain with 1 snapshots` when my img has some internal snapshots in it.

**Comment by SH4RKNANDO** [comment]
same problem with vagrant and vangrat-libvirt plugin

**Comment by ekeyme** [comment]
> ### System configuration
> 
> **OS/Distro version:**: Manjaro kernel 4.19
> 
> **Libvirt version:** 0.0.45
> 
> Hello. I'm wondering that there is no mention of taking snapshot via virt-manager since sahara is not a very good solution. Is it recommended? I got `==> default: Error when updating domain settings: Call to virDomainUndefineFlags failed: Requested operation is not valid: cannot delete inacti ve domain with 1 snapshots` when my img has some internal snapshots in it.

I have the same problem on ubuntu 2004(focal):

- OS/Distro version: ubuntu 2004
- Kernel: 5.4.0-100-generic
- Vagrant 2.2.19
- vagrant-libvirt version: vagrant-libvirt (0.7.0, global)
- libvirt: libvirtd (libvirt) 6.0.0
- ruby-libvirt: 0.8.0
