### ISSUE TITLE
boot option ignored

### ISSUE THREAD

**Issue by hightoxicity** [vagrant-libvirt/vagrant-libvirt#937]
### Steps to reproduce
1.https://github.com/hightoxicity/k8s-prodgrade-lab/tree/feat-libvirt-ipxeboot-withdisk

Having:
https://github.com/hightoxicity/k8s-prodgrade-lab/blob/feat-libvirt-ipxeboot-withdisk/Vagrantfile#L240

Here is what we get for concerned machines:

```
   <os>
    <type arch='x86_64' machine='pc-i440fx-xenial'>hvm</type>
    <boot dev='hd'/>
  </os>
```

### Expected behaviour
It should boot from the ipxe network available when we declare an empty disk (the way described in the doc). When we try to boot without declaring a disk (diskless boot), ipxe boot is currently working (https://github.com/hightoxicity/k8s-prodgrade-lab/compare/feat-libvirt-ipxeboot-diskless).

### Actual behaviour
It stucks on disk boot attempt

### System configuration

**OS/Distro version:**:

> Linux nosystem 4.15.0-36-generic #39~16.04.1-Ubuntu SMP Tue Sep 25 08:59:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Libvirt version:**:

> 1.3.1-1ubuntu10.24

**Output of `vagrant version; vagrant plugin list`:**

> Installed Version: 2.1.4
> Latest Version: 2.2.0
>  
> To upgrade to the latest version, visit the downloads page and
> download and install the latest version of Vagrant from the URL
> below:
> 
>   https://www.vagrantup.com/downloads.html
> 
> If you're curious what changed in the latest release, view the
> CHANGELOG below:
> 
>   https://github.com/hashicorp/vagrant/blob/v2.2.0/CHANGELOG.md
> vagrant-alpine (0.3.0, global)
> vagrant-host-shell (0.0.4, global)
> vagrant-ignition (0.0.3, global)
> vagrant-libvirt (0.0.43, global)
> vagrant-reload (0.0.1, global)
> vagrant-vbguest (0.15.2, global)

**Are you using upstream vagrant package or your distros package?**

> Distro 2.1.4

**Comment by hightoxicity** [comment]
Doing a lot of cleaning into my Vagrantfile, I found in which case it does not work, boot decalaration is lost after doing a second provider call...

Easy way to reproduce:

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "k8s-worker-002" do |srv|

      srv.vm.provider :libvirt do |l1, ov1|
        l1.boot 'network'
      end

      srv.vm.provider :libvirt do |l2, ov2|
        l2.memory = "512"
        ov2.vm.box = "generic/ubuntu1804"
        ov2.vm.synced_folder '.', '/vagrant', id: "vagrant-root", disabled: true
      end
    end
end
```

**Comment by electrofelix** [comment]
Sorry, it took a while, coming across this now. Basically anything that starts in the plugin config code with a default other than `UNSET_VALUE` needs to be handled via the `def merge(other)` function. Appears this was missed.

Fix was relatively straight forward, however I have set it so that if it is defined in subsequent section blocks, the last definition will win rather than be additive, since I think that makes more sense for managing the boot order.
