### ISSUE TITLE
Feature request: allow to define memballoon 'None'

### ISSUE THREAD

**Issue by mykaul** [vagrant-libvirt/vagrant-libvirt#945]
Currently, the default of libvirt is to create a balloon device:
```
    <memballoon model='virtio'>
      <alias name='balloon0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
    </memballoon>
```

Without anyone managing it, it's useless.
It's easy to NOT define via:
```
<memballoon model='none'/>
```

But libvirt-vagrant does not have this definition available

**Comment by electrofelix** [comment]
This was fixed by #1083, sorry missed this issue was related at the time.
