### ISSUE TITLE
Error creating VM: virError(Code=38, Domain=0, Message='Cannot get interface MTU on 'virbr0': No such device')

### ISSUE THREAD

**Issue by gee4vee** [vagrant-libvirt/vagrant-libvirt#979]
### Steps to reproduce
1. Install kvm2 driver and Minikube following:
https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#kvm2-driver
2. minikube config set vm-driver kvm2
3. minikube start

### Expected behaviour
Minikube starts successfully 

### Actual behaviour
Error:
```[root@testvm0001 ~]# minikube start
😄  minikube v0.34.1 on linux (amd64)
🔥  Creating kvm2 VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
💣  Unable to start VM: create: Error creating machine: Error in driver during machine creation: Error creating VM: virError(Code=38, Domain=0, Message='Cannot get interface MTU on 'virbr0': No such device')

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
```

### System configuration
**OS/Distro version:**:
centos7

**Libvirt version:**
4.5.0-10.el7_6.4

**Comment by electrofelix** [comment]
@gee4vee erm, did you log this with the wrong project?

**Comment by electrofelix** [comment]
Appears to be a problem with minikube and not vagrant-libvirt.
