### ISSUE TITLE
Install error: http://gems.hashicorp.com/ username:password

### ISSUE THREAD

**Issue by h1z1** [vagrant-libvirt/vagrant-libvirt#980]
### Steps to reproduce
1.  Install vagrant 
2.  vagrant plugin install vagrant-libvirt
3.

### Expected behaviour
plugin should install as per install instructions

### Actual behaviour
Error is thrown:

```
/opt/rh/sclo-vagrant1/root/usr/share/vagrant/bin/vagrant:174:in `<main>'
 INFO interface: error: Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Authentication is required for https://gems.hashicorp.com/.
Please supply credentials for this source. You can do this by running:
 bundle config https://gems.hashicorp.com/ username:password
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Authentication is required for https://gems.hashicorp.com/.
Please supply credentials for this source. You can do this by running:
 bundle config https://gems.hashicorp.com/ username:password
 INFO interface: Machine: error-exit ["Vagrant::Errors::BundlerError", "Bundler, the underlying system Vagrant uses to install plugins,\nreported an error. The error is shown below. These errors are usually\ncaused by misconfigured plugin installations or transient network\nissues. The error from Bundler is:\n\nAuthentication is required for https://gems.hashicorp.com/.\nPlease supply credentials for this source. You can do this by running:\n bundle config https://gems.hashicorp.com/ username:password"]
```

### System configuration
**OS/Distro version:**: CentOS 7

**Libvirt version:** 4.5.0

**Output of `vagrant version; vagrant plugin list`:**
Installed Version: 1.8.1
Latest Version: 2.2.4

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**

```
Same as above. 
```

**A Vagrantfile to reproduce the issue:**
```
NA
```

**Are you using upstream vagrant package or your distros package?**
Distro

**Comment by electrofelix** [comment]
This is a problem with vagrant trying to use gems.hashicorp.com to retrieve plugins from, there is nothing that can be done from vagrant-libvirt because it's not even getting as far as talking to it.

I expect upstream vagrant will simply say to report the issue to you sister to fix up the URL that the vagrant package is using (I believe they changed it a whole back)
