### ISSUE TITLE
Install error: Dependency missing

### ISSUE THREAD

**Issue by h1z1** [vagrant-libvirt/vagrant-libvirt#981]
### Steps to reproduce
1.  git clone https://github.com/vagrant-libvirt/vagrant-libvirt.git
2. cd vagrant-libvirt
3. bundle install

### Expected behaviour
plugin builds as per install instructions

### Actual behaviour
Install fails with missing ruby dependency:

```
$ bundle install
Your Gemfile lists the gem vagrant-libvirt (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
Your Gemfile lists the gem rspec-core (~> 3.5.0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
Your Gemfile lists the gem rspec-expectations (~> 3.5.0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
Your Gemfile lists the gem rspec-mocks (~> 3.5.0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
Your Gemfile lists the gem rake (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
Fetching https://github.com/hashicorp/vagrant.git
Fetching git://github.com/hashicorp/vagrant-spec.git
Fetching gem metadata from https://rubygems.org/............
Fetching additional metadata from https://rubygems.org/..
Resolving dependencies...
Installing rake 12.3.2

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /opt/rh/rh-ruby22/root/usr/bin/ruby -r ./siteconf20190303-101997-1v7ksuw.rb extconf.rb 
mkmf.rb can't find header files for ruby at /opt/rh/rh-ruby22/root/usr/share/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /home/vm2/.gem/ruby/gems/bcrypt_pbkdf-1.0.0 for inspection.
Results logged to /home/vm2/.gem/ruby/extensions/x86_64-linux/bcrypt_pbkdf-1.0.0/gem_make.out
An error occurred while installing bcrypt_pbkdf (1.0.0), and Bundler cannot
continue.
Make sure that `gem install bcrypt_pbkdf -v '1.0.0'` succeeds before bundling.
```

### System configuration
**OS/Distro version:**:
CentOS 7

**Libvirt version:**
 4.5.0

**Output of `vagrant version; vagrant plugin list`:**
Installed Version: 1.8.1
Latest Version: 2.2.4

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**
```
NA.  Build itself fails.
```

**A Vagrantfile to reproduce the issue:**
```
NA
```

**Are you using upstream vagrant package or your distros package?**
Distro

Installing bcrypt_pbkdf appears to work but fails later in the process:

```
Updating https://github.com/hashicorp/vagrant.git
Updating git://github.com/hashicorp/vagrant-spec.git
Fetching gem metadata from https://rubygems.org/............
Fetching additional metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 12.3.2
Installing bcrypt_pbkdf 1.0.0
Installing builder 3.2.3
Installing ffi 1.10.0
Installing childprocess 0.6.3
Installing coderay 1.1.2
Installing concurrent-ruby 1.1.4
Installing multi_json 1.13.1
Installing unf_ext 0.0.7.5
Installing unf 0.1.4
Installing domain_name 0.5.20180417
Installing http-cookie 1.0.3
Installing mime-types-data 3.2018.0812
Installing mime-types 3.2.2
Installing netrc 0.11.0
Installing rest-client 2.0.2
Installing docile 1.3.1
Installing json 2.2.0
Installing simplecov-html 0.10.2
Installing simplecov 0.16.1
Installing tins 1.20.2
Installing term-ansicolor 1.7.1
Installing thor 0.18.1
Installing coveralls 0.7.1
Installing diff-lcs 1.3
Installing ed25519 1.2.4
Installing erubis 2.7.0
Installing excon 0.62.0
Installing formatador 0.2.5
Installing fog-core 2.1.2
Installing fog-json 1.2.0
Installing mini_portile2 2.4.0

Gem::InstallError: nokogiri requires Ruby version >= 2.3.0.
An error occurred while installing nokogiri (1.10.1), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.10.1'` succeeds before bundling.

```

Manually installing "nokogiri"  and using ruby 2.5 appears to work.

I'm actually more floored by the contents of prepare_redhat_for_box.sh:

```
[ -d ~vagrant/.ssh ] || mkdir ~vagrant/.ssh
chmod 700 ~vagrant/.ssh
cat > ~vagrant/.ssh/authorized_keys << EOF
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key
EOF
chmod 600 ~vagrant/.ssh/authorized_keys
```

What are these two keys and why are they installed everywhere?

**Comment by electrofelix** [comment]
Please read the error message more closely, it's saying that it cannot find the ruby headers which means you didn't install the required packages as part of the initial install instructions and as a consequence things are not going to work as expected. If you want to update the reader.md to explicitly reference the plugin install instructions as part of the development instructions will be happy to merge.

Also the bundle command defaults to the latest vagrant, however it appears you want to test against an older version. Please have a look at the Gemfiles contents, you need to set `VAGRANT_VERSION` to the appropriate version for it to get the correct dependencies. Probably `v1.8.1` based on the rest of you comment.

**Comment by h1z1** [comment]
The headers would not (and didn't) help as it failed on another package - nokogiri.  

> For the second error the Gemfiles tells the bundle command to default to retrieving the latest vagrant from source,

Which on at least CentOS 7 fails with the system ruby - 2.0.   

>  you want to update the reader.md to explicitly reference the plugin install instructions as part of the development instructions will be happy to merge.

Honestly the ruby ecosystem is quite the confusing pile of ... frustration.   My guess is in the Gemfile  something like :
```
ruby "~> 2.5.0"
```

and 

```
yum install \
  rh-ruby25 \
  rh-ruby25-ruby-libs \
  rh-ruby25-runtime \
  rh-ruby25-ruby \
  rh-ruby25-ruby-devel
```

**Comment by electrofelix** [comment]
> The headers would not (and didn't) help as it failed on another package - nokogiri.

As replied for the second error which is the nokogiri one, you need to set `VAGRANT_VERSION` to `v1.8.1` to ensure retrieval of the correct version of nokogiri
```VAGRANT_VERSION=v1.8.1 bundle install```

Have a look at https://github.com/hashicorp/vagrant/blob/v1.8.1/vagrant.gemspec#L35 which pins nokogiri to a suitable version.

If you are using the distro package, you need to install the ruby headers as the vagrant install will be using the system ruby, which typically does not have the headers available by default, instead of the embedded version supplied by the upstream download, which does ship with headers included. Otherwise any plugin install that needs to build a native library to hook into the system will fail.

By not setting the version you end up getting https://github.com/hashicorp/vagrant/blob/master/vagrant.gemspec from the latest master which does not have a pin as newer versions of ruby used by vagrant are supported by nokogiri and they don't pin any more, and as vagrant-libvirt is relying on using the version that is compatible with vagrant (to allow working with multiple versions of vagrant) this results in the failure you saw above.

**Comment by h1z1** [comment]
Not quite sure I follow.  An attempt  was made with the ruby 2.0 headers installed, it still failed.   Knowing what I do now it's clear I could have set VAGRANT_VERSION as suggested above but would it not make sense to add a test for the version of ruby and act accordingly?  At least for building.   If  =< 2.3, set VAGRANT_VERSION=v1.8.1

**Comment by electrofelix** [comment]
@h1z1 This plugin can be installed with multiple versions of vagrant and the version of ruby required is determined by what vagrant is using, not by this plugin, therefore cannot pin the version of vagrant to use based on the ruby version used in order to support being able to build/install the plugin against multiple versions of vagrant.

What you're asking for would break trying to test against other versions of vagrant.

**Comment by h1z1** [comment]
Sure.  I mean, it already is broken.  Cheers.

**Comment by electrofelix** [comment]
I can't see that I can fix your problem without creating another one, if there is a way to do so, be happy to make a change to do so
