### ISSUE TITLE
vagrant plugin list does not see the vagrant-libvirt package

### ISSUE THREAD

**Issue by mcandre** [vagrant-libvirt/vagrant-libvirt#990]
One problem with setting up this plugin in Ubuntu is that the Ubuntu repositories do offer a vagrant-libvirt package. However, Vagrant does not appear to find the plugin when installed this way :/

**Comment by electrofelix** [comment]
That would be an issue for Ubuntu in how it is packaging such plugins or Vagrant in how it's supposed to determine what plugins are installed, this isn't something that can be solved from any of the plugins.
