### ISSUE TITLE
Bad configure flags for Ubuntu

### ISSUE THREAD

**Issue by mcandre** [vagrant-libvirt/vagrant-libvirt#991]
Hi, after lots of Googling I was finally able to install the vagrant-libvirt plugin on my Ubuntu 18.10 Cosmic Cuttlefish host. Aside from the messed up dependencies (libvirt-bin does not exist in Ubuntu 18.10), I also had to explicitly declare where the libvirt headers reside, with a configure environment variable:

```console
$ CONFIGURE_ARGS="with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib/libvirt" vagrant plugin install vagrant-libvirt
Installed the plugin 'vagrant-libvirt (0.0.45)'!
```

Please add this environment variable prefix to the Ubuntu install steps in the README, so that other Ubuntu users can see the correct setup commands.

**Comment by electrofelix** [comment]
I believe this should have been marked solved with the updating of the docs to reference use of a helper script if you wanted to work with upstream vagrant and better instructions for working with the vagrant provided by the distro packages, see https://vagrant-libvirt.github.io/vagrant-libvirt/installation.html#ubuntu-1810-debian-9-and-up
