### ISSUE TITLE
virt-manager image cache out of date

### ISSUE THREAD

**Issue by mcandre** [vagrant-libvirt/vagrant-libvirt#993]
As new Vagrant box versions release, the virt-manager image cache quickly becomes out of date, silently supplying old images on `vagrant up`. Please make sure that each `vagrant box add` / `vagrant up` keeps the virt-manager storage pool up to date.

If we insert new entries to virt-manager, we should make sure to properly delete/overwrite old entries for that Vagrant box, otherwise we create a bad situation where users get invalid qemu images.

**Comment by electrofelix** [comment]
@mcandre This should already be in place and matching https://www.vagrantup.com/docs/boxes/versioning.html#automatic-update-checking, so a `vagrant up` will check if a box is up to date, provided the box provides a version, if there is no version, there isn't anything can be done.

Newer versions are imported into libvirt encoding the version into the image file name to ensure that the vagrant up can use the newer base image without impacting machines already running with the previous version.

Unless you are talking about something else?

**Comment by electrofelix** [comment]
It's possible if you were working locally build boxes that this might have occurred, which was fixed in #1512, based on this fix which would have appeared in the 0.10.x releases series, going to make this as fixed.
