### ISSUE TITLE
box export broken in multiple ways

### ISSUE THREAD

**Issue by mcandre** [vagrant-libvirt/vagrant-libvirt#994]
Hi, I am trying to add some configuration to a libvirt Vagrant box and then export that for reuse. I can do this with VMware and VirtualBox guests, but when I do this with libvirt, I get all sorts of errors!

Source:

https://github.com/mcandre/vagrant-debian-cpp/tree/ppc64el

One error strangely indicates missing read permissions on .IMG files. Even though Packer and `vagrant up` can read image files just fine.

When I grant read permissions, the next error has to do with a missing filename. The Ruby log seems to use a blank filename here?

And after enough runs, I finally get an error about some `_tmp_package` file already exists. Ideally that file would simply be overwritten. For now I am manually removing that file and trying and trying again.

I'm using base box mcandre/debian-ppc64el, on qemu 2.12 with machine "pseries", with vagrant-libvirt 0.0.45, with libvirt 4.6.0, on Vagrant 2.2.4, on Ubuntu 18.10 Cosmic Cuttlefish, on a System76 Galaga Pro.

**Comment by mcandre** [comment]
Example trace:

```console
$ vagrant package --output debian-ppc64el.box
...
/home/andrew/.vagrant.d/gems/2.4.4/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/package_domain.rb:41:in ``': No such file or directory - virt-sysprep (Errno::ENOENT)
	from /home/andrew/.vagrant.d/gems/2.4.4/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/package_domain.rb:41:in `call'
	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
...
```

**Comment by mcandre** [comment]
After installing libguestfs-tools, the blank file/directory error goes away. But I still see many file permission errors:

```console
Require set read access to /var/lib/libvirt/images/ppc64el_default.img. sudo chmod a+r /var/lib/libvirt/images/ppc64el_default.img
```

I have to reset the file permissions on that path every dang time I `vagrant up`!

In addition, libguestfs reports an error accessing the host kernel:

```console
$ env LIBGUESTFS_DEBUG=1 LIBGUESTFS_TRACE=1 vagrant package --output vagrant-debian-cpp-ppc64el.box
...
cp: cannot open '/boot/vmlinuz-4.18.0-17-generic' for reading: Permission denied
supermin: cp -p '/boot/vmlinuz-4.18.0-17-generic' '/var/tmp/.guestfs-1000/appliance.d.f4o3z1oh/kernel': command failed, see earlier errors
...
```

**Comment by mcandre** [comment]
One further oddity with Debian ppc64el on vagrant-libvirt. The base box successfully connects to sshd. The `vagrant up` instance successfully connects to sshd. But when I `vagrant package`, the resulting box waits indefinitely for an sshd connection that never completes. I'm not sure why this is happening.

For what it's worth, sshd is confirmed active (`systemctl status ssh`).

**Comment by mcandre** [comment]
Good news, network appears to be working between the guest and the host, without requiring any specific configuration overrides. I can telnet to port 22 on the guest and get back an OpenSSH banner.

This means that the problem is likely the guest SSH public key getting overwritten somehow in the process of `vagrant up`, `vagrant package`. Even though I have `config.ssh.insert_key = false` configured in my `Vagrantfile` used to create this box.

**Comment by codylane** [comment]
@mcandre - I'm not affiliated with this project but I can appreciate the time and effort that you put into this.  Kudos my friend.  I was thinking I was going crazy that I was doing something wrong in my environment and I'm having the exact same issues trying to package a box via libvirt.

**Comment by ryanfitzsimon** [comment]
#928 should resolve the permission issue causing this message:
```
Require set read access to /var/lib/libvirt/images/ppc64el_default.img. sudo chmod a+r /var/lib/libvirt/images/ppc64el_default.img
```

**Comment by mcandre** [comment]
Good news!

I dug into guest ssh logs with `systemctl status ssh` via VNC. Now, the logs don't always show this error, but occasionally you will see complaints about missing "host" (guest) SSH keys. You can work around this by executing `sudo ssh-keygen -A`, again in VNC. Thereafter, `vagrant up` is able to complete SSH connections and proceed through any provisioning scripts.

Now, I am not sure how these keys are getting removed. The parent box seems to have all the keys that it needs. Something smells rotten in the land of `vagrant export`...

**Comment by ultraNick** [comment]
I have totally same problem with you. and I figure out this option `export VAGRANT_LIBVIRT_VIRT_SYSPREP_OPERATIONS="defaults,-ssh-userdir,-ssh-hostkeys,-lvm-uuids"` doesn't work.

**Comment by skjoedt** [comment]
The ssh hostkeys are removed during vagrant package by the virt-sysprep operation "ssh-hostkeys". 
@ultraNick is correct in using the environment variable to disable the ssh-hostkeys operation which is in line with the README here

https://github.com/vagrant-libvirt/vagrant-libvirt#package-box-from-vm

However, I can confirm from my own tests that the hostkeys are indeed still removed when you get to do vagrant up later. I assume it could be a bug where the "-" is not respected.

**Comment by HugoPoi** [comment]
Beware `VAGRANT_LIBVIRT_VIRT_SYSPREP_OPERATIONS` is only working in master branch, not present in v0.0.45

**Comment by GSergeevich** [comment]
```
after 2020-02-01.
Gem::Specification.default_specifications_dir called from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/bundler.rb:428.
Installed the plugin 'vagrant-libvirt (0.0.45)'!
german@x230: vagrant-libvirt$ export VAGRANT_LIBVIRT_VIRT_SYSPREP_OPERATIONS="defaults,-ssh-userdir,-ssh-hostkeys,-lvm-uuids"
german@x230: vagrant-libvirt$ vagrant package

==> default: Packaging domain...
(eval):3: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/ui.rb:223: warning: The called method `say' is defined here
==> default: Require set read access to /home/german/virtpool/test_default.img. sudo chmod a+r /home/german/virtpool/test_default.img
Traceback (most recent call last):
	28: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/bin/vagrant:182:in `<main>'
	27: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/environment.rb:290:in `cli'
	26: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/cli.rb:66:in `execute'
	25: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/plugins/commands/package/command.rb:45:in `execute'
	24: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/plugins/commands/package/command.rb:77:in `package_target'
	23: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/plugin/v2/command.rb:232:in `with_target_vms'
	22: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/plugin/v2/command.rb:232:in `each'
	21: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/plugin/v2/command.rb:238:in `block in with_target_vms'
	20: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/plugins/commands/package/command.rb:79:in `block in package_target'
	19: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/plugins/commands/package/command.rb:90:in `package_vm'
	18: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/machine.rb:195:in `action'
	17: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/machine.rb:195:in `call'
	16: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/environment.rb:613:in `lock'
	15: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/machine.rb:209:in `block in action'
	14: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/machine.rb:238:in `action_raw'
	13: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:102:in `run'
	12: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/util/busy.rb:19:in `busy'
	11: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:102:in `block in run'
	10: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/builder.rb:116:in `call'
	 9: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	 8: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
	 7: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	 6: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	 5: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	 4: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
	 3: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	 2: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
	 1: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
/home/german/.vagrant.d/gems/2.7.0/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/package_domain.rb:34:in `call': Have no access (RuntimeError)

```

**Comment by HugoPoi** [comment]
Do a `sudo chmod a+r /home/german/virtpool/test_default.img`
