### ISSUE TITLE
Better default qemu URI

### ISSUE THREAD

**Issue by mcandre** [vagrant-libvirt/vagrant-libvirt#995]
`vagrant up` and `vagrant destroy` often complain that certificates cannot be found. The resolution is to configure the qemu URI as `'qemu+unix:///system'`. Can we make this the default, especially when the qemu driver is enabled?

**Comment by electrofelix** [comment]
Is this still an issue? I've never bumped into his myself, so it might be related to behaviour on different distros.

One noticeable change over the last number of months is better support for picking up LIBVIRT_DEFAULT_URI as a fallback default when possible which might make it easier to configure this when needed for particular systems.

**Comment by electrofelix** [comment]
Going to assume this has likely been resolved at the distro level.
