### ISSUE TITLE
 INFO interface: error: Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: XML error: Non-empty feature list specified without CPU model

### ISSUE THREAD

**Issue by mcandre** [vagrant-libvirt/vagrant-libvirt#996]
While debugging libvirt boxes, I often see this weird error on `vagrant up`:

```console
 INFO interface: error: Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: XML error: Non-empty feature list specified without CPU model
```

**Comment by electrofelix** [comment]
I suspect this might be a case of nested virtualization being enabled or cpu features being specified when the cpu mode has been set to 'host-passthrough'.

The following would be sufficient to trigger this as skips setting the cpu model while also trying to set a cpu feature block
```
Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |libvirt|
    libvirt.cpu_mode = 'host-passthrough'
    libvirt.nested = true
  end
end
```

**Comment by electrofelix** [comment]
This appears to have been resolved, but not by vagrant-libvirt, instead it appears that libvirt ignores any cpu features if the cpu_model is not set.
